### ISSUE TITLE
[Bug] [dlink-web] frontend-maven-plugin encounter error=86, Bad CPU type in executable

### ISSUE THREAD

**Issue by meet-alfie** [DataLinkDC/dinky#1001]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

      
 Symptom When I run the "mvn clean install -DskipTests" command locally, the dlink-web error occurs;
 I suspect the Node version is not compatible with my machine, can someone tell me the correct version or the problem, thanks

### What you expected to happen

`  [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.0:npm (npm install) on project dlink-web: Failed to run task: 'npm install --force' failed. java.io.IOException: Cannot run program "/Users/alfie/workspace/code/learn/dlink/dlink-web/node/node" (in directory "/Users/alfie/workspace/code/learn/dlink/dlink-web"): error=86, Bad CPU type in executable -> [Help 1]`

### How to reproduce

**ENV**
- Operating System 
         MacBook Pro M1
- IDE Name
        IDEA 2021.2 aarch64
- JDK Version
        zulu-8(1.8.0_342)
- MAVEN Version
         3.6.3
- NODE Version
        v14.17.0
- NPM Version
        7.19.0
- DLINK Version
         dev(0.6.7)

If i switch to the dlink-web directory, i  run the command  

> npm install --force

 count the error:

```
fatal - Error: Generator tmp not found.
    at Command.fn (/Users/alfie/workspace/code/learn/dlink/dlink-web/node_modules/umi/node_modules/@umijs/core/dist/service/generatePlugin.js:50:17)
    at Service.run (/Users/alfie/workspace/code/learn/dlink/dlink-web/node_modules/umi/node_modules/@umijs/core/dist/service/service.js:271:29)
    at async Service.run2 (/Users/alfie/workspace/code/learn/dlink/dlink-web/node_modules/umi/dist/service/service.js:74:12)
    at async Object.run (/Users/alfie/workspace/code/learn/dlink/dlink-web/node_modules/umi/dist/cli/cli.js:55:7)
```

 in the root directory, if i run the command 

> mvn clean install -DskipTests

, i get an front error

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi. This needs to be solved by a professional front-end.

**Comment by meet-alfie** [comment]
@aiwenmo Tks.Perhaps something generated after NPN install is not deleted totally and affects this. 
when I pull back the initial warehouse code and re-execute the command, it works. 
In addition, Node is required to be V14.19.0 on the official website and V14.17.0 on docs. Both versions are applicable for me.
