### ISSUE TITLE
[Feature][注册中心] 集群配置管理

### ISSUE THREAD

**Issue by lwzhangMr** [DataLinkDC/dinky#1004]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

hdf上传提示无hadoop配置

### Use case

hdf上传应该依赖上面的hadoop配置路径，而不是重新手动上传hadoop配置到项目的/config/hadoop-conf下

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
#1007
