### ISSUE TITLE
[Bug] [Frontend] 字段信息页面显示越界

### ISSUE THREAD

**Issue by zhuxt2015** [DataLinkDC/dinky#1009]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/13765310/189088971-cab2b597-8b45-4dc1-a635-0b37f9171f28.png)

### What you expected to happen

如题

### How to reproduce

数据开发-元数据->右键一个表->字段信息

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
- [X] #1017
