### ISSUE TITLE
[Bug] [web] UI page display misalignment 

### ISSUE THREAD

**Issue by gaoyan1998** [DataLinkDC/dinky#1012]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

The overall UI has the problem of padding disappearing, including the low menu height, which is especially obvious on the data source page. The first one has exceeded the limit.
![bug3.png](https://s1.imagehub.cc/images/2022/09/09/bug3.png)
![bug2.png](https://s1.imagehub.cc/images/2022/09/09/bug2.png)

### What you expected to happen

It may be a global configuration problem

### How to reproduce

Just remove the code `.ant-pro-card-body` from global.less  can be fix. 
maybe just a small diff，but it affects the browsing experience
![fix2.png](https://s1.imagehub.cc/images/2022/09/09/fix2.png)
![fix1.png](https://s1.imagehub.cc/images/2022/09/09/fix1.png)

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
In addition, deleting the style configuration of the card just makes the submenu normal, and the following parameter needs to be modified
```
.ant-tabs-top > .ant-tabs-nav, .ant-tabs-bottom > .ant-tabs-nav, .ant-tabs-top > div > .ant-tabs-nav, .ant-tabs-bottom > div > .ant-tabs-nav {
  margin: 0 0 0px 0!important;
}
```

**Comment by aiwenmo** [comment]
Hi. It's a good fix.
