### ISSUE TITLE
[Optimization][UI] 数据开发左侧菜单显示区域太窄,同时建议不要隐藏菜单

### ISSUE THREAD

**Issue by zhuxt2015** [DataLinkDC/dinky#1028]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

左侧菜单列表全部展示出来, 参考flink UI, 可以折叠左侧菜单
<img width="106" alt="image" src="https://user-images.githubusercontent.com/13765310/190600346-bf3089fa-21f3-4ea9-baac-7a3511f1af87.png">
<img width="359" alt="image" src="https://user-images.githubusercontent.com/13765310/190600544-c65d8152-44f5-4a7f-96cc-a1b6c6351eda.png">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
这个左侧tab和flinkwebui的左侧菜单栏不太一样

**Comment by zhuxt2015** [comment]
> 这个左侧tab和flinkwebui的左侧菜单栏不太一样

是不一样，只是建议展示区域宽一些，同时把所有tab显示出来

**Comment by aiwenmo** [comment]
> > 这个左侧tab和flinkwebui的左侧菜单栏不太一样
> 
> 是不一样，只是建议展示区域宽一些，同时把所有tab显示出来

展示区域是指每个tab的内容区域吗，如果是的话，这个是可以拖拽的。当然界面的布局操作目前有很大的优化空间，由于经理有限，目前还没推动这块的优化

**Comment by Zzm0809** [comment]
dev 已实现拖动
