### ISSUE TITLE
[Optimization][devops] Use more screen space when window is maximized

### ISSUE THREAD

**Issue by leeoo** [DataLinkDC/dinky#1032]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

As title, that should be better display for below cases. [Dinky 0.6.7]

![图片](https://user-images.githubusercontent.com/2136182/190945032-58d7f450-3c7a-44c1-88b1-c6119bb6c16c.png)

![图片](https://user-images.githubusercontent.com/2136182/190945145-318cfaaf-29ca-4439-8d14-3ea620d6ea36.png)

![图片](https://user-images.githubusercontent.com/2136182/190945219-cea65490-22c7-41ee-bc0a-be9cffdaa684.png)

![图片](https://user-images.githubusercontent.com/2136182/190945301-f5fa170f-3cf0-4db7-a942-d282e3539572.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
等下统一改成 vh 的高度应该就可以了
