### ISSUE TITLE
flink任务网络异常造成重启，yarn节点变更，无法获取任务信息，导致unknown状态

### ISSUE THREAD

**Issue by NoddleSp** [DataLinkDC/dinky#1033]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/86007832/190961607-31ff6938-1a49-4029-98e1-231784fcec0c.png)

此任务提交日期是16日，17日因为网络原因造成zk连不上
重连时失败Remote connection to [null] failed with java.net.ConnectException: Connection refused

之后容器外重启导致节点变化，但是请求的JobManagerHost变了，如图16日是节点A，重启后是节点B，获取不到最新的任务信息（jid没变）
JobHistory jobHistoryJson = jobHistoryService.refreshJobHistory(id, jobInfoDetail.getCluster().getJobManagerHost(), jobInfoDetail.getInstance().getJid(), jobInfoDetail.isNeedSave());

### What you expected to happen

支持任务容器外重启，yarn节点变更也能获取任务信息

### How to reproduce

参考上面

### Version

0.6.6

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
请问是什么提交模式，yarn-perjob 或者 yarn-application 吗

**Comment by NoddleSp** [comment]
> 请问是什么提交模式，yarn-perjob 或者 yarn-application 吗

yarn-per-job模式

**Comment by aiwenmo** [comment]
目前会这样，可以优化下

**Comment by aiwenmo** [comment]
在自动注册集群实例时获取HA所有的地址

**Comment by NoddleSp** [comment]
> 在自动注册集群实例时获取HA所有的地址

这样的方式行不通，因为同一个ip端口也是变化的，还有其他好的建议没，不会只有扫yarn列表去实时获取每个任务的jm地址了吧

**Comment by aiwenmo** [comment]
> > 在自动注册集群实例时获取HA所有的地址
> 
> 这样的方式行不通，因为同一个ip端口也是变化的，还有其他好的建议没，不会只有扫yarn列表去实时获取每个任务的jm地址了吧

有一种可行的方式是，dinky 通过yarn 的 application 实例信息去访问 JM ，而不是具体的IP地址和端口号

**Comment by NoddleSp** [comment]
> > > 在自动注册集群实例时获取HA所有的地址
> > 
> > 
> > 这样的方式行不通，因为同一个ip端口也是变化的，还有其他好的建议没，不会只有扫yarn列表去实时获取每个任务的jm地址了吧
> 
> 有一种可行的方式是，dinky 通过yarn 的 application 实例信息去访问 JM ，而不是具体的IP地址和端口号

谢啦，我去看看咋实现

**Comment by NoddleSp** [comment]
https://hadoop.apache.org/docs/current/hadoop-yarn/hadoop-yarn-site/ResourceManagerRest.html#Cluster_Application_API
找到了，可以根据这个api去获取最新的JM地址

**Comment by nylqd** [comment]
https://github.com/DataLinkDC/dlink/blob/dev/dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java#L976

目前checkJobStatus已经是支持通过yarn application id来刷新作业状态，感觉可以在这里更进一步

如果通过application id 获取回来的状态是RUNNING，则把最新的JM host从yarn里面retrieve回来，然后更新到cluster里面

**Comment by LeonYoah** [comment]
然后呢，后来的代码好像也没实现这个功能
