### ISSUE TITLE
[Bug] [dlink-web] Session timeout cannot automatically jump to the login page

### ISSUE THREAD

**Issue by didiaode18** [DataLinkDC/dinky#1034]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/22792154/191153081-b68be34b-fbf6-4e6a-8b82-22993b532167.png)
![image](https://user-images.githubusercontent.com/22792154/191153080-bac1c023-83d1-4c93-8b1f-446ffe6cdb1b.png)
When the session times out, you cannot perform any operations

### What you expected to happen

Session timeout should jump directly to the login page and provide friendly re-login information

### How to reproduce

When the session times out, you can continue to operate the previous job

### Version

0.6.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
like issue： 
#1008 
#168

**Comment by hdygxsj** [comment]
please assign to me

**Comment by Zzm0809** [comment]
> please assign to me

hi , @hdygxsj 这个功能已经在 dev 分支实现, 但是可能还需要优化 , 比如在数据开发页面时 停留过久导致会话过期, 那么此时应该弹出确认框, 询问是否重新登陆 是:返回到 login 页面, 否: 做其他操作,避免正在编辑的内容丢失 ,


如果可能, 可以实现定时保存功能那么就不存在 上述操作 可以直接返回登录页

**Comment by hdygxsj** [comment]
> > please assign to me
> 
> hi , @hdygxsj 这个功能已经在 dev 分支实现, 但是可能还需要优化 , 比如在数据开发页面时 停留过久导致会话过期, 那么此时应该弹出确认框, 询问是否重新登陆 是:返回到 login 页面, 否: 做其他操作,避免正在编辑的内容丢失 ,
> 
> 如果可能, 可以实现定时保存功能那么就不存在 上述操作 可以直接返回登录页

有对应的issue吗，我有空实现它

**Comment by Zzm0809** [comment]
> 

No, you can create an issue to discuss
