### ISSUE TITLE
[Bug] [WEB UI]  K8S session集群端口变了, 提交任务时没有错误提示 

### ISSUE THREAD

**Issue by zhuxt2015** [DataLinkDC/dinky#1040]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

如题, 无论是执行当前SQL还是异步提交, 提示框都一闪而过
<img width="423" alt="image" src="https://user-images.githubusercontent.com/13765310/191472209-797a2365-ef37-445d-a789-89bd65f0bd40.png">

### What you expected to happen

应该给出具体错误信息, 提示用户为什么提交不成功。 比如无法链接到Flink集群。

### How to reproduce

修改K8S session集群的端口, 然后往集群提交任务。

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
下方历史选项卡可以看到具体的信息

**Comment by zhuxt2015** [comment]
> 下方历史选项卡可以看到具体的信息

历史中没有产生新的记录,看不错具体信息

**Comment by aiwenmo** [comment]
> 

嗯好，请暂时尝试查看 dlink.log 是否有异常信息。这段时间会优化异常反馈这块。
