### ISSUE TITLE
yarn-session批模式下，自动刷新任务状态，并提供数据下载

### ISSUE THREAD

**Issue by ghost** [DataLinkDC/dinky#1047]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

建议yarn-session批模式下，执行完作业后，自动刷新任务状态，并提供数据下载功能，主要目标是：提高flink 作为 hive执行引擎时的使用体验，替代数据库客户端的部分功能，在dlink中可以完成大部分日常工作
![图片](https://user-images.githubusercontent.com/40230796/191915729-6ae21fb4-ab16-418f-95f0-bb4e19cc233c.png)
![图片](https://user-images.githubusercontent.com/40230796/191915931-c6d312ef-39b4-406a-acec-28d77f15fc51.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
下载全部的数据吗，还是前多少条

**Comment by ghost** [comment]
> 下载全部的数据吗，还是前多少条

下载全部数据，我认为数量还是sql控制好一点

**Comment by aiwenmo** [comment]
> > 下载全部的数据吗，还是前多少条
> 
> 下载全部数据，我认为数量还是sql控制好一点

那如果sql没有写限制，岂不会 OOM。还有就是把全部数据导出的意义是什么，导出后自行要进行什么样的操作来分析

**Comment by ynzzxc** [comment]
> > > 下载全部的数据吗，还是前多少条
> > 
> > 
> > 下载全部数据，我认为数量还是sql控制好一点
> 
> 那如果sql没有写限制，岂不会 OOM。还有就是把全部数据导出的意义是什么，导出后自行要进行什么样的操作来分析
比如给业务导一份临时数据。不论通过什么平台去做这件事，都可能发生sql没有限制这件事，但如果我在dlink做这件事，oom的仅仅是一个flink job，以下我系统的阐述以下我产生这个想法的原因。

目前flinksql降低了开发flink任务的门槛，但并未降低进入flink生态的门槛，目前的dlink亦然。
我认为dlink能够轻易的改变这一现状，这既有利于flink生态的扩张，也可以让dlink成为驰骋flink生态最便捷的路径；
我的建议大体可分为以下两部分：
（1）让所有数据库都能便捷的用上flink引擎
	在没有成型数仓体系的企业中，或者处理一些临时任务时，往往自从库中提取数据，不仅给数据库造成压力，而且不同的数据库要写不同的sql；
	如果在dlink上使用flinksql的standalone或yarn-session模式，将会有很好的体验。
	要实现这一点，从功能上看，dlink只缺少一个数据下载的功能；
	从体验上看，部署不够便捷，开发页面交互不友好（sql开发页面的交互，众多开源bi平台基本达成了共识，可以借鉴）。
（2）提供一种最快速、最便捷的etl体验方案
比如在开发页面提供一个作业组、前置任务、后置任务的选项。

然后任何会写sql的人，都可以通过以下4步，开启自己的flink之旅，并推动公司普及，
（1）下载flink和dlink，解压
（2）启动flink，start-cluster.sh
（3）启动dlink，auto.sh start
（4）登陆dlink，配置实例，开始使用

以上只是我个人经验的一家之言，如果社区对此感兴趣，可以进一步交流。dlink为我的工作带来了方便，我也希望有机会为dlink的发展做些微不足道的贡献。

**Comment by ynzzxc** [comment]
> > > 下载全部的数据吗，还是前多少条
> > 
> > 
> > 下载全部数据，我认为数量还是sql控制好一点
> 
> 那如果sql没有写限制，岂不会 OOM。还有就是把全部数据导出的意义是什么，导出后自行要进行什么样的操作来分析

    比如给业务导一份临时数据。不论通过什么平台去做这件事，都可能发生sql没有限制这件事，但如果我在dlink做这件事，oom的仅仅是一个flink job，以下我系统的阐述以下我产生这个想法的原因。

目前flinksql降低了开发flink任务的门槛，但并未降低进入flink生态的门槛，目前的dlink亦然。
我认为dlink能够轻易的改变这一现状，这既有利于flink生态的扩张，也可以让dlink成为驰骋flink生态最便捷的路径；
我的建议大体可分为以下两部分：
（1）让所有数据库都能便捷的用上flink引擎
在没有成型数仓体系的企业中，或者处理一些临时任务时，往往自从库中提取数据，不仅给数据库造成压力，而且不同的数据库要写不同的sql；
如果在dlink上使用flinksql的standalone或yarn-session模式，将会有很好的体验。
要实现这一点，从功能上看，dlink只缺少一个数据下载的功能；
从体验上看，部署不够便捷，开发页面交互不友好（sql开发页面的交互，众多开源bi平台基本达成了共识，可以借鉴）。
（2）提供一种最快速、最便捷的etl体验方案
比如在开发页面提供一个作业组、前置任务、后置任务的选项。

然后任何会写sql的人，都可以通过以下4步，开启自己的flink之旅，并推动公司普及，
（1）下载flink和dlink，解压
（2）启动flink，start-cluster.sh
（3）启动dlink，auto.sh start
（4）登陆dlink，配置实例，开始使用

以上只是我个人经验的一家之言，如果社区对此感兴趣，可以进一步交流。dlink为我的工作带来了方便，我也希望有机会为dlink的发展做些微不足道的贡献。

**Comment by ghost** [comment]
> > > 下载全部的数据吗，还是前多少条
> > 
> > 
> > 下载全部数据，我认为数量还是sql控制好一点
> 
> 那如果sql没有写限制，岂不会 OOM。还有就是把全部数据导出的意义是什么，导出后自行要进行什么样的操作来分析

比如给业务导一份临时数据。不论通过什么平台去做这件事，都可能发生sql没有限制这件事，但如果我在dlink做这件事，oom的仅仅是一个flink job，以下我系统的阐述一下我产生这个想法的原因。
目前flinksql降低了开发flink任务的门槛，但并未降低进入flink生态的门槛，目前的dlink亦然。
我认为dlink能够轻易的改变这一现状，这既有利于flink生态的扩张，也可以让dlink成为驰骋flink生态最便捷的路径；
我的建议大体可分为以下两部分：
（1）让所有数据库都能便捷的用上flink引擎
在没有成型数仓体系的企业中，或者处理一些临时任务时，往往自从库中提取数据，不仅给数据库造成压力，而且不同的数据库要写不同的sql；
如果在dlink上使用flinksql的standalone或yarn-session模式，将会有很好的体验。
要实现这一点，从功能上看，dlink只缺少一个数据下载的功能；
从体验上看，部署不够便捷，开发页面交互不友好（sql开发页面的交互，众多开源bi平台基本达成了共识，可以借鉴）。
（2）提供一种最快速、最便捷的etl体验方案
比如在开发页面提供一个作业组、前置任务、后置任务的选项。

然后任何会写sql的人，都可以通过以下4步，开启自己的flink之旅，并推动公司普及，
（1）下载flink和dlink，解压
（2）启动flink，start-cluster.sh
（3）启动dlink，auto.sh start
（4）登陆dlink，配置实例，开始使用

以上只是我个人经验的一家之言，如果社区对此感兴趣，可以进一步交流。dlink为我的工作带来了方便，我也希望有机会为dlink的发展做些微不足道的贡献。

**Comment by aiwenmo** [comment]
非常感谢您的认可与建议，以下是我对此的个人解答：
（1）oom是dlink发生而不是flinkjob发生，当然可以通过设计特殊的实现方式来规避该问题，但成本比较高，且该功能不实用。大数据量的背景下，最好的方式是把 dlink 当成 OLAP 来进行直接进行源库查询或 Flink OLAP 查询，而不是输出所有结果再放到第三方工具如 Excel 去人工分析。
（2）流作业中没有前置任务和后置任务，关于批作业的 DAG 调度，目前需要集成外部平台来做，如 DolphinScheduler 等。
（3）降低门槛这块作为开源项目需要兼顾多种场景，而非企业定制化开发来得容易，还在不断的改进和研究中。
（4）目前使用dlink的各种能力需要具备一定的flink知识，纯sql开发者应该只负责基于平台开发业务sql，而不包括平台部署和运维，平台的生产应用需要多个工作岗位协作。
（5）欢迎在使用过程中通过 issue 反馈问题以及修复bug。

**Comment by ghost** [comment]
> 非常感谢您的认可与建议，以下是我对此的个人解答： （1）oom是dlink发生而不是flinkjob发生，当然可以通过设计特殊的实现方式来规避该问题，但成本比较高，且该功能不实用。大数据量的背景下，最好的方式是把 dlink 当成 OLAP 来进行直接进行源库查询或 Flink OLAP 查询，而不是输出所有结果再放到第三方工具如 Excel 去人工分析。 （2）流作业中没有前置任务和后置任务，关于批作业的 DAG 调度，目前需要集成外部平台来做，如 DolphinScheduler 等。 （3）降低门槛这块作为开源项目需要兼顾多种场景，而非企业定制化开发来得容易，还在不断的改进和研究中。 （4）目前使用dlink的各种能力需要具备一定的flink知识，纯sql开发者应该只负责基于平台开发业务sql，而不包括平台部署和运维，平台的生产应用需要多个工作岗位协作。 （5）欢迎在使用过程中通过 issue 反馈问题以及修复bug。

感谢文末大佬非常耐心的回复，我表示非常认同，以及补充几点~
（1）大量数据一般不会直接下载，分析结果也基本是在bi中去呈现的，如果sql中没限制数量，就像代码写了死循环一样，不是工具本身必须考虑的。
（2）我目前需要下载的情况，大约是需求没做完或者需求有变动，但要一份新数据；上下游数据对不上，要把某个时段的数据导出来对比一下；谁灵机一动有个想法，想先看看结果再决定要不要继续下一步分析，以及还没把所有数据写进hudi等。
（3）对于已经有olap或者htap基础设施的人来说，确实不实用，但对于想要尝试和学习flinksql的人来说则比较有用。让flink成为所有数据库的执行引擎，这可能不是dlink目前的重点方向，但从长远来看一定会壮大dlink生态。只是恰巧基于关系型数据库做分析的用户常有下载数据的需求（一般是中小企业、成长企业）。如果dlink生态中有大量中小企业、成长企业，也更容易孵化出商业产品，在他们建设数仓时也会更倾向于dlink生态，连数仓都还没建成的企业，往往是一人多任的（悲）。

我扯远了。。。
