### ISSUE TITLE
[Bug] [Mysql] Insufficient string length

### ISSUE THREAD

**Issue by kangshisen** [DataLinkDC/dinky#1063]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

在dlink编辑框里面如果输入的sql过长，会出现字符不够使用的报错情况，经查看是因为mysql存储的是text类型
![37321664263788_ pic](https://user-images.githubusercontent.com/38653300/192665060-36f434c1-c48b-4a14-9c46-cd83b533e77d.jpg)

### What you expected to happen

修改长度为mediumtext或者langtext

### How to reproduce

在界面输入大量sql，预计到1000行左右会出现这个问题
<img width="813" alt="image" src="https://user-images.githubusercontent.com/38653300/192664842-3f5c7ce1-d283-4a80-89b6-43940e0669aa.png">

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
pr: #1238
