### ISSUE TITLE
添加oracle数据库源时报错：invalid oracle validationQuery. select 1, may should be : select 1 FROM DUAL

### ISSUE THREAD

**Issue by bbccaaac** [DataLinkDC/dinky#1072]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

添加oracle数据库源时报错：invalid oracle validationQuery. select 1, may should be : select 1 FROM DUAL

### What you expected to happen

初始搜索了一下代码，怀疑是dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/driver/AbstractJdbcDriver.java  ds.setValidationQuery("select 1")导致，oracle的测试应该使用select 1 from dual

### How to reproduce

添加oracle数据源点测试或保存都能重现

### Version

0.6.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
嗯那oracle的实现类需要重写这个的方法，这个应该是之前加这个参数时没有考虑兼容性
