### ISSUE TITLE
[优化][数据库表命名] 数据库的dlink_task相关表命名优化

### ISSUE THREAD

**Issue by dk333** [DataLinkDC/dinky#1084]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

dlink_task_statement，实际上是作业的sql定义。所以，其实叫做dlink_job_statementg更合适

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
您好，请问只是单词 task 改为 job 吗？

**Comment by dk333** [comment]
> 

是的。从官方图上看，层级关系它应该是job到task再到operator。这个应该是job。
另外，我只是说这张表，举例，其它相关表，应该也是一样的。
有不对的地方，请指正，谢谢。
[
![image](https://user-images.githubusercontent.com/24607870/195009695-c9b47ed1-d7a6-4284-9df1-f641871aba30.png)
](url)

**Comment by aiwenmo** [comment]
嗯，Dinky 的 Task 概念不是 Flink Task.
