### ISSUE TITLE
[Feature][web] support SQL query to export results

### ISSUE THREAD

**Issue by walkhan** [DataLinkDC/dinky#1087]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

support SQL query to export results to csv or txt
the following locations：
![image](https://user-images.githubusercontent.com/16821730/194995765-7be95514-dea9-4b46-9cb7-359d2ac09e9f.png)
Data export function is available at the top right

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
has supported in 1.0
