### ISSUE TITLE
[Bug] [web] FlinkSQL with statement data preview is blank

### ISSUE THREAD

**Issue by walkhan** [DataLinkDC/dinky#1091]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

FlinkSQL with statement data preview is blank
![61fd44718df1db255e713d7e9e4fbf7](https://user-images.githubusercontent.com/16821730/195277126-e3e054dd-fb35-4cea-b68e-d85de2119f07.png)

### What you expected to happen

The debugging has not become two vertical bars, but the job on the FLink webui is successful, and it has been running.

### How to reproduce

The with statement supports SQL query data preview.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
- [X] #1795
