### ISSUE TITLE
flink web端任务报错了，但是dinky web中该任务还是显示在运行中

### ISSUE THREAD

**Issue by luolaoban9527** [DataLinkDC/dinky#1094]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

在dinky中设置了报警，在flink web端看到某个任务报错重启了，但是dinky中依然显示该任务处于正常的运行状态 ，不会发邮件报警。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by luolaoban9527** [comment]
![lQLPJxbDpAMMFrjNAqfNBuKwkzY0gMoVFCsDQZqeEkBMAA_1762_679](https://user-images.githubusercontent.com/73995685/195518156-b5068d1a-ba98-44e4-8691-631f3a717881.png)

**Comment by luolaoban9527** [comment]
![QQ截图20221013142717](https://user-images.githubusercontent.com/73995685/195518653-794ea91b-7738-468f-b863-33c3762dfff4.png)

**Comment by aiwenmo** [comment]
目前任务重启不会发报警，后续可以支持这种情况

**Comment by luolaoban9527** [comment]
我们现在用的是0.6.6版本，flink web显示任务报错后，dinky web显示还是正常的，不会发送邮件报警！

**Comment by aiwenmo** [comment]
> 我们现在用的是0.6.6版本，flink web显示任务报错后，dinky web显示还是正常的，不会发送邮件报警！

目前有一分钟的容错，后续可以改成配置化

**Comment by gaoyan1998** [comment]
1.0 Alarm related strategies have been reconstructed
