### ISSUE TITLE
[Bug] [Module Name] Bug title 计算血缘失败

### ISSUE THREAD

**Issue by gujincheng** [DataLinkDC/dinky#1096]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

在以下2种情况计算血缘会失败
1. 先删除表，再创建表，再执行insert into
2. 之前已经创建过表，sql里不再创建表，直接执行insert into

报错如下：
![image](https://user-images.githubusercontent.com/26380832/195553421-42432e41-e261-476b-944b-b2b471da8284.png)

### What you expected to happen

说明这里计算血缘是直接解析的当前的sql语句，我感觉这里应该是先解析当前sql，如果解析不成功，会去catalog里获取表的元数据，然后再继续计算血缘

### How to reproduce

1. 先删除表，再创建表，再执行insert into
2. 之前已经创建过表，sql里不再创建表，直接执行insert into

### Version

0.6.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
血缘在不使用 catalog 的情况下，需要一次性执行完整的语句，包含建表语句。
