### ISSUE TITLE
[Feature][pom] add spotless plugins

### ISSUE THREAD

**Issue by gtk96** [DataLinkDC/dinky#1101]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add this plug-in to help improve the code format. 
 
When the code changes, run mvn spotless: apply to repair the code style

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gtk96** [comment]
My idea comes from the dolphinscheduler community and the pom of the Flink cdc community

**Comment by aiwenmo** [comment]
Hi. It's a good idea. thx
