### ISSUE TITLE
[Bug] [dlink-scheduler]  dlink里选择前置任务后，在DS里与前置任务不能在同一个工作流

### ISSUE THREAD

**Issue by SongGary** [DataLinkDC/dinky#1104]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

我将dinky里开发的数据计算任务推送到DS调度。
第一个任务推送过去，新建一个任务定义 和 工作流定义。
第二个任务设置第一个任务为前置任务并推送过去，DS里并不能保持这种前后置关系，而且第二个任务也不在同一个工作流，而同时也没有生成工作流，而是工作流：0。

### What you expected to happen

推送两个设置前置关系的计算任务，在DS里保持前后置关系并在同一个工作流里。

### How to reproduce

开发两个简单任务，设置前置关系并推送DS就可以。

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
dinky 不会去做这个逻辑 自行衡量
