### ISSUE TITLE
[Bug] [dlink-web] 任务编辑页面只能编辑一个任务Tab

### ISSUE THREAD

**Issue by SongGary** [DataLinkDC/dinky#1113]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

新建一个任务，打开一个编辑Tab，没有问题。
如果我再点击一个任务，打开一个tab, 新任务可以查看、编辑。
但是我若切换到第一个任务tab，则第一个任务展示为白板，不能编辑，其他任务则无法打开，变为不可编辑的状态。

### What you expected to happen

可以打开多个任务开发Tab，并在多个Tab页面任意顺畅的切换

### How to reproduce

先后创建两个任意的任务Tab页面，并尝试切换就可以。

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
dev 未复现这个bug。

**Comment by gaoyan1998** [comment]
> dev 未复现这个bug。

有的，两个sql tab切换就会这样，目前最新dev还是存在这个bug
