### ISSUE TITLE
[Bug] [metadata] PG数据库元数据获取schema失败

### ISSUE THREAD

**Issue by boolean-dev** [DataLinkDC/dinky#1130]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

我使用的是 AWS 的 RDS PostgreSQL数据库，在获取数据表的元数据时，无法获取 schema，在查看日志和源码之后，发现获取 schema  的 sql存在问题：
![image](https://user-images.githubusercontent.com/20177406/197167224-47487d07-e09e-4a02-bd97-31720f745e3c.png)
![image](https://user-images.githubusercontent.com/20177406/197167291-2f5a7e8e-2cdf-475b-a220-c8076f866148.png)

建议改成如下的查询 schema SQL
> 此 SQL是从 Navicat 获取 PG的schema改造而来，应该说通用性更好一些：
```sql
SELECT nspname AS "schema_name" FROM pg_namespace WHERE nspname NOT LIKE 'pg_%' AND nspname != 'information_schema';
```

### What you expected to happen

正常获取PG数据库的schema

### How to reproduce

获取 AWS RDS PostgreSQL 的schema

### Anything else

后续我会提交相应的PR
> 目前我已经在 AWS RDS Aurora PostgreSQL、AWS RDS PostgreSQL、PostgreSQL12、PostgreSQL13 上进行了测试，新的SQL都可以正常获取 schema

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
很棒，期待您的PR~

**Comment by boolean-dev** [comment]
您好，我这个bug的提交好像已经合到了dinky的dev了，我就不再次进行 pr了
另外一个 kafka #1083 的 issue 我这边再次申请一次 PR
