### ISSUE TITLE
[Feature] The task directory can support flexible adjustment or automatic sorting by first letter

### ISSUE THREAD

**Issue by zhanghairui521** [DataLinkDC/dinky#1134]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

![Uploading 实时计算任务目录.png…]()

随着Dinky在生产环境的深入使用，越来越多的业务基于Dinky完成开发，但是文件夹及任务的位置都是按照创建的先后排序的
	1、是否可以支持按照首字母排序目录 或 手动拖拽调整文件夹上下顺序
	2、文件夹中的任务顺序无法调整，最好也是可以按照首字母排序 或 手动拖拽调整上下顺序

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
这是一个必要的功能，那么是首字母排序较好还是拖拽调整顺序好呢

**Comment by zhanghairui521** [comment]
> 这是一个必要的功能，那么是首字母排序较好还是拖拽调整顺序好呢

就我们目前应用的话，目录中展示的是任务别名，也就是以中文为主，以首字母排序的方式并不是那么直观？所以相对我可能更倾向拖拽调整顺序。

**Comment by suxinshuo** [comment]
Can I try this? The similar system I used before was sorted by first letter. I can first implement a version that is sorted by first letter.

**Comment by Zzm0809** [comment]
> Can I try this? The similar system I used before was sorted by first letter. I can first implement a version that is sorted by first letter.

Ofcourse, but you need to develop this feature based on the dev branch !
Can you tell me about your design?

**Comment by suxinshuo** [comment]
> > Can I try this? The similar system I used before was sorted by first letter. I can first implement a version that is sorted by first letter.
> 
> Ofcourse, but you need to develop this feature based on the dev branch ! Can you tell me about your design?

I see that the directory tree is now sorted by Catalogue id before build it. I will try to change it to sort by name.

![image](https://github.com/DataLinkDC/dinky/assets/34018346/2ddae790-c9fa-49e7-9ceb-30f4a30b61b5)

**Comment by Zzm0809** [comment]
> > > Can I try this? The similar system I used before was sorted by first letter. I can first implement a version that is sorted by first letter.
> > 
> > 
> > Ofcourse, but you need to develop this feature based on the dev branch ! Can you tell me about your design?
> 
> I see that the directory tree is now sorted by Catalogue id before build it. I will try to change it to sort by name.
> 
> ![image](https://private-user-images.githubusercontent.com/34018346/325072738-2ddae790-c9fa-49e7-9ceb-30f4a30b61b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzA5NzEsIm5iZiI6MTcxMzkzMDY3MSwicGF0aCI6Ii8zNDAxODM0Ni8zMjUwNzI3MzgtMmRkYWU3OTAtYzlmYS00OWU3LTljZWItMzBmNGEzMGI2MWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDAzNTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNGMyMDliOWQ1YzM5NDBmZGFmNTk2NDU2OTk4NDZjZjMyYmMwZTgxMTUzODJmZDdlMTY4NWZhOTVjZjAyYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6WJ4uZdkGJQlXKj3aJtLkS9J-2R3Hwx58EqY7ou8uJc)

Of course this is possible, but how to sort freely according to the front-end selection?

I think if this function is implemented, can it support different sorting strategies, such as ascending and descending order according to the name, ascending and descending order according to the directory name, or ascending and descending order according to the task creation time, etc.

**Comment by suxinshuo** [comment]
@Zzm0809 Yes, your idea is better. I will give the design tomorrow.

**Comment by Zzm0809** [comment]
> @Zzm0809 Yes, your idea is better. I will give the design tomorrow.

note: Drag and drop sorting is not considered for the time being.

If you have different ideas, you can implement them directly
I suggest that you can have the following sorting items(Only personal advice):
![image](https://github.com/DataLinkDC/dinky/assets/58576849/d0dd3db3-5ddd-4fdc-9d87-9fb9c77c038c)

**Comment by suxinshuo** [comment]
> > @Zzm0809 Yes, your idea is better. I will give the design tomorrow.
> 
> note: Drag and drop sorting is not considered for the time being.
> 
> If you have different ideas, you can implement them directly I suggest that you can have the following sorting items(Only personal advice): ![image](https://private-user-images.githubusercontent.com/58576849/325095891-d0dd3db3-5ddd-4fdc-9d87-9fb9c77c038c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTc1OTcsIm5iZiI6MTcxMzk1NzI5NywicGF0aCI6Ii81ODU3Njg0OS8zMjUwOTU4OTEtZDBkZDNkYjMtNWRkZC00ZmRjLTlkODctOWZiOWM3N2MwMzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDExMTQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliZTU4MGVhOWViYWFmMGYyN2JjYWNiMjgzMTFlZWZhNWNiM2IwOWUwMTM1OTBlYWY1NjI1MTZjNjE4MDk4M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oeGBIKgN1fHZKrQ_TwEaNf4wpHVW0nSJ_YbzUoq6jec)

I don't understand the rule of sorting by directory name. If there are directories and tasks at the same level, how to sort them? Can you give an example?

**Comment by Zzm0809** [comment]
> > > @Zzm0809 Yes, your idea is better. I will give the design tomorrow.
> > 
> > 
> > note: Drag and drop sorting is not considered for the time being.
> > If you have different ideas, you can implement them directly I suggest that you can have the following sorting items(Only personal advice): ![image](https://private-user-images.githubusercontent.com/58576849/325095891-d0dd3db3-5ddd-4fdc-9d87-9fb9c77c038c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTc1OTcsIm5iZiI6MTcxMzk1NzI5NywicGF0aCI6Ii81ODU3Njg0OS8zMjUwOTU4OTEtZDBkZDNkYjMtNWRkZC00ZmRjLTlkODctOWZiOWM3N2MwMzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDExMTQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliZTU4MGVhOWViYWFmMGYyN2JjYWNiMjgzMTFlZWZhNWNiM2IwOWUwMTM1OTBlYWY1NjI1MTZjNjE4MDk4M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oeGBIKgN1fHZKrQ_TwEaNf4wpHVW0nSJ_YbzUoq6jec)
> 
> I don't understand the rule of sorting by directory name. If there are directories and tasks at the same level, how to sort them? Can you give an example?

The backend sorts recursively after getting the final tree structure.

Or you can implement simple name sorting first
