### ISSUE TITLE
[Bug] [dlink-admin] config.getGatewayConfig() maybe NPE

### ISSUE THREAD

**Issue by leechor** [DataLinkDC/dinky#1140]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

local environment submit sql statement, because of [config.getGatewayConfig().getType()](https://github.com/DataLinkDC/dlink/blob/f53833affc7af601f86fd0701cccb3b3f06804ae/dlink-admin/src/main/java/com/dlink/service/impl/StudioServiceImpl.java#L178)

### What you expected to happen

empty

### How to reproduce

empty

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
thx. I am willing to submit a Fix.

**Comment by aiwenmo** [comment]
已修复

**Comment by aiwenmo** [comment]
Fixed.
