### ISSUE TITLE
[Bug] [dlink web] BI->折线图-阶梯线开关打开后关闭无效，依然保持阶梯线效果

### ISSUE THREAD

**Issue by zhangzhaohuazai** [DataLinkDC/dinky#1169]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

BI->折线图-阶梯线开关打开后关闭无效，依然保持阶梯线效果

### What you expected to happen

首次点击打开阶梯线按钮，图像显示为阶梯线效果，而再次点击即可恢复原始图像，多次点击能够正常显示阶梯线效果和关闭该效果

### How to reproduce

选择BI中的折线图，配置x轴y轴，然后让图线显示出来。然后多次点击阶梯线开关

### Version

0.6.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
BI has delete at 1.0
