### ISSUE TITLE
[Feature][Dlink-Admin] 新增作业树目录级删除功能（包括删除子目录/作业）

### ISSUE THREAD

**Issue by Forus0322** [DataLinkDC/dinky#1236]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

新增作业树一键删除目录以及子目录/作业功能。

删除时递归校验所有子作业，是否存运行中作业，如果存在则无法删除，并弹出运行中作业ID以便用户排查。
当所有子作业均是非运行状态时，则删除所有子目录/作业以及当前目录。

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
弹出运行中作业ID以便用户排查。
------------------
这个提示ID会不会体验不太好呢 ， 建议返回对象，提示作业名称

**Comment by Forus0322** [comment]
> ## 弹出运行中作业ID以便用户排查。
> 这个提示ID会不会体验不太好呢 ， 建议返回对象，提示作业名称
> 业名称

好，稍后修改返回作业名称，方便用户排查。

**Comment by Forus0322** [comment]
已修改并重新提了PR
