### ISSUE TITLE
[Bug] [日志] 日志级别为info, 控制台能打印Error 日志，日志文件中无。

### ISSUE THREAD

**Issue by deepthinkin** [DataLinkDC/dinky#1244]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

env:
dlink on k8s 
log4j2.xml 保持默认未修改的情况 ,日志文件中不能记录error 日志，控制台可以
![image](https://user-images.githubusercontent.com/23011292/201261085-1f6d055e-a6a0-4042-a96f-15fafffdf1ae.png)

控制台打印的A B 区域日志信息，日志文件中只有A区域的内容
![image](https://user-images.githubusercontent.com/23011292/201270803-08e1b71d-a6a1-4dc1-b84a-54bda7625862.png)

另外 部署时可否把log4j2.xml 放置jar外面，这样的话可灵活更改日志配置。

### What you expected to happen

nothing

### How to reproduce

nothing

### Anything else

nothing

### Version

0.6.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
0.6.7 的log4j2.xml 在 jar外面

**Comment by deepthinkin** [comment]
看了下代码，异常信息没有写到日志文件，原因是代码中没有加log相关的代码，dlink-metadata-base 模块建议加上log.
![image](https://user-images.githubusercontent.com/23011292/201452547-2269e61e-31e5-45ee-a13f-ee6f3d633f3f.png)
