### ISSUE TITLE
[Bug] [CDCSOURCE]  Failed to sync data to Iceberg using dinky CDCSOURCE

### ISSUE THREAD

**Issue by MrDannyWu** [DataLinkDC/dinky#1270]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What you expected to happen

I think that CDCSOURCE is not adapted to iceberg, and it is not loaded into hive catalog, so it becomes the default catalog and default table, resulting in writing iceberg tables that are not based on hive.

### How to reproduce

1. I create hive_catalog through sqlenv.
```
CREATE CATALOG hive_iceberg
WITH (
    'clients'='5',
    'type'='iceberg',
    'catalog-type'='hive',
    'property-version'='1',
    'uri'='thrift://nn-1:9083',
    'warehouse'='hdfs://nn-1:8020/user/hive/warehouse/'
);
```
![image](https://user-images.githubusercontent.com/19458048/202630872-6dabdda9-73a8-4e46-bb28-cee9057c3e38.png)

 2. I create a CDCSOURCE 
 ```
    'connector'='mysql-cdc',
    'hostname'='192.168.101.98',
    'port'='3306',
    'username'='',
    'password'='',
    'database-name'='db_test',
    'table-name'='db_test\.ice_test',
    'source.debezium.skipped.operations'='d',
    'source.server-id'='5859',
    'sink.connector'='iceberg',
    'checkpoint'='3000',
    'parallelism'='1',
    'sink.type'='iceberg',
    'sink.uri'='thrift://nn-99:9083,thrift://nn-100:9083',
    'sink.sink.db'='dwd',
    'sink.table.prefix'='dwd_1_',
    'sink.table.lower'='true',
    'sink.catalog-type'='hive',
    'sink.catalog-name'='hive_catalog',
    'sink.format-version'='2',
    'sink.iceberg.mr.catalog'='hive',
    'sink.engine.hive.enabled'='true',
    'sink.write.upsert.enabled'='true',
    'sink.write.metadata.previous-versions-max'='3',
    'sink.hive.vectorized.execution.enabled'='false',
    'sink.write.metadata.delete-after-commit.enabled'='true',
    'sink.warehouse'='hdfs://nameservice1/user/hive/warehouse/dwd.db/${tableName}'
```
![image](https://user-images.githubusercontent.com/19458048/202631229-cc67c202-a4f3-49db-aa0c-38aebca511f4.png)

3. The task can be submitted successfully and no error is reported, but it is not loaded to the catalog, and the data writing path is wrong.
![image](https://user-images.githubusercontent.com/19458048/202631465-05081a4e-7d14-471e-bdb5-ba20367d390c.png)
![image](https://user-images.githubusercontent.com/19458048/202632122-43e6a62a-950a-4085-8968-b91da61527e3.png)

### Version

0.6.7

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by maqiang0813** [comment]
Hi MrDannyWu , you can try to use below sql you can get the right  iceberg table location in /user/hive/warehouse/test.db/${tableName}.  and everything is working well.
EXECUTE CDCSOURCE cdcsource2iceberg WITH (
  'connector' = 'mysql-cdc',
  'hostname' = 'xxx',
  'port' = '3306',
  'username' = 'xxx',
  'password' = 'xxx',
  'checkpoint' = '3000',
  'scan.startup.mode' = 'initial',
  'parallelism' = '1',
  'table-name' = 'test\.test_1,test\.test_2',
  'sink.connector'='iceberg',
  'sink.type'='iceberg',
  'sink.clients'='1',
  'sink.property-version'='1',
   'sink.uri'='thrift://xxx:9083',
   'sink.table.lower'='true',
   'sink.catalog-type'='hive',
   'sink.catalog-name'='hive_catalog',
   'sink.catalog-database'='test',
   'sink.catalog-table'='${tableName}',
   'sink.format-version'='2',
   'sink.write.upsert.enabled'='true',
   --'sink.write.metadata.previous-versions-max'='3',
   --'sink.write.metadata.delete-after-commit.enabled'='true',
   'sink.warehouse'='hdfs://xxx/user/hive/warehouse'
);

But there is another problem, now table name 'sink.catalog-table' cannot be  set a user defined name. 
but if the value of 'sink.catalog-table' is not '${tableName}' but a concrete name  like 'test_user', then the flink task cannot run correctly. if you don't set 'sink.catalog-table' ,then the program will generate a table automatically with suffix "_x" (x is a number) .that's to say ,when you restart the flink task, a new table with a new suffix number will be created.
so for now, use cdcsouce cannot sink data into a user defined table and also you cannot compact many tables into one iceberg table.

I think we should fix the issue that iceberg table  'sink.catalog-table' cannot be  set a user defined name.

**Comment by MrDannyWu** [comment]
> Hi MrDannyWu , you can try to use below sql you can get the right iceberg table location in /user/hive/warehouse/test.db/${tableName}. and everything is working well. EXECUTE CDCSOURCE cdcsource2iceberg WITH ( 'connector' = 'mysql-cdc', 'hostname' = 'xxx', 'port' = '3306', 'username' = 'xxx', 'password' = 'xxx', 'checkpoint' = '3000', 'scan.startup.mode' = 'initial', 'parallelism' = '1', 'table-name' = 'test.test_1,test.test_2', 'sink.connector'='iceberg', 'sink.type'='iceberg', 'sink.clients'='1', 'sink.property-version'='1', 'sink.uri'='thrift://xxx:9083', 'sink.table.lower'='true', 'sink.catalog-type'='hive', 'sink.catalog-name'='hive_catalog', 'sink.catalog-database'='test', 'sink.catalog-table'='${tableName}', 'sink.format-version'='2', 'sink.write.upsert.enabled'='true', --'sink.write.metadata.previous-versions-max'='3', --'sink.write.metadata.delete-after-commit.enabled'='true', 'sink.warehouse'='hdfs://xxx/user/hive/warehouse' );
> 
> But there is another problem, now table name 'sink.catalog-table' cannot be set a user defined name. but if the value of 'sink.catalog-table' is not '${tableName}' but a concrete name like 'test_user', then the flink task cannot run correctly. if you don't set 'sink.catalog-table' ,then the program will generate a table automatically with suffix "_x" (x is a number) .that's to say ,when you restart the flink task, a new table with a new suffix number will be created. so for now, use cdcsouce cannot sink data into a user defined table and also you cannot compact many tables into one iceberg table.
> 
> I think we should fix the issue that iceberg table 'sink.catalog-table' cannot be set a user defined name.

Ok, thanks for your reply, hopefully this will be fixed soon in the future.
