### ISSUE TITLE
[Bug] Failed to login in.

### ISSUE THREAD

**Issue by jefftlin** [DataLinkDC/dinky#1271]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

I login in with admin/admin but the log saw some output as follows：
![企业微信截图_16687640244624](https://user-images.githubusercontent.com/57786627/202669555-d25c4a27-25ab-42a8-9fd7-6f36c6dac8a6.png)

### What you expected to happen

Start success!

### How to reproduce

1、Config the mysql connection on application.yml, the version of my mysql is 5.7.31
2、Execute "sh auto.sh start" and login in with admin/admin

### Anything else

It seems like need to config token, but no tips in the docs. 

### Version

0.6.7

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Log in to the system from the login page.

**Comment by jefftlin** [comment]
> Log in to the system from the login page.

It's a landing page. http://127.0.0.1:9999/#/user/login
![企业微信截图_1668772184260](https://user-images.githubusercontent.com/57786627/202698822-64b5a1a6-56c9-4cde-bd11-ec94352c6605.png)
Need I add some config. The connection information of mysql is currently configured, but there is no other information.

**Comment by jefftlin** [comment]
The status code is 500

**Comment by aiwenmo** [comment]
At present, only you have encountered this problem. Please carefully check every step of deployment.
