### ISSUE TITLE
[Feature][sql] finksql 引入关于日期的变量

### ISSUE THREAD

**Issue by dzygcc** [DataLinkDC/dinky#1290]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

flink sql 中经常需要yyyyMMdd 格式的日期，并且需要该日期需要随着时间的变化而变化。

实现方法：

引入内置变量${yyyyMMdd}, 在变量替换阶段，将该变量替换成当前的日期。

另外，同时支持日期的加减，例如${yyyyMMdd-1}  表示当前日期前1天，${yyyyMMdd+1} 表示当前日期后面一天。 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leeoo** [comment]
感觉变量名改成 `_CURRENT_DATE_` 这种会比 "yyyyMMdd" 这种格式化字符串更好些

**Comment by Zzm0809** [comment]
pr is #1320
