### ISSUE TITLE
[Bug] [dlink app] k8s submit failed

### ISSUE THREAD

**Issue by gaoyan1998** [DataLinkDC/dinky#1311]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

In normal times, k8s is fine, but if the database is changed to a complex password with special characters, dlink-app will receive an incomplete password, resulting in a failure to connect to the database

### What you expected to happen

For example:
 the password is :  AGTUKSX16894&#^@zxcv
 and the dlink-app receive is : AGTUKSX16894&  
the last was lost

### How to reproduce

.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by czy868** [comment]
app是通过命令行获取账号密码的，命令行遇见#就截断掉了，可以在外层套一个单引号就能解决了。不过这个问题要兼容掉吗？还是让用户自己规避啊？ @aiwenmo
