### ISSUE TITLE
[Bug] [web] F2 全屏不可用

### ISSUE THREAD

**Issue by conghe2402** [DataLinkDC/dinky#1321]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

任务编辑窗口内 F2 ，全屏展开，但是无法编辑和使用

### What you expected to happen

F2 全屏模式下可编辑任务

### How to reproduce

进入任务编辑界面 按下F2

### Version

0.7.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
看下任务是不是已发布或者已上线了

**Comment by Zzm0809** [comment]
未复现
