### ISSUE TITLE
任务被kill掉很长时间了，在运维中心依然显示运行中

### ISSUE THREAD

**Issue by LiuHao0606** [DataLinkDC/dinky#1322]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar document requirement.

### Description

1.已经被kill掉的任务（flink的webui界面手动点击canal吧任务kill），依然显示运行中(此时距任务被kill掉一过去一小时)
![image](https://user-images.githubusercontent.com/53438025/203933820-56cb2c4e-96fd-4c9d-a4a4-bca078b3b9f6.png)
2.此任务的flink webui界面已经无法访问，yarn显示任务被kill
3.点击普通停止，提示停止成功，查看日志显示：com.dlink.api.FlinkAPI 83 get - Unable to connect to Flink JobManager: http://xx.x.xx.xxx:51005

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
请问是使用的0.7.0的安装包吗，0.7.0的左上角任务状态会更新成 停止 的，下方还是 运行中

**Comment by LiuHao0606** [comment]
是的，0.7.0，任务现在还是显示在运行中
![image](https://user-images.githubusercontent.com/53438025/203974332-dd41bca1-3d54-422f-a257-9103c2418c09.png)

**Comment by LiuHao0606** [comment]
是的，0.7.0的安装包
![image](https://user-images.githubusercontent.com/53438025/203974663-5f48887c-f57e-4833-aa76-f6d37e47ecad.png)

**Comment by gaoxianzhu** [comment]
我也遇到了同样的问题，最新发布的0.7.0版本，任务已经停止了，点进去还显示运行中
![image](https://user-images.githubusercontent.com/112841355/210727947-c81dfbd9-4aa7-4a29-89fa-914acb223ee1.png)
![image](https://user-images.githubusercontent.com/112841355/210727960-89841f7c-de46-4803-ab96-b2e56fb417f2.png)

**Comment by zhangzhaohuazai** [comment]
我也有遇到
