### ISSUE TITLE
[Bug] [Module Name] openapi/submitTask接口任务重启的提交报错

### ISSUE THREAD

**Issue by wangyepeng22** [DataLinkDC/dinky#1345]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/82625429/204452166-3c38dfdf-be17-42e6-85b9-a3c3cd5dd220.png)
http://192.168.***:8887/openapi/submitTask
请求接口提示用户未登录
![image](https://user-images.githubusercontent.com/82625429/204452252-4312b9bc-b59c-4063-ae50-eb3f48a45294.png)
查看代码里面需要获取用户id

### What you expected to happen

期望重启服务不走用户鉴权

### How to reproduce

http://192.168.***:8887/openapi/submitTask
接口请求,不要报错
{"datas":null,"code":401,"msg":"用户未登录，请先登录","time":"2022-11-29 14:00:53"}

### Version

0.7.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
已修复
