### ISSUE TITLE
Dinky任务状态在dolphinscheduler返回有问题

### ISSUE THREAD

**Issue by wangyayuan18** [DataLinkDC/dinky#1347]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

dinky推送任务到dolphinscheduler调度任务，任务状态返回失败，但yarn上面表示任务已经运行成功

![9ea5b82611d0ba863f7849a6577f4d8](https://user-images.githubusercontent.com/64136230/204471964-abf9510c-7574-4322-b592-c5a8cc2d524b.png)

![6055ed8fd13d5a99a8c02fd6f35a4e9](https://user-images.githubusercontent.com/64136230/204471991-a9a113f9-e8be-495e-ad46-83eed55e80c4.png)

![a9ac4012a127679cedb425e953b5fb1](https://user-images.githubusercontent.com/64136230/204472005-5209cb7a-9289-4d4d-96ef-4ba2064bc68c.png)

### What you expected to happen

1

### How to reproduce

1

### Version

0.7.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
- [X] #1368
