### ISSUE TITLE
[Bug] [计算血缘] FlinkSql中使用了全局变量后，无法计算血缘

### ISSUE THREAD

**Issue by tyzheng114** [DataLinkDC/dinky#1349]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

在dinky-0.7.0-rc2版本中,FlinkSQL任务使用了用${}引入的全局变量后（全局变量已注册并且任务已启用全局变量），计算血缘发现显示为空，用实际值替换这个全局变量的表达式后，血缘正常计算

### What you expected to happen

有全局变量的情况下，应当也能正常计算血缘

### How to reproduce

1.在全局变量中注册一个全局变量，例如${connector}='connector';
2.创建一个FlinkSql任务，并且开启全局变量
3.FlinkSql中使用${connector},例如
CREATE TABLE datagen (
 f_random INT,
 f_random_str STRING,
 ts AS localtimestamp,
 WATERMARK FOR ts AS ts
) WITH (
 'connector' = 'datagen',
 'rows-per-second'='5',
 'fields.f_random.min'='1',
 'fields.f_random.max'='1000',
 'fields.f_random_str.length'='10'
);
CREATE TABLE printCon (
 f_random INT,
 f_random_str STRING
) WITH (
 ${connector} = 'print'
);
INSERT INTO printCon 
select f_random,f_random_str from datagen;
4.计算血缘后发现显示为空，通过浏览器的开发者工具发现计算血缘的返回值为空

### Version

0.7.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhu-mingye** [comment]
${connector} 变量预先声明了吗

**Comment by zhu-mingye** [comment]
hi, 复现原因为 带有 **WATERMARK** 的sql 解析不出来血缘， 与全局变量无关

**Comment by aiwenmo** [comment]
- [X] #1355
