### ISSUE TITLE
jdbc sqlserver url中包含";"，dlink语法检查无法通过

### ISSUE THREAD

**Issue by ghost** [DataLinkDC/dinky#1350]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

'connector' = 'jdbc',
 'url'='jdbc:sqlserver://121.10.39.20:1433;DatabaseName=test'

url中有";"，dlink语法检查无法通过；测试flink sql-client不受影响。
dlink中，在任何地方加上";"（除sql语句末尾或注释以外），语法检查都无法通过。

### What you expected to happen

。

### How to reproduce

dlink中，在任何地方加上";"（除sql语句末尾或注释以外）

### Anything else

  。

### Version

0.6.7

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
**系统设置** 内修改下语句分隔符(可以设置为在sql中没出现过的符号) 同时在作业中 语句结束的分隔符按照更新后的值修改下 并保存

**Comment by ghost** [comment]
> **系统设置** 内修改下语句分隔符(可以设置为在sql中没出现过的符号) 同时在作业中 语句结束的分隔符按照更新后的值修改下 并保存

明白了~谢谢
