### ISSUE TITLE
[Feature]请求支持Kafka数据源

### ISSUE THREAD

**Issue by apa7** [DataLinkDC/dinky#1356]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Flink团队开发者，你们好！
我们团队准备使用debezium+kafka+flink，dinky管理台的数据源管理能否支持 配置kafka数据源并管理查看topic情况呢？
感谢！

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
后续会有相关支持
