### ISSUE TITLE
前端-配置中心-UDF模板、新增UDF函数模板时，代码块样式BUG

### ISSUE THREAD

**Issue by biandou1313** [DataLinkDC/dinky#1360]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

![1669941829088_0C08A286-1F4C-42b6-8061-8CE9027B66E9](https://user-images.githubusercontent.com/34857750/205197562-e36df5a1-d90d-4071-8310-7db8c5650253.png)

### What you expected to happen

![1669941829088_0C08A286-1F4C-42b6-8061-8CE9027B66E9](https://user-images.githubusercontent.com/34857750/205197562-e36df5a1-d90d-4071-8310-7db8c5650253.png)

### How to reproduce

![1669941829088_0C08A286-1F4C-42b6-8061-8CE9027B66E9](https://user-images.githubusercontent.com/34857750/205197562-e36df5a1-d90d-4071-8310-7db8c5650253.png)

### Version

0.7.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
pr #1388
