### ISSUE TITLE
[Optimization][WebUI] Add "Clear All" menu item to clear all log in right click dialog on DataStudio's Info console

### ISSUE THREAD

**Issue by leeoo** [DataLinkDC/dinky#1378]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

Dinky 0.7.0-rc2

Add "Clear All" menu item to clear all log in right click dialog on DataStudio's Info console.

Optimization result like below.

![图片](https://user-images.githubusercontent.com/2136182/205531576-b920bddb-1561-4fb9-a9ca-30648733bf0c.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
![image](https://user-images.githubusercontent.com/32723967/210126862-1f32b8aa-fdf5-4b81-9a47-a9e9a7ef569e.png)
