### ISSUE TITLE
[Bug] [数据开发] 已运行过Flink作业无法删除 

### ISSUE THREAD

**Issue by jiamingjing** [DataLinkDC/dinky#1381]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

新创建任务未运行时可正常删除，新创建任务运行一次后，手动停止任务，再操作删除任务，此时提示删除失败，请检查作业[xxxxx]状态。

### What you expected to happen

任务非运行状态可正常删除。

### How to reproduce

新创建Flink作业，并运行，任务正常运行后，取消任务运行。任务此时为停止状态，左侧目录中点鼠标右键选择删除作业

### Anything else

源码定位到CatalogueServiceImpl如下步骤时发现作业状态比对错误：
                if (job == null
                        || (JobStatus.FINISHED.equals(job.getStatus())
                                || JobStatus.FAILED.equals(job.getStatus())
                                || JobStatus.CANCELED.equals(job.getStatus())
                                || JobStatus.UNKNOWN.equals(job.getStatus()))) {
修改为如下重新编译后，作业可正常删除
                if (job == null
                        || (JobStatus.FINISHED.getValue().equals(job.getStatus())
                                || JobStatus.FAILED.getValue().equals(job.getStatus())
                                || JobStatus.CANCELED.getValue().equals(job.getStatus())
                                || JobStatus.UNKNOWN.getValue().equals(job.getStatus()))) {

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
您好，非常感谢您的bug反馈以及修复建议。此外欢迎提交PR修复此bug。

**Comment by Zzm0809** [comment]
pr is #1430
