### ISSUE TITLE
[Bug] [元数据中心] 当mysql中的库名包含'-'时,元数据查看时报错

### ISSUE THREAD

**Issue by LiuHao0606** [DataLinkDC/dinky#1382]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.点击数据查询，直接报错
![1670232257634](https://user-images.githubusercontent.com/53438025/205601771-a9b8c34c-3e15-4b09-bc0e-5fc8193d22b8.jpg)

2.SQL 生成为空
![image](https://user-images.githubusercontent.com/53438025/205602221-a4327292-9eef-4b44-afc4-3d3f74dc1105.png)

### What you expected to happen

期望正常展示数据

### How to reproduce

-----

### Anything else

-

### Version

0.7.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
什么数据源

**Comment by aiwenmo** [comment]
升级到 0.7.0-rc3 试试，有相关修复
