### ISSUE TITLE
[Bug] [数据开发] flinksql 双引号报错

### ISSUE THREAD

**Issue by det101** [DataLinkDC/dinky#1384]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

flinksql中带双引号或者反斜线都会报语法错误
<img width="707" alt="image" src="https://user-images.githubusercontent.com/3656843/205623944-e62800f2-6b07-4499-9124-f53a3c132a25.png">

flinksql如下
```
CREATE TABLE KafkaTable (
  `user_id` BIGINT,
  `item_id` BIGINT,
  `behavior` STRING,
  `ts` TIMESTAMP(3) METADATA FROM 'timestamp'
) WITH (
  'connector' = 'kafka',
  'properties.security.protocol' = 'SASL_PLAINTEXT',
  'properties.sasl.mechanism' = 'PLAIN',
  'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.plain.PlainLoginModule required username=\"username\" password=\"password\";'
)
```

### What you expected to happen

properties.sasl.jaas.config  支持配置

### How to reproduce

新建flinksql  如下

```
CREATE TABLE KafkaTable (
  `user_id` BIGINT,
  `item_id` BIGINT,
  `behavior` STRING,
  `ts` TIMESTAMP(3) METADATA FROM 'timestamp'
) WITH (
  'connector' = 'kafka',
  'properties.security.protocol' = 'SASL_PLAINTEXT',
  'properties.sasl.mechanism' = 'PLAIN',
  'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.plain.PlainLoginModule required username=\"username\" password=\"password\";'
)
```

点击代码检查

### Version

0.6.7

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by czy868** [comment]
@aiwenmo 我来修复这个

**Comment by czy868** [comment]
0.6.7没测，0.7.0已经没有这个问题
