### ISSUE TITLE
[Bug] [数据开发] 相同任务,使用k8s application 模式只有第一次可以正常提交任务

### ISSUE THREAD

**Issue by hzhili** [DataLinkDC/dinky#1385]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

使用K8S application 模式执行任务，同一个任务第一次可以正常提交，并可以在运维中心中看见任务详情，如果手动停止任务，不修改任务名称的情况下再次执行，就会报Duplicate entry 'test' for key 'idx_name'；查看源码发现在任务提交成功后会在dlink_cluster表插入一条集群信息，但是任务停止的时候却不会进行删除，并且集群名称使用的是任务名称，当任务停止并再次提交时，依旧会使用任务名称进行再次进行插入，而没有进行更新，导致违反唯一约束。

### What you expected to happen

![image](https://user-images.githubusercontent.com/39455920/205628827-d156f8d9-2d31-4286-94d2-378829b8b691.png)

### How to reproduce

1、新建一个flink sql 任务，名称可以随便起；
2、使用K8S application 模式进行提交；
3、第一次成功提交后，手动停止任务；
4、不修改任何内容，待任务停止后，再次进行提交；

### Version

0.6.7

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
在注册中心，集群管理，点一下回收就好了，0.7应该是修复了这个问题

**Comment by hzhili** [comment]
好的,我升级到0.7.0试试
