### ISSUE TITLE
[Bug] [Module Name] 主干分支编译报错

### ISSUE THREAD

**Issue by dzygcc** [DataLinkDC/dinky#1404]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/1546503/206176288-735aa03a-8bfd-4030-93fe-4bfd58ae7f48.png)

### What you expected to happen

idea编译 build通过

### How to reproduce

dev 分支： 09452e8d85d18cc7be33740a29f4fbaa88d438b5

intellij idea  run app 报错。

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by nylqd** [comment]
https://github.com/DataLinkDC/dlink/pull/1389
