### ISSUE TITLE
整库同步会报大量不相关schema的异常[Bug] [Module Name] Bug title 

### ISSUE THREAD

**Issue by mooncake020** [DataLinkDC/dinky#1405]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

比如我mysql数据库下有db1 db2两个schema  我在同步db1时  db2下有个表没有添加主键也会导致控制台报错。

### What you expected to happen

期望做元数据校验时更精确一点 这些无关异常日志会干扰错误排查

### How to reproduce

mysql数据库下创建db1 db2两个schema   在db1创建符合要求的表并同步 在db2创建没有主键的表。

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
在创建整库同步时，目前阶段，dinky 没有元数据的校验。如果你报错了，还请贴下报错信息

**Comment by gaoyan1998** [comment]
This is a problem with Flink CDC, please check the Flink CDC documentation
