### ISSUE TITLE
[Bug] [Module Name] Bug title 整库同步数据获取失败

### ISSUE THREAD

**Issue by mooncake020** [DataLinkDC/dinky#1406]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

整库同步时 提交任务后去flinkwebui  并没有按表创建子任务 只有一个任务  任务内容为：Source: MySQL CDC Source -> Map -> Process -> (Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map, Flat Map)  并没有下一步任务  应该 是解析数据库元数据除了问题

### What you expected to happen

正常解析

### How to reproduce

不确定原因

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mooncake020** [comment]
控制台无异常、log无异常

**Comment by Zzm0809** [comment]
并行度一致会将任务链 chain到一起

**Comment by mooncake020** [comment]
原因明确了 。。。k8s和外部mysql网络问题。。。数据库连接异常
