### ISSUE TITLE
本地调试 添加数据源提示[Bug] [Module Name] 本地调试 添加数据源提示缺少数据源类型

### ISSUE THREAD

**Issue by mooncake020** [DataLinkDC/dinky#1407]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

本地环境 按照文档要求做了相关设置  启动dlink  测试添加 数据源  报缺少数据源类型Mysql的依赖。请在lib下添加对应的依赖扩展。 实际情况是 项目已经依赖了mysql driver 并且后续测试中我也添加了相关 jar作为库添加到dlink-admin项目下  也是无济于事。

### What you expected to happen

正常添加

### How to reproduce

前面已做描述

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
本地调试需要通过 profile 选择 dev 并且去掉 prod

**Comment by Sigal0** [comment]
> 本地调试需要通过 profile 选择 dev 并且去掉 prod

遇到一样的问题，而且profile已经勾选dev，还是会报这个错误，怎么解决啊？
