### ISSUE TITLE
如何支持mysql、pg、oracle 等主流数据库的upsert操作

### ISSUE THREAD

**Issue by cmdares** [DataLinkDC/dinky#1423]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

以mysql为例：
kafka向mysql写入数据的时候能否根据mysql的主键进行比对，如果主键不同，就插入，如果主键相同就更新，例如以下myql中的upsert操作：
insert into oc_product(code,name,updateTime) 
select code,name,updateTime FROM oc_product_tmp
on duplicate key update
code=values(code),name = VALUES(name),updateTime = VALUES(updateTime)

对于oracle 有merge into 。。。。。

### Use case

数据增量更新

### Related issues

无

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
这个 flink-connector-jdbc 支持的
