### ISSUE TITLE
[Bug] [数据开发] 多个任务编辑窗口切换时,已打开的窗口内容消失

### ISSUE THREAD

**Issue by hzhili** [DataLinkDC/dinky#1433]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

当多个任务编辑窗口切换时，窗口内容消失，必须重新打开才能正常显示

### What you expected to happen

![dlink数据开发bug](https://user-images.githubusercontent.com/39455920/207593453-501b2cc1-774c-4230-8405-74f6f60b7087.gif)

### How to reproduce

打开两个或以上编辑器Tab页签，然后点击Tab页签互相切换

### Version

0.7.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hzhili** [comment]
配置中心->UDF模板->新建或编辑不显示模板代码框，应该也是同样的问题

**Comment by Zzm0809** [comment]
已修复这个问题 等 0.7.0-release发版

**Comment by hzhili** [comment]
好的,谢谢
