### ISSUE TITLE
[cdc][mysql]功能标题Flinkcdc 监控binlog的话，如何实现当mysql字段增加的时候，flinksql下的create table 后面的字段也动态的新增呢

### ISSUE THREAD

**Issue by Tangsonghuai** [DataLinkDC/dinky#1444]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Flinkcdc 监控binlog的话，如何实现当mysql字段增加的时候，flinksql下的create table 后面的字段也动态的新增呢

### Use case

--mysql cdc监控一张表，并把数据写入到另外一张表
-- Flink SQL  开启心跳检查
SET execution.checkpointing.interval = 3s;
 
DROP TABLE IF EXISTS source_log;
CREATE TABLE IF NOT EXISTS source_log (
  `user_id` varchar(20) NOT NULL,
  `sex` varchar(20) COMMENT '消费时间',
  -- `data` STRING COMMENT '数据标识',
  PRIMARY KEY (`user_id`) NOT ENFORCED
) COMMENT '记录表' WITH (
  'connector' = 'mysql-cdc',
  'hostname' = '172.18.1.16',
  'port' = '3306',
  'username' = 'root',
  'password' = 'Fulin@888',
  'database-name' = 'test',
  'table-name' = 'user_info'
);
 
-- 目标表，使用jdbc连接器
DROP TABLE IF EXISTS log;
CREATE TABLE IF NOT EXISTS log (
  `user_id` varchar(20) NOT NULL,
  `sex` varchar(20) COMMENT '消费时间',
  PRIMARY KEY (`user_id`) NOT ENFORCED
) COMMENT '记录表' WITH (
  'connector' = 'jdbc',
  'url' = 'jdbc:mysql://172.18.1.16:3306/test',
  'username' = 'root',
  'password' = 'Fulin@888',
  'table-name' = 'log'
);
-- 执行同步
INSERT INTO log SELECT * FROM source_log;

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wellCh4n** [comment]
Are you looking for Schema Evolution?

**Comment by Tangsonghuai** [comment]
> Are you looking for Schema Evolution?

About dinky? no, I have not ever seen the 'Schema Evolution' in dinky 's doc! please help

**Comment by wellCh4n** [comment]
> > Are you looking for Schema 
> >         Evolution
> >         ?
> 
> About dinky? no, I have not ever seen the 'Schema Evolution ' in dinky 's doc! please help

Sadly, as you know, dinky does not support mysql schema evolution. But i saw a new commit in cdc module https://github.com/DataLinkDC/dlink/commit/09452e8d85d18cc7be33740a29f4fbaa88d438b5 , that is Doris schema evolution FYI.
But I am not practicing this. @aiwenmo could you talk to us more about this feature? I hear you will be speaking about this feature at the Doris meeting.

**Comment by aiwenmo** [comment]
> > > Are you looking for Schema
> > > Evolution
> > > ?
> > 
> > 
> > About dinky? no, I have not ever seen the 'Schema Evolution ' in dinky 's doc! please help
> 
> Sadly, as you know, dinky does not support mysql schema evolution. But i saw a new commit in cdc module [09452e8](https://github.com/DataLinkDC/dlink/commit/09452e8d85d18cc7be33740a29f4fbaa88d438b5) , that is Doris schema evolution FYI. But I am not practicing this. @aiwenmo could you talk to us more about this feature? I hear you will be speaking about this feature at the Doris meeting.

Please follow this Doris Summit.

**Comment by Tangsonghuai** [comment]
> > > > Are you looking for Schema
> > > > Evolution
> > > > ?
> > > 
> > > 
> > > About dinky? no, I have not ever seen the 'Schema Evolution ' in dinky 's doc! please help
> > 
> > 
> > Sadly, as you know, dinky does not support mysql schema evolution. But i saw a new commit in cdc module [09452e8](https://github.com/DataLinkDC/dlink/commit/09452e8d85d18cc7be33740a29f4fbaa88d438b5) , that is Doris schema evolution FYI. But I am not practicing this. @aiwenmo could you talk to us more about this feature? I hear you will be speaking about this feature at the Doris meeting.
> 
> Please follow this Doris Summit.

hi，bro,Could you give me this 'Doris Summit' 's url or image? I can't find this in network, sorry。
是说的2023年1月初的doris峰会吗？

**Comment by aiwenmo** [comment]
> > > > > Are you looking for Schema
> > > > > Evolution
> > > > > ?
> > > > 
> > > > 
> > > > About dinky? no, I have not ever seen the 'Schema Evolution ' in dinky 's doc! please help
> > > 
> > > 
> > > Sadly, as you know, dinky does not support mysql schema evolution. But i saw a new commit in cdc module [09452e8](https://github.com/DataLinkDC/dlink/commit/09452e8d85d18cc7be33740a29f4fbaa88d438b5) , that is Doris schema evolution FYI. But I am not practicing this. @aiwenmo could you talk to us more about this feature? I hear you will be speaking about this feature at the Doris meeting.
> > 
> > 
> > Please follow this Doris Summit.
> 
> hi，bro,Could you give me this 'Doris Summit' 's url or image? I can't find this in network, sorry。 是说的2023年1月初的doris峰会吗？

Yes.
