### ISSUE TITLE
[Document][doc]  Exception is displayed in the section of 0.7 Version Deployment Guide

### ISSUE THREAD

**Issue by gtk96** [DataLinkDC/dinky#1456]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar document requirement.

### Description

<img width="928" alt="image" src="https://user-images.githubusercontent.com/34996528/208807028-310e1520-87ad-4148-ab09-6b29a89600b4.png">

### Are you willing to submit a PR?

- [X] #1485

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gtk96** [comment]
This should be a bug - -

**Comment by aiwenmo** [comment]
Yes I am willing to fix it.

**Comment by zackyoungh** [comment]
#1472
