### ISSUE TITLE
[Feature][wokflow] New spotless check for workflow construction

### ISSUE THREAD

**Issue by gtk96** [DataLinkDC/dinky#1457]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Remind contributors to format code by adding new checks

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Automatically checked spotless at compile time.
So no need to add spotless check for workflow construction.

**Comment by gtk96** [comment]
I agree with you
