### ISSUE TITLE
Flinkwebui Add Proxy Jump Configuration

### ISSUE THREAD

**Issue by gaoxianzhu** [DataLinkDC/dinky#1460]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Because the production environment has no network，

When I click the flinkwebui, I hope that I can jump to the ui interface through the proxy method. This is the configuration method:

http://sz25076:8088/proxy/{{applicationId}}/

![image](https://user-images.githubusercontent.com/112841355/209048085-7977ba1b-c65f-4682-8fd5-7a8e1a49c58b.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
1.0 has supported
