### ISSUE TITLE
[Optimization][app] Submiter references the PythonOptions constants, even if the task does not use Python udf.

### ISSUE THREAD

**Issue by wellCh4n** [DataLinkDC/dinky#1465]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

Submiter references the PythonOptions constants, even if the task does not use Python udf.
即使任务没有使用Python udf，Submiter 还是引用了PythonOptions的常量。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Your code is not up to date.
