### ISSUE TITLE
[Bug] [dlink-gateway] kubernetes 启flink pod 内配置文件缺失

### ISSUE THREAD

**Issue by czy868** [DataLinkDC/dinky#1478]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

flink on kubernetes native application模式下，提交任务。通过gateway启动pod，pod正常启动，但是进入pod观察发现flink/conf文件下部分静态配置文件并没有初始化进去，随后出现报错。
![image](https://user-images.githubusercontent.com/58894589/209767695-224a80eb-23ff-4c01-a165-e445fd3a9d33.png)
![image](https://user-images.githubusercontent.com/58894589/209767930-74bfa7b3-f4db-42f7-ab48-ac771e5ecd84.png)

通过run application指令形式并没有发生这种情况。

### What you expected to happen

创建KubernetesClusterDescriptor时需要重定向本地conf路径。(目前本地代码已修复这一问题)

### How to reproduce

flink on kubernetes native application模式下，提交任务，观察日志

### Version

0.7.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zackyoungh** [comment]
![image](https://user-images.githubusercontent.com/42713096/209911960-1cffc9ba-7252-4674-ad2d-feb44456ba68.png)
你需要指定这个参数

**Comment by czy868** [comment]
我尝试一下。
不过我通过在构建KubernetesClusterDescriptor时，指定了路径也解决这个问题了

**Comment by aiwenmo** [comment]
> 我尝试一下。 不过我通过在构建KubernetesClusterDescriptor时，指定了路径也解决这个问题了

在 dlink-gateway 里追加的代码吗
