### ISSUE TITLE
[Bug] [Lineage] Lineage result wrong

### ISSUE THREAD

**Issue by leechor** [DataLinkDC/dinky#1481]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

When using CEP feature.  some part of the result is not according to the actual relation.

### What you expected to happen

the right result

### How to reproduce

use CEP.

### Anything else

[Class RelMdExpressionLineage](https://calcite.apache.org/javadocAggregate/org/apache/calcite/rel/metadata/RelMdExpressionLineage.html), this calcite support for lineage, is possible use it to calculate lineage?

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
- [X] #1489
