### ISSUE TITLE
[Bug] 无主键的表, 怎么同步?

### ISSUE THREAD

**Issue by cooltnt** [DataLinkDC/dinky#1496]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

在测试cdc单表及cdcsource整库同步时, 有遇到有些表是没有设置主键的, 这时候同步就会报错。

这个问题实际上看起来有点不合理， 因为没有主键的表，要实现cdc方式的同步。但是有些库，特别是bi库，会大量存在无主键，

但多字段可确定唯一记录的场景（不会在建表的时候就把复合主键建上）

大家是怎么解决的？因为有时候是不方便给这些表去加主键的。

这个后续会有解决方案吗？

### What you expected to happen

希望无主键的表, 也能实现同步

### How to reproduce

无

### Version

0.6.7

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
可以在Sink环节去订制无主键的处理，社区源码里所提供的是有主键的处理方式，从而实现思路上来讲，这些都很容易扩展，关键看如何去定义参数来确定哪些字段是主键效果。

**Comment by cooltnt** [comment]
> 可以在Sink环节去订制无主键的处理，社区源码里所提供的是有主键的处理方式，从而实现思路上来讲，这些都很容易扩展，关键看如何去定义参数来确定哪些字段是主键效果。

感谢回复. 

你指的是去改造源码, 还是指在建sink表时有处理方法?

**Comment by aiwenmo** [comment]
> > 可以在Sink环节去订制无主键的处理，社区源码里所提供的是有主键的处理方式，从而实现思路上来讲，这些都很容易扩展，关键看如何去定义参数来确定哪些字段是主键效果。
> 
> 感谢回复.
> 
> 你指的是去改造源码, 还是指在建sink表时有处理方法?

Sink时处理

**Comment by cooltnt** [comment]
> > > 可以在Sink环节去订制无主键的处理，社区源码里所提供的是有主键的处理方式，从而实现思路上来讲，这些都很容易扩展，关键看如何去定义参数来确定哪些字段是主键效果。
> > 
> > 
> > 感谢回复.
> > 你指的是去改造源码, 还是指在建sink表时有处理方法?
> 
> Sink时处理

感谢回复.

我昨天测试出问题所在了,  源物理表可以无主键, 但是过程中的sink, 且目标表必须有主键, 否则同步会失败.

且mysql的处理方式还比较特殊.

**Comment by deepthinkin** [comment]
mysql 整库集成的参数中可否添加设置black.list 过滤下有问题的表（无主键的表，或者不想同步的表），虽然有table-name参数能控制要同步的表，有时表太多操作起来不方便，当定位到1000张表中有1张导致整库集成失败时，通过black.list 参数过滤掉就不会影响到整个作业999张表的执行。

**Comment by cooltnt** [comment]
> mysql 整库集成的参数中可否添加设置black.list 过滤下有问题的表（无主键的表，或者不想同步的表），虽然有table-name参数能控制要同步的表，有时表太多操作起来不方便，当定位到1000张表中有1张导致整库集成失败时，通过black.list 参数过滤掉就不会影响到整个作业999张表的执行。


这个建议我支持,  有时候排掉几张表要方便的多,  不过table-name 好像是支持正则的, 只不过写正则其实真的不容易
