### ISSUE TITLE
[Feature]support per-job mode for flink jar

### ISSUE THREAD

**Issue by nylqd** [DataLinkDC/dinky#1517]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
1.0 has supported
