### ISSUE TITLE
[Feature][Module Name] jar模式支持告警和savepoint管理

### ISSUE THREAD

**Issue by stgztsw** [DataLinkDC/dinky#1547]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

希望jar模式支持告警和savepoint管理，flink还是有一些场景不太适合用flinksql来实现的，着一些任务目前没有任务失败告警，比较麻烦

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
告警和savepoint管理不区分jar还是sql任务

**Comment by stgztsw** [comment]
> 

但是jar任务部署页面没有告警配置，所以导致jar任务失败，不会告警啊
