### ISSUE TITLE
[Bug] [0.7.0-executor]  多源cdc整合，构建单一sink时构建不成功

### ISSUE THREAD

**Issue by charles-zzy** [DataLinkDC/dinky#1568]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

当我按照官网测试 CDCSOURCE 整库同步到doris时，发现doris sink一直构建不出来

### What you expected to happen

按正常逻辑来走，sink应该是可以构建出来的，但是没有

### How to reproduce

当我debug时发现，build cdcsource时，构建的sink是从sinkList里取出来的，但在构建sinkList时 只会取前缀为  'sink[*]'开头的配置，导致sink构建不出来，如下是部分代码   CDCSource: 129:150,  所以得加个逻辑处理 把sink. 开头的补充到sinkList里 或者 当sinkList为空时 取config中的sink 进行构建
 ` Map<String, String> sink = new HashMap<>();
        for (Map.Entry<String, String> entry : config.entrySet()) {
            if (entry.getKey().startsWith("sink.")) {
                String key = entry.getKey();
                key = key.replaceFirst("sink.", "");
                if (!sink.containsKey(key)) {
                    sink.put(key, entry.getValue());
                }
            }
        }
        /**
         * 支持多目标写入功能, 从0开始顺序写入配置.
         */
        Map<String, Map<String, String>> sinks = new HashMap<>();
        final Pattern p = Pattern.compile("sink\\[(?<index>.*)\\]");
        for (Map.Entry<String, String> entry : config.entrySet()) {
            if (entry.getKey().startsWith("sink[")) {
                String key = entry.getKey();
                Matcher matcher = p.matcher(key);
                if (matcher.find()) {
                    final String index = ma
![企业微信截图_16738350817330](https://user-images.githubusercontent.com/54978103/212589086-e25774bc-1636-4c2b-b51c-70df181af65c.png)
tcher.group("index");
                    Map<String, String> sinkMap = sinks.get(index);`
![企业微信截图_16738357703593](https://user-images.githubusercontent.com/54978103/212589004-133bd78a-136a-4bc5-95db-de81aa0eae9b.png)

### Version

0.7.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by charles-zzy** [comment]
![企业微信截图_16738350817330](https://user-images.githubusercontent.com/54978103/212589291-0532094c-39fc-4463-b07d-6ea4de5af2ab.png)

补一个截图

**Comment by charles-zzy** [comment]
代码逻辑看漏了 这里没问题，核心问题就是doris没建表，指定auto.create参数对doris不生效导致sink构建不出来，另外目前DorisDriver没有实现创建表的接口

**Comment by ASanlittleboss** [comment]
> 你好，你是用api写的吗？我用flink sql做cdcsource时也构建不出doris sink算子，也是报错unknown table

**Comment by charles-zzy** [comment]
> > 你好，你是用api写的吗？我用flink sql做cdcsource时也构建不出doris sink算子，也是报错unknown table

我这边在调试代码的时候发现，再sink到doris时，官网给出的指定的连接参数是有问题的，直接导致sink构建失败 可以参考下我这边修改后的参数，目前是可以构建sink的了

**Comment by charles-zzy** [comment]
> > > 你好，你是用api写的吗？我用flink sql做cdcsource时也构建不出doris sink算子，也是报错unknown table
> 
> 我这边在调试代码的时候发现，再sink到doris时，官网给出的指定的连接参数是有问题的，直接导致sink构建失败 可以参考下我这边修改后的参数，目前是可以构建sink的了

![image](https://user-images.githubusercontent.com/54978103/212806019-a009aff8-a2a1-4b26-a7ae-940ea0d58ec9.png)

**Comment by charles-zzy** [comment]
![image](https://user-images.githubusercontent.com/54978103/212806076-7df53a9f-07d5-4fa9-94e5-0eff5eec8a4a.png)

这个是当时调试时修改前的报错

**Comment by ASanlittleboss** [comment]
> ![image](https://user-images.githubusercontent.com/54978103/212806076-7df53a9f-07d5-4fa9-94e5-0eff5eec8a4a.png)
> 
> 这个是当时调试时修改前的报错

我也有遇到这个报错，btw，这种方式要在doris先建表吗？
