### ISSUE TITLE
[Bug] [0.7.0] After the database is created, no relevant information will be displayed after refreshing

### ISSUE THREAD

**Issue by yyy188** [DataLinkDC/dinky#1570]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

After the database is created, no relevant information will be displayed after refreshing
![微信图片_20230116150415](https://user-images.githubusercontent.com/13779323/212617458-ec4e1f3c-4097-4b46-acac-50088c2800fc.png)

Google Chrome 109.0.5414.75

### What you expected to happen

After the database is created, no relevant information will be displayed **after refreshing**

### How to reproduce

1.running flink sql:create database tmp1;
2.trigger refresh button; 

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
上边不是有个刷新按钮吗 
 点一下会重新获取

**Comment by yyy188** [comment]
无效，试过了。使用谷歌浏览器版本Google Chrome 109.0.5414.75

**Comment by gaoyan1998** [comment]
fixed
