### ISSUE TITLE
[Bug] [0.7.0] When the task is completed, the status of the job is not updated

### ISSUE THREAD

**Issue by yyy188** [DataLinkDC/dinky#1573]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

When the task is completed, the status of the job is not updated.

**only**  If I refresh the page **manually**, the status will be updated.
 

### What you expected to happen

 When the task is completed, the status of the job is not updated.

### How to reproduce

 
1.  running A  flink sql job:

drop CATALOG if exists mysql_catalog;
CREATE CATALOG mysql_catalog WITH(
    'type' = 'jdbc',
    'default-database' = 'test',
    'username' = '***',
    'password' = '****',
    'base-url' =  'jdbc:mysql://******:3306'
);
use CATALOG mysql_catalog;
insert into  tb_user2
SELECT * FROM tb_user;

2.   when the task is completed
![image](https://user-images.githubusercontent.com/13779323/213077373-6751a87d-3c0c-42a7-be02-2b5f4f753508.png)

![image](https://user-images.githubusercontent.com/13779323/213077483-892ffd11-dd22-40e0-a855-24bb0aba9ff0.png)

3. the status of the job is not updated.
![image](https://user-images.githubusercontent.com/13779323/213077628-76e1d154-de47-424c-90a5-c07e57dd827a.png)

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
The development page needs to be refreshed manually.

**Comment by wellCh4n** [comment]
> The development page needs to be refreshed manually.

Could get status of task by loop, refresh this button if the task was finished?
