### ISSUE TITLE
Unknown column 'tenant_id' in 'field list'

### ISSUE THREAD

**Issue by dafanshu** [DataLinkDC/dinky#1575]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Dinky User Console:
[FlinkExecute] 2023-01-18T09:35:24.224 INFO: Start initialize FlinkSQLEnv:
[FlinkExecute] 2023-01-18T09:35:24.229 CONFIG: Variable opened.
[FlinkExecute] 2023-01-18T09:35:24.229 INFO: Initializing global variables...
[FlinkExecute] 2023-01-18T09:35:24.233 ERROR: org.springframework.jdbc.BadSqlGrammarException: 
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'tenant_id' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'tenant_id' in 'field list'

### What you expected to happen

execute success

### How to reproduce

EXECUTE CDCSOURCE jobname WITH (
  'connector' = 'iot-mysql-106',
  'hostname' = 'mysql-cpxnhn.ddc',
  'port' = '3306',
  'username' = 'dev',
  'password' = 'dev',
  'checkpoint' = '3000',
  'scan.startup.mode' = 'initial',
  'parallelism' = '1',
  'table-name' = 'dlink\.dlink_flink_document',
  'sink.connector' = 'doris-on-k8s',
  'sink.fenodes' = 'doris-fe.doris-on-k8s:9030',
  'sink.username' = 'root',
  'sink.password' = '',
  'sink.sink.batch.size' = '1',
  'sink.sink.max-retries' = '1',
  'sink.sink.batch.interval' = '60000',
  'sink.sink.db' = 'demo',
  'sink.table.prefix' = 'ODS_',
  'sink.table.upper' = 'true',
  'sink.table.identifier' = '${schemaName}.${tableName}',
  'sink.sink.enable-delete' = 'true'
)

### Version

0.7.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
This bug has been fixed.
