### ISSUE TITLE
[Bug] [0.7.1][多租户文档管理共用] 

### ISSUE THREAD

**Issue by malinquan** [DataLinkDC/dinky#1582]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

不用用户下的不同租户新建文档可以互相修改

### What you expected to happen

不同租户拥有自己的文档管理权限就可以了

### How to reproduce

用户1新建文档后 用户2可以修改

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
Q：不同租户拥有自己的文档管理权限就可以了
---------------------------------------------
A：目前得文档都是属于公共使用的 ， 并且会在数据开发编辑器内触发快捷提示，如果使用租户隔离，部分功能应该会有限制，如果是希望隔离的文档含有敏感信息等 可以通过全局变量定义的方式， 新版本中可以租户隔离全局变量，后续会在数据开发中增加全局变量快速提示的功能

**Comment by Zzm0809** [comment]
用户1新建文档后 用户2可以修改
---------
由于目前权限相关未实现 故增删改的功能对用户都是可见的

**Comment by gaoyan1998** [comment]
1.0 has supported
