### ISSUE TITLE
[FAQ] 0.6.7开发的作业怎么快速迁移至0.7.1

### ISSUE THREAD

**Issue by cooltnt** [DataLinkDC/dinky#1584]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

作业似乎无法批量导入, 导出, 删除(除非删除目录).  

如果数据库版本不是升级, 而是新装了, 那要怎样才能快速将作业相关数据迁移?

我手动导了几张task相关表, 不行.      从0.6.7导出作业, 再到0.7.1**无法导入**

有没有迁移脚本可提供?

### What you expected to happen

1. 希望能够快速迁移所有作业任务.
2. 希望能够批量导出作业(按文件夹分别导出, 也可以是整个根目录)

### How to reproduce

重新新建作业, 粘贴脚本

### Version

0.7.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
1.升级得情况下 执行升级sql即可 
2.导入导出作业是有一定得要求得，见官网文档：http://www.dlink.top/docs/0.7/administrator_guide/studio/job_import_export

**Comment by cooltnt** [comment]
> 1.升级得情况下 执行升级sql即可 2.导入导出作业是有一定得要求得，见官网文档：http://www.dlink.top/docs/0.7/administrator_guide/studio/job_import_export

感谢回复.
1. 版本升级sql可以用,  只不过我今天是全新部署了0.7.1,  然后就想着把原来脚本迁过来(没有发现多作业导出这个细节^_^)
2. 原来有这个细节, 没注意, 我多个选中, 很自然的右键导出, 没成功, 也没去试用上面的图标.  十分感谢提醒, 刚才试了, 可以多个导出.    不过0.6.7导出的作业, 无法导入0.7.1,  应该是json元素有区别了. 

不纠结了,  我整库升级一个.
