### ISSUE TITLE
[Bug] [dlink-admin] task name changed but the task name in maintain center not changed

### ISSUE THREAD

**Issue by gitfortian** [DataLinkDC/dinky#1591]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

数据开发页 脚本名称由 flinksql给成了 数据生成源表写入打印流表 但是运维中心的任务名称没有改变 还是之前的flinksql

### What you expected to happen

运维中心的任务名称没有改变 

### How to reproduce

1、新建flinksql作业  
2、运行
3、修改flinksql作业名称

### Version

0.7.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
This is normal, not a bug
