### ISSUE TITLE
[Bug] CDCSOURCE mysql cdc date类型写入pg, 数值有误, 全部为1970-01-01

### ISSUE THREAD

**Issue by cooltnt** [DataLinkDC/dinky#1600]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

目前所用版本 dinky 0.7.1  flink 1.16.0  flinkcdc 2.3.0

1. cdcsource方式将含date类型字段的表, 同步到postgresql , 首次全量初始化完成后, 发现目标表对应字段值均为1970-01-01, 但是修改下源表数据, 该记录date字段值变正确.
2. 用sink方式单表同步, 不存在此问题.

发现issues中有相关已关闭问题
https://github.com/DataLinkDC/dinky/pull/799
https://github.com/DataLinkDC/dinky/issues/821

### What you expected to happen

希望能正确同步date类型字段

### How to reproduce

单表sink方式同步

### Version

0.7.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leeoo** [comment]
Dinky 0.7.1, Flink 1.16.0, MySQL 8.0.29, CDC connectors 2.3.0, Doris 1.2.1 环境下，在 CDCSOURCE 整库同步 mysql 到 doris 时同样遇到此问题！

**Comment by aiwenmo** [comment]
> Dinky 0.7.1, Flink 1.16.0, MySQL 8.0.29, CDC connectors 2.3.0, Doris 1.2.1 环境下，在 CDCSOURCE 整库同步 mysql 到 doris 时同样遇到此问题！

![image](https://user-images.githubusercontent.com/32723967/221860195-220206f0-3b6e-4a0e-8d1d-77ffe9c1ffca.png)
我无法复现该问题

**Comment by cygnusdark** [comment]
同样遇到此问题
环境：
Dinky 0.7.3
Doris 1.1
Flink 1.16.0 & Flink 1.17.0
在尝试修改源码解决中

**Comment by adu-shzz** [comment]
同样遇到此问题，用的 datetime 类型字段 
环境：
Dinky: v0.7.3
数据库: MySQL 5.7
Kafka: v2.4.1
Flink: 1.16.0 & 1.17.0

**Comment by javaht** [comment]
pg整库到hudi 0.12.2   
数据类型为date 
hudi里均为1970-01-01

**Comment by aiwenmo** [comment]
com.dlink.cdc.AbstractSinkBuilder.getLogicalType

case TIMESTAMP:
return new TimestampType(column.getLength());

**Comment by aiwenmo** [comment]
- [X] #2557
