### ISSUE TITLE
[Bug] [0.7.0] CDCSOURCE 全局变量问题

### ISSUE THREAD

**Issue by cooltnt** [DataLinkDC/dinky#1607]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

scan.startup.mode 想用全局变量控制, 
但是一旦开启, 就会提示  'sink.table-name' = 'public.${tableName}'  处的变量tableName 未定义。
该变量不应该是属于sink表默认的元数据（环境）变量吗？ 不开启全局变量是能正常运行的。

EXECUTE CDCSOURCE cdc_mysql WITH (
'connector' = 'mysql-cdc',
'hostname' = '127.0.0.1',
'port' = '3306',
'username' = 'root',
'password' = '123456',
'checkpoint' = '600000',
'scan.startup.mode' = 'initial',
--${g_startup_mode},  -- 此处想用全局变量
'parallelism' = '1',
'table-name' = 'test\.test_table',
'source.server-time-zone' = 'UTC',
'sink.url' =  'jdbc:postgresql://127.0.0.1/cdc_test',
'sink.username' = 'test',
'sink.password' = 'test',
'sink.connector' = 'jdbc',
'sink.sink.db' = 'cdc_test',
'sink.table-name' = 'public.${tableName}' 
);

### What you expected to happen

全局变量，作业变量，或元数据变量能共存

### How to reproduce

在cdcsource方式下， 不使用全局变量

### Version

0.7.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
目前 CDCSOURCE 不支持全局变量

**Comment by mamacmm** [comment]
本来也想用变量生成 label-prefix  ，发现不支持。

因为doris里面的label-prefix 需要每次执行任务前修改下，所以想改成这样：
```
'sink.sink.label-prefix' = '${schemaName}_${tableName}_'+UUID()
```
但测试发现不起作用
