### ISSUE TITLE
[Feature][dlinky-admin] support get task lineage by taskid with openapi

### ISSUE THREAD

**Issue by gitfortian** [DataLinkDC/dinky#1608]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

so far,dinky provide a task internal lineage,it can't meet the demand that who want search a global lineage,can dinky provide
a openapi to show a task lineage then user can save it to graphdb

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gitfortian** [comment]
base on it ,i can make a global lineage

**Comment by aiwenmo** [comment]
This is a good idea.
