### ISSUE TITLE
[Feature] The flink program for yarn deployment of the knox agent provides access to the web ui pages

### ISSUE THREAD

**Issue by dsanww** [DataLinkDC/dinky#1628]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, the flink program deployed on yarn of the knox agent cannot correctly access the web ui page. It is hoped that you can add support in the future

### Use case

Currently, the flink program deployed on yarn of the knox agent cannot correctly access the web ui page. It is hoped that you can add support in the future

### Related issues

Currently, the flink program deployed on yarn of the knox agent cannot correctly access the web ui page. It is hoped that you can add support in the future

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
try 1.0
