### ISSUE TITLE
[Bug] [dlink-admin] Invoking lineage api will not get the right result

### ISSUE THREAD

**Issue by gitfortian** [DataLinkDC/dinky#1637]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

When the flinksql task with a flinksqlEnv task, the call lineage did not get the correct result because there was no newline

### What you expected to happen

get a correct reslult from lineage openapi

### How to reproduce

flinksql task with a flinksqlEnv task

### Version

0.7.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
- [X] #1653
