### ISSUE TITLE
[Bug] [容器环境] FLINK 1.16对接报错

### ISSUE THREAD

**Issue by niaoshuai** [DataLinkDC/dinky#1639]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![图片](https://user-images.githubusercontent.com/5117373/217983455-c561e1f4-1712-468c-a03c-03d84cfa3579.png)

### What you expected to happen

Dinky User Console:
[FlinkExecute] 2023-02-10T10:13:53.768 INFO: Start initialize FlinkSQLEnv:
[FlinkExecute] 2023-02-10T10:13:53.769 INFO: Finish initialize FlinkSQLEnv.
[FlinkExecute] 2023-02-10T10:13:53.769 INFO: Initializing Flink job config...
[FlinkExecute] 2023-02-10T10:13:53.787 ERROR: java.lang.NoClassDefFoundError: org/apache/flink/configuration/Configuration

### How to reproduce

Dinky User Console:
[FlinkExecute] 2023-02-10T10:13:53.768 INFO: Start initialize FlinkSQLEnv:
[FlinkExecute] 2023-02-10T10:13:53.769 INFO: Finish initialize FlinkSQLEnv.
[FlinkExecute] 2023-02-10T10:13:53.769 INFO: Initializing Flink job config...
[FlinkExecute] 2023-02-10T10:13:53.787 ERROR: java.lang.NoClassDefFoundError: org/apache/flink/configuration/Configuration

### Anything else

Dinky User Console:
[FlinkExecute] 2023-02-10T10:13:53.768 INFO: Start initialize FlinkSQLEnv:
[FlinkExecute] 2023-02-10T10:13:53.769 INFO: Finish initialize FlinkSQLEnv.
[FlinkExecute] 2023-02-10T10:13:53.769 INFO: Initializing Flink job config...
[FlinkExecute] 2023-02-10T10:13:53.787 ERROR: java.lang.NoClassDefFoundError: org/apache/flink/configuration/Configuration

### Version

0.7.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by benyuereal** [comment]
最后怎么解决的？

**Comment by niaoshuai** [comment]
没解决 切到1.14 并不用容器了

**Comment by llywww** [comment]
可以在下一个版本解决吗

**Comment by saoxia** [comment]
> 没解决 切到1.14并不能用容器了

是dinky不能用容器，还是flink不能用容器啊

**Comment by aiwenmo** [comment]
dinky 镜像里的 plugins 的flink1.16目录里没加 flink 依赖。

**Comment by saoxia** [comment]
> dinky 镜像里的 plugins 的flink1.16目录里没加 flink 依赖。

请问需要哪些依赖，我刚刚把兼容的jar包都添加进去了还是同样报错

**Comment by aiwenmo** [comment]
> > dinky 镜像里的 plugins 的flink1.16目录里没加 flink 依赖。
> 
> 请问需要哪些依赖，我刚刚把兼容的jar包都添加进去了还是同样报错

$FLINK_HOME/lib 下的依赖

**Comment by saoxia** [comment]
> > > dinky 镜像里的 plugins 的flink1.16目录里没加 flink 依赖。
> > 
> > 
> > 请问需要哪些依赖，我刚刚把兼容的jar包都添加进去了还是同样报错
> 
> $FLINK_HOME/lib 下的依赖
添加后报错变成了下面：
ERROR: java.lang.NoClassDefFoundError: org/apache/flink/table/planner/plan/optimize/program/FlinkChainedProgram

**Comment by aiwenmo** [comment]
> > > > dinky 镜像里的 plugins 的flink1.16目录里没加 flink 依赖。
> > > 
> > > 
> > > 请问需要哪些依赖，我刚刚把兼容的jar包都添加进去了还是同样报错
> > 
> > 
> > $FLINK_HOME/lib 下的依赖
> > 添加后报错变成了下面：
> > ERROR: java.lang.NoClassDefFoundError: org/apache/flink/table/planner/plan/optimize/program/FlinkChainedProgram

#1520
