### ISSUE TITLE
[Feature][UDF]  Single udf supports multiple classes 

### ISSUE THREAD

**Issue by SYG-ATONE** [DataLinkDC/dinky#1640]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Writing multiple classes with a single udf is not supported; If you want to use tool classes to facilitate code management and call, it is not supported now

### Use case

![9d6e496a0fbe455ae524e321d97d428](https://user-images.githubusercontent.com/53116148/217992673-89e78f33-35d1-4c21-a54d-23fe22c8c127.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leechor** [comment]
the temporary solution is that you can try to put these classes as the inner classes.
