### ISSUE TITLE
自动时间触发savepoint状态

### ISSUE THREAD

**Issue by wangyayuan18** [DataLinkDC/dinky#1643]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

自动时间触发savepoint状态
比如1天自动触发一次，1小时触发一次等....

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhengtingxue** [comment]
好主意，我现在是自己写了个cron定时，每天定时调api接口保存savepoint
