### ISSUE TITLE
[Feature][dlink-admin]  Yarnsession support applicationId and resoucemanager config

### ISSUE THREAD

**Issue by alexander1005** [DataLinkDC/dinky#1647]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, the dlink session mode does not support the applicationId option, which is a bad thing, When the yarnsession fails and changes the address, the failure does not come out. So We support the yarnsession option

### Use case

support the yarnsession option

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi.Please show the effect screenshot.

**Comment by alexander1005** [comment]
![image](https://user-images.githubusercontent.com/36446084/218648532-9e1fe37f-dd5d-46e2-ab61-20bcdb9a8586.png)
![image](https://user-images.githubusercontent.com/36446084/218648576-5f3f7827-8eca-4676-b147-39ac5b6b6b6e.png)

**Comment by alexander1005** [comment]
![image](https://user-images.githubusercontent.com/36446084/218648694-dc9d3d18-7a37-4cad-8d49-4a0678a79ba6.png)

**Comment by alexander1005** [comment]
![image](https://user-images.githubusercontent.com/36446084/218648751-cc041fef-6769-41ea-866d-d9c10a600330.png)

**Comment by aiwenmo** [comment]
This parameter is only available in yarn mode.Need to adjust the position and visibility.

**Comment by alexander1005** [comment]
> 

yes , i just suppurt yarn session mode

**Comment by aiwenmo** [comment]
Good! Welcome submit this PR to 0.7 branch. thx

**Comment by alexander1005** [comment]
![image](https://user-images.githubusercontent.com/36446084/218650281-8f804cf5-c4eb-4e04-a1da-8a06c8aa7170.png)
