### ISSUE TITLE
[Feature][数据开发] hive作业 不能上线问题

### ISSUE THREAD

**Issue by ChaseXue** [DataLinkDC/dinky#1651]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://user-images.githubusercontent.com/26411759/219049090-1e6845c1-a7f3-4510-a6a1-b4e74edfd776.png)
![ECU@EI9FK5H)4HUP@YQTOPV](https://user-images.githubusercontent.com/26411759/219049132-99530635-2140-45eb-95f4-2c80a0c477ee.jpg)

### Use case

hive作业正常上线，dolphinscheduler 可以成功调度

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chenss-1** [comment]
what's your  version of hive datasource jdbc

**Comment by aiwenmo** [comment]
use Dinky 1.0.
