### ISSUE TITLE
[Bug] [0.7.1] 复制作业, 标题默认为父父级的名字 

### ISSUE THREAD

**Issue by cooltnt** [DataLinkDC/dinky#1655]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

操作步骤如下:
1. 新建作业 [作业A]
2. 复制[作业A], 此时作业名默认为 作业A_1,  修改为[作业B]
3. 复制作业[作业B], 此时默认名居然为 **[作业A_1]** , 且作业提交运行后, 在flink中标题也为 [作业A]
在查看数据库表 dlink_task后发现, 字段name, alias值并不一致, 复制,运行时应该默认取的是alias

注: 1,2,3步过程中有从0.6.7开发作业后导出, 再导入0.7.1的操作, 也可能存在再次从0.7.1导出, 再导入0.6.7, 
不知道是不是不同版本之间导入, 导出引起?

### What you expected to happen

多版本之间作业能兼容

### How to reproduce

修改数据库表

### Version

0.7.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
1.0 has fixed
