### ISSUE TITLE
[Feature] Auto Catalog，分库分表采集，Doris 写入覆盖，自动同步schema Job

### ISSUE THREAD

**Issue by enterwhat** [DataLinkDC/dinky#1664]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

https://mp.weixin.qq.com/s/wNrHTRCP44BWkOhCKzIeSA
![image](https://user-images.githubusercontent.com/9004317/219525450-ad9ca9dd-2da3-4174-b978-08527a8b5658.png)
![image](https://user-images.githubusercontent.com/9004317/219525488-e325f898-c54c-4cf7-b06b-215c51918c5e.png)
![image](https://user-images.githubusercontent.com/9004317/219525504-b883d839-82fb-4c2e-bf9a-af41421f059d.png)
![image](https://user-images.githubusercontent.com/9004317/219525539-e1d65ec8-edd5-4d64-b45e-93a0343bcbcf.png)

### Use case

https://mp.weixin.qq.com/s/wNrHTRCP44BWkOhCKzIeSA

### Related issues

https://mp.weixin.qq.com/s/wNrHTRCP44BWkOhCKzIeSA

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
1.Dinky 支持持久化的 Catalog 管理，无需 CREATE TABLE 语句。
2.Dinky 支持 FlinkSQL 行级权限。
3.其他欢迎讨论支持。
