### ISSUE TITLE
[Optimization][CDCSOURCE] support jdbc.properties parameter

### ISSUE THREAD

**Issue by cygnusdark** [DataLinkDC/dinky#1677]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

问题说明：
MySQL表字段的数据类型为tinyint(1)时，在Flink SQL DDL中会被解析为boolean类型，见Apache Flink 官网关于字段数据类型映射的介绍：
<img width="800" alt="image" src="https://user-images.githubusercontent.com/53288632/221121770-de36c41c-43c6-4c23-a141-901b3ce8d807.png">
通过查阅ververica官网，MySQL CDC连接器选项支持jdbc.properties参数，但是dinky的CDCSOURCE不支持解析该参数，即使配置了
  'jdbc.properties.tinyInt1isBit' = 'false',
  'jdbc.properties.transformedBitIsBoolean' = 'false',
在生成DDL语句时仍会将tinting(1)转为boolean类型，从而导致无法使用CDCSOURCE进行整库同步。
<img width="857" alt="image" src="https://user-images.githubusercontent.com/53288632/221122385-f5dc1c5c-cd5d-4d37-b9cb-4574909c4fbb.png">
解决方案：
目前只能通过自己写Flink DDL显式定义Flink中该表字段的数据类型，希望社区支持在CDCSOURCE语法中配置jdbc.properties.*，或支持tinyInt1isBit && transformedBitIsBoolean参数，实现dinky自动解析tinying(1)为tinying，而非boolean

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
- [X] #1683
