### ISSUE TITLE
[Improvement][doc] Documentation Improvement 

### ISSUE THREAD

**Issue by Zzm0809** [DataLinkDC/dinky#1693]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

Documentation Improvement Discussion

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yuzq24** [comment]
CDCSOURCE整库同步写入doris官网案例写不进去诶

**Comment by siriume** [comment]
> CDCSOURCE整库同步写入doris官网案例写不进去诶

整库同步的文档还需要进一步完善

**Comment by yuzq24** [comment]
> > CDCSOURCE整库同步写入doris官网案例写不进去诶
> 
> 整库同步的文档还需要进一步完善

嗯， 我还有问题 就是： 整库同步到doris的一直都写不进去， 发现重启dinky以后成功写入了。  之前写入kafka的demo也是都已经成功了， 但是过了2天莫名其妙的又不行了， 也是重启dinky之后就又可以了， 这种情况下 可能是什么问题导致的呢

**Comment by siriume** [comment]
> > > CDCSOURCE整库同步写入doris官网案例写不进去诶
> > 
> > 
> > 整库同步的文档还需要进一步完善
> 
> 嗯， 我还有问题 就是： 整库同步到doris的一直都写不进去， 发现重启dinky以后成功写入了。 之前写入kafka的demo也是都已经成功了， 但是过了2天莫名其妙的又不行了， 也是重启dinky之后就又可以了， 这种情况下 可能是什么问题导致的呢

具体得报错日志能发一份么

**Comment by aiwenmo** [comment]
> > > CDCSOURCE整库同步写入doris官网案例写不进去诶
> > 
> > 
> > 整库同步的文档还需要进一步完善
> 
> 嗯， 我还有问题 就是： 整库同步到doris的一直都写不进去， 发现重启dinky以后成功写入了。 之前写入kafka的demo也是都已经成功了， 但是过了2天莫名其妙的又不行了， 也是重启dinky之后就又可以了， 这种情况下 可能是什么问题导致的呢

升级到0.7.2，修复了这个bug，原因是jdbc连接超时，无法获取元数据信息

**Comment by yuzq24** [comment]
OK


***@***.***
 
From: aiwenmo
Date: 2023-03-01 19:56
To: DataLinkDC/dinky
CC: yuzq24; Comment
Subject: Re: [DataLinkDC/dinky] [Discussion][doc] Documentation Improvement Discussion (Issue #1693)
CDCSOURCE整库同步写入doris官网案例写不进去诶
整库同步的文档还需要进一步完善
嗯， 我还有问题 就是： 整库同步到doris的一直都写不进去， 发现重启dinky以后成功写入了。 之前写入kafka的demo也是都已经成功了， 但是过了2天莫名其妙的又不行了， 也是重启dinky之后就又可以了， 这种情况下 可能是什么问题导致的呢
升级到0.7.2，修复了这个bug，原因是jdbc连接超时，无法获取元数据信息
