### ISSUE TITLE
[Bug] [k8s app mode] 实例名称重复，都是000000，导致第二个任务提交的时候主键冲突

### ISSUE THREAD

**Issue by zhengtingxue** [DataLinkDC/dinky#1711]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

dlink 0.7.2,flink1.15.3， k8s application mode,提交一个任务成功，然后集群管理->flink实例管理，里面新增了一条记录，实例名称是00000000，全是0，然后提交第二个k8s app任务，提示00000主键冲突，猜测是第二个实例名称也是000000，然后主键冲突了，

### What you expected to happen

实例名称展示为集群名称，不要用实例名，这样就不会冲突了

### How to reproduce

1. 提交一个k8s app任务
2. 再提交一个k8s app任务
3. 就会出现主键冲突的报错

### Version

0.7.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by andystenhe** [comment]
在0.7.2, flink-1.14中测试过, 删除表约束可以正常使用
ALTER TABLE dlink_cluster drop CONSTRAINT dlink_cluster_un

**Comment by gaoyan1998** [comment]
fixed
