### ISSUE TITLE
[Bug] [不能赋权同一租户] 072版本不能赋权普通用户到admin用户

### ISSUE THREAD

**Issue by yqzdy1207** [DataLinkDC/dinky#1718]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

072版本不能赋权普通用户到admin用户

### What you expected to happen

前提：067版本依次升级到072版本
1. 登陆admin用户为普通用设置和admin用户为同一租户
2. 为普通租户分配角色租户后
3. 登陆普通租户发现没有admin用户的权限

### How to reproduce

前提：067版本依次升级到072版本
1. 登陆admin用户为普通用设置和admin用户为同一租户
2. 为普通租户分配角色租户后
3. 登陆普通租户发现没有admin用户的权限

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
为租户分配新用户后，解决
