### ISSUE TITLE
[Bug] [Flink Application不支持全局变量] 

### ISSUE THREAD

**Issue by yqzdy1207** [DataLinkDC/dinky#1727]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

0.7.2版本的Dinky 使用全局变量后，Flink Application模式不支持，per-job模式支持

### What you expected to happen

0.7.2版本的Dinky 使用全局变量后，Flink Application模式不支持，per-job模式支持

### How to reproduce

0.7.2版本的Dinky 使用全局变量后，Flink Application模式不支持，per-job模式支持

### Version

0.7.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
The problem has been confirmed.
Welcome to fix it.

**Comment by gaoyan1998** [comment]
fixed
