### ISSUE TITLE
[Bug] [数据开发] 获取最新结果不显示boolean类型的值

### ISSUE THREAD

**Issue by zhuxt2015** [DataLinkDC/dinky#1729]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

获取最新结果不显示boolean类型的字段值
<img width="938" alt="image" src="https://user-images.githubusercontent.com/13765310/224467332-31122596-3ac7-48c7-84a7-167f64e280c6.png">

### What you expected to happen

显示boolean值

### How to reproduce

创建FLinkSQL任务, select true, false, 然后点击结果tab中的获取最新结果按钮

### Version

0.6.7

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
升级到0.7.2，已解决
