### ISSUE TITLE
[Bug] [dlink-admin] 配置k8s集群执行‘测试’按钮时没有自动构建镜像问题以及其它优化

### ISSUE THREAD

**Issue by shirukai** [DataLinkDC/dinky#1734]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

在页面配置好集群信息之后，执行【测试】按钮，不会触发构建镜像操作，原因是新增集群，集群配置ID为空
![image](https://user-images.githubusercontent.com/29705424/225211268-4bffa5be-bbe1-4875-b0c6-fd57546f719b.png)

### What you expected to happen

没有自动构建镜像，k8s-session集群启动时出现问题

### How to reproduce

关于构建镜像这个问题，有以下建议：
1.  将构建镜像的逻辑从testGateway方法中拿出来，单独作为一个接口提供，调整页面布局，默认不显示docker配置项，在kubernetes.container.image配置项后面添加一个可以触发构建镜像的按钮，如果用户需要构建镜像，则弹出填写docker信息，并能够触发构建，将生成的镜像地址，自动填入kubernetes.container.image中
![image](https://user-images.githubusercontent.com/29705424/225212202-9af31aab-2d88-4eab-936e-dcdcc1cfbfc5.png)

2. 自动构建镜像使用的Dockefile中的FLINK_VERSION参数没有被替换掉

3.  testGateway只测试了能否初始化k8s客户端，并没有测试默认的客户端是否具有操作k8s权限的问题。默认使用的是serviceaccout是default，页面上是否可以支持用户指定serviceaccount，并在testGateway时验证serviceaccount可用性

### Version

0.7.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zackyoungh** [comment]
后续打算构建镜像提炼出来，单独做一个工具
