### ISSUE TITLE
[Feature] support db2 + cassandra

### ISSUE THREAD

**Issue by melin** [DataLinkDC/dinky#1740]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by madecang** [comment]
sink or source?

**Comment by melin** [comment]
优先source，最好支持sink。
