### ISSUE TITLE
[Bug] [bin] Startup class error in anto.sh

### ISSUE THREAD

**Issue by aiwenmo** [DataLinkDC/dinky#1744]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Startup class error in anto.sh.

### What you expected to happen

Startup successfully.

### How to reproduce

sh auto.sh start

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by nzh9900** [comment]
@aiwenmo  I am willing to help fix this issue.
