### ISSUE TITLE
Merge PR in 0.7 branch into dev branch

### ISSUE THREAD

**Issue by aiwenmo** [DataLinkDC/dinky#1759]
The following list is the latest refactoring tasks (keep up to date). 

Since the code in version 0.8 and 0.7 are maintained in two branches simultaneously, it is now necessary to manually merge code changes from versions 0.7.1 to 0.7.3 into the dev branch. If you are interested in a task, please leave a message. Of course, you can also proactively find tasks not listed in the submission record, and comment here to add claims. For example, I am interested in performing this task. If you leave a message, please submit a PR within three days. If it exceeds three days, other contributors are welcome to do so.

> 以下列表是最新的重构任务（保持最新）。
>
> 由于 0.8  版本的代码和 0.7 版本的代码是分为两个分支同时维护的，现在需要将 0.7.1 版本到 0.7.3 版本的代码变动人工合并至 dev 分支。 如果您对某项任务感兴趣，请留言。当然您也可以从提交记录中主动寻找未列举的任务，并此处评论追加认领。例如，我对执行此任务感兴趣。如果您留言，请在三天内提交PR。如果超过三天，欢迎其他贡献者这样做。

### Frontends && Backends
- [x] #1641 
- [ ] #1647 
- [x] #1666 
- [x] #1715 

### Backends
- [x] #1760 
- [x] #1593 
- [x] #1615 
- [x] #1608 
- [x] #1652 
- [x] #1662 
- [x] #1670 
- [x] #1672 
- [x] #1682 
- [x] #1638 
- [x] #1686 
- [x] #1778 
- [x] #1779 
- [x] #1794 
- [x] #1795 
- [x] #1801 
- [x] #1812 
- [x] #1842 
- [x] #1849 
- [x] #1851 
- [x]  #1774 
- [x] #1862 
- [x] #1888 
- [x] #1909 
- [x] #1917 
- [x] #1944
### Frontends
- [x] #1624 
- [x] #1547 
- [x] #797 

### How to contribute

http://www.dlink.top/docs/next/developer_guide/contribution/how_contribute

### How to commit 

http://www.dlink.top/docs/next/developer_guide/contribution/commit_code

### How to pull request

http://www.dlink.top/docs/next/developer_guide/contribution/pull_request

**Comment by nzh9900** [comment]
I will help merge #1638

**Comment by donggong** [comment]
I will help merge #1547

**Comment by aiwenmo** [comment]
- [x] #1831

**Comment by leechor** [comment]
#1954 #1812 merged

**Comment by leechor** [comment]
#1854 #1955 merged

**Comment by leeoo** [comment]
#1670 has been fixed in dev branch.
