### ISSUE TITLE
生成的DDL最后一个字段有逗号

### ISSUE THREAD

**Issue by cdadi** [DataLinkDC/dinky#1763]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![ddl](https://user-images.githubusercontent.com/112104374/227084976-48a9eb21-1286-4f77-a253-37712a3abdc0.png)

### What you expected to happen

去掉逗号

### How to reproduce

生成的ddl

### Version

0.7.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
- [X] #1767
