### ISSUE TITLE
[Bug] [0.7] 错误: 找不到或无法加载主类 com.dlink.Dlink

### ISSUE THREAD

**Issue by chenxu8989** [DataLinkDC/dinky#1765]
### Search before asking

- [x] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

# 启动失败

今天解决依赖的问题的时候无法重启了，而且发现启动的时候没有日志，我在启动脚本里吧终端日志的输出位置改了下，发现日志上提示启动失败， 找不到主类

我这个dinky是重新解压的，不缺什么东西，只是修改了application.yml里面的mysql连接， 其他没动过

```log
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=512M; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=1024M; support was removed in 8.0
错误: 找不到或无法加载主类 com.dlink.Dlink
```

### What you expected to happen

启动失败

### How to reproduce

启动失败

### Version

0.7.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Dinky 的版本号是
