### ISSUE TITLE
异步提交失败

### ISSUE THREAD

**Issue by yangwbud** [DataLinkDC/dinky#1768]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

当提交flink-on-yarn时报：Caused by: java.lang.ClassCastException: org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$GetFileInfoRequestProto cannot be cast to com.google.protobuf.Message

### What you expected to happen

导致flink-sql,flink-stream等任务提交不到yarn集群上

### How to reproduce

目前我用的最新版本0.7.2版本

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
请发下 dinky 的 plugins 下的截图

**Comment by ArmstrongGou** [comment]
我也遇到同样的问题，求答复！！

**Comment by gaoyan1998** [comment]
> 我也遇到同样的问题，求答复！！

classloader.resolve-order: parent-first
加一个这个参数试试

**Comment by aiwenmo** [comment]
classloader.resolve-order: parent-first
https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/ops/debugging/debugging_classloading/#x-cannot-be-cast-to-x-exceptions
