### ISSUE TITLE
[Bug] [CDCSOURCEN] 'sink.connector' = 'doris' 无法创建sink

### ISSUE THREAD

**Issue by AlstoreMr** [DataLinkDC/dinky#1770]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

- Dinky 0.7.2
- Flink 1.14.6
- flink-doris-connector-1.14_2.12-1.1.1.jar
- flink-sql-connector-mysql-cdc-2.3.0.jar

MySQL整库同步至Doris， 'sink.connector' = 'doris' 时只有Source 无法创建Sink  而 'sink.connector' = 'datastream-doris-schema-evolution' MySQL datetime类型到doris datetime类型，值为 null  

### What you expected to happen

MySQL到Doris 整库同步

### How to reproduce

-- SET 'execution.checkpointing.interval' = '10s';
EXECUTE CDCSOURCE ER WITH (
  'connector' = 'mysql-cdc',
  'hostname' = 'xxx',
  'port' = '3306',
  'username' = 'root',
  'password' = '123456',
  'checkpoint' = '3000',
  'scan.startup.mode' = 'initial',
  'parallelism' = '1',
  'table-name' = 'sbc-goods\.goods_brand,sbc-goods\.goods_cate,sbc-goods\.customer_auth',
  'sink.connector' = 'doris',
  'sink.fenodes' = 'xxx:8030',
  'sink.username' = 'root',
  'sink.password' = '123456',
  'sink.sink.properties.format' = 'json',
  'sink.sink.properties.read_json_by_line' = 'true',
  'sink.sink.enable-delete' = 'true',
  'sink.sink.batch.size' = '100',
  -- 'sink.doris.batch.size' = '1000',
  'sink.sink.max-retries' = '1',
  'sink.sink.batch.interval' = '60000',
  'sink.sink.db' = 'ODS_SBC_GOODS_APP',
  'sink.table.prefix' = 'ODS_',
  'sink.table.upper' = 'true'
)

### Version

0.7.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
'sink.connector' = 'doris' 时，后台日志有报错吗，输出的细节信息中扫描到了几个源表呢

**Comment by AlstoreMr** [comment]
> 'sink.connector' = 'doris' 时，后台日志有报错吗，输出的细节信息中扫描到了几个源表呢

ERROR com.dlink.cdc.sql.SQLSinkBuilder 285 lambda$build$0 - org.apache.flink.table.api.SqlParserException: Invalid SQL identifier VIEW_sbc-goods_booking_sale_goods.
Caused by: org.apache.flink.sql.parser.impl.ParseException: Encountered "-" at line 1, column 9.
mysql 数据库名中 “-” 的原因 应该是

**Comment by aiwenmo** [comment]
整库同步默认把中划线转成下划线了

**Comment by AlstoreMr** [comment]
> 整库同步默认把中划线转成下划线了

改完 之后source 有的就是 sink 就有问题   

  SQLSinkBuilder  addTableSink 这地方怎么改呢

**Comment by aiwenmo** [comment]
目标用户也需要是下划线
