### ISSUE TITLE
[Feature]能够控制sink 连接数量

### ISSUE THREAD

**Issue by melin** [DataLinkDC/dinky#1771]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

source 合并控制了连接数量，目标端sink 控制不了， 如果source 有1000表，会导致sink 端连接数太多，需要支持sink 连接复用，减少连接数量。
![image](https://user-images.githubusercontent.com/1145830/227424559-37d8e002-1cd0-4824-9001-4861db41f873.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
This is a great suggestion. thx
