### ISSUE TITLE
[Bug] [Admin] Task is deleted. Task instances and history are not deleted consecutively

### ISSUE THREAD

**Issue by zq0757** [DataLinkDC/dinky#1784]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Task is deleted. Task instances and history are not deleted consecutively

### What you expected to happen

When a Task is deleted, the task instance and task history can be deleted in cascade

### How to reproduce

A flinksql task is added on the data development interface, and the task is submitted. A record is generated on the operation and maintenance center interface. After a test, the flinksql task is deleted

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by magic20191** [comment]
The same situation occurred in the 0.7.2version

**Comment by aiwenmo** [comment]
We need to commit it into 0.7 branch~
