### ISSUE TITLE
RECURSIVE函数

### ISSUE THREAD

**Issue by wangyayuan18** [DataLinkDC/dinky#1788]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

dinky是否支持RECURSIVE函数

![image](https://user-images.githubusercontent.com/64136230/228121335-3c736ace-f975-4949-aa8d-d491a0f4db6f.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Not Supported.

**Comment by aiwenmo** [comment]
Mysql task supports.
