### ISSUE TITLE
[Bug] [数据开发] dinky 0.7.0 flink jar上传出现 Filesystem closed 错误 

### ISSUE THREAD

**Issue by ChaseXue** [DataLinkDC/dinky#1798]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

首次上传flink jar 会成功，更新jar再次上传会出现java.io.IOException: Filesystem closed 错误。dinky服务重启可以上传成功，但再次上传问题会重现
![image](https://user-images.githubusercontent.com/26411759/228409617-cbbcdb5b-a87e-4361-a1c5-3febd0b39253.png)

![image](https://user-images.githubusercontent.com/26411759/228407853-64d5c448-19dc-4eeb-bc78-00e711842413.png)

### What you expected to happen

jar更新能正常上传

### How to reproduce

flink jar 更新重新上传

### Version

0.7.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dzygcc** [comment]
希望尽快解决

**Comment by twenty-zhang** [comment]
我简陋的解决了这个问题，在com.dlink.utils.HdfsUtil#uploadFile(String, byte[], String)中增加对FileSystem hdfs的可用性判断，如果出现Exception则处理并重新init

**Comment by dzygcc** [comment]
> 我简陋的解决了这个问题，在com.dlink.utils.HdfsUtil#uploadFile(String, byte[], String)中增加对FileSystem hdfs的可用性判断，如果出现Exception则处理并重新init

估计会进到哪个版本的包呢

**Comment by gaoyan1998** [comment]
1.0 reconstructs the jar submission method and provides better usage methods
