### ISSUE TITLE
[Bug] [CDCSOURCE] When multiple sources and multiple sinks, the sink output fails

### ISSUE THREAD

**Issue by AntChen27** [DataLinkDC/dinky#1801]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

使用CDCSOURCE命令时，CDC源使用多个表，Sink使用多个目的地，只有第一个目的地接收到数据，后续目的地接收不到数据

### What you expected to happen

多个目的地均收到数据

### How to reproduce

使用CDCSOURCE命令时，CDC源使用多个表，Sink使用多个目的地

### Version

0.7.2

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Show your sql. thx

**Comment by AntChen27** [comment]
```
EXECUTE CDCSOURCE ods_demo_sync_job WITH (
    'connector' = 'mysql-cdc',
    'hostname' = '127.0.0.1',
    'port' = '3306',
    'username' = 'root',
    'password' = '123456',
    'checkpoint' = '900000',
    'parallelism' = '1',
    'scan.startup.mode' = 'initial',
    'jdbc.properties.tinyInt1isBit' = 'false',
    'jdbc.properties.transformedBitIsBoolean' = 'false',
    'table-name' = 'db_demo\.tab1,db_demo\.tab2',
	
    --下沉输出 （kafka）
    'sink[0].connector' = 'kafka',
    'sink[0].topic' = 'dw_demo_ods_${schemaName}_${tableName}',
    'sink[0].format' = 'debezium-json',
    'sink[0].properties.group.id' = '${tableName}',
    'sink[0].properties.bootstrap.servers' = '127.0.0.1:9092',

    --下沉输出 （TiDB）
    'sink[1].connector' = 'jdbc',
    'sink[1].url' = 'jdbc:mysql://127.0.0.1:4000/dw_demo_ods_${schemaName}',
    'sink[1].table-name' = 's_${tableName}',
    'sink[1].username' = 'root',
    'sink[1].password' = '123456'
);
```


flink version 1.16.1

**Comment by AntChen27** [comment]
I have adjusted and optimized this problem today, but I don't know whether it conflicts with the system design

**Comment by aiwenmo** [comment]
Has the problem been solved?

**Comment by AntChen27** [comment]
It's done. I'll submit the code tomorrow

**Comment by aiwenmo** [comment]
thx.

**Comment by aiwenmo** [comment]
I greatly appreciate your research and welcome to join the WeChat contributor group for further communication and construction~~
