### ISSUE TITLE
[Feature]KafkaSink 支持 partitioner

### ISSUE THREAD

**Issue by melin** [DataLinkDC/dinky#1809]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

KafkaSink 支持 partitioner，保障相同主键数据的写入顺序，否则容易乱序
![image](https://user-images.githubusercontent.com/1145830/228766936-b9ef801a-df06-48b3-b279-4a330a3a1ae3.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
sink.connector=?

**Comment by melin** [comment]
> sink.connector=?

kafka

**Comment by S0uLHun43r** [comment]
>
我们想把目前自己的flinkcdc任务搬迁上来，请问目前kafka sink是否支持partitioner
