### ISSUE TITLE
[Bug] [邮件告警] 任务【***】：UNKNOWN

### ISSUE THREAD

**Issue by hy0664** [DataLinkDC/dinky#1813]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

用了0.7.2新版本后，经常邮件告警显示作业是unknow，进去看flinkwebui作业是正常运行的，然后去dlink作业里要刷新一下状态才正常，过一段时间又unknow，不知道是不是bug还是我配置问题，之前0.6.8没这个问题的。

### What you expected to happen

<html>
<body>
<pre style="line-height: 23.8px; white-space: pre-wrap; color: rgb(0, 0, 0); font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">

Alert Type | Alert Time | Job ID | Job Name | Job Type | Job Status | Job StartTime | Job EndTime | Job Duration | Exception Log
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Flink 实时监控 | 2023-03-31 14:44:43 | db5e267f4088d3c621cce33f1bbfd4c3 | ODS_*** | FlinkSql | UNKNOWN | 2022-12-05 11:08:46 | 2023-03-31 14:44:43 | 116天 3小时 35分 56秒 | http://***:8081/#/job/db5e267f4088d3c621cce33f1bbfd4c3/exceptions

</pre>
</body>
</html>

### How to reproduce

正常运行过段时间就会收到邮件告警

### Version

0.7.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
fixed
