### ISSUE TITLE
[Refactor][web] refactor The metadata center is merged into the data source by clicking to jump

### ISSUE THREAD

**Issue by Zzm0809** [DataLinkDC/dinky#1823]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

refactor The metadata center is merged into the data source by clicking to jump

1.register a datasource
2.click this datasource
3.Replace current page Enter metadata center

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by arunimaChintu** [comment]
I want to work on this issue. Please assign me this issue

**Comment by Zzm0809** [comment]
> I want to work on this issue. Please assign me this issue

Hello, this issue needs to be completed after the registration of the data source in the registration center is completed.

**Comment by Zzm0809** [comment]
@arunimaChintu hi , this issue has processing???
