### ISSUE TITLE
[Refactor][web] refactor settingcenter‘s systeminfo

### ISSUE THREAD

**Issue by Zzm0809** [DataLinkDC/dinky#1825]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

refactor settingcenter‘s systeminfo

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by arunimaChintu** [comment]
I want to work on this issue.Please assign me this issue

**Comment by Zzm0809** [comment]
> I want to work on this issue.Please assign me this issue


That's great, looking forward to your pr
