### ISSUE TITLE
[Refactor][web] refactor systemcenter‘s process list

### ISSUE THREAD

**Issue by Zzm0809** [DataLinkDC/dinky#1826]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

refactor systemcenter‘s process list

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by arunimaChintu** [comment]
I want to work on this issue. Please assign me this issue

**Comment by Zzm0809** [comment]
> I want to work on this issue. Please assign me this issue

That's great, looking forward to your pr

**Comment by arunimaChintu** [comment]
Thankyou so much for assigning me . I have already cloned it, but I am not able to install the project dependencies , and I can't read the documentations provided since they are written in some different language that I don't understand. Can you please help me

**Comment by aiwenmo** [comment]
Please state your question.

**Comment by arunimaChintu** [comment]
how to install it? I can't install this after cloning. Can you please suggest me the commands to install

**Comment by Zzm0809** [comment]
> how to install it? I can't install this after cloning. Can you please suggest me the commands to install

You can refer to the debugging section of the official website for local startup debugging http://www.dlink.top/docs/next/developer_guide/local_debug

**Comment by wmtbnbo** [comment]
> Thankyou so much for assigning me . I have already cloned it, but I am not able to install the project dependencies , and I can't read the documentations provided since they are written in some different language that I don't understand. Can you please help me
[Development documentation.docx](https://github.com/DataLinkDC/dinky/files/11217418/Development.documentation.docx)
I have translated some development instructions on Dinky official website in this document, hoping to be helpful to you

**Comment by Zzm0809** [comment]
> > Thankyou so much for assigning me . I have already cloned it, but I am not able to install the project dependencies , and I can't read the documentations provided since they are written in some different language that I don't understand. Can you please help me
> > [Development documentation.docx](https://github.com/DataLinkDC/dinky/files/11217418/Development.documentation.docx)
> > I have translated some development instructions on Dinky official website in this document, hoping to be helpful to you

You are wonderful

**Comment by Zzm0809** [comment]
@wmtbnbo hi, this issue has processing???

**Comment by wmtbnbo** [comment]
> @wmtbnbo hi, this issue has processing???

sorry. @arunimaChintu  Accepted this issue.So i didn't handle this issue

**Comment by Zzm0809** [comment]
> sorry. @arunimaChintu Accepted this issue.So i didn't handle this issue

oh  sorry ,  @arunimaChintu this issue has processing????
