### ISSUE TITLE
[Refactor][admin] deprecate namespace

### ISSUE THREAD

**Issue by Zzm0809** [DataLinkDC/dinky#1830]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
I want to work on this issue. Please assign me this issue.
