### ISSUE TITLE
[Refactor][admin,web] move application.yaml's of dolphinscheduler's config to system setting

### ISSUE THREAD

**Issue by Zzm0809** [DataLinkDC/dinky#1836]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

move application.yaml's of dolphinscheduler's config to system setting

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Ksj14-kumar** [comment]
Hi @zhu-mingye, is anyone working on this issue? if not please assign it to me. I want to work on it.
I am using a window system so that according to my OS, I can convert it into an INI file. is it is right?

**Comment by Zzm0809** [comment]
> Hi @zhu-mingye, is anyone working on this issue? if not please assign it to me. I want to work on it. I am using a window system so that according to my OS, I can convert it into an INI file. is it is right?

I can convert it into an INI file.???
What does this mean? I don't understand

**Comment by Ksj14-kumar** [comment]
@zhu-mingye, [Source](https://en.wikipedia.org/wiki/INI_file) INI files were commonly used as system setting files for Windows operating systems and other applications. do you want it? if I am wrong so please explain what system setting means on issue #1836.

**Comment by Zzm0809** [comment]
> @zhu-mingye, [Source](https://en.wikipedia.org/wiki/INI_file) INI files were commonly used as system setting files for Windows operating systems and other applications. do you want it? if I am wrong so please explain what system setting means on issue #1836.

In dinky, system settings are used to manage global initialization configuration items in the program, such as: statement separator. task monitoring waiting time

**Comment by Zzm0809** [comment]
> > @zhu-mingye, [Source](https://en.wikipedia.org/wiki/INI_file) INI files were commonly used as system setting files for Windows operating systems and other applications. do you want it? if I am wrong so please explain what system setting means on issue #1836.
> 
> In dinky, system settings are used to manage global initialization configuration items in the program, such as: statement separator. task monitoring waiting time



@Ksj14-kumar 
Do you still need to open this issue and implement it

**Comment by Ksj14-kumar** [comment]
> > > @zhu-mingye, [Source](https://en.wikipedia.org/wiki/INI_file) INI files were commonly used as system setting files for Windows operating systems and other applications. do you want it? if I am wrong so please explain what system setting means on issue #1836.
> > 
> > 
> > In dinky, system settings are used to manage global initialization configuration items in the program, such as: statement separator. task monitoring waiting time
> 
> @Ksj14-kumar Do you still need to open this issue and implement it

@zhu-mingye, yes, I am working on it.

**Comment by Zzm0809** [comment]
> > > > @zhu-mingye, [Source](https://en.wikipedia.org/wiki/INI_file) INI files were commonly used as system setting files for Windows operating systems and other applications. do you want it? if I am wrong so please explain what system setting means on issue #1836.
> > > 
> > > 
> > > In dinky, system settings are used to manage global initialization configuration items in the program, such as: statement separator. task monitoring waiting time
> > 
> > 
> > @Ksj14-kumar Do you still need to open this issue and implement it
> 
> @zhu-mingye, yes, I am working on it.

ok looking forward to your pr

**Comment by Ksj14-kumar** [comment]
@zhu-mingye, you can close this issue I am not able to solve this issue.
