### ISSUE TITLE
[Bug] Postgres Sql to  Postgres Sql timestamp  type conversion error

### ISSUE THREAD

**Issue by javaht** [DataLinkDC/dinky#1846]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

时间会转换为以下格式：

![f38851bc2b98b762a3119f407f8b0ab](https://user-images.githubusercontent.com/54611681/229558908-75699a20-5366-4bbd-b0e4-7d05b46fb5e4.png)

### Use case

解决办法：
1.time.precision.mode=connect,   这种配置,  会将全部转成毫秒

debezium关于postgres的地址：
https://debezium.io/documentation/reference/1.6/connectors/postgresql.html#postgresql-time-precision-mode-adaptive-time-microseconds

### Related issues

none

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by javaht** [comment]
如果有八个小时的时差 修改一下sink的时区为UTC试试

**Comment by aiwenmo** [comment]
You're great. thx
