### ISSUE TITLE
[Bug] [Metadata] PostgreSql get DDL script error

### ISSUE THREAD

**Issue by boolean-dev** [DataLinkDC/dinky#1847]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

获取 pgsql 的 ddl 时，生成的 ddl 语句和源数据库的 ddl 不一致，如下图

![图片](https://user-images.githubusercontent.com/20177406/229675378-2b48a0a1-dd15-49dc-9c9b-0e00d45e2e63.png)

问题如下：
- not null 属性错位了
- no primary key
- create table 语句末尾截取异常
---
When getting the DDL of pgsql, the generated DDL statements are not consistent with the DDL of the source database, as shown in the following figure:

![图片](https://user-images.githubusercontent.com/20177406/229675378-2b48a0a1-dd15-49dc-9c9b-0e00d45e2e63.png)

The questions are as follows:
- The not null property is misplaced
-  no primary key
- The exception is truncated at the end of the create table statement

### What you expected to happen

Generate the correct pgsql DDL

### How to reproduce

Just get the DDL for pgsql

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by javaht** [comment]
https://github.com/DataLinkDC/dinky/blob/dev/dinky-metadata/dinky-metadata-postgresql/src/main/java/org/dinky/metadata/query/PostgreSqlQuery.java  看下这里的代码   重新打包

**Comment by aiwenmo** [comment]
dev or 0.7.2 ?

**Comment by boolean-dev** [comment]
dev,我这边已经修复好了，这两天会把修复好的PR上去

**Comment by boolean-dev** [comment]
我这边刚拉取了下最新的代码，还是存在问题
![image](https://user-images.githubusercontent.com/20177406/230832972-0615a230-6de2-42a5-9274-0b7c88e0dd8b.png)

我后续还在这个 issues 下面提交PR？

**Comment by aiwenmo** [comment]
> 我这边刚拉取了下最新的代码，还是存在问题 ![image](https://user-images.githubusercontent.com/20177406/230832972-0615a230-6de2-42a5-9274-0b7c88e0dd8b.png)
> 
> 我后续还在这个 issues 下面提交PR？

我把修复代码提交的 0.7 分支了
