### ISSUE TITLE
[Feature][dinky-cdc] 支持cdc整库同步到 paimon数据胡

### ISSUE THREAD

**Issue by gitfortian** [DataLinkDC/dinky#1855]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

支持cdc整库同步到 paimon数据胡

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by javaht** [comment]
有没有可能paimon以前叫 Flink Table Store
![image](https://user-images.githubusercontent.com/54611681/230405401-138469fe-0103-448e-bf98-6cb5e9485404.png)

**Comment by gitfortian** [comment]
ok



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月06日 22:18 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [DataLinkDC/dinky] [Feature][dinky-cdc] 支持cdc整库同步到 paimon数据胡 (Issue #1855) |

有没有可能paimon以前叫 Flink Table Store
