### ISSUE TITLE
[Feature][Registration Center & Metadata Center] Support Paimon as datasource

### ISSUE THREAD

**Issue by leeoo** [DataLinkDC/dinky#1856]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Support Paimon as datasource, so we can conveniently view catalogs, databases, tables and columns, generate SQL and do query in SQL Console, etc.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by javaht** [comment]
有没有可能paimon以前叫 Flink Table Store
![image](https://user-images.githubusercontent.com/54611681/230405786-473276d4-e09d-4cba-aa1d-03c14df88a20.png)

**Comment by gaoyan1998** [comment]
has supported
