### ISSUE TITLE
dinky任务手动停止不了

### ISSUE THREAD

**Issue by wangyayuan18** [DataLinkDC/dinky#1867]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.dinky运维中心，任务状态是运行中，但实例名称为空，也就是说dinky运维中心虽然任务运行中，但跟yarn通信不通，因为yarn上面任务失败自动重试过了，之前也说过，现在dinky还没有做到实时监控yarn任务通信状态
![image](https://user-images.githubusercontent.com/64136230/230886794-79d1f951-802a-4eca-89d1-5e68beb7a561.png)
2.因为dinky运维中心不能手动savepoint了，我只能用flink命令在服务器上手动savepoint停止任务，但dinky上面有点任务还在运行中，有点任务确实是停止了，所以我只能去数据库里面更改现运行中任务状态为cancle状态才能停止

### What you expected to happen

1.dinky运维中心，任务状态是运行中，但实例名称为空，也就是说dinky运维中心虽然任务运行中，但跟yarn通信不通，因为yarn上面任务失败自动重试过了，之前也说过，现在dinky还没有做到实时监控yarn任务通信状态
![image](https://user-images.githubusercontent.com/64136230/230886794-79d1f951-802a-4eca-89d1-5e68beb7a561.png)
2.因为dinky运维中心不能手动savepoint了，我只能用flink命令在服务器上手动savepoint停止任务，但dinky上面有点任务还在运行中，有点任务确实是停止了，所以我只能去数据库里面更改现运行中任务状态为cancle状态才能停止

### How to reproduce

1.dinky运维中心，任务状态是运行中，但实例名称为空，也就是说dinky运维中心虽然任务运行中，但跟yarn通信不通，因为yarn上面任务失败自动重试过了，之前也说过，现在dinky还没有做到实时监控yarn任务通信状态
![image](https://user-images.githubusercontent.com/64136230/230886794-79d1f951-802a-4eca-89d1-5e68beb7a561.png)
2.因为dinky运维中心不能手动savepoint了，我只能用flink命令在服务器上手动savepoint停止任务，但dinky上面有点任务还在运行中，有点任务确实是停止了，所以我只能去数据库里面更改现运行中任务状态为cancle状态才能停止

### Version

0.7.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
1.0 fixed
