### ISSUE TITLE
[Bug] [dlink-admin] UDF重复，导致Dlink无法重启的问题 Duplicate key com.dlink.function.data.model.UDF

### ISSUE THREAD

**Issue by ixiekun** [DataLinkDC/dinky#1876]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Dlink0.7.2下的UDF 目前还在孵化阶段，请谨慎使用；
step1: 当我进行UDF测试的时候，不小心COPY相同的代码位于不同的UDF中
![image](https://user-images.githubusercontent.com/48663402/231369649-aa2c8351-29de-462c-aad1-632288fa1b6a.png)
step2: 当我进行Dlink重启的时候，提示重复的函数，不能启动
![image](https://user-images.githubusercontent.com/48663402/231369866-309b6d29-498a-42e6-8cfe-ad166e117c0a.png)

### What you expected to happen

目前UDF还在孵化阶段，请谨慎使用；
应该在UDF定义的时候，将函数名和作业名字关联，确保函数名和作业名一样，是唯一的
![image](https://user-images.githubusercontent.com/48663402/231370774-9704bc5d-ec86-4699-aeb1-9726043ca3d2.png)

### How to reproduce

只需要定义两个UDF，名字不同，但是内容是一样的即可

### Version

0.7.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Aitongong** [comment]
临时解决方案：

**Comment by gaoyan1998** [comment]
1.0 fixed
