### ISSUE TITLE
[Bug] [CDCSOURCE] 自动建表 Auto generateCreateTableSql 生成的语句部分不正确

### ISSUE THREAD

**Issue by jeeinn** [DataLinkDC/dinky#1880]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

INFO  com.dlink.metadata.driver.MySqlDriver 82 generateCreateTableSql - Auto generateCreateTableSql

对 enum 类型转换
```
  `type` enum('A','T','V') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'A',
```
↓↓↓
```
`type`  enum(0) DEFAULT A,
```
---
对 unsigned 标记转换 已知：https://github.com/DataLinkDC/dinky/issues/1787
```
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`parent_id` smallint(5) unsigned NOT NULL DEFAULT '0',
```
↓↓↓
```
`id`  int unsigned(10) NOT  NULL  AUTO_INCREMENT ,
`parent_id`  smallint unsigned(5) DEFAULT 0,
```

### What you expected to happen

可以转换为正确建表语句

### How to reproduce

清空目标库，自动建表时发生

### Anything else

https://github.com/DataLinkDC/dinky/blob/7223d3c5537b555a3fc02ef0df89e8486dce2740/dinky-metadata/dinky-metadata-mysql/src/main/java/org/dinky/metadata/driver/MySqlDriver.java#L93-L132

### Version

0.7.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
unsigned 已在0.7分支修复，dev分支还未修复。关于枚举类型的，你有适合的解决方案吗

**Comment by jeeinn** [comment]
是不是可以直接使用获取数据源时的建表语句呢，这里自己生成可能还会有其他未知问题。我不太懂哈，只是随便说说。
ps: 非java开发

**Comment by aiwenmo** [comment]
show create table ?

**Comment by jeeinn** [comment]
对对对，是这个意思

**Comment by Zzm0809** [comment]
> unsigned 已在0.7分支修复，dev分支还未修复。关于枚举类型的，你有适合的解决方案吗

```sql

SELECT
column_type
FROM
information_schema. COLUMNS
WHERE
TABLE_SCHEMA = "数据库名"
AND DATA_TYPE = 'enum'
AND table_name="表明"
AND column_name="列名";
```

可见:
![image](https://github.com/DataLinkDC/dinky/assets/58576849/e479be49-ed21-4c3c-85ef-55414eb79610)
