### ISSUE TITLE
[Bug] [Module Name] ERROR: java.lang.NoClassDefFoundError: org/apache/flink/configuration/RestOptions

### ISSUE THREAD

**Issue by Jayce-Ye** [DataLinkDC/dinky#1881]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

 报错Caused by: java.lang.ClassNotFoundException: org.apache.kafka.connect.json.JsonConverter

### What you expected to happen

解决包冲突

### How to reproduce

执行flink cdc同步语句

### Version

0.7.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
use fat jar

**Comment by Jayce-Ye** [comment]
use fat jar ,report errors

 ERROR: java.lang.NoClassDefFoundError: Lorg/apache/kafka/connect/json/JsonConverter;

**Comment by Jayce-Ye** [comment]
> use fat jar
use fat jar ,report errors

ERROR: java.lang.NoClassDefFoundError: Lorg/apache/kafka/connect/json/JsonConverter;

**Comment by aiwenmo** [comment]
使用的什么功能

**Comment by Jayce-Ye** [comment]
> 使用的什么功能 local 模式和per-job都会，下面是执行语句

CREATE TABLE datagen (
 id STRING,
 name STRING,
 age INT
) WITH (
 'connector' = 'datagen',
 'rows-per-second' = '5', -- 每秒生成的数据行数据
 'fields.id.length' = '5', --字段长度限制
 'fields.name.length'='3',
 'fields.age.min' ='1', -- 最小值
 'fields.age.max'='100' -- 最大值
);

-- LIKE： 基于已有的表创建表
CREATE TABLE print_table (
 id STRING,
 name STRING,
 age INT
) WITH ('connector' = 'print');

insert into print_table select * from datagen; 是否缺少kafka的包呢

**Comment by aiwenmo** [comment]
看下 plugins 下的依赖

**Comment by Jayce-Ye** [comment]
> 看下 plugins 下的依赖

![image](https://user-images.githubusercontent.com/23288082/233327966-95726bd4-979b-48a3-b366-4280600bea1c.png)

**Comment by Jayce-Ye** [comment]
找到问题了，多了
![image](https://user-images.githubusercontent.com/23288082/233835253-80ada33c-5c6e-48aa-8b69-9db57e403bc7.png)
这个，有这个
![image](https://user-images.githubusercontent.com/23288082/233835265-163a5baf-2e88-43a9-9b71-1e5846606187.png)
就行了
