### ISSUE TITLE
CDCSOURCE 整库同步 源库可不可以是TIDB

### ISSUE THREAD

**Issue by kgdxpr** [DataLinkDC/dinky#1886]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

CDCSOURCE 整库同步 源库可不可以是TIDB

### What you expected to happen

CDCSOURCE 整库同步 源库可不可以是TIDB

### How to reproduce

CDCSOURCE 整库同步 源库可不可以是TIDB

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
你可以通过扩展来实现 , 可以参考 mysql 的实现方式

**Comment by yqzdy1207** [comment]
需求 + 1 ，想支持到TIDB 6.5.2

**Comment by Zzm0809** [comment]
> 需求 + 1 ，想支持到TIDB 6.5.2

来实现一下?
