### ISSUE TITLE
0.7.2 安装，解压后没有html

### ISSUE THREAD

**Issue by yxiaoy6** [DataLinkDC/dinky#1897]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

0.7.2解压后没有html文件，nginx前端root应该怎么部署？

### What you expected to happen

希望提供最新版本的html目录

### How to reproduce

下载后解压

### Version

0.7.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
从dlink-admin.jar解压获取 statics 目录，即为html目录
