### ISSUE TITLE
The high availability mode is not perfect enough to automatically recognize new job addresses

### ISSUE THREAD

**Issue by LeonYoah** [DataLinkDC/dinky#1900]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

**场景：** 任务使用yarn perjob模式正常启动，且配置了连接zookeeper的**高可用**， 突然有一天yarn网络波动，导致该任务的job manager失败了，然后任务重启，这时候flink他会自动读checkpoint和高可用的配置去恢复任务，但是任务的地址由 slave1:34467 变成了 master:45564,这是dinky无法获取新的地址，导致任务显示未知状态

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
来个完美的方案
