### ISSUE TITLE
[Bug] CDCSOURCE 整库同步 Mysql 设置 parallelism 并发数量 > 1 时，update数据，数据会丢失同步

### ISSUE THREAD

**Issue by tan-zhuo** [DataLinkDC/dinky#1910]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

启动任务时，会自动去比对全量数据。比对完成后数据是正确的。
但数据源修改某条数据记录后，就会丢失这条记录。
![image](https://user-images.githubusercontent.com/32378959/233818943-348a8b90-f644-469c-9855-8f8b2de43bd0.png)

### What you expected to happen

正确同步数据。

### How to reproduce

编写同步 CDCSOURCE SQL后，设置并行度 > 1,待数据全部同步完成后 去修改 源表数据。则发生数据丢失。

### Version

0.7.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
如何验证丢失同步

**Comment by tan-zhuo** [comment]
> 如何验证丢失同步

Mysql整库同步时，设置并行数量>1，待表数据都同步完成后，修改源表数据，目标表就会丢失这条update数据。

**Comment by aiwenmo** [comment]
sink到print试试

**Comment by tan-zhuo** [comment]
> sink到print试试

空了我打印出来 看下具体原因。现在先暂时设置的 并行 1

**Comment by gaoyan1998** [comment]
can not support
