### ISSUE TITLE
[Bug] 使用 CDCSOURCE 同步数据表时，如果来源表数据库名称带有"-"符号，则无法同步数据

### ISSUE THREAD

**Issue by tan-zhuo** [DataLinkDC/dinky#1911]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

来源表数据库名称带有"-"符号，则无法同步数据
![lQLPJwAMlLJ4eK7NAgbNAmewQjNL0uzQdcAEPK1khoAKAA_615_518](https://user-images.githubusercontent.com/32378959/233819086-d2287977-f644-4074-87ae-9451b271db54.png)
获取计划，抛出异常
![image](https://user-images.githubusercontent.com/32378959/233819115-4e061d2f-10e4-4f5a-ba96-55d761180d63.png)

如果配置不带 "-" 符号的数据库，进行同步
![image](https://user-images.githubusercontent.com/32378959/233819193-5b0979e2-b1ff-4d70-8b6a-fc260faa509b.png)

计划正常：
![image](https://user-images.githubusercontent.com/32378959/233819140-1c537fc7-a709-4914-8398-09d324dbc135.png)

看了下源码还是故意这样处理的？不太理解用意是什么。
补充：我已经通过git记录查看到这句代码的起因：#1536  但这个修复方案 完全无法解决问题，需要继续进行修复
![image](https://user-images.githubusercontent.com/32378959/233825465-57b04f90-96b8-4d51-a69a-47c9c9ad9135.png)

在创建CDC来源实例时，调用了 table 中的函数，导致数据库名称被替换
![image](https://user-images.githubusercontent.com/32378959/233826969-c86fc9c2-c98a-499f-a533-1bea82782a3e.png)

### What you expected to happen

支持 table-name 数据库带上 "-" 符号，很多公司数据库命名都会有该字符
例如：不注重规范的公司，则会出现这种库名

### How to reproduce

CDCSOURCE SQL脚本中 table-name 参数中的数据库名带上 "-" 即可重现

### Version

0.7.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
目前存在这个问题，如何解决比较好呢

**Comment by tan-zhuo** [comment]
> 目前存在这个问题，如何解决比较好呢

这个问题的根本原因应该是 flink-sql-connector-mysql-cdc 的问题，但我在 flink-sql-connector-mysql-cdc -2.3.0.jar 版本中使用带有 “-” 符号的数据库名称也可以正常使用。你可以试一试。

**Comment by tan-zhuo** [comment]
> 目前存在这个问题，如何解决比较好呢

目前我通过日志看到的是只有在创建 SQLSinkBuilder.addTableSink 方法中的 view 是必须下划线，但其实 cdc 是没有强制必须下划线的，所以我目前的解决办法
创建cdc连接时，获取原字符串，不要替换
![image](https://user-images.githubusercontent.com/32378959/233935161-9f858406-c7b5-4902-a846-055d5035dc20.png)

创建视图进行统一替换为下划线
![image](https://user-images.githubusercontent.com/32378959/233935249-baaaf970-f6b8-4b33-8710-461f7a92560e.png)

目前能够正常运行
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/32378959/233935636-c59d9ec8-7bf7-4993-8946-f920e16a3ebe.png">

**Comment by AlstoreMr** [comment]
![3C44D829-096A-4f1e-A5D3-362C51A4AC5F](https://github.com/DataLinkDC/dinky/assets/88300531/aaa114d7-cda0-484d-809f-8ad24aa70c0e)
可以修改一下

**Comment by gaoyan1998** [comment]
fix at 0.7.5 later
