### ISSUE TITLE
[Bug] pom 中疑似单词拼写错误

### ISSUE THREAD

**Issue by chenxu8989** [DataLinkDC/dinky#1916]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

项目根目录中 pom.xml 65行疑似拼写了错误单词

<jackjson.version>2.14.1</jackjson.version>

jackson  ->  jackjson

如果是故意这么写的, 那就请忽略吧.

### What you expected to happen

项目根目录中 pom.xml 65行疑似拼写了错误单词

### How to reproduce

项目根目录中 pom.xml 65行疑似拼写了错误单词

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Yes. You are right. Welcome to fix it.
