### ISSUE TITLE
[Feature][dlink-client] Analyze custom functions from Flink SQL

### ISSUE THREAD

**Issue by HamaWhiteGG** [DataLinkDC/dinky#1930]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Analyze the custom function from Flink SQL, so that users can see which tasks the custom function is used in the product in the future. Especially when deleting a function, it can also remind users who use this function

### Use case

1. Create custom function my_suffix_udf.
```sql 
CREATE FUNCTION IF NOT EXISTS my_suffix_udf AS 'com.hw.lineage.flink.common.MySuffixFunction'
```
2. For example, use function my_suffix_udf in Flink SQL.
```sql
 INSERT INTO dwd_hudi_usersSELECT id ,
         LOWER(my_suffix_udf(name)) ,
         UPPER(TRIM(name)) AS company_name ,
         birthday ,
         ts ,
         DATE_FORMAT(birthday,
         'yyyyMMdd')
FROM ods_mysql_users 

```
3. Finally, it is parsed that the above SQL uses the custom function `my_suffix_udf`, which does not contain System Functions.

### Related issues

no

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leechor** [comment]
what use of reminding the function that be deleted already?

**Comment by HamaWhiteGG** [comment]
In the product design, a warning can be issued before deletion, telling users which tasks this function is used by and what risks will be caused by deletion. 

Even for some important tasks, you can prevent deleting a function unless the user first removes the reference to this function. Depends on how the product is designed

**Comment by leechor** [comment]
> In the product design, a warning can be issued before deletion, telling users which tasks this function is used by and what risks will be caused by deletion.
> 
> Even for some important tasks, you can prevent deleting a function unless the user first removes the reference to this function. Depends on how the product is designed

I have misunderstood, it's good design.

**Comment by HamaWhiteGG** [comment]
Note that this feature **only** supports **flink1.14, 1.15, 1.16 and 1.17**

**Comment by aiwenmo** [comment]
> Note that this feature **only** supports **flink1.14, 1.15, 1.16 and 1.17**

This is no problem. tnx
