### ISSUE TITLE
[Bug] [Client] cdcsource task set checkpoint parameter is invalid

### ISSUE THREAD

**Issue by boolean-dev** [DataLinkDC/dinky#1939]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

The cdcsource task set checkpoint parameter is invalid.
Mission Environment:
- Flink 1.15
- Source database: PostgreSql
- Sink database:  StarRocks

The set checkpoint parameter does not fail when I perform a normal Flink-Sql task, but it does not take effect when I perform the cdcsource task, so I looked into the cause of the problem.
When a normal SQL task is found to be executing, Flink configures the configuration as follows:
![image](https://user-images.githubusercontent.com/20177406/236400702-3fc01af9-a901-44ca-a77a-1e5805bed4d6.png)

Flink executes both Flink's config and checkpointcfg, so the checkpoint set parameter takes effect when the Flink SQL task executes.
But right now at the StarRocks Sink, the checkpoint parameter does not take effect.
So Far I've verified the Cdcsource StarRocks side, which doesn't take effect, and it's not clear if the other sinks will

---
cdcsource 任务 set checkpoint 参数失效.
任务执行环境：
- Flink 1.15
- Source database: PostgreSql
- Sink database:  StarRocks

当我执行普通的 Flink-Sql 任务时， set checkpoint 参数并不会失效，但是执行 cdcsource 任务时, 参数并不会生效，因此，我对问题出现的原因进行了排查。
发现普通的 sql 任务执行时，Flink 会将配置进行如下的配置:
![image](https://user-images.githubusercontent.com/20177406/236400702-3fc01af9-a901-44ca-a77a-1e5805bed4d6.png)

Flink 会同时执行 flink 的 config 和 checkpointcfg，因此，在 Flink Sql 任务执行时， checkpoint set 参数将会生效。
但是目前在 StarRocks Sink 端，checkpoint 参数并不会生效。
目前我验证了cdcsource StarRocks 端，此参数不会生效，尚不清楚其他 sink 端是否会生效

### What you expected to happen

When the cdcsource task is executed, the set checkpoint parameter takes effect.

---
执行 cdcsource 任务时，set checkpoint 参数生效

### How to reproduce

Execute the PostgreSql2StarRocks cdcsource task

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi. Are you using dev branch?
