### ISSUE TITLE
with语句和with多从句检验问题

### ISSUE THREAD

**Issue by wangyayuan18** [DataLinkDC/dinky#1946]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

USE CATALOG default_catalog;

use default_database;

CREATE TABLE test(
  id int,
  a_user_id varchar,
  b_user_id varchar,
  PRIMARY KEY (id) NOT ENFORCED
) with(
   'connector' = 'jdbc',
   'url' = 'jdbc:mysql://xxx.xx.xx.xx:3306/datacheck?createDatabaseIfNotExist=true&useSSL=false',
   'table-name' = 'test',
   'username'='xxx',
   'password'='xxx'
);

with atable as (
  select 
  user_id
  from 
  hive_catalog.ods.ods_market_tb_order_detail_pt_mm_s
  where pt=202301 and day_dt=20230101
  ),
  btable as (
  select 
  user_id
  from 
  hive_catalog.ods.ods_market_tb_recharge_detail_pt_mm_s
  where pt=202301 and day_dt=20230101
  );

  insert into default_catalog.default_database.test
  SELECT 1 as id,* FROM default_catalog.default_database.aatable, 
  default_catalog.default_database.btable;

![image](https://user-images.githubusercontent.com/64136230/236616674-b6b36e05-9fcf-4a58-bc57-27db980a1455.png)

多with从句语法检验不报错，但弹窗里面没有with语句

### What you expected to happen

单with从句也是一样的问题
![image](https://user-images.githubusercontent.com/64136230/236616710-d0cf9366-da87-4b98-96a3-51d5d10d8843.png)
![image](https://user-images.githubusercontent.com/64136230/236616715-e2e52ef9-c088-42aa-8bfb-be0564ebbb5d.png)
![image](https://user-images.githubusercontent.com/64136230/236616701-a044febe-4af8-49a0-b3b5-80575dd2e248.png)

### How to reproduce

1

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ZBHdd** [comment]
这个有解决吗
