### ISSUE TITLE
[Feature][Client] cdcsource sink add rename parameter

### ISSUE THREAD

**Issue by boolean-dev** [DataLinkDC/dinky#1949]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

I need to synchronize the partition table (the branch table) and merge multiple tables from the original library into one table.
For example:
The original table has the following data tables,
order_default,
order_2020,
order_2021,
order_2022,
order_hot
i need to synchronize these tables and write them to a table on the Sink: 'order' .
Currently, cdcsource is unable to implement this requirement.

---
我需要同步分区表(分库分表),需要将原库的多张表合并为一张表。
例如：
原表有如下几张数据表，
order_default,
order_2020,
order_2021,
order_2022,
order_hot
我需要将以上几张表同步后，写入至 Sink 端的一张表:`order`。
目前情况下，cdcsource 暂时无法实现此需求。

### Use case

add 'sink.table.rename' parameter so that all synchronized tables of the current 'cdcsource' are renamed to this table name

---
增加 `sink.table.rename` 参数，使得当前 `cdcsource` 的所有同步的表同重命名为此表名

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
dinky is support  multiple tables now .
 Try 'split.enable' = 'true'

**Comment by boolean-dev** [comment]
I'm user PostgresSql, And now not support ` 'split.enable' = 'true'` multiple tables
（´＿｀）😭

**Comment by boolean-dev** [comment]
I tried modifying the code to make PostgreSQL support multiple tables, but it didn't work.

Therefore, I am not sure if this additional rename parameter will be used by others, and I am not sure if this feature should be merged into the Dinky Master Branch
