### ISSUE TITLE
[Bug] [dinkyAdmin]  In yarn session mode ,the  savepoint stop will Failure

### ISSUE THREAD

**Issue by lovingfeel** [DataLinkDC/dinky#1952]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

In yarn session mode ,the  savepoint stop will Failure ~~ because HttpUtil.post() methods not specific param "target-directory",
  ,and  set state.savepoints.dir ="hdfs://xxx.xxx.xx" is not effective

### What you expected to happen

 expected to click savepoint stop button can return  nomal stop flink job

### How to reproduce

1， http request add param  “target-directory”=“hdfs://xxx.xxx.xx”

### Anything else

no

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Specify in the flink-conf file.
