### ISSUE TITLE
[Bug] [python udf]  Cannot drop a catalog which is currently in use.

### ISSUE THREAD

**Issue by lapDog** [DataLinkDC/dinky#1965]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

跑官方例子
create temporary function sb_p as 'python_udf_test.SubFunction' language PYTHON;
这句注册临时函数抛出
org.apache.flink.table.catalog.exceptions.CatalogException: Cannot drop a catalog which is currently in use.
flink环境standalone ->defaultcatalog,python环境conda python3.8,udf编译成功，执行失败。
我不知道为什么创建临时函数要unregcatalog...大佬帮忙看看呢
![图片](https://github.com/DataLinkDC/dinky/assets/11813246/102ecd05-e58b-499c-98ac-8159a08ea9a8)

### What you expected to happen

nope,,,idnw

### How to reproduce

按照官方文档配置，执行
create temporary function sb_p as 'python_udf_test.SubFunction' language PYTHON;
必现

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leeoo** [comment]
I encountered this problem some days ago too, you can open com.dlink.executor.Executor.java file, remove or uncomment below code which is marked by red frame, and then replace the same jar under dinky's lib directory with re-build's dlink-executor-0.7.3.jar.
![图片](https://github.com/DataLinkDC/dinky/assets/2136182/498aa3fa-9d6c-464a-894d-14c2891fca3a)

**Comment by lapDog** [comment]
> I encountered this problem some days ago too, you can open com.dlink.executor.Executor.java file, remove or uncomment below code which is marked by red frame, and then replace the same jar under dinky's lib directory with re-build's dlink-executor-0.7.3.jar. ![图片](https://user-images.githubusercontent.com/2136182/237597272-498aa3fa-9d6c-464a-894d-14c2891fca3a.png)

thanks,man,i will try ...

**Comment by lapDog** [comment]
> I encountered this problem some days ago too, you can open com.dlink.executor.Executor.java file, remove or uncomment below code which is marked by red frame, and then replace the same jar under dinky's lib directory with re-build's dlink-executor-0.7.3.jar. ![图片](https://user-images.githubusercontent.com/2136182/237597272-498aa3fa-9d6c-464a-894d-14c2891fca3a.png)

i cannot found it, my version is latest 0.7.3. this code like this.
![图片](https://github.com/DataLinkDC/dinky/assets/11813246/fdf7a99e-cd6e-4e78-a8df-d7552fb49511)

**Comment by leeoo** [comment]
Umm..., I see it is still in the latest code of 0.7 branch, please have a check again.
https://github.com/DataLinkDC/dinky/blob/0.7/dlink-executor/src/main/java/com/dlink/executor/Executor.java
![图片](https://github.com/DataLinkDC/dinky/assets/2136182/e06a8db1-ccce-46c8-9999-266060d9d1a7)

**Comment by leeoo** [comment]
Fix this bug in PR #1960
