### ISSUE TITLE
[Bug] [dinky-web] 运维中心一键上下线查询报错

### ISSUE THREAD

**Issue by George-zqq** [DataLinkDC/dinky#1985]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

> 在运维中心一键上下线中, 如果选择框不选任何选项, 查询会报 Something went wrong, 如下图
![image](https://github.com/DataLinkDC/dinky/assets/23392145/bc81d83e-537b-469e-9442-3629eed0713c)

### What you expected to happen

`1. 在未选择的任何选项时候, 可将查询按钮置灰`

### How to reproduce

`1. 选择运维中心`
`2. 选择一键上线`
`3. 弹出选择框不选择任何选项`
`4. 点击查询`

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
1.0 has deleted
