### ISSUE TITLE
[Bug] [环境配置] 其他配置参数添加不了

### ISSUE THREAD

**Issue by luoyize** [DataLinkDC/dinky#1998]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

输入参数，再输入值，参数就消失了，再输入参数，值消失了

### What you expected to happen

其他参数配置有问题

### How to reproduce

输入参数，再输入值，参数就消失了，再输入参数，值消失了

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leechor** [comment]
先刷新一下页面

**Comment by luoyize** [comment]
> 先刷新一下页面

可以了
