### ISSUE TITLE
[Refactor][web] refactor datastudio page

### ISSUE THREAD

**Issue by Zzm0809** [DataLinkDC/dinky#2011]
### Refactoring points (based on the existing layout, such as layout changes, the following related optimization points will also be considered)

- Adjust the proportion of edit box and console ( 编辑框与控制台占比调整) 
- Console added Maximize/Minimize (控制台加入 最大化/最小化)
- Minimization of the left and right sides (左右侧的最小化实现)
- Search of metadata tables (元数据表目录树的搜索)

### Sub Task

- [ ] #1696 (to be done after the layout is completed)
- [ ] #2124 refactor datastudio's layout

**Comment by Zzm0809** [comment]
> note: 数据开发页面需要缓存一些配置/初始数据,需要使用数据流(dva) 进行状态管理, 以下是需要状态管理的列表:

- 需要缓存 `配置中心` -> `全局设置` 中的全部配置,
  - ds配置主要用来集成 ds , 如果该配置项开启 则显示推送到ds的按钮开关

> 按钮相关:

- 如果作业类型非 `flinksql`, 则不展示(或者禁用) 执行计划/逻辑检查等按钮
- 如未启动 ds 则不展示(或者禁用) ds 推送功能按钮

**Comment by javaht** [comment]
元数据中心-元数据 加一个搜索框。用来搜索表
![image](https://github.com/DataLinkDC/dinky/assets/54611681/57247efb-aa9f-455d-9289-d1c17b6942ca)

ok, 这个在规划内 已有issue: #1696

**Comment by leeoo** [comment]
当前 0.7.3 版本的数据开发界面的作业编辑文本框的默认高度有点小了，建议调大作业编辑文本框高度，降低控制台的高度，可以将二者比例调到大致7:3

**Comment by Zzm0809** [comment]
> 当前 0.7.3 版本的数据开发界面的作业编辑文本框的默认高度有点小了，建议调大作业编辑文本框高度，降低控制台的高度，可以将二者比例调到大致7:3

ok, tks , 会做一些调整 , 或者你认为如果默认最小化如何, 需要时再调出

**Comment by leeoo** [comment]
> > 当前 0.7.3 版本的数据开发界面的作业编辑文本框的默认高度有点小了，建议调大作业编辑文本框高度，降低控制台的高度，可以将二者比例调到大致7:3
> 
> ok, tks , 会做一些调整 , 或者你认为如果默认最小化如何, 需要时再调出

参考 IDEA、Eclispse 那样就行，不用默认最小化，就占比低点就行，控制台不要喧宾夺主即可，甚至可以考虑给控制台加个最大化按钮，这样有时候看错误日志时就不用手工上下拖动来把控制台调界面整到最大了

**Comment by leeoo** [comment]
![图片](https://github.com/DataLinkDC/dinky/assets/2136182/ad586fff-e713-4885-96f8-1538d90050a4)
这个最小化按钮实际上没有效果，建议加上效果

**Comment by Zzm0809** [comment]
> > > 当前 0.7.3 版本的数据开发界面的作业编辑文本框的默认高度有点小了，建议调大作业编辑文本框高度，降低控制台的高度，可以将二者比例调到大致7:3
> > 
> > 
> > ok, tks , 会做一些调整 , 或者你认为如果默认最小化如何, 需要时再调出
> 
> 参考 IDEA、Eclispse 那样就行，不用默认最小化，就占比低点就行，控制台不要喧宾夺主即可，甚至可以考虑给控制台加个最大化按钮，这样有时候看错误日志时就不用手工上下拖动来把控制台调界面整到最大了

OK, 这些优化点将在重构时加入进去

**Comment by leeoo** [comment]
建议添加“选中当前打开的作业”按钮，具体参见 issue #1412

**Comment by leeoo** [comment]
之前提的几个 issue： #1023 #1031 #1032 

Btw, #1031 在 Dinky 0.7.3 版本复现步骤
![图片](https://github.com/DataLinkDC/dinky/assets/2136182/7fe1b4c8-3fa9-47ef-82b9-a3c6b3063cf6)
![图片](https://github.com/DataLinkDC/dinky/assets/2136182/260b81cc-2ed1-483f-8e21-c220ccbad2f8)

**Comment by Doit-pudding** [comment]
1. 加强K8S的交互逻辑，经常出现资源已存在（非正常运行），无法再次提交作业的情况。
2. 开启K8S高可用配置，会出现insert dlink_clusert 唯一索引冲突的问题，优化一下。 
3. 优化下运维中心。
4. 优化登陆时选择租户的逻辑，如果归属单一租户，直接进入即可。  另外，删除租户，请删除用户关联关系。

**Comment by Zzm0809** [comment]
> 1. 加强K8S的交互逻辑，经常出现资源已存在（非正常运行），无法再次提交作业的情况。
> 2. 开启K8S高可用配置，会出现insert dlink_clusert 唯一索引冲突的问题，优化一下。
> 3. 优化下运维中心。
> 4. 优化登陆时选择租户的逻辑，如果归属单一租户，直接进入即可。  另外，删除租户，请删除用户关联关系。

1. @gaoyan1998 
2. @gaoyan1998 
3. @gaoyan1998 
   @Doit-pudding 说明下优化思路及建议
4. 均已实现
