### ISSUE TITLE
[Feature][web] Add dashboard to display the platform overview

### ISSUE THREAD

**Issue by aiwenmo** [DataLinkDC/dinky#2030]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
![a4c5b9b35fd5c3c6e7126b29bfa39b3](https://github.com/DataLinkDC/dinky/assets/32723967/2306543d-1ad1-4336-8bf9-cd5aaf970545)
This is a static page, and I am implementing a data interface. 
If you have any good suggestions, please discuss them here.

**Comment by whmnoe4j** [comment]
很棒的特性，期待，这个是在哪个版本实现啊

**Comment by Zzm0809** [comment]
> 很棒的特性，期待，这个是在哪个版本实现啊

dev 新 web 模块

**Comment by leeoo** [comment]
建议在上面部分添加“告警次数”指标

**Comment by Zzm0809** [comment]
> 建议在上面部分添加“告警次数”指标

告警次数? 我理解可以添加`存在告警的任务数`

**Comment by leeoo** [comment]
建议加上“实时作业数量”、“批处理作业数量”这2个统计指标

**Comment by leeoo** [comment]
建议加上“实时作业数量”、“批处理作业数量”这2个统计指标
