### ISSUE TITLE
[Bug] [CDCSource整库同步] 无法Sink到Doris

### ISSUE THREAD

**Issue by panxianhaoo** [DataLinkDC/dinky#2037]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

dinky版本：0.7.3
flink版本：1.16.1
doris版本：1.2.4
使用如下语句进行整库同步
SET execution.checkpointing.interval = 10s;
SET execution.checkpointing.tolerable-failed-checkpoints=10;
SET state.checkpoint-storage = filesystem;
SET state.checkpoints.dir=file:///home/flink;
EXECUTE CDCSOURCE doris_all WITH (
  'connector' = 'mysql-cdc',
  'hostname' = '',
  'port' = '3306',
  'username' = 'root',
  'password' = '',
  'checkpoint' = '10000',
  'scan.startup.mode' = 'initial',
  'parallelism' = '1',
  'table-name' = 'test\.table1,test\.table2',
  'sink.connector' = 'doris',
  'sink.fenodes' = '',
  'sink.username' = 'root',
  'sink.password' = '123456',
  'sink.doris.batch.size' = '1000',
  'sink.sink.max-retries' = '1',
  'sink.sink.batch.interval' = '60000',
  'sink.sink.db' = 'test',
  'sink.sink.properties.format' ='json',
  'sink.sink.properties.read_json_by_line' ='true',
  'sink.table.identifier' = '${schemaName}.${tableName}',
  'sink.sink.label-prefix' = '${schemaName}_${tableName}_1'
);
可以肯定读到了Mysql数据
![image](https://github.com/DataLinkDC/dinky/assets/30815101/0a231960-78b1-45ac-b8c7-e2d6250cf76b)

但是Doris里没有数据导入，同时查看日志，没有出现Doris Streamload的相关日志

Flink任务全程无报错

但是单独使用Flink SQL对单表进行同步是正常的，但是对整库同步是不行的

### What you expected to happen

期望可以正常同步

### How to reproduce

社区群也有反馈类似情况

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
试一下datastream-doris

**Comment by dyp12** [comment]
@panxianhaoo 可以发一下详细的日志嘛

**Comment by aiwenmo** [comment]
可能没有构建出正确的 modifyoperations，检查下日志。

**Comment by yuerspring** [comment]
同问

**Comment by X1304951263** [comment]
可以在配置中心-系统信息-logs  看下具体的日志，基本可以确定是任务构建中间有失败的步骤，但是任务还是能提交，我也遇见过这个问题

**Comment by yuerspring** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yuerspring** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
