### ISSUE TITLE
[Bug] [Web] 在数据开发中创建flink视图，字段顺序被强制按字母排序

### ISSUE THREAD

**Issue by e8tg001** [DataLinkDC/dinky#2078]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

在dinky下创建视图时，视图的字段被强制按字母顺序排序；

我不清楚这是因为dinky用flink1.17的jar包导致的，还是dinky做了上层封装导致的；

造成的问题：查询视图会导致，查询字段与视图排序后的字段类型不匹配，直接抛错，如:NumberFormatException: For input string: 'xxx'. Invalid character found.

### What you expected to happen

保持到flinkSQL原生模式一致

### How to reproduce

我在flink1.17的sql-client命令行窗口下创建视图，默认视图的字段，会根据创建时select的字段顺序默认创建；
如：
Flink SQL> CREATE VIEW count_min_order_view AS 
> SELECT
> DATE_FORMAT(TUMBLE_START(ts, INTERVAL '1' MINUTE), 'HH:mm') as window_start,
> DATE_FORMAT(TUMBLE_END(ts, INTERVAL '1' MINUTE), 'HH:mm') as window_end,
> COUNT(orderId) as order_num,
> COUNT(userName) as user_num,
> SUM(totalPrice) as sales_amount,
> SUM(num) as count_num 
> FROM order_source
> GROUP BY TUMBLE(ts, INTERVAL '1' MINUTE);

Flink SQL> show create view count_min_order_view;
| CREATE VIEW `default_catalog`.`default_database`.`count_min_order_view`(`window_start`, `window_end`, `order_num`, `user_num`, `sales_amount`, `count_num`) as
SELECT .... 略 |
其中视图字段(`window_start`, `window_end`, `order_num`, `user_num`, `sales_amount`, `count_num`) 是按select的字段排序的；

但在dinky下创建视图时，确被强制按字段的顺序排序，而不是不显示指定视图字段时，按select的字段排序，
如：
CREATE VIEW count_min_order_view AS 
SELECT
DATE_FORMAT(TUMBLE_START(ts, INTERVAL '1' MINUTE), 'HH:mm') as window_start,
DATE_FORMAT(TUMBLE_END(ts, INTERVAL '1' MINUTE), 'HH:mm') as window_end,
COUNT(orderId) as order_num,
COUNT(userName) as user_num,
SUM(totalPrice) as sales_amount,
SUM(num) as count_num 
FROM order_source
GROUP BY TUMBLE(ts, INTERVAL '1' MINUTE);

show create view count_min_order_view;
-- dinky下显示
CREATE VIEW `my_catalog`.`default_database`.`count_min_order_view`(`count_num`, `order_num`, `sales_amount`, `user_num`, `window_end`, `window_start`) as SELECT `DATE_FORMAT`(TUMBLE_START(`order_source`.`ts`, INTERVAL '1' MINUTE), 'HH:mm') AS `window_start`, `DATE_FORMAT`(TUMBLE_END(`order_source`.`ts`, INTERVAL '1' MINUTE), 'HH:mm') AS `window_end`, COUNT(`order_source`.`orderId`) AS `order_num`, COUNT(`order_source`.`userName`) AS `user_num`, SUM(`order_source`.`totalPrice`) AS `sales_amount`, SUM(`order_source`.`num`) AS `count_num` FROM `my_catalog`.`default_database`.`order_source` GROUP BY $TUMBLE(`order_source`.`ts`, INTERVAL '1' MINUTE)

其中的(`count_num`, `order_num`, `sales_amount`, `user_num`, `window_end`, `window_start`)并不是按SELECT 字段顺序创建；

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
dinky 没有相关的处理
