### ISSUE TITLE
[Bug] [CDCSOURCE] CDCSOURCE sqlServer 整库同步timestamp类型错误

### ISSUE THREAD

**Issue by David-steve** [DataLinkDC/dinky#2101]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

CDCSOURCE sqlServer整库同步在遇到timestamp类型时，会将timestamp转换为BYTES类型，而flink SQL不支持bytes类型；这会引发一个错误：Unsupported type: BYTES

### What you expected to happen

CDCSOURCE 无法对SQLserver中包含timestamp的的数据表进行同步

### How to reproduce

当SQLserver中的数据类型有timestamp出现时就会出现 Unsupported type: BYTES的错误

### Anything else

flink 版本 1.14
dinky 版本 0.7.3

### Version

0.7.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
在 SQLSink 里加下类型转换试试，有个值类型转换的方法

**Comment by David-steve** [comment]
在 SqlServerTypeConvert 模块中，原先是将 timestamp 转换成BYTES类型，我将其改为转换成STRING类型后，可以正常进行数据同步了
