### ISSUE TITLE
[Bug] [admin] 从运维中心通过作业快照重启作业时，如果从指定ck恢复，会导致作业的sp策略变成指定一次，并行指定的路径为重启时使用的cp路径

### ISSUE THREAD

**Issue by shadoubudong** [DataLinkDC/dinky#2108]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

当从运维中心通过作业快照重启作业时，如果从指定ck恢复，会导致作业的sp策略变成指定一次，并行指定的路径为重启时使用的cp路径

### What you expected to happen

当从运维中心通过作业快照重启作业时，如果从指定ck恢复，不应该修改作业的sp策略。

### How to reproduce

1、设置作业sp策略为最近一次
2、启动作业，运行后带sp停止
3、启动作业，待有checkpoint完成后，停止作业
4、进入运维中心->作业快照，选择从历史checkpoint恢复作业
5、待作业恢复成功，进入数据开发页面，刷新页面，查看此时作业的sp策略

### Version

0.7.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
这是正常的，因为从指定一次的cp恢复的作业

**Comment by shadoubudong** [comment]
> 
感觉和实际需求有点出入，假设一个场景，作业设置的sp策略是最近一次，但由于运行中异常导致作业失败，此时选择从最近的cp恢复。希望的结果是本次从cp恢复，但sp策略还是保持最近一次。现在的实现是一旦因为作业异常从cp恢复后，sp策略就变成了指定一次了，后续作业的正常启停，都会从这个cp恢复状态

**Comment by aiwenmo** [comment]
- [X] #2247
