### ISSUE TITLE
[Feature][admin,web] 全局变量新增加密选项

### ISSUE THREAD

**Issue by shadoubudong** [DataLinkDC/dinky#2109]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

使用全局变量时，如果涉及到类似数据库密码这样的变量，新增加密选项，在数据库中以密文存储，并且前端展示时以******代替。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanjf** [comment]
please assign me

**Comment by Zzm0809** [comment]
> please assign me

OK ,done

**Comment by ruanjf** [comment]
PR #2178
