### ISSUE TITLE
[Bug] [数据开发] FlinkJar作业提交失败

### ISSUE THREAD

**Issue by lifei1234** [DataLinkDC/dinky#2114]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

我开发了一个FlinkJar，点击“提交作业到集群”按钮后提示异步提交失败，查看异常信息如下：
Caused by: java.io.IOException: Cannot find any jar files for plugin in directory [plugins/flink1.17]. Please provide the jar files for the plugin or delete the directory.
	at org.apache.flink.core.plugin.DirectoryBasedPluginFinder.createJarURLsFromDirectory(DirectoryBasedPluginFinder.java:103)
	at org.apache.flink.core.plugin.DirectoryBasedPluginFinder.createPluginDescriptorForSubDirectory(DirectoryBasedPluginFinder.java:88)
	at org.apache.flink.util.function.FunctionUtils.lambda$uncheckedFunction$2(FunctionUtils.java:73)
	... 105 more

这里很奇怪，为什么会去plugins/flink1.17下去找flink的jar包

### What you expected to happen

我认为可能是个bug，同样的Flinkjar作业在0.6.7下就没有问题，以下是一些可参考信息：

- Dinky启动命令
sh auto.sh start 1.14

- 作业配置

![image](https://github.com/DataLinkDC/dinky/assets/15207092/db9a4942-0089-448a-9c6f-3dd10777cfb6)

- 集群配置
![image](https://github.com/DataLinkDC/dinky/assets/15207092/5d9e054b-3b8f-4b12-8fe2-c988799747b2)
![image](https://github.com/DataLinkDC/dinky/assets/15207092/6cd885ad-6e56-42d1-9283-9df3b35ee611)

-jar包放置情况
我用的flink1.14，所以其他本版的插件没有额外放置任何其他的jar包：

├── dlink-app-1.14-0.7.3-jar-with-dependencies.jar
├── flink1.11
│   └── dinky
│       ├── dlink-client-1.11-0.7.3.jar
│       └── dlink-connector-jdbc-1.11-0.7.3.jar
├── flink1.12
│   └── dinky
│       ├── dlink-client-1.12-0.7.3.jar
│       └── dlink-connector-jdbc-1.12-0.7.3.jar
├── flink1.13
│   └── dinky
│       ├── dlink-catalog-mysql-1.13-0.7.3.jar
│       ├── dlink-client-1.13-0.7.3.jar
│       └── dlink-connector-jdbc-1.13-0.7.3.jar
├── flink1.14（flink的依赖包我放在dinky目录下也试过）
│   ├── dinky
│   │   ├── dlink-catalog-mysql-1.14-0.7.3.jar
│   │   ├── dlink-client-1.14-0.7.3.jar
│   │   └── dlink-connector-jdbc-1.14-0.7.3.jar
│   ├── flink-connector-jdbc_2.11-1.14.4.jar
│   ├── flink-core-1.14.4.jar
│   ├── flink-csv-1.14.4.jar
│   ├── flink-dist_2.11-1.14.4.jar
│   ├── flink-doris-connector-1.14_2.11-1.1.0.jar
│   ├── flink-json-1.14.4.jar
│   ├── flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
│   ├── flink-shaded-zookeeper-3.4.14.jar
│   ├── flink-sql-connector-kafka_2.11-1.14.4.jar
│   ├── flink-sql-connector-mysql-cdc-2.2.0.jar
│   ├── flink-table_2.11-1.14.4.jar
│   ├── flink-tidb-connector-1.14-0.0.5-SNAPSHOT.jar
│   ├── hudi-flink1.14-bundle_2.11-0.11.0.jar
│   ├── javax.ws.rs-api-2.0.jar
│   ├── log4j-1.2-api-2.17.1.jar
│   ├── log4j-api-2.17.1.jar
│   ├── log4j-core-2.17.1.jar
│   ├── log4j-slf4j-impl-2.17.1.jar
│   ├── mysql-connector-java-8.0.18.jar
│   └── ojdbc6-12.1.0.1-atlassian-hosted.jar
├── flink1.15
│   └── dinky
│       ├── dlink-catalog-mysql-1.15-0.7.3.jar
│       └── dlink-client-1.15-0.7.3.jar
├── flink1.16
│   └── dinky
│       ├── dlink-catalog-mysql-1.16-0.7.3.jar
│       └── dlink-client-1.16-0.7.3.jar
└── flink1.17
    └── dinky
        ├── dlink-catalog-mysql-1.17-0.7.3.jar
        └── dlink-client-1.17-0.7.3.jar

### How to reproduce

任意一个Flinkjar直接提交到集群或者异步提交作业就可以复现

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yihao-tcf** [comment]
我也遇到同样的问题了

**Comment by CodeDevMasterPro** [comment]
与之相反，使用Dinky v0.7.3，Flink1.17，提交任务，提示：Cannot find any jar files for plugin in directory [plugins/flink1.11]. Please provide the jar files for the plugin or delete the directory.

**Comment by hanpi14** [comment]
我也是,0.7.3也出现了这个bug

**Comment by kissycn** [comment]
Flink1.17.1  Dinky 0.7.3  同样有这个问题

**Comment by yihao-tcf** [comment]
可以回退到0.7.2，0.7.2我使用正常

**Comment by InteliaK** [comment]
flink 1.14.2   dinky 0.7.3 同样遇到这个问题了

**Comment by ysq5202121** [comment]
一样

**Comment by ysq5202121** [comment]
我尝试了删除非启动版本的目录就可以了

**Comment by Flutemr** [comment]
> 我尝试了删除非启动版本的目录就可以了

比如我使用 ./auto start 1.16 ，我把plugins下除了flink1.16版本的其他目录都删掉吗？

**Comment by ysq5202121** [comment]
@Flutemr  留下一个即可，就可以正常使用

**Comment by Flutemr** [comment]
谢了。你用udf会有问题吗？我按照其他人提交的fix代码，修改了源码后，发现些数据到hive会报错。具体的在 #2203  。

**Comment by Flutemr** [comment]
> 谢了。你用udf会有问题吗？我按照其他人提交的fix代码，修改了源码后，发现些数据到hive会报错。具体的在 #2203 。



> @Flutemr 留下一个即可，就可以正常使用

谢了。你用udf会有问题吗？我按照其他人提交的fix代码，修改了源码后，发现些数据到hive会报错。具体的在 #2203 。

**Comment by ysq5202121** [comment]
@Flutemr  没用过

**Comment by Zzm0809** [comment]
原因是因为 flink 会去扫描一个名为 plugins 的文件夹且不允许为空 恰好 dinky 有这个文件夹 所以报错, 可以删除为空的
