### ISSUE TITLE
[Bug] [CDCSOURCE MYSQL] Mysql整库同步建表异常

### ISSUE THREAD

**Issue by 735140144** [DataLinkDC/dinky#2116]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

ERROR com.alibaba.druid.stat.DruidDataSourceStatManager 165 addDataSource - register mbean error javax.management.MalformedObjectNameException: Invalid character '=' in value part of property

[dlink] 2023-06-30 13:35:24 CST INFO  com.dlink.metadata.driver.MySqlDriver 82 generateCreateTableSql - Auto generateCreateTableSql CREATE TABLE IF NOT EXISTS `wechat_test`.`test_test` (
  `id`  (20) NOT  NULL  COMMENT '111',
  `shus`  (21) NULL ,
  PRIMARY KEY (`id`)
)
 ENGINE=InnoDB;
[dlink] 2023-06-30 13:35:24 CST ERROR com.dlink.trans.ddl.CreateCDCSourceOperation 195 build - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(20) NOT  NULL  COMMENT '111',
  `shus`  (21) NULL ,
  PRIMARY KEY (`id`)
)

缺少字段类型

对应代码部分：com.dlink.metadata.driver.MySqlDriver 105-108行后，110行前缺少字段类型

Column column = table.getColumns().get(i);
            sb.append("  `").append(column.getName()).append("`  ");
            if (Asserts.isNotNullString(column.getType())
                    && column.getType().toLowerCase().contains("unsigned")) {
                sb.append(column.getType().replaceAll("(?i)unsigned", "(" + column.getLength() + ") unsigned"));
            } else {
                // 处理浮点类型
                if (column.getPrecision() > 0 && column.getScale() > 0) {
                    sb.append("(")
                            .append(column.getLength())
                            .append(",").append(column.getScale())
                            .append(")");
                } else if (null != column.getLength()) { // 处理字符串类型和数值型
                    sb.append("(").append(column.getLength()).append(")");
                }
            }

### What you expected to happen

ERROR com.alibaba.druid.stat.DruidDataSourceStatManager 165 addDataSource - register mbean error javax.management.MalformedObjectNameException: Invalid character '=' in value part of property

[dlink] 2023-06-30 13:35:24 CST INFO  com.dlink.metadata.driver.MySqlDriver 82 generateCreateTableSql - Auto generateCreateTableSql CREATE TABLE IF NOT EXISTS `wechat_test`.`test_test` (
  `id`  (20) NOT  NULL  COMMENT '111',
  `shus`  (21) NULL ,
  PRIMARY KEY (`id`)
)

### How to reproduce

EXECUTE CDCSOURCE cdc_mysql WITH (
 'connector' = 'mysql-cdc',
 'hostname' = '127.0.0.1',
 'port' = '3306',
 'username' = 'root',
 'password' = '123456',
 'checkpoint' = '3000',
 'scan.startup.mode' = 'initial',
 'parallelism' = '1',
 'table-name' = 'dwd_offline\..*',
 'sink.connector' = 'jdbc',
 'sink.url' = 'jdbc:mysql://127.0.0.1:3306/test2?characterEncoding=utf-8&useSSL=false',
 'sink.username' = 'root',
 'sink.password' = '123456',
 'sink.sink.db' = 'test2',
 'sink.table.prefix' = 'test_',
 'sink.table.lower' = 'true',
 'sink.table-name' = '${tableName}',
 'sink.driver' = 'com.mysql.jdbc.Driver',
 'sink.sink.buffer-flush.interval' = '2s',
 'sink.sink.buffer-flush.max-rows' = '100',
 'sink.sink.max-retries' = '5',
 'sink.auto.create' = 'true'
)

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leechor** [comment]
refer to #2042 ,

**Comment by aiwenmo** [comment]
#1909
