### ISSUE TITLE
[Bug] [connectors] Compilation failure

### ISSUE THREAD

**Issue by xiaofan2022** [DataLinkDC/dinky#2134]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![coplie](https://github.com/DataLinkDC/dinky/assets/41982310/e495b600-effb-488b-9685-b7a71337a135)

### What you expected to happen

Successful compilation( version **_0.7_**)

### How to reproduce

mvn -B clean install          
-Dmaven.test.skip=true         
-Dcheckstyle.skip=true  
-Dspotless.check.skip=true     
-P prod,scala-2.12,flink-1.13,maven-central 

or
mvn -B clean install          
-Dmaven.test.skip=true         
-Dcheckstyle.skip=true  
-Dspotless.check.skip=true     
-P prod,scala-2.12,flink-1.14,maven-central

### Anything else

![connetor](https://github.com/DataLinkDC/dinky/assets/41982310/eb850256-8219-4128-9194-d7ec5b521245)
Why isn't model dlink-connector-jdbc-1.16 defined in the profile?
**_version_0.7_**

### Version

0.7.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leechor** [comment]
先运行maven的 install 命令.
