### ISSUE TITLE
openapi/submitTask接口任务启动报错

### ISSUE THREAD

**Issue by SPWanderer** [DataLinkDC/dinky#2140]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/DataLinkDC/dinky/assets/38491945/8a7377c1-6cce-41fb-af6a-e9148c748f08)
接口提示：未能读取到有效Token
检查代码发现在TaskServiceImpl中的submitTask方法，调用了buildJobConfig，而该方法中获取了用户权限，进而继续去获取了登录信息
![image](https://github.com/DataLinkDC/dinky/assets/38491945/a0e31a8c-78e4-499c-a12a-4701a476cb88)
![image](https://github.com/DataLinkDC/dinky/assets/38491945/7416cceb-9c83-43f2-b83d-d7fd2288ab98)

### What you expected to happen

/openapi下的接口，不应该继续从登录信息中获取userId，/openapi/submitTask能正常运行任务

### How to reproduce

直接调用/openapi/submitTask，不传入cookie会报错

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leechor** [comment]
刷新一下页面.重新登录

**Comment by SPWanderer** [comment]
> 这个接口是openapi下面的开放接口嘛，应该是不需要登录的，可以通过外部系统直接调用

**Comment by Zzm0809** [comment]
> 

最好的方式是实现 token 管理 , 通过 token 集成权限 等信息,  然后访问 openapi

**Comment by aiwenmo** [comment]
` @GetMapping("/submitTask")
    public Result submitTask(@RequestParam Integer id) {
        taskService.initTenantByTaskId(id);
        JobResult jobResult = taskService.submitTask(id);
        if (jobResult.isSuccess()) {
            return Result.succeed(jobResult, "执行成功");
        } else {
            return Result.failed(jobResult, jobResult.getError());
        }
    }`
