### ISSUE TITLE
批任务执行完成后，task状态和接收记录异常

### ISSUE THREAD

**Issue by ynzzxc** [DataLinkDC/dinky#2142]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

批任务执行完成后，任务详情页task状态和接收记录异常，如图
![火狐截图_2023-07-18T11-15-37 960Z](https://github.com/DataLinkDC/dinky/assets/128353785/cd80a683-dfbd-417a-98a2-245c66ef4c79)

dinky-0.7.3
flink-1.17.1
doris-2.0

### What you expected to happen

...

### How to reproduce

...

### Anything else

...

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ynzzxc** [comment]
有时候正常，有时候不正常（大部分），不知道为啥
![图片](https://github.com/DataLinkDC/dinky/assets/128353785/2e11176d-e778-4cea-a603-962fcd1e58d9)

**Comment by aiwenmo** [comment]
This is the latest obtained job status, not the final job status.

**Comment by aiwenmo** [comment]
After the per-job task is completed, dinky cannot access JobManager.

**Comment by ynzzxc** [comment]
> This is the latest obtained job status, not the final job status.

我可以理解为dinky按一定时间间隔获取状态，如果在时间间隔期间任务完成且job销毁，则dinky无法获取到最终状态吗
