### ISSUE TITLE
[FAQ][create flink cluster] 是否可以通过dinky来创建一个flink集群

### ISSUE THREAD

**Issue by VincentZhangy** [DataLinkDC/dinky#2143]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
This feature has been implemented
  The steps are:
1. Create a cluster configuration (guaranteed to be available)
2. Click `Start Cluster` in the `Operation` column (currently only yarn session can be started)
3. You can see it in the `flink instance management`
