### ISSUE TITLE
[Bug] [Flink mysql cdc] jdbc connector里配置的password含--字符串，解析错误， 导致数据库连接失败

### ISSUE THREAD

**Issue by laneypeng** [DataLinkDC/dinky#2144]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Dinky版本：0.7.3
Flink版本：1.14.6
Mysql版本：5.7

问题：通过dinky提交flink mysql cdc-> mysql  的sql job，提交到flink standalone报错，提示sink配置无法连接数据库，
但是我已经检查了相关权限，并且直接使用flink sql-client客户端提交相同的sql，提交的任务和dinky提交的任务并行度为1，并且也是在同一台机器上执行，但通过flink sql_client提交的任务没有任何报错，并且能写入数据。

### What you expected to happen

Dinky在解析sql job后在用户名密码处做了操作导致用户名密码不匹配，否则，在flink sql client执行相同代码肯定也会提示配置错误

### How to reproduce

1、使用flink mysql cdc进行数据整合后入库mysql，具体sql如下
drop table if exists trans_detail;
CREATE TABLE `trans_detail` (
  `FID`             VARCHAR(36) NOT NULL,
  `CASEID`          VARCHAR(36) COMMENT '案件ID',
  `BILLNUM`         VARCHAR(36) COMMENT '账单号',
  `ACCOUNTINGTYPE`  VARCHAR(10) COMMENT '记账类型',
  `TRANSWAY`        VARCHAR(20) COMMENT '交易方式',
  `MERCHANTNUM`     VARCHAR(50) COMMENT '银联商户号',
  `PUBACCOUNT`      VARCHAR(50) COMMENT '公存账户',
  `BUSTYPE`         VARCHAR(10) COMMENT '业务类型',
  `ASSID`           VARCHAR(36) COMMENT '关联业务ID',
  `ASSTABLENAME`    VARCHAR(50) COMMENT '关联表名称',
  `AUDITSTATUS`     VARCHAR(10) COMMENT '审核状态',
  `TRANSDATE`       TIMESTAMP COMMENT '交易时间',
  `VOUCHERDATE`     TIMESTAMP COMMENT '凭证时间',
  `OLDTRANSID`      VARCHAR(36) COMMENT '原交易ID',
  `POSITIVE`        VARCHAR(2) COMMENT '正/反',
  `BUSACCOUNTTYPE`  VARCHAR(10) COMMENT '交易分类',
  `TRANSAMOUNT`     DECIMAL(22, 2) COMMENT '交易金额',
  `ACCOUNTPERIOD`   DECIMAL(3, 0) COMMENT '账期',
  `PRODUCTNUM`      VARCHAR(255) COMMENT '产品编码',
  `PRODUCTCLASSNUM` VARCHAR(36) COMMENT '产品类别编码',
  `SOURCESFUNDSNUM` VARCHAR(36) COMMENT '资金来源编码',
  `ISCORRECT`       DECIMAL(1, 0) COMMENT '是否已冲正',
  `TRADINGCODE`     VARCHAR(25) COMMENT '交易码',
  `HASADJUSTING`    DECIMAL(1, 0) COMMENT '是否有调账',
  `PROSTATE`        VARCHAR(8) COMMENT '处理状态',
  `CUSTNAME`        VARCHAR(50) COMMENT '客户名称',
  `PRODUCTID`       VARCHAR(36) COMMENT '产品ID',
  `SOURCESFUNDSID`  VARCHAR(36) COMMENT '资金来源ID',
  `CONTRACTID`      VARCHAR(36),
  `CONTRACTNUM`     VARCHAR(36),
  `ACCOUNTNO`       VARCHAR(36) COMMENT '账户号',
  `AID`             VARCHAR(36) COMMENT '账户id',
  PRIMARY KEY (`FID`) NOT ENFORCED
) WITH (
 'connector' = 'jdbc',
  'url' = 'jdbc:mysql://slave-1:3306/test',
  'username' = 'dlink',
  'password' = 'dlink22',
  'table-name' = 'trans_detail',
  'sink.buffer-flush.max-rows' = '10000',
  'sink.buffer-flush.interval' = '2s'
  );

drop table if exists  t_account;
CREATE TABLE t_account (
  `ACCOUNTNO` varchar(36)  NOT NULL COMMENT '账户号',
  `FUNDINGSOURCES` varchar(36)   COMMENT '资金来源',
  `FCONTRACTCODE` varchar(80)  COMMENT '合同号',
  PRIMARY KEY (`ACCOUNTNO`) NOT ENFORCED
) WITH (
 'connector' = 'jdbc',
  'url' = 'jdbc:mysql://slave-1:3306/test',
  'username' = 'dlink',
  'password' = 'dlink22',
  'table-name' = 't_account',
  'sink.buffer-flush.max-rows' = '10000',
  'sink.buffer-flush.interval' = '2s'
);
CREATE TABLE `tr_flow_base_info_v2` (
  `id` varchar(40) NOT NULL COMMENT 'null',
  `com_no` varchar(40) COMMENT '公司编号',
  `transaction_no` varchar(40) COMMENT '交易编号',
  `contract_no` varchar(40) COMMENT '合同编号',
  `transaction_type_no` varchar(40) COMMENT '交易类型编号',
  `transaction_method_no` varchar(40) COMMENT '交易方式编号',
  `transaction_total_amount` decimal(20,8)  COMMENT '交易总金额',
  `is_account` varchar(8),
  `transaction_state` varchar(8),
  `belong_user_type` varchar(10),
  `inst_time` TIMESTAMP COMMENT '新增时间',
  `updt_time` TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`) NOT ENFORCED
) WITH (
  'connector' = 'jdbc',
  'url' = 'jdbc:mysql://localhost:3306/finance_pro',
  'username' = 'data_warehouse',
  'password' = 'Pl--com1',
  'table-name' = 'tr_flow_base_info_v2',
  'sink.buffer-flush.max-rows' = '10000',
  'sink.buffer-flush.interval' = '2s'
);

INSERT  INTO tr_flow_base_info_v2
  SELECT
    FID AS id,
    'COM-201708250091510104MA6DGK9F1W' AS com_no,
    FID AS transaction_no,
    a.FCONTRACTCODE as contract_no,
    BUSTYPE as transaction_type_no,
    TRANSWAY as transaction_method_no,
    TRANSAMOUNT as transaction_total_amount,
    if(BUSACCOUNTTYPE='BAY','20050002','20050001') AS is_account,
    if(BUSACCOUNTTYPE='BAY' and AUDITSTATUS='Y','20030002','20030001') AS transaction_state,
    '30070003' as belong_user_type,
    VOUCHERDATE AS inst_time,
    CURRENT_TIMESTAMP updt_time
  FROM trans_detail t
  LEFT JOIN t_account  a on t.ACCOUNTNO = a.ACCOUNTNO;

2、提交到flink standalone报错，提示sink配置无法连接数据库，但是我已经检查了相关权限，并且直接使用flink sql-client客户端提交相同的sql，提交的任务和dinky提交的任务也是在同一台机器上执行，但通过flink sql_client提交的任务没有任何报错，并且能写入数据。
java.io.IOException: unable to open JDBC writer
    at org.apache.flink.connector.jdbc.internal.JdbcOutputFormat.open(JdbcOutputFormat.java:145)
    at org.apache.flink.connector.jdbc.internal.GenericJdbcSinkFunction.open(GenericJdbcSinkFunction.java:52)
    at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:34)
    at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:100)
    at org.apache.flink.table.runtime.operators.sink.SinkOperator.open(SinkOperator.java:58)
    at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.initializeStateAndOpenOperators(RegularOperatorChain.java:110)
    at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreGates(StreamTask.java:708)
    at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.call(StreamTaskActionExecutor.java:55)
    at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:684)
    at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:651)
    at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958)
    at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:927)
    at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:766)
    at org.apache.flink.runtime.taskmanager.Task.run(Task.java:575)
    at java.lang.Thread.run(Thread.java:750)
Caused by: java.sql.SQLException: Access denied for user 'data_warehouse'@'47.111.92.7' (using password: YES)
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
    at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
    at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
    at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
    at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
    at org.apache.flink.connector.jdbc.internal.connection.SimpleJdbcConnectionProvider.getOrEstablishConnection(SimpleJdbcConnectionProvider.java:121)
    at org.apache.flink.connector.jdbc.internal.JdbcOutputFormat.open(JdbcOutputFormat.java:143)
    ... 14 more

3、用arthas监控执行日志
[arthas@15414]$ watch  com.mysql.cj.jdbc.ConnectionImpl getInstance -x 3 -n 1
Press Q or Ctrl+C to abort.
Affect(class count: 1 , method count: 1) cost in 163 ms, listenerId: 2
method=com.mysql.cj.jdbc.ConnectionImpl.getInstance location=AtExceptionExit
ts=2023-07-22 17:10:45; [cost=10.074549ms] result=@ArrayList[
    @Object[][
        @HostInfo[
            NO_PORT=@Integer[-1],
            HOST_PORT_SEPARATOR=@String[:],
            originalUrl=@SingleConnectionUrl[com.mysql.cj.conf.url.SingleConnectionUrl@136f55f5 :: {type: "SINGLE_CONNECTION", hosts: [com.mysql.cj.conf.HostInfo@44f9a1de :: {host: "localhost", port: 3306, hostProperties: {dbname=finance_pro}}], database: "finance_pro", properties: {password=Pl, user=data_warehouse}, propertiesTransformer: null}],
            host=@String[localhost],
            port=@Integer[3306],
            user=@String[data_warehouse],
            password=@String[Pl],
            hostProperties=@HashMap[isEmpty=false;size=1],
        ],
    ],
    null,
    null,
]

可以看到 password 处密码解析错误，只显示了--之前的字符串

4、将密码改为Pl-com1，任务监控日志变为：
[arthas@15414]$ watch  com.mysql.cj.jdbc.ConnectionImpl getInstance -x 3 -n 1
Press Q or Ctrl+C to abort.
Affect(class count: 1 , method count: 1) cost in 155 ms, listenerId: 3
method=com.mysql.cj.jdbc.ConnectionImpl.getInstance location=AtExceptionExit
ts=2023-07-22 17:15:43; [cost=12.113967ms] result=@ArrayList[
    @Object[][
        @HostInfo[
            NO_PORT=@Integer[-1],
            HOST_PORT_SEPARATOR=@String[:],
            originalUrl=@SingleConnectionUrl[com.mysql.cj.conf.url.SingleConnectionUrl@385e1c45 :: {type: "SINGLE_CONNECTION", hosts: [com.mysql.cj.conf.HostInfo@6c78ae4f :: {host: "localhost", port: 3306, hostProperties: {dbname=finance_pro}}], database: "finance_pro", properties: {password=Pl-com1, user=data_warehouse}, propertiesTransformer: null}],
            host=@String[localhost],
            port=@Integer[3306],
            user=@String[data_warehouse],
            password=@String[Pl-com1],
            hostProperties=@HashMap[isEmpty=false;size=1],
        ],
    ],
    null,
    null,
]
可以看到密码完整显示出来了

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tgluon** [comment]
I hope to solve this issue.

**Comment by tgluon** [comment]
dev 分支，已经修复，具体 如下：
![image](https://github.com/DataLinkDC/dinky/assets/26194129/07030508-b9fa-4bdb-a185-6c92af628962)
