### ISSUE TITLE
[Bug] [CDCSOURCE] java.lang.IllegalStateException: No operators defined in streaming topology. Cannot execute

### ISSUE THREAD

**Issue by bluewaterstar** [DataLinkDC/dinky#2167]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

mysql 到mysql整库同步，自动生成的表缺少字段类型

### What you expected to happen

![image](https://github.com/DataLinkDC/dinky/assets/39643648/d1e5ddf0-aa56-4e99-a854-8d4dd496357e)

### How to reproduce

flink 1.17.0
dinky 0.7.3
mysql cdc 2.4.0
mysql 8.0.30

EXECUTE CDCSOURCE cdc_mysql WITH (
 'connector' = 'mysql-cdc',
 'hostname' = '127.0.0.1',
 'port' = '3306',
 'username' = 'root',
 'password' = '123456',
 'checkpoint' = '3000',
 'scan.startup.mode' = 'initial',
 'parallelism' = '1',
 'table-name' = 'bigdata\.products,bigdata\.orders',
 'sink.connector' = 'jdbc',
 'sink.url' = 'jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&useSSL=false',
 'sink.username' = 'root',
 'sink.password' = '123456',
 'sink.sink.db' = 'test',
 'sink.table.prefix' = 'test_',
 'sink.table.lower' = 'true',
 'sink.table-name' = '${tableName}',
 'sink.driver' = 'com.mysql.jdbc.Driver',
 'sink.sink.buffer-flush.interval' = '2s',
 'sink.sink.buffer-flush.max-rows' = '100',
 'sink.sink.max-retries' = '5',
 'sink.auto.create' = 'true'
)

### Version

0.7.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bluewaterstar** [comment]
[dlink] 2023-08-02 19:35:06 CST INFO  com.dlink.metadata.driver.MySqlDriver 82 generateCreateTableSql - Auto generateCreateTableSql CREATE TABLE IF NOT EXISTS `test`.`test1_t_indicator_domain` (
  `ID`   NOT  NULL  AUTO_INCREMENT  COMMENT '主键',
  `NAME`  (20) NULL  COMMENT '指标域名称',
  `CODE`  (20) NULL  COMMENT '指标域标识',
  `PARENT_ID`   NULL  COMMENT '上级指标域ID',
  `CREATED_BY`   NULL  COMMENT '创建人',
  `CREATED_TIME`   DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATED_BY`   NULL  COMMENT '更新人',
  `UPDATED_TIME`   DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `DELETED`  (1) DEFAULT '0' COMMENT '是否删除',
  `STATUS`  (20) DEFAULT '2000' COMMENT '状态',
  PRIMARY KEY (`ID`)
)
 ENGINE=InnoDB COMMENT='指标域管理';
[dlink] 2023-08-02 19:35:06 CST ERROR com.dlink.trans.ddl.CreateCDCSourceOperation 195 build - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NOT  NULL  AUTO_INCREMENT  COMMENT '主键',
  `NAME`  (20) NULL  COMMENT '指�' at line 2 java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NOT  NULL  AUTO_INCREMENT  COMMENT '主键',
  `NAME`  (20) NULL  COMMENT '指�' at line 2
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[flink-sql-connector-mysql-cdc-2.4.0.jar:2.4.0]

**Comment by aiwenmo** [comment]
#1909

**Comment by SpringHuBiWei** [comment]
这个解决了吗，我看文档上写着要重启Dinky,似乎没啥用

**Comment by gaoyan1998** [comment]
> 这个解决了吗，我看文档上写着要重启Dinky,似乎没啥用

升级0.7.4解决
