### ISSUE TITLE
[Bug] [元数据中心] 在元数据中心页面，选择doris的数据源，再点击左边具体的某张表，点击“SQL 生成”功能，页面报错：Cannot read properties of null (reading 'flinkSqlCreate")

### ISSUE THREAD

**Issue by boddiguo** [DataLinkDC/dinky#2168]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

在元数据中心页面，选择doris的数据源，再点击左边具体的某张表，然后点击“SQL 生成”功能，页面报错，显示：Cannot read properties of null (reading 'flinkSqlCreate")
<img width="1719" alt="dinky-元数据中心报错1" src="https://github.com/DataLinkDC/dinky/assets/26771735/1a948658-0106-492a-93c6-082d1f97e1ec">
<img width="1301" alt="dinky-元数据中心报错2" src="https://github.com/DataLinkDC/dinky/assets/26771735/a004946d-db48-41f9-b198-fbb3bfb1a544">

### What you expected to happen

正常显示doris flink sql

### How to reproduce

在元数据中心页面，选择doris的数据源，再点击左边具体的某张表，然后点击“SQL 生成”功能

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
Please wait for the dev refactoring to complete the release

**Comment by aiwenmo** [comment]
Use dinky-web instead of dlink-web.

**Comment by boddiguo** [comment]
@aiwenmo from the exception stack:
<img width="805" alt="image" src="https://github.com/DataLinkDC/dinky/assets/26771735/852dab10-9441-4d13-a0cf-792767c97d3d">
I found the issue is due to  the backend code, the code has a bug in the method:getSqlSelect of claas org.dinky.metadata.driver.AbstractDriver: 
<img width="912" alt="image" src="https://github.com/DataLinkDC/dinky/assets/26771735/18704ff1-09c0-4b78-b569-bb14df9a8055">
it only need one % in this code, so the code fragment sb.append(String.format("`%s` %\n", columns.get(i).getName())); need change to sb.append(String.format("`%s` \n", columns.get(i).getName())).

please verify again, thank you!

**Comment by Zzm0809** [comment]
> @aiwenmo from the exception stack: <img alt="image" width="805" src="https://user-images.githubusercontent.com/26771735/260719451-852dab10-9441-4d13-a0cf-792767c97d3d.png"> I found the issue is due to the backend code, the code has a bug in the method:getSqlSelect of claas org.dinky.metadata.driver.AbstractDriver: <img alt="image" width="912" src="https://user-images.githubusercontent.com/26771735/260720652-18704ff1-09c0-4b78-b569-bb14df9a8055.png"> it only need one % in this code, so the code fragment sb.append(String.format("`%s` %\n", columns.get(i).getName())); need change to sb.append(String.format("`%s` \n", columns.get(i).getName())).
> 
> please verify again, thank you!

you are right , this is a bug , you can fix it to dev branch
