### ISSUE TITLE
[Bug] [admin] 当以on k8s application模式提交

### ISSUE THREAD

**Issue by seawenc** [DataLinkDC/dinky#2174]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

超过一分钟前端就自动超时了，当以application模式提交时，大于一分钟很正常

以下图片为超时后页面

![image](https://github.com/DataLinkDC/dinky/assets/40030020/79ddd601-02c4-46a4-bcf1-0600252aa51f)

### What you expected to happen

能正常关闭弹窗，更新此job状态

### How to reproduce

以on k8s application方式提交时大概率就会超时

### Anything else

此问题我改不动，请求大神来优化

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
One method is to modify configuration items to increase waiting time.

**Comment by Zzm0809** [comment]
#2173
