### ISSUE TITLE
[Bug] [admin] 如果on k8s application模式提交失败时控制台无任何信息

### ISSUE THREAD

**Issue by seawenc** [DataLinkDC/dinky#2175]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

on k8s application模式提交失败时控制台无任何信息，此bug已修，此issue只为提pr

解决后的效果：  
![image](https://github.com/DataLinkDC/dinky/assets/40030020/f420fc2a-0170-49e1-bc23-165f2261f496)

### What you expected to happen

能打印出错误信息

### How to reproduce

* 方式一： k8s on application模式下重复提交同一个任务  
* 方式二：任务名用中文  

### Version

0.7.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by seawenc** [comment]
关联pr： https://github.com/DataLinkDC/dinky/pull/2177

**Comment by Zzm0809** [comment]
#2173
