### ISSUE TITLE
[Bug] [admin] 提交任务后，未获得到jobid时未抛错，导致很多功能异常

### ISSUE THREAD

**Issue by seawenc** [DataLinkDC/dinky#2176]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

如题，大家看是否需要修改，我本地已经改了，大家看是否需修改，若需要修改，我提一下pr

类： KubernetesApplicationGateway

![image](https://github.com/DataLinkDC/dinky/assets/40030020/6925ced3-8da7-4de3-af66-60ccac3e9642)

### What you expected to happen

发生错误时，将错误信息打印到控制台

### How to reproduce

在配置中心，将获取job id的最大等待时间设置为1秒

### Version

0.7.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Flutemr** [comment]
你用0.7.3提交任务不会报错吗？提交任务，提示：Cannot find any jar files for plugin in directory [plugins/flink1.11]. Please provide the jar files for the plugin or delete the directory.
使用0.7.2就能正常。

**Comment by aiwenmo** [comment]
Welcome to pull request into 0.7 branch.
