### ISSUE TITLE
[Bug]手动执行后后台一直在继续执行任务

### ISSUE THREAD

**Issue by Flutemr** [DataLinkDC/dinky#2179]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

在local模式下，我手动执行了下flinksql任务，是kafka数据写入hive表，提示执行成功。我在运维里看不到这个任务，只是在控制台历史中有这个执行记录。我在hive表中看，发现会一直继续插入数据。删表重建后，数据又会继续写入。也查不到一直写数据的这个进程，不知道在哪里执行这个写入数据的任务。
![1691457668212](https://github.com/DataLinkDC/dinky/assets/30035663/1a7685d8-973e-4ef9-8b7f-e51a21306a75)

### What you expected to happen

同上

### How to reproduce

同上

### Version

0.7.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi. This depends on whether the port number is specified.
If a port number is specified, a new JobManager will be created.
If not, it will execute on the program itself.
For example, `set rest.post = '8086'`.

**Comment by aiwenmo** [comment]
In the local mode.

**Comment by Flutemr** [comment]
> In the local mode.

Ok, thanks. I'll try

**Comment by Flutemr** [comment]
> Hi. This depends on whether the port number is specified. If a port number is specified, a new JobManager will be created. If not, it will execute on the program itself. For example, `set rest.post = '8086'`.

May I ask whether it should be configured in the yml file of flink or in the yml file of dinky? Thank you
