### ISSUE TITLE
org.dinky.data.exception.MetaDataException: 缺少数据源类型【Oracle】的依赖，请在 lib 下添加对应的扩展依赖[Bug] [Module Name] Bug title 

### ISSUE THREAD

**Issue by kkkiii** [DataLinkDC/dinky#2196]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

submit oracle cdc source script,report error as title

org.dinky.data.exception.MetaDataException: 缺少数据源类型【Oracle】的依赖，请在 lib 下添加对应的扩展依赖[Bug] [Module Name] Bug title 

org.dinky.metadata.driver.Driver 这本程序
执行不进去 for 语句里 

结果返回driver 为空

    static Optional<Driver> get(DriverConfig config) {
        Asserts.checkNotNull(config, "数据源配置不能为空");
        ServiceLoader<Driver> drivers = ServiceLoader.load(Driver.class);
        for (Driver driver : drivers) {
            if (driver.canHandle(config.getType())) {
                return Optional.of(driver.setDriverConfig(config));
            }
        }
        return Optional.empty();
    }

附上cdcsource script
EXECUTE CDCSOURCE demo_print WITH (
 'connector' = 'oracle-cdc',
 'hostname' = '192.168.100.175',
 'port' = '1521',
 'username'='hisdb',
 'password'='hisdb',
 'database-name'='ORCL',
 'checkpoint' = '3000',
 'scan.startup.mode' = 'initial',
 'parallelism' = '1',
  'schema-name'='HISDB',
 'table-name' = 'HISDB\.CLINICACCDETAIL'
 'debezium.database.tablename.case.insensitive' = 'false',
 'debezium.log.mining.strategy' = 'online_catalog',
 'debezium.log.mining.continuous.mine' = 'true',
 'debezium.dababase.rac' = 'false',
  'sink.connector' = 'doris',
  'sink.fenodes' = '192.168.100.188:8030',
  'sink.username' = 'test',
  'sink.password' = 'test',
  'doris.sink.batch.size' = '1',
  'sink.sink.max-retries' = '1',
  -- 'sink.sink.batch.interval' = '60000',
  'sink.sink.db' = 'test_db',
  'sink.table.prefix' = 'ods_his_',
  'sink.table.lower' = 'true',
  'sink.table.identifier' = '${schemaName}.${tableName}',
  'sink.sink.label-prefix' = '${schemaName}_${tableName}_60',
  'sink.sink.enable-2pc'='false',
  'sink.sink.enable-delete' = 'true'
);

### What you expected to happen

dev expect to support oracle cdc

### How to reproduce

try source oracle sink to doris cdcsource mode

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kkkiii** [comment]
你希望我把依赖加到哪个module里面？加的内容是什么？

        <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc8</artifactId>
            <version>19.8.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.oracle.database.nls</groupId>
            <artifactId>orai18n</artifactId>
            <version>19.18.0.0</version>
        </dependency>


        <dependency>
            <groupId>com.ververica</groupId>
            <artifactId>flink-sql-connector-oracle-cdc</artifactId>
            <version>2.4.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.doris</groupId>
            <artifactId>flink-doris-connector-1.17</artifactId>
            <version>1.4.0</version>
        </dependency>

这几个行么？

**Comment by aiwenmo** [comment]
IDEA?

**Comment by kkkiii** [comment]
aiwenmo ,exactly!

**Comment by aiwenmo** [comment]
http://www.dlink.top/docs/next/developer_guide/local_debug

**Comment by Aitongong** [comment]
> 
这种方式没法解决  还是会报错这个

**Comment by Aitongong** [comment]
需要在dlink-admin下添加比如
        <dependency>
            <groupId>com.dlink</groupId>
            <artifactId>dlink-metadata-oracle</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.dlink</groupId>
            <artifactId>dlink-metadata-mysql</artifactId>
            <scope>provided</scope>
        </dependency>
        这种依赖才能行

**Comment by Aitongong** [comment]
需要在dlink-admin下添加比如

`        <dependency>
            <groupId>com.dlink</groupId>
            <artifactId>dlink-metadata-oracle</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.dlink</groupId>
            <artifactId>dlink-metadata-mysql</artifactId>
            <scope>provided</scope>
        </dependency>`
这种依赖才能行
