### ISSUE TITLE
[Feature][dlink-executor] UDF management center

### ISSUE THREAD

**Issue by leechor** [DataLinkDC/dinky#2201]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

1. UDF maybe contains other resources, dynamic library, etc. bundle all of them in one jar is convenient
2. UDF may be used in various tasks, load and upload is a redundancy work, 
3. the jar of the UDF version may be changed, there is a potent dangerous upload the wrong version.

according to the above reasons, managing all UDF jars is necessary

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leechor** [comment]
Design:
1. the jar of UDF could be as binary data in the MySQL database.
2. when uploading the jar to the database, we can analyze the customized UDF class name by the FLINK UDF interface.
3. after selecting a special jar in the task configuration, the user gets autocomplete power.

**Comment by leechor** [comment]
database table
`
create table dinky.dinky_udf_jar
(
    id               int auto_increment
        primary key,
    tenant_id        int           null,
    name             char(64)      not null,
    alias            char(64)      null,
    function_class json          null,
    description      varchar(4096) null,
    type             tinyint(1)    null,
    url              text          null,
    jar              longblob      null,
    create_name      datetime      null,
    update_time      datetime      null on update CURRENT_TIMESTAMP
);
`
`url` and `jar` items according to `url`, are mutual, `function_class` contains UDF class package that is acquired from the jar when storing the jar package in database. is an array represented by `json`.

**Comment by leechor** [comment]
the `UDF` online and git repository could produce a jar to the `dinky_udf_jar` table. `dinky_udf_jar` haven't version item because the version is defined in `jar` name. even if the `jar` file name doesn't contain version information, the uploader should add it.

**Comment by leechor** [comment]
**Design:**

1. The UDF jar could be stored as binary data in the MySQL database.
2. When uploading the jar to the database, we can analyze the customized UDF class name using the FLINK UDF interface.
3. After selecting a specific jar in the task configuration, the user gains autocomplete functionality.

**Database Table:**

```sql
sqlCopy codeCREATE TABLE dinky.dinky_udf_package
(
    id             INT AUTO_INCREMENT PRIMARY KEY,
    tenant_id      INT           NULL,
    name           CHAR(64)      NOT NULL,
    alias          CHAR(64)      NULL,
    function_class JSON          NULL,
    description    VARCHAR(4096) NULL,
    path_type      TINYINT(1)    NULL,
    package_type   TINYINT(1)    NULL,
    url            TEXT          NULL,
    package        LONGBLOB      NULL,
    version        CHAR(32)      NULL,
    create_time    DATETIME      NULL,
    update_time    DATETIME      NULL ON UPDATE CURRENT_TIMESTAMP
);
```

The `url` and `package` fields are interconnected based on the `url`. The `function_class` contains the `UDF` class package acquired from the `package` when storing it in the database, represented as `json`.

The `json` format is as follows:

```json
{
    "com.diny.udf.className": "identifier",
    "com.diny.udf.classNameOther": "identifierOther"
}
```

The `identifier` serves as the default `UDF` function name in `sql`. This identifier only needs to be unique within a single task (not globally unique). Therefore, validation of this constraint occurs during task validation. If necessary, users can customize the `identifier` in their `sql` statements.

The `UDF` online editor and git repository can generate a `package` that can be stored in the `dinky_udf_package` table.

**Interaction**

Add a page for managing the `package`, add a right property tab to insert `UDF` of a `package` to `sql`, after select a `package`, it will generate 

```sql
CREATE [TEMPORARY|TEMPORARY SYSTEM] FUNCTION 
  [IF NOT EXISTS] [catalog_name.][db_name.]function_name 
  AS identifier [LANGUAGE JAVA|SCALA|PYTHON]
```

by its information, the user could copy and paste. when the user submits this task, dinky will automatically download this `package` and upload it to `flink` runtime context.

**Comment by zackyoungh** [comment]
#2491
