### ISSUE TITLE
[Feature] support user reset password & recovery user

### ISSUE THREAD

**Issue by Doit-pudding** [DataLinkDC/dinky#2208]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. 普通人员密码遗失，管理员修改其密码，需要原始密码。  建议管理员重置密码，不需要原始密码。
2. 人员删除，再添加该用户名，提示用户已存在。 请修改交互逻辑（比如管理员可以看到、恢复用户），或者调整unique key。

### What you expected to happen

1. 普通人员密码遗失，管理员修改其密码，需要原始密码。  建议管理员重置密码，不需要原始密码。
2. 人员删除，再添加该用户名，提示用户已存在。 请修改交互逻辑（比如管理员可以看到、恢复用户），或者调整unique key。

### How to reproduce

以上

### Version

0.7.3

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
@Doit-pudding Thanks for your suggestion, can you come to implement this function in dev branch
