### ISSUE TITLE
[Bug] [Module Name] Bug title 

### ISSUE THREAD

**Issue by liaoxiaodongabc** [DataLinkDC/dinky#2241]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

In sql-clint, view fields are created in normal order, while in dinky, view fields are created in chaotic order (alphabetically sorted by field first).

### What you expected to happen

I expect，In sql-clint, view fields are created in normal order

### How to reproduce

啊啊啊啊啊啊啊啊啊啊

### Version

0.7.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi. Please provide an example.
