### ISSUE TITLE
[Bug] clickhouse数据源无法使用

### ISSUE THREAD

**Issue by ysq5202121** [DataLinkDC/dinky#2248]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

java.sql.SQLException: ru.yandex.clickhouse.ClickHouseDriver
![image](https://github.com/DataLinkDC/dinky/assets/8586973/6aca26c8-1f7d-4c88-af89-0aee2f656b54)

### What you expected to happen

希望能成功

### How to reproduce

添加一个clickhouse数据有即可

### Version

0.7.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Add dependencies in the plugins directory.

**Comment by ysq5202121** [comment]
@aiwenmo 什么依赖，不懂啊

**Comment by xuzhigong** [comment]
@ysq5202121 添加依赖clickhouse-jdbc-0.2.6.jar

**Comment by ysq5202121** [comment]
@xuzhigong 添加在那个目录

**Comment by xuzhigong** [comment]
@ysq5202121     dlink-release-0.7.X/lib

**Comment by ysq5202121** [comment]
@xuzhigong   你的回答很正确，原来我弄的版本一直不正确，我以为应该能支持最新版本JDBC.........,感谢！

**Comment by ysq5202121** [comment]
@xuzhigong 一定要clickhouse-jdbc-0.2.6.jar ？？？？？？

**Comment by ysq5202121** [comment]
我两个星期才解决这个问题，服了
