### ISSUE TITLE
[Bug] [Operation and Maintenance Center] There is a problem with step reading and it is not accurate

### ISSUE THREAD

**Issue by xiaohei88** [DataLinkDC/dinky#2266]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

运维中心获取的step不准确，我作业进入维护或者发布了或者上线了，在运维中心界面，生命周期的数据一直没变。因为他读取的dlink_job_instance里的step这个字段，但是这个字段在作业维护的时候没做维护。

### What you expected to happen

我希望我作业维护的时候，生命周期的状态需要跟着走。
我自己修改了代码
```java
task.setStep(JobLifeCycle.DEVELOP.getValue());
            this.updateTaskAndJobInstanceById(task);

private boolean updateTaskAndJobInstanceById(Task task) {
        boolean flg = updateById(task);
        if (flg) {
            JobInstance jobInstance = jobInstanceService.getJobInstanceByTaskId(task.getId());
            if (jobInstance != null) {
                jobInstance.setStep(task.getStep());
                jobInstanceService.updateById(jobInstance);
            }
        }
        return false;
    }
```
不知道是否正确

### How to reproduce

在数据开发模块，对作业发布、维护。再去运维中心看。

### Version

0.7.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
The task of the operation and maintenance center is to Flink job instances rather than data development jobs.
