### ISSUE TITLE
dlink-client-1.16 cdc source cannot recognize oracle-cdc type

### ISSUE THREAD

**Issue by tttzzzwww** [DataLinkDC/dinky#2267]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

dlink 0.7.4 经过查看源码，发现oracle 整库同步在1.16中被去掉了，1.15是存在的，1.16为什么将oracle整库同步去掉了，是需要自行编写吗，异常点：未匹配到对应 CDC Source 类型的【" + config.getType(...

### What you expected to happen

整库同步我看官方文档【http://www.dlink.top/docs/next/data_integration_guide/cdcsource_statements/】支持了很多种数据库，不仅是mysql，但源码没有支持，去掉的原因是否需要由用户自定义。

### How to reproduce

基于dlink 1.16  整库同步oracle即可复现

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
This is simple, users can add it themselves.

**Comment by tttzzzwww** [comment]
> 这个很简单，用户可以自己添加。
OK, I want to consult below, can the oracle whole library synchronization in dlink-client-1.14 be used directly? After I migrated it to dlink-client-1.16, the submitted task was not wrong, but the data could not be synchronized (the full volume and increment were not effective).
（ok，我想咨询下，dlink-client-1.14内的oracle整库同步可以直接使用吗？我这边将其迁移到dlink-client-1.16后，提交任务没有报错，但数据无法同步（全量、增量都不生效）
提交的整库同步SQL

public static String getOracleCdcSourceSql() {
    String cdcExecuteSql = "EXECUTE CDCSOURCE cdc_oracle WITH ("
            + "'connector' = 'oracle-cdc',"
            + "'hostname' = 'x.x.x.x',"
            + "'port' = '1521',"
            + "'username' = 'xxx,"
            + "'password' = xxx',"
            + "'database-name' = 'orcl',"
            + "'checkpoint' = '3000',"
            + "'scan.startup.mode' = 'initial',"
            + "'parallelism' = '1',"
            + "'table-name' = 'SUCCEZ_TEST\\.TEST_STUDENT',"
            + "'debezium.database.tablename.case.insensitive' = 'false',"
            + "'debezium.log.mining.strategy'='online_catalog',"
            + "'sink.connector' = 'jdbc',"
            + "'sink.url' = 'jdbc:mysql://192.x.x.122:3306/flinktest',"
            + "'sink.username' = 'xxx',"
            + "'sink.password' = 'xxx',"
//                + "'sink.sink.db' = 'xx',"
//                + "'sink.table.upper' = 'true',"
            + "'sink.table-name' = '${tableName}',"
//                + "'sink.driver' = 'com.mysql.cj.jdbc.Driver',"
//                + "'sink.sink.buffer-flush.interval' = '2s',"
//                + "'sink.sink.buffer-flush.max-rows' = '100',"
            + "'sink.sink.max-retries' = '5'"
            + ")";
    return cdcExecuteSql;
 }

**Comment by tttzzzwww** [comment]
问题已解决，具体可见：https://github.com/DataLinkDC/dinky/discussions/2270
