### ISSUE TITLE
savepoint

### ISSUE THREAD

**Issue by Aitongong** [DataLinkDC/dinky#2273]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Cannot map checkpoint/savepoint state for operator 141d3e51f76730254ed522f0ecc3aaed to the new program, because the operator is not available in the new program. If you want to allow to skip this, you can set the --allowNonRestoredState option on the CLI.   修改sql任务后无法基于savepoint重启

### What you expected to happen

正常提交代码方式 bin/flink run -s :savepointPath -n [:runArgs] 可以解决  在dlink中应该如何解决

### How to reproduce

执行任意sql语句，基于savepoint停止、恢复

### Version

0.7.1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
https://stackoverflow.com/questions/56977241/adding-uid-to-operator-causes-cannot-map-checkpoint-savepoint-state-for-operato

**Comment by Zzm0809** [comment]
https://nightlies.apache.org/flink/flink-docs-master/docs/ops/state/savepoints/#allowing-non-restored-state

**Comment by Aitongong** [comment]
> https://nightlies.apache.org/flink/flink-docs-master/docs/ops/state/savepoints/#allowing-non-restored-state

是的 这是我们提交flink程序  可以设置 bin/flink run -s :savepointPath -n [:runArgs] 解决  但是dlink中如何解决这个问题呢

**Comment by Aitongong** [comment]
![图片](https://github.com/DataLinkDC/dinky/assets/58808511/372b37e1-db0d-47a6-a714-d3a73447f0c7)
我在代码中看到只有这些模式才支持 修改代码恢复  请问yarn-session可以支持吗

**Comment by aiwenmo** [comment]
All modes support save point recovery.

**Comment by Aitongong** [comment]
> All modes support save point recovery.

我修改了执行sql之后  然后基于savepoint重启恢复  yarn-session模式下不能恢复  会报我描述的错误

**Comment by gaoyan1998** [comment]
use params `execution.savepoint.ignore-unclaimed-state:true` 
Allows skipping savepoint states that cannot be restored. This operation is allowed if the operator is removed from the pipeline after the savepoint is triggered.
This is not dinky's problem, see the official documentation for details
https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/config/

**Comment by Aitongong** [comment]
> use params `execution.savepoint.ignore-unclaimed-state:true` Allows skipping savepoint states that cannot be restored. This operation is allowed if the operator is removed from the pipeline after the savepoint is triggered. This is not dinky's problem, see the official documentation for details https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/config/
This parameter has no effect，  my flink version：1.15.3

**Comment by Aitongong** [comment]
> use params `execution.savepoint.ignore-unclaimed-state:true` Allows skipping savepoint states that cannot be restored. This operation is allowed if the operator is removed from the pipeline after the savepoint is triggered. This is not dinky's problem, see the official documentation for details https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/config/

This parameter has no effect， my flink version：1.15.3

**Comment by gaoyan1998** [comment]
> > use params `execution.savepoint.ignore-unclaimed-state:true` Allows skipping savepoint states that cannot be restored. This operation is allowed if the operator is removed from the pipeline after the savepoint is triggered. This is not dinky's problem, see the official documentation for details https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/config/
> 
> This parameter has no effect， my flink version：1.15.3

my flink version is 1.15.2, 
Where did you add this parameter?

**Comment by Aitongong** [comment]
> > > use params `execution.savepoint.ignore-unclaimed-state:true` Allows skipping savepoint states that cannot be restored. This operation is allowed if the operator is removed from the pipeline after the savepoint is triggered. This is not dinky's problem, see the official documentation for details https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/config/
> > 
> > 
> > This parameter has no effect， my flink version：1.15.3
> 
> my flink version is 1.15.2, Where did you add this parameter?

dinky script

**Comment by gaoyan1998** [comment]
> > use params `execution.savepoint.ignore-unclaimed-state:true` Allows skipping savepoint states that cannot be restored. This operation is allowed if the operator is removed from the pipeline after the savepoint is triggered. This is not dinky's problem, see the official documentation for details https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/config/
> 
> This parameter has no effect， my flink version：1.15.3

Add in `more configuration` via dinky's lower-right corner, do not add in sql script

**Comment by Aitongong** [comment]
> > > use params `execution.savepoint.ignore-unclaimed-state:true` Allows skipping savepoint states that cannot be restored. This operation is allowed if the operator is removed from the pipeline after the savepoint is triggered. This is not dinky's problem, see the official documentation for details https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/config/
> > 
> > 
> > This parameter has no effect， my flink version：1.15.3
> 
> Add in `more configuration` via dinky's lower-right corner, do not add in sql script

I'm using session mode

**Comment by gaoyan1998** [comment]
> 

The same goes for a session. You can try it

**Comment by gaoyan1998** [comment]
> > > > use params `execution.savepoint.ignore-unclaimed-state:true` Allows skipping savepoint states that cannot be restored. This operation is allowed if the operator is removed from the pipeline after the savepoint is triggered. This is not dinky's problem, see the official documentation for details https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/config/
> > > 
> > > 
> > > This parameter has no effect， my flink version：1.15.3
> > 
> > 
> > Add in `more configuration` via dinky's lower-right corner, do not add in sql script
> 
> I'm using session mode

The same goes for a session. You can try it

**Comment by zackyoungh** [comment]
set execution.savepoint.ignore-unclaimed-state=true
