### ISSUE TITLE
[Bug] [k8s native] stdout log cannot be viewed

### ISSUE THREAD

**Issue by kevinlin299** [DataLinkDC/dinky#2276]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/DataLinkDC/dinky/assets/40079776/5e8f7f05-afa5-4e6f-bf6b-d99699a71cbf)
![image](https://github.com/DataLinkDC/dinky/assets/40079776/d291c95e-d13c-4ff0-9a7f-9050983e9676)
![image](https://github.com/DataLinkDC/dinky/assets/40079776/5178a4c9-9b6f-4e7c-b652-06b179236777)

I launched the Flink cluster using k8s native. The configuration files for Flink are located in a specified location, and the logs can be viewed normally. However, the logs cannot be viewed normally in stdout. This is the same for both jobmanager and taskmanager.

### What you expected to happen

The stdout logs of both the jobmanager and taskmanager can be displayed normally.

### How to reproduce

Launch a Flink cluster using k8s native cluster configuration management, create a Flink SQL job, and select the newly launched cluster.

### Anything else
This is the error message in the log interface of the taskmanagers:
{"errors":["Internal server error.","<Exception on server side:\norg.apache.flink.util.FlinkException: The file STDOUT does not exist on the TaskExecutor.\n\tat org.apache.flink.runtime.taskexecutor.TaskExecutor.lambda$requestFileUploadByFilePath$24(TaskExecutor.java:2059)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n\nEnd of exception on server side>"]}
This is the error message in the log interface of the jobmanager:
{"errors":["This file does not exist in JobManager log dir."]}
This is a list of configuration files for Flink：
![image](https://github.com/DataLinkDC/dinky/assets/40079776/8782cc9a-130a-4c00-9b11-08a73c476621)

_No response_

### Version

0.7.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Check your k8s session cluster

**Comment by kevinlin299** [comment]
The default configuration files were placed under the dinky flink configuration file, but after starting in k8s native mode, only these three configuration files were left in the container.
pod：
![G 1H)TKEH3Q246M(58TSM3R](https://github.com/DataLinkDC/dinky/assets/40079776/6d668dfe-6c7e-4d39-8082-77ea99ffba5a)

dinky conf dir：
![K)}S{K ZR4 9MASDD%AQH7V](https://github.com/DataLinkDC/dinky/assets/40079776/be75e76c-085f-48b7-b247-e590cb4ff760)

**Comment by gaoyan1998** [comment]
Take a look at these two articles
https://blog.csdn.net/weixin_43956650/article/details/131673955

https://blog.csdn.net/Allocator/article/details/106858679

**Comment by RaymondFishWang** [comment]
I also find this problem in dinky 1.00 rc4. but I used the k8s operator, the conf directory is created by dinky with configmap , I can't add other files in this directory. 
![image](https://github.com/DataLinkDC/dinky/assets/152674254/0e8075ab-b791-405b-afb2-cf1d613177d1)

**Comment by randyho** [comment]
我现在用的 flink 1.20.0，发现flink-console.sh 里面增加了一个控制变量STD_REDIRECT_TO_FILE，把它的值设置成true，就会输出stdout和 stderr
