### ISSUE TITLE
0.7.0 startup error: Table 'dinky.dlink_tenant' doesn't exist

### ISSUE THREAD

**Issue by tilepotter** [DataLinkDC/dinky#2279]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

0.7.0版本启动报错：Table 'dinky.dlink_tenant' doesn't exist，建库初始化脚本和upgrade下的ddl都没有这张表

### What you expected to happen

能正常启动

### How to reproduce

启动服务

### Version

0.7.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
use 0.7.4
