### ISSUE TITLE
[Bug] [Data development flink cdc] cdc synchronizes mysql data to hivecatalog. It runs normally but the data cannot be synchronized.

### ISSUE THREAD

**Issue by ChaseXue** [DataLinkDC/dinky#2322]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

任务运行正常，但数据无法同步
![image](https://github.com/DataLinkDC/dinky/assets/26411759/a05f2c12-1419-4973-b79d-470361d2af49)

mysql数据：
![image](https://github.com/DataLinkDC/dinky/assets/26411759/92afc2e4-fa72-4514-8765-51ebd290d45c)

hive数据：
![image](https://github.com/DataLinkDC/dinky/assets/26411759/87b693d9-b1f8-4aa8-ab84-b9087ba00a0b)

### What you expected to happen

mysql 数据能正常同步到hive

### How to reproduce

任务sql：
![image](https://github.com/DataLinkDC/dinky/assets/26411759/785d648e-a9bf-4d2c-bc1c-b1bb4149b814)

### Anything else

dinky版本0.7.4
模式yarn-application

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Check if the jobgraph has successfully constructed the sink operator.
