### ISSUE TITLE
[Bug] [web] datastudio 's job tag bug 

### ISSUE THREAD

**Issue by XRXxrx** [DataLinkDC/dinky#2325]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

dlink-web项目中数据开发模块，任务目录选择两个任务在编辑器中打开，点击tab切换或者树状目录切换或者删除tab标签时，切换到另一个任务编辑器里面内容的宽高变成了5px,然后按F12调出控制台页面动一下它又恢复正常了；当你拖动改变编辑器的宽高再进行tab栏切换登相关操作时也会出现这个问题

### What you expected to happen

我希望dlink-web项目中数据开发模块任务目录无论是tab栏的切换删除还是编辑器的宽高改变编辑器里面的内容宽高都应该是正常的

### How to reproduce

https://github.com/DataLinkDC/dinky/assets/80390650/469fd7d4-3b32-4bea-a1ec-8d52eb28e22e

就跟视频中这样重现

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
请升级到0.7.x

**Comment by Zzm0809** [comment]
问题早就被修复了 找找对应的PR
