### ISSUE TITLE
[Bug] Request timeout causes job status to be UNKNOWN

### ISSUE THREAD

**Issue by andystenhe** [DataLinkDC/dinky#2326]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

When the network is unstable or the job manager is stuck, the flink job status is marked as unknown and the job status is normal in real-time. The exceptions are as follows:
[dlink] 2023-09-18 17:17:42 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:18:28 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:19:06 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:22:33 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:23:24 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:24:16 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:25:45 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:26:38 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:29:14 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:29:32 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:31:00 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:33:27 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:33:41 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:33:51 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:35:05 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:35:30 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:36:20 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:36:44 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:37:33 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:37:59 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:38:35 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:39:00 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:39:13 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107
[dlink] 2023-09-18 17:39:49 CST INFO  com.dlink.api.FlinkAPI 85 get - Unable to connect to Flink JobManager: http://127.0.0.2:40107

### What you expected to happen

The timeout time for requesting the job manager url is 1 second, which is too low. I hope to adjust it to 10 seconds so that it will not be marked as an exception too easily.

### How to reproduce

It can easily appear with less memory for job manager

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
This means that dinky cannot connect to the flink cluster. Please check your network.

**Comment by andystenhe** [comment]
In my Flink job, it is deployed on Kubernetes, and Dinky accesses the Job Manager through a shared load balancer. During peak hours, Dinky experiences timeouts when retrieving the job status via HTTP. Upon observation, the actual response time is only 2-3 seconds. Upon inspecting the timeout configuration of Dinky, it is set to 1 second, indicating potential room for optimization.

**Comment by gaoyan1998** [comment]
#2327
