### ISSUE TITLE
[Bug] [CDCSOURCE] mysql cannot synchronize the entire database to doris2.0 version

### ISSUE THREAD

**Issue by zhanghengdashuaibi** [DataLinkDC/dinky#2344]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

测试mysql整库同步到doris2.0版本中，sink时出现错误，源表已经读出来了，在sink的时候报错
doris fe response cannot map to schema.res:"errCode=7,detailMessage=unknowdatabases",
我在flink中执行doris的官网整库同步的命令是没有任何问题的

### What you expected to happen

在dlink执行整库同时出现了问题

### How to reproduce

flink1.17.1
doris2.0.0
flink-doris-connector-1.17-1.4.0
mysql整库同步到doris，执行就会出问题

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Please show your SQL.

**Comment by zhanghengdashuaibi** [comment]
> 请出示您的 SQL。

EXECUTE CDCSOURCE demo_doris_schema_evolution WITH (

  'connector' = 'mysql-cdc',

  'hostname' = '192.168.3.199',

  'port' = '32306',

  'username' = 'root',

  'password' = 'Hczy!@#2022',

  'checkpoint' = '10000',

  'scan.startup.mode' = 'initial',

  'parallelism' = '1',

  --'table-name' = 'dlink\..*',
  --'database-name' = 'dlink',
  'table-name' = 'test\.test_cdc',

  'sink.connector' = 'doris',

  'sink.fenodes' = '192.168.3.199:58446',

  'sink.username' = 'root',

  'sink.password' = '',

  'sink.doris.batch.size' = '1000',

  'sink.sink.max-retries' = '1',

  'sink.sink.db' = 'test',

  --'sink.table.prefix' = 'ODS_',

  'sink.table.upper' = 'true',

  'sink.table.identifier' = '${schemaName}.${tableName}',

  --'sink.table.identifier' = 'dlink.${tableName}',

  --'sink.sink.label-prefix' = '${schemaName}.${tableName}_1',

  'sink.sink.enable-delete' = 'true'

);

**Comment by aiwenmo** [comment]
Sink database is test, but table name is TEST.tablename1.
