### ISSUE TITLE
关于在启动任务时候不动savepoint 后续停止任务SavePoint失败，下线失败

### ISSUE THREAD

**Issue by ai-smalleryu** [DataLinkDC/dinky#237]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

SavePoint策略**什么都不选**，提示默认禁止，但是不选情况下yarnapplication任务跑完后任务点击停止会**SavePoint失败，下线失败**

### What you expected to happen

正在排查

### How to reproduce

我的 flink sql demo
CREATE TABLE datagen (
    f_sequence INT,
    f_random INT,
    f_random_str STRING,
    ts AS localtimestamp,
    WATERMARK FOR ts AS ts
  ) WITH (
    'connector' = 'datagen',
    -- optional options --
    'rows-per-second'='5',
    'fields.f_sequence.kind'='sequence',
    'fields.f_sequence.start'='1',
    'fields.f_sequence.end'='500',
    'fields.f_random.min'='1',
    'fields.f_random.max'='500',
    'fields.f_random_str.length'='10'
  );

  select * from datagen;

### Version

0.6.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
How is your progress? thx.
