### ISSUE TITLE
[Bug] [CDCSOURCE] Unable to synchronize data using CDCSOURCE

### ISSUE THREAD

**Issue by RoderickAdriance** [DataLinkDC/dinky#2373]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I use CDCSOURCE to synchronize this table fails and not get exeception.
I'm using CDCSOURCE to synchronize my tables, but this table doesn't work.

//The following are configured this table for testing using CDCSOURCE alone on dinky.
![image](https://github.com/DataLinkDC/dinky/assets/31174431/263669ea-b5ab-4fff-811f-c0e1a6f45389)

//Flink Web UI
![image](https://github.com/DataLinkDC/dinky/assets/31174431/e10ba5ef-00cf-4ec7-9326-438839f60645)

//But when I use single table sync it will be fine
![image](https://github.com/DataLinkDC/dinky/assets/31174431/03c1c621-cd1b-416a-a981-7cafe11d3468)

### What you expected to happen

![image](https://github.com/DataLinkDC/dinky/assets/31174431/401f71a7-b5d4-41bd-ab10-e1939b10f814)

### How to reproduce

Use CDCSOURCE to sink special table.

### Version

0.7.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Find the reason for not creating sinks from the log.
