### ISSUE TITLE
[Bug] [Doris] The "SQL generation" function cannot be used in version 0.7.4 "Metadata Center" connection to the Doris data warehouse

### ISSUE THREAD

**Issue by NCUZK** [DataLinkDC/dinky#2392]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="808" alt="image" src="https://github.com/DataLinkDC/dinky/assets/25876796/79b7d2a2-ef5d-46a5-956f-a391cdf6bd53">
Caused by: java.lang.StackOverflowError
 at com.dlink.metadata.driver.AbstractJdbcDriver.listColumnsSortByPK(AbstractJdbcDriver.java:390) ~[dlink-metadata-base-0.7.4.jar:?]
 at com.dlink.metadata.driver.DorisDriver.listColumns(DorisDriver.java:187) ~[dlink-metadata-doris-0.7.4.jar:?]

<img width="714" alt="image" src="https://github.com/DataLinkDC/dinky/assets/25876796/87133334-26f6-4340-aa6d-c13fd5e3d23a">

### What you expected to happen

可以正常自动生成SQL

### How to reproduce

问题版本0.7.4

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by NCUZK** [comment]
使用dlink-metadata-doris-0.7.3.jar替换后可以使用

**Comment by aiwenmo** [comment]
Fixed
