### ISSUE TITLE
Forced transfer of abnormal BUG

### ISSUE THREAD

**Issue by 15002035197** [DataLinkDC/dinky#2427]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

dinky版本是0.7.5
flink版本是1.17.1
在dinky中执行整库同步任务后，观察flink任务同步数据时，发现部分表数据同步正常，有部分表数据无法同步，dinky和flink可视化界面没有异常显示，然后去查看flink日志(flink-root-taskexecutor-4-test-server.log)时发现，在同步数据的过程中发生了异常。
[异常.txt](https://github.com/DataLinkDC/dinky/files/13110561/default.txt)

### What you expected to happen

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean

### How to reproduce

一、首先涉及的版本
1、dinky版本是0.7.5
2、flink版本是1.17.1
二、部署过程：正常部署dinky和flink
三、部署依赖：我是这样做
1、将dinky的lib中的dlink-catalog-mysql-1.17-0.7.5.jar、dlink-client-1.17-0.7.5.jar、dlink-client-base-0.7.5.jar、dlink-common-0.7.5.jar放置在flink的lib中
2、将flink的lib文件中相关finlk的jar包放置在dlink的plugins中
四、在Dinky创建整库同步任务

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leechor** [comment]
https://github.com/DataLinkDC/dinky/issues/1695

**Comment by aiwenmo** [comment]
'jdbc.properties.tinyInt1isBit' = 'true',
'jdbc.properties.transformedBitIsBoolean' = 'true',
