### ISSUE TITLE
[Bug] [Data Development]Unhandled Rejection (TypeError): Cannot read properties of null (reading 'status')

### ISSUE THREAD

**Issue by lj-michale** [DataLinkDC/dinky#2456]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Data Studio|Unhandled Rejection (TypeError): Cannot read properties of null (reading 'status')
![微信截图_20231030151245](https://github.com/DataLinkDC/dinky/assets/22366151/dbf88ab1-ef63-4031-852b-bcd1497129c1)

### What you expected to happen

正常创建开发作业

### How to reproduce

新建一个flinksql开发作业

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Try latest code.
