### ISSUE TITLE
Sqlserver entire database synchronization task failed

### ISSUE THREAD

**Issue by wsczm** [DataLinkDC/dinky#2475]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Sqlserver整库同步任务失败

### What you expected to happen

![Uploading image.png…]()

### How to reproduce

新建作业 运行 提示No operators defined in streaming topology. Cannot execute.

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Check the error message in the log, the reason is that Sink was not successfully built.
