### ISSUE TITLE
[Bug] [dinky-web] dinky web startup error

### ISSUE THREAD

**Issue by lj-michale** [DataLinkDC/dinky#2508]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

 dinky web startup error
![微信截图_20231108102951](https://github.com/DataLinkDC/dinky/assets/22366151/119a9231-de25-4bec-b570-62140fd4de15)

### What you expected to happen

 dinky web start normally

### How to reproduce

startup  dinky-web server by npm run dev

### Anything else

no

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leechor** [comment]
it seems absent some library, you should rerun `npm install --force`

**Comment by Zzm0809** [comment]
找到变更历史 回滚该文件
