### ISSUE TITLE
[Feature][dlink-metadata-postgresql]  An error is caused when the precision of the numeric or decimal type in postgres exceeds 38

### ISSUE THREAD

**Issue by javaht** [DataLinkDC/dinky#2538]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![d443c727c86dd10c0b044911979ed9e](https://github.com/DataLinkDC/dinky/assets/54611681/9435aa25-724e-47e7-8c4c-1969d3467dfd)

My idea is to change the code to string when the precision of numeric or decimal exceeds 38. For this reason, I have modified the following two places.

1.Add a new judgment to the PostgreSqlTypeConvert class，
![image](https://github.com/DataLinkDC/dinky/assets/54611681/ec419d5e-b13c-4d11-8d91-8b6841c2ec47)
2.Modify the getColumnProcessing method in FlinkBaseUtil
![image](https://github.com/DataLinkDC/dinky/assets/54611681/da9cdc0b-1491-400c-b874-12273b89e076)

I tested postgresql to work. Of course other databases should exist but I only modified postgresql

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Welcome to submit this fix.
