### ISSUE TITLE
[Bug] [CDCSOURCE] MySQL to Starrocks date type field value is solidified as: 1970-01-19

### ISSUE THREAD

**Issue by byd-android-2017** [DataLinkDC/dinky#2545]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

升级前： Flink1.14.6, Dinky 0.7.2  CDCSOURC同步作业工作正常；
升级后：Flink1.14.6, Dinky 0.7.5  CDCSOURC同步作业日期、日期时间字段值，在目标数据上出现问题，字段值被固化为：1970-01-19

### What you expected to happen

日期、日期时间字段值与原表一致（MySQL to Starrocks）

### How to reproduce

同步包含日期、日期时间字段的表（MySQL to Starrocks）

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
I have found the reason, and I will fix it.

**Comment by aiwenmo** [comment]
#2557

**Comment by aiwenmo** [comment]
- [X] #2557

**Comment by aiwenmo** [comment]
com.dlink.cdc.AbstractSinkBuilder.getLogicalType

case TIMESTAMP:
                return new TimestampType(column.getLength());
