### ISSUE TITLE
[Feature] Please support Flink 1.18 in dinky 0.7 series

### ISSUE THREAD

**Issue by leeoo** [DataLinkDC/dinky#2553]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Please support Flink 1.18 in dinky 0.7 series.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
0.7 不维护了 自行支持
