### ISSUE TITLE
[Bug] [sql] dinky-pg.sql file has some sql error

### ISSUE THREAD

**Issue by mengyueyue** [DataLinkDC/dinky#2562]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

i'm using pg db, then use dinky-pg.sql to create tables met sql error when execute sql

1. problem 1 (use not exist table)
![image](https://github.com/DataLinkDC/dinky/assets/11819880/f6f8b032-4cfa-427b-ba36-f23dcd0f83b3)

dinky_schema_history、dinky_task_statement、dinky_upload_file_record all has this problem

2. problem 2 (wrong single quote escaping)
![image](https://github.com/DataLinkDC/dinky/assets/11819880/45c500db-39da-4ed6-8361-376d25d76150)

The following three sql have the same problem

`INSERT INTO public.dinky_alert_rules (id, name, rule, template_id, rule_type, trigger_conditions, description, enabled, create_time, update_time) VALUES (3, 'alert.rule.jobFail', '[{"ruleKey":"jobInstance.status","ruleOperator":"EQ","ruleValue":"\'FAILED\'","rulePriority":"1"}]', 1, 'SYSTEM', ' or ', '', 1, '1970-01-01 00:00:00', '2023-09-04 23:03:02');
`

`
INSERT INTO public.dinky_alert_rules (id, name, rule, template_id, rule_type, trigger_conditions, description, enabled, create_time, update_time) VALUES (4, 'alert.rule.getJobInfoFail', '[{"ruleKey":"jobInstance.status","ruleOperator":"EQ","ruleValue":"\'UNKNOWN\'","rulePriority":"1"}]', 1, 'SYSTEM', ' or ', '', 1, '1970-01-01 00:00:00', '2023-09-05 18:03:43');
`

`
INSERT INTO public.dinky_alert_rules (id, name, rule, template_id, rule_type, trigger_conditions, description, enabled, create_time, update_time) VALUES (5, 'alert.rule.jobRestart', '[{"ruleKey":"jobInstance.status","ruleOperator":"EQ","ruleValue":"\'RESTARTING\'","rulePriority":"1"}]', 1, 'SYSTEM', ' or ', '', 1, '1970-01-01 00:00:00', '2023-09-06 21:35:12');
`

correct is : "''FAILED''"

3. problem 3 (error data type)

![image](https://github.com/DataLinkDC/dinky/assets/11819880/8e826fb5-5f92-4fa7-a2ec-1076a3b61f8f)

there would be int4_ops not int2_ops , because resources_id data type is int4 in dinky_udf_manage table

### What you expected to happen

all sql  result is ok

### How to reproduce

just execute dinky-pg.sql in pg db

### Anything else

every time

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
同步最新代码

**Comment by mengyueyue** [comment]
@Zzm0809 你好，通过同步最新代码，发现社区已经解决了problem1，但是2和3还是存在的

**Comment by Zzm0809** [comment]
> @Zzm0809 你好，通过同步最新代码，发现社区已经解决了problem1，但是2和3还是存在的

@mengyueyue 如还存在, 欢迎来修复
