### ISSUE TITLE
Failed to submit hudi task

### ISSUE THREAD

**Issue by goldzzz1** [DataLinkDC/dinky#2564]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

insert into  t1 select * from kafka_ods_orders 
我执行了这一条语句，将kafka的数据插入到一个hudi表中 
但是hudi表并没有数据 
然后我去flinkweb中看了相关记录 也没有出现什么报错 不知道什么原因 

### What you expected to happen

我想知道如何解决 
我之前在本地的flink-sql-client写了同样的建表语句，是可以成功的

### How to reproduce

就是创建一个kafka表，然后执行我上面所述的sql，flink是stanalone模式的

### Version

0.7.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Add checkpoint to your task.
