### ISSUE TITLE
[Feature][k8s native] supports Flink WebUI proxy

### ISSUE THREAD

**Issue by Baibaiwuguo** [DataLinkDC/dinky#2600]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

If I want to access flinkUI, I need to use clusterIp:port.But i do not want  to use too many Ip segments, so  I have to configure the entry to access the flink ui by `Ingress`. For example, domain:80/taskId. Then, I can use less ip,  and this way is more beautiful.
Of course,  we can discuss how to  proxy flinkUI.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
Hello, thank you for your suggestion, this feature has been implemented in 1.0, dinky can help you to proxy flink ui pages without requiring you to configure ingress yourself
