### ISSUE TITLE
Dlinky adds the atals plugin

### ISSUE THREAD

**Issue by smileyboy2019** [DataLinkDC/dinky#2635]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Can we submit an Apache atals for storage and unified metadata management of the blood relationship analysis provided by dlinky?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
This is a good suggestion. Currently, there is no storage available. Do you have any good ideas?
