### ISSUE TITLE
[Feature][cdc] Support Flink CDC pipeline task in FlinkSQL dialect

### ISSUE THREAD

**Issue by aiwenmo** [DataLinkDC/dinky#2712]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

source:
  type: mysql
  hostname: localhost
  port: 3306
  username: root
  password: 123456
  tables: app_db.\.*
  server-id: 5400-5404
  server-time-zone: UTC

sink:
  type: doris
  fenodes: 127.0.0.1:8030
  username: root
  password: ""
  table.create.properties.light_schema_change: true
  table.create.properties.replication_num: 1

pipeline:
  name: Sync MySQL Database to Doris
  parallelism: 2

### Use case

source:
  type: mysql
  hostname: localhost
  port: 3306
  username: root
  password: 123456
  tables: app_db.\.*
  server-id: 5400-5404
  server-time-zone: UTC

sink:
  type: doris
  fenodes: 127.0.0.1:8030
  username: root
  password: ""
  table.create.properties.light_schema_change: true
  table.create.properties.replication_num: 1

pipeline:
  name: Sync MySQL Database to Doris
  parallelism: 2

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
![image](https://github.com/DataLinkDC/dinky/assets/32723967/cc1bb43d-7cc7-4f13-8353-8d6cedcc7e06)

**Comment by aiwenmo** [comment]
![6c19756eb1f3c4933d1726b9ec6c440](https://github.com/DataLinkDC/dinky/assets/32723967/307da527-1342-482e-9d10-d74cba4c79c1)

**Comment by aiwenmo** [comment]
![a8195b2a553d7719ae84995f65492fc](https://github.com/DataLinkDC/dinky/assets/32723967/c436aab0-220f-423b-887e-d79d56f40605)

**Comment by leonardBang** [comment]
Thanks @aiwenmo for driving this work, Niubility !

**Comment by aiwenmo** [comment]
![image](https://github.com/DataLinkDC/dinky/assets/32723967/2b226991-da59-4cab-80ed-31316bed1f1b)

**Comment by aiwenmo** [comment]
```sql
EXECUTE PIPELINE WITHYAML (
source:
  type: mysql
  hostname: localhost
  port: 3306
  username: root
  password: 123456
  tables: app_db.\.*
  server-id: 5400-5404
  server-time-zone: UTC

sink:
  type: doris
  fenodes: 127.0.0.1:8030
  username: root
  password: ""
  table.create.properties.light_schema_change: true
  table.create.properties.replication_num: 1

pipeline:
  name: Sync MySQL Database to Doris
  parallelism: 2
)
```

**Comment by aiwenmo** [comment]
> Thanks @aiwenmo for driving this work, Niubility !

Thank you to the FlinkCDC community for designing and implementing a pipeline that is easy to integrate.
