### ISSUE TITLE
[Bug] [CDCSOURCE] Oracle12C synchronization doris does not report an error or synchronize

### ISSUE THREAD

**Issue by donsmile** [DataLinkDC/dinky#2718]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/DataLinkDC/dinky/assets/27986841/5c6b6e36-0e98-4447-9b40-ec6fc97ac953)
![image](https://github.com/DataLinkDC/dinky/assets/27986841/78e5fbb7-06a0-4ca7-972c-75dc13958c56)
不报错也不同步数据，起初怀疑是oracle12c的pdb设置参数不对，截图中我把所有的设置方法的可能性都加上了也不行

### What you expected to happen

成功同步

### How to reproduce

dinky 0.75版本  flink1.17  手动扩展doris和oracle的sink和source，扩展方法是把flink1.15的包拿过来

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
自行扩展的 需要考虑api兼容性 参数是否与版本一致，需要自行在本地debug排查问题

**Comment by donsmile** [comment]
> 自行扩展的 需要考虑api兼容性 参数是否与版本一致，需要自行在本地debug排查问题
