### ISSUE TITLE
[Bug] [dinky-admin] Create two empty jobs and switch to each other with an error message

### ISSUE THREAD

**Issue by black1-mao** [DataLinkDC/dinky#2743]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![error](https://github.com/DataLinkDC/dinky/assets/58390922/f34f7f2b-f72d-4738-a694-dd36477c59a4)

### What you expected to happen

no error

### How to reproduce

Create two empty jobs to switch between, backend service reports an error

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
log???

please read https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way

**Comment by Zzm0809** [comment]
Unable to reproduce, functions normally
