### ISSUE TITLE
The heartbeat monitoring of the data source is not effective, and the data source is abnormal but returns success

### ISSUE THREAD

**Issue by yangzehan** [DataLinkDC/dinky#2744]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

The heartbeat monitoring of the data source is not effective, and the data source is abnormal but returns success
![aa49d368ac0f0487cbc7849d4005c5c](https://github.com/DataLinkDC/dinky/assets/76773988/1ee2cd2c-b67a-45d4-ac80-bf8b2814f746)

### What you expected to happen

The heartbeat monitoring of the data source is not effective, and the data source returns an exception

### How to reproduce

Click on heartbeat monitoring

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yangzehan** [comment]
Additional: Bugs that occur without the hive JDBC connector

**Comment by Zzm0809** [comment]
> Additional: Bugs that occur without the hive JDBC connector

Check whether the backend service has error logs？？
