### ISSUE TITLE
[Optimization][admin] Paimon version conflict

### ISSUE THREAD

**Issue by gaoyan1998** [DataLinkDC/dinky#2749]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

build shaded paimn bundle

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
has Optimizationed
