### ISSUE TITLE
[Bug] [Web] Display "-1" in DataStudio Job Config's SavePointStrategy after creating a flinksql job

### ISSUE THREAD

**Issue by leeoo** [DataLinkDC/dinky#2760]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Env:  Dinky 1.0-rc1 20231215，Firefox 121
![图片](https://github.com/DataLinkDC/dinky/assets/2136182/ab2c368f-37fe-4672-8c63-50be685a2217)

### What you expected to happen

Display "Disabled".

### How to reproduce

DataStudio > Project > Create a flinksql job > Open the new created job > Seeing right pannel's SavePointStrategy.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
Problems caused by historical data, please execute
```sql
update dinky_task set save_point_strategy = 0 where save_point_strategy is not null and save_point_strategy = -1;
```

i will be fix it
