### ISSUE TITLE
[Bug] [Devops] No savepoint generated after clicking 'Smart Stop' on a flinksql job's Devops page

### ISSUE THREAD

**Issue by leeoo** [DataLinkDC/dinky#2761]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Env:  Dinky 1.0-rc1 20231215

As title.

### What you expected to happen

A savepoint shoud be generated after clicking 'Smart Stop' to a flinksql job.

### How to reproduce

Data Studio > Open a normal flinksql job > Click 'Execute' button > Devops > View the job detail > Click 'Smart Stop' button > See Savepoint tab in 'Checkpoints Info' tab.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
log???
