### ISSUE TITLE
[Bug] [Admin] Set parameter does not take effect

### ISSUE THREAD

**Issue by 18216499322** [DataLinkDC/dinky#2762]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

The set parameter configured in the Flink SQL job does not take effect

### What you expected to happen

Configure the set parameter in the Flink SQL job to take effect

### How to reproduce

![企业微信截图_17034868067485](https://github.com/DataLinkDC/dinky/assets/75019445/23edf858-f577-4535-9424-5c087069e5d3)
![企业微信截图_17034868179123](https://github.com/DataLinkDC/dinky/assets/75019445/87e54f23-b567-4042-9212-accd9e3f6eda)

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
is flink 1.17, 1.18?

**Comment by 18216499322** [comment]
> is flink 1.17, 1.18?

The version tested is 1.17
