### ISSUE TITLE
The webpage will display this error.

### ISSUE THREAD

**Issue by JasonFang1993** [DataLinkDC/dinky#2774]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/DataLinkDC/dinky/assets/55202939/77866dc6-3cfc-42c7-ac53-db690a10399f)

### What you expected to happen

The webpage will display this error.

### How to reproduce

The webpage will display this error.

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
Please post the complete error message

**Comment by Zzm0809** [comment]
log???
