### ISSUE TITLE
[Feature][Docker] update dinky docker image for v1.0.0-rc1

### ISSUE THREAD

**Issue by wxtt522** [DataLinkDC/dinky#2779]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://github.com/DataLinkDC/dinky/assets/28422636/24b0a360-23c4-4e32-92fa-43ca8ba428f9)
the docker version installation image of dinky has been updated a year ago，I think it is very necessary for docker users to experience the features of the new version

### Related issues

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
http://www.dinky.org.cn/docs/next/deploy_guide/docker_deploy

**Comment by aiwenmo** [comment]
dinkydocker, not ylyue/dinky.

**Comment by wxtt522** [comment]
I made a mistake，It has indeed updated the v1.0 image，very thankful
