### ISSUE TITLE
[Improvement][Admin] The latest saved point can only be restarted from the saved point, not from the checkpoint

### ISSUE THREAD

**Issue by 18216499322** [DataLinkDC/dinky#2784]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

Restart from the save point or checkpoint whichever is closer

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
Use the `Restart here` button to the right of the checkpoint list in the Operations Center

**Comment by aiwenmo** [comment]
Can implement a new feature that supports savepoint recovery strategy from the latest checkpoint recovery.

**Comment by gaoyan1998** [comment]
Try rc3 later
