### ISSUE TITLE
[Bug] [web]  delete property not work

### ISSUE THREAD

**Issue by lijunkai** [DataLinkDC/dinky#2790]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="960" alt="dinky-bug" src="https://github.com/DataLinkDC/dinky/assets/26005541/d5ea47b8-fd1c-4423-b2eb-9361b8808226">

### What you expected to happen

delete property  when you don't need

### How to reproduce

see the picture

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
无法复现

**Comment by lijunkai** [comment]
![image](https://github.com/DataLinkDC/dinky/assets/26005541/d638b73a-d8f4-4849-9c7e-d13565f07065)
try add one first and then update it

**Comment by lijunkai** [comment]
![image](https://github.com/DataLinkDC/dinky/assets/26005541/09962ee3-8d89-45e0-b938-d810ada38487)

**Comment by gaoyan1998** [comment]
Is your computer's zoom setting too high?

**Comment by lijunkai** [comment]
no, it's normal 100% 
![image](https://github.com/DataLinkDC/dinky/assets/26005541/96f5b421-90d0-4b2a-9884-8044a05e893d)


my windows computer resolution ratio ： 
![image](https://github.com/DataLinkDC/dinky/assets/26005541/eb0b472b-c461-4f29-be22-0c7c8877e514)
