### ISSUE TITLE
[Improvement] [FlinkJar] support submit jar to yarn-session and specify custom program args

### ISSUE THREAD

**Issue by lijunkai** [DataLinkDC/dinky#2794]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

flinkjar  seems don't  support to  submit to flink yarn-session cluster

![image](https://github.com/DataLinkDC/dinky/assets/26005541/3e4fbd07-a0c4-4031-83c5-2697c4ec26c7)

### What you expected to happen

support submit jar to yarn-session and specify custom program args

### How to reproduce

see  pictures

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leechor** [comment]
in dinky 1.0, submit jar could by SQL command, try 'EXECUTE JAR` to get the SQL syntax feature and example suggestion.
