### ISSUE TITLE
/hookJobDone api app mode refreshJob method job status is not updated correctly

### ISSUE THREAD

**Issue by yangzehan** [DataLinkDC/dinky#2836]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![aac26d32da0588260cdab39699ed893](https://github.com/DataLinkDC/dinky/assets/76773988/69c5687c-e9a1-4d65-aef2-e28da89c7a00)
The status is not refreshed correctly

### What you expected to happen

Refresh the end state correctly

### How to reproduce

Run FlinkSQL in app mode

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
- [X] #2840
