### ISSUE TITLE
[Feature][Web] Add the function of one-click recycling for automatic cluster registration in Registration Center

### ISSUE THREAD

**Issue by xialei30** [DataLinkDC/dinky#2842]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

【注册中心】-【集群】-【Flink 实例】界面，在升级到 1.0.0 版本后，取消掉了一键回收失效集群的功能，现在需要一个一个的删除。希望增加批量操作功能

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
目前自动回收，请看官方文档

**Comment by xialei30** [comment]
> 目前自动回收，请看官方文档

了解
