### ISSUE TITLE
[Bug] [Web] Other task's savepoints have appeared in current task's savepoint list

### ISSUE THREAD

**Issue by xialei30** [DataLinkDC/dinky#2855]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

开发作业右侧的 savepoint 列表出现其他作业的 savepoint

![savepoints](https://github.com/DataLinkDC/dinky/assets/140967927/b8567a1c-85b2-46a2-ab27-c288b730b019)

### What you expected to happen

只展示当前作业的 savepoint

### How to reproduce

新建一个 flink 作业，右侧的 savepoint 列表会出现之前作业的 savepoint

### Version

1.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
this is a bug  , i will fix it
