### ISSUE TITLE
There is a flaw in dinky user rights management. Ordinary users can vertically exceed their rights and obtain the same rights as admin. Ordinary users can vertically exceed their rights and obtain the same rights as admin.

### ISSUE THREAD

**Issue by listenquiet** [DataLinkDC/dinky#2866]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

The user rights management flaw in dinky allows any ordinary user to view, modify and delete other users' passwords, view, modify and delete other users' data source passwords and Flink instance configurations, and even promote any user to a super administrator.
dinky用户权限管理缺陷，导致任意普通用户可以查看、修改和删除其他用户密码，查看修改和删除其他用户的数据源密码、Flink实例配置，甚至可以把任意用户提升为超级管理员。

### What you expected to happen

Ordinary users should not have the same permissions as admin.
普通用户不应该有和admin一样的权限。

### How to reproduce

Verification idea: use admin to create users, change user passwords, create and modify data sources and Flink instance configurations, delete users or data sources and Flink configurations, capture the http packages for these operations, and then use ordinary user cookies to replace them with http packages. Send it to see if the administrator can perform operations as an ordinary user.
验证思路：使用admin创建用户、修改用户密码、创建并修改数据源和Flink实例配置、删除用户或数据源和Flink配置，把这些操作的http包抓下来，然后使用普通用户的cookie替换到http包里进行发送，查看是否能以普通用户的身份进行管理员的操作。
Reproduction steps 复现步骤：
### 1.Environment construction, use docker to build the latest version/环境搭建，使用docker搭建最新版

`docker run --name dinky-mysql dinkydocker/dinky-mysql-server:0.7.5`
![dinky搭建1](https://github.com/DataLinkDC/dinky/assets/17470525/31643970-7b70-4681-9368-86721d4945aa)
![dinky搭建2](https://github.com/DataLinkDC/dinky/assets/17470525/5b2112d2-7ab4-4e62-9e53-ed64a338ff64)

`docker run --restart=always -p 8888:8888 -p 8081:8081  -e MYSQL_ADDR=dinky-mysql:3306 --name dinky --link dinky-mysql:dinky-mysql dinkydocker/dinky-standalone-server:0.7.5-flink14`
![dinky搭建3](https://github.com/DataLinkDC/dinky/assets/17470525/aaa742ac-ee49-406f-9893-697001abefa4)

### 2.Log in using the default password admin:admin

使用默认密码admin：admin登录
![admin登录](https://github.com/DataLinkDC/dinky/assets/17470525/17f541fe-1d62-496f-a946-5838f081563f)
![admin首页目录树](https://github.com/DataLinkDC/dinky/assets/17470525/ff37719b-7954-4200-a3aa-02c50ad56ce0)
![admin目录树首页数据包](https://github.com/DataLinkDC/dinky/assets/17470525/8718ad0e-5eee-4f1e-b9bb-29c65582203c)

### 3. Use admin to perform regular operations and capture http data packets/使用admin进行常规操作，抓取http数据包

**admin creates a data source/admin创建数据源**
![admin创建数据源](https://github.com/DataLinkDC/dinky/assets/17470525/10449ea7-bf73-4d7e-bb42-ee789b10a84e)
![admin创建数据源2](https://github.com/DataLinkDC/dinky/assets/17470525/18563a92-9527-447d-a471-2c070a4d611d)
![admin创建数据源http](https://github.com/DataLinkDC/dinky/assets/17470525/52b02e5b-93f5-4284-8209-c842609d0b0e)

**admin view data source/admin查看数据源**
![admin查看数据源](https://github.com/DataLinkDC/dinky/assets/17470525/92d667d1-b84a-4da2-b454-6d1b2b341247)
![admin查看数据源http](https://github.com/DataLinkDC/dinky/assets/17470525/86b50e3a-9af2-4704-984a-a46101e7d4d0)

**admin creates a flinkinstance/admin创建flink实例**
![admin创建flink实例](https://github.com/DataLinkDC/dinky/assets/17470525/d9d624db-12af-4c52-9cc3-acc9c8f0c12a)
![admin创建flink实例http](https://github.com/DataLinkDC/dinky/assets/17470525/2ac266cb-992c-49f5-93bb-745fb73ddbbe)

**admin view flinkinstance/admin查看flink实例**
![admin查看flink实例](https://github.com/DataLinkDC/dinky/assets/17470525/c1a36f03-9f3c-4bae-a486-add0bc91ec49)
![admin查看flink实例http](https://github.com/DataLinkDC/dinky/assets/17470525/db5a4d40-e75d-4bf7-b8f0-38e78d7bbb26)

**admin Create user/admin创建用户**
![admin创建用户](https://github.com/DataLinkDC/dinky/assets/17470525/357ea500-69b9-471e-a46a-3d767ca433fa)
![admin创建用户http](https://github.com/DataLinkDC/dinky/assets/17470525/c8fb08a6-1e47-4b81-8715-1fe983448280)

**admin view all users/admin查看所有用户**
![admin查看所有用户](https://github.com/DataLinkDC/dinky/assets/17470525/18ac24ad-2361-40c4-bcb5-a01efd0f12cd)
![admin查看所有用户http](https://github.com/DataLinkDC/dinky/assets/17470525/84b787b4-f433-4b2f-9846-b762a9099f8c)

**admin modify User password/admin修改用户密码**
![admin修改用户密码](https://github.com/DataLinkDC/dinky/assets/17470525/db62296a-bb2d-4dab-8695-619203eff2fd)
![admin修改用户密码http](https://github.com/DataLinkDC/dinky/assets/17470525/3193e83e-59bb-46a2-998e-5d0d0dd68317)

**admin create tenant/admin创建租户**
![admin创建租户](https://github.com/DataLinkDC/dinky/assets/17470525/27bd929d-9a7e-43a9-9e9f-a4295f06f44b)
![admin创建租户http](https://github.com/DataLinkDC/dinky/assets/17470525/81563ff8-67c3-4157-802e-fe0ff3b88061)

**admin view all tenant/admin查看所有租户**
![admin查看所有租户](https://github.com/DataLinkDC/dinky/assets/17470525/d0046419-c497-44a7-b4a2-1dfd08e0cb4d)
![admin查看所有租户http](https://github.com/DataLinkDC/dinky/assets/17470525/8baac86a-2d90-4fdd-a876-d058be87cd26)

**admin create role/admin创建角色**
![admin创建角色](https://github.com/DataLinkDC/dinky/assets/17470525/d7b62b37-5974-4eea-902e-bc0f91b35adc)
![admin创建角色http](https://github.com/DataLinkDC/dinky/assets/17470525/cae8f87a-6143-4e60-b70a-6981800803a9)

**admin view all role/admin查看所有角色**
![admin查看所有角色](https://github.com/DataLinkDC/dinky/assets/17470525/d2b3561a-097f-4fbe-ab28-b79dbbb8848c)
![admin查看所有角色http](https://github.com/DataLinkDC/dinky/assets/17470525/b6c76ab5-e8ed-429f-a943-dcd1aadf0b64)

**admin sets the data permissions of the role/admin设置角色数据权限**
![admin设置角色数据权限](https://github.com/DataLinkDC/dinky/assets/17470525/a9a9fb60-54a5-416c-962d-ce2f259bd473)
![admin设置角色数据权限http](https://github.com/DataLinkDC/dinky/assets/17470525/655ed47e-9dd9-48bd-86da-0656cf93f90f)

**admin view the data permissions of the role/admin查看角色数据权限**
![admin查看角色数据权限](https://github.com/DataLinkDC/dinky/assets/17470525/3e0fc3dd-128a-40ff-b5b2-987b2329a396)
![admin查看角色数据权限http](https://github.com/DataLinkDC/dinky/assets/17470525/e04012d6-54f0-4af4-86a1-629cc47376e1)

**admin assigns roles to users/admin给用户分配角色**
![admin给用户分配角色](https://github.com/DataLinkDC/dinky/assets/17470525/f6eba39a-67c3-4984-a830-db24d70346b3)
![admin给用户分配角色2](https://github.com/DataLinkDC/dinky/assets/17470525/c4878dae-dd28-4587-8207-9e5e9f011ee7)
![admin给用户分配角色http](https://github.com/DataLinkDC/dinky/assets/17470525/60a6f166-7f03-42e5-9ad8-f9e6159712d7)

**admin assigns users to tenants/admin给租户分配用户**
![admin给租户分配用户](https://github.com/DataLinkDC/dinky/assets/17470525/e77ff3ee-df09-4daa-a8cf-a32f1010026c)
![admin给租户分配用户2](https://github.com/DataLinkDC/dinky/assets/17470525/a34fea2c-d253-4153-96c1-740b9d49daeb)
![admin给租户分配用户http](https://github.com/DataLinkDC/dinky/assets/17470525/2f154303-eb71-4b16-b7f2-3827c2b33bfc)

**admin create namespace/admin创建命名空间**
![admin创建命名空间](https://github.com/DataLinkDC/dinky/assets/17470525/b3303189-d900-4232-9675-f83a0b38da48)
![admin创建命名空间http](https://github.com/DataLinkDC/dinky/assets/17470525/9f4b6212-047d-4e6a-aa91-50c516890678)

**admin view namespace/admin查看命名空间**
![admin查看所有命名空间](https://github.com/DataLinkDC/dinky/assets/17470525/5a0f8b0a-dad8-4561-8230-d3999b11138b)
![admin查看所有命名空间http](https://github.com/DataLinkDC/dinky/assets/17470525/fbb505b9-3493-4f78-b382-806a03be8c98)

**admin delete namespace/admin删除命名空间**
![admin删除命名空间http](https://github.com/DataLinkDC/dinky/assets/17470525/3548b669-7519-40f7-a138-4c6b7b176cde)

### 4. Create a normal user/创建一个普通用户
**Then create a user named secUser and a tenant named secTenant respectively, associate the secUser user to the secTenant tenant, do not associate it with any role, and do not assign any role data permissions. This secUser user is an ordinary user./再分别创建一个名字为secUser的用户、名字为secTenant的租户，把secUser用户关联到secTenant租户，不关联任何角色，不分配任何角色数据权限，此secUser用户为普通用户**
![创建一个secUser普通用户](https://github.com/DataLinkDC/dinky/assets/17470525/ac533419-5521-4f5b-987e-04e1b32f0598)

The default password set by the server for new users is 123456/server给新用户设置的默认密码为123456
![新用户密码为123456](https://github.com/DataLinkDC/dinky/assets/17470525/5a6193e5-c9b5-49b5-997d-5c3c95a4c101)

**Log in as a normal user and get a token 3cf34c6b-60fb-4869-b6b3-117dd44e5ac9 /使用普通用户登录，获得token**
![普通用户token](https://github.com/DataLinkDC/dinky/assets/17470525/be9aa8dc-1a2e-4aa8-93ca-629cf1fc0ed8)

**In the web management interface, ordinary users cannot manage FlinkInstance and data sources, nor can they manage users/在web管理界面,普通用户无法管理FlinkInstance和数据源，也无法管理用户**
![普通用户无管理权限1](https://github.com/DataLinkDC/dinky/assets/17470525/580faec5-da2e-4f6c-b87e-72819134f98a)
![普通用户无管理权限2](https://github.com/DataLinkDC/dinky/assets/17470525/f14ca99b-171c-463c-a43c-d6759743fb2c)
![普通用户无管理权限3](https://github.com/DataLinkDC/dinky/assets/17470525/f6861e11-8c13-4fc8-96cb-438692dfedc9)

### 5. But if we replace the token of the ordinary user secUser into the various operations package of admin, we find that ordinary users also have various permissions of admin./但如果我们把secUser这个普通用户的token替换到admin各种操作的包里，发现普通用户也拥有了admin的各种权限

**Ordinary user creates user/普通用户创建用户**
![普通用户创建用户](https://github.com/DataLinkDC/dinky/assets/17470525/40c79b1b-343a-463a-a569-f56fa42a65f8)

**Ordinary users can view all user passwords/普通用户查看所有用户密码**
![普通用户查看所有用户密码](https://github.com/DataLinkDC/dinky/assets/17470525/e369a216-c88e-4980-86a5-5399e32f5580)

**Ordinary users change the passwords of other users/普通用户修改其他用户的密码**
![普通用户修改其他用户密码](https://github.com/DataLinkDC/dinky/assets/17470525/8efdd503-37f1-4701-909e-457917740fab)

**Ordinary users exceed their authority and delete other users/普通用户越权删除其他用户**
![普通用户越权删除其他用户](https://github.com/DataLinkDC/dinky/assets/17470525/585670d2-b30a-4d88-9ee8-c631f71fcbb8)

**Ordinary users view all tenants/普通用户查看所有租户**
![普通用户查看所有租户](https://github.com/DataLinkDC/dinky/assets/17470525/97f324a3-8f6d-4dc4-b745-34d8b70c8d0f)

**Ordinary users assign users to tenants/普通用户给租户分配用户**
![普通用户给租户分配用户](https://github.com/DataLinkDC/dinky/assets/17470525/d5a0123f-ccc8-4879-8e8b-6f58030cf9cb)

**Ordinary users exceed their authority to view the data source created by admin/普通用户越权查看admin创建数据源**
![普通用户查看其他用户的数据源](https://github.com/DataLinkDC/dinky/assets/17470525/4d72248a-89e7-4588-b56d-071368ec707e)

**Ordinary users exceed their authority to view the flink instance created by admin/普通用户越权查看admin 创建的flink实例**
![普通用户查看其他用户的flink实例](https://github.com/DataLinkDC/dinky/assets/17470525/0bcca1b3-0213-4eb3-b4b5-c4b946330e8d)

**Ordinary users view data permissions for roles/普通用户查看数据权限**
![普通用户查看角色数据权限](https://github.com/DataLinkDC/dinky/assets/17470525/a566a1b8-fb98-4b46-894d-df018215905a)

**Ordinary users set data permissions for roles/普通用户给角色设置数据权限**
![普通用户给角色设置数据权限](https://github.com/DataLinkDC/dinky/assets/17470525/8e7b9633-4bd1-41d7-980a-a0ef1b7267a5)

**Ordinary users view all nameSpaces/普通用户查看所有nameSpace**
![普通用户查看所有命名空间](https://github.com/DataLinkDC/dinky/assets/17470525/04849857-8ad0-432d-bf94-3c17b164836d)

**Ordinary users delete the namespace created by admin/普通用户删除admin创建的命名空间**
![普通用户删除admin用户创建的命名空间](https://github.com/DataLinkDC/dinky/assets/17470525/043e9e29-c1c6-4962-84f8-d3c8595f0a4e)

**Ordinary users assign SuperAdmin roles to other ordinary users/普通用户给其他普通用户分配SuperAdmin角色**
![普通用户把其他用户设置为超管](https://github.com/DataLinkDC/dinky/assets/17470525/b6977bb9-c97d-445b-9f72-abcd7360a1eb)

**Ordinary users can also delete data sources and Flink instances created by other users without permission, and obtain the homepage directory tree of other users without permission. No examples will be given here./普通用户还可以越权删除其他用户创建的数据源和Flink实例、可以越权获取其他用户的首页目录树，不再举例**

### Anything else

I only tested the latest version 0.7.5 and version 0.7.3, and both have such problems. Other versions such as 0.6.x and 0.5.x have not been tested.
我只测试了最新的0.7.5版本和0.7.3版本，都存在这样的问题。其他版本比如0.6.x和0.5.x未测试过

### Version

0.7.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
please use v1.0.0

**Comment by aiwenmo** [comment]
Please try v1.0.0-rc2.
