### ISSUE TITLE
[Bug] [dinky-admin] Page shows session dose not exists after backend restart

### ISSUE THREAD

**Issue by gitfortian** [DataLinkDC/dinky#2872]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/DataLinkDC/dinky/assets/52306466/2c430b40-6889-467d-80b9-6ee78eb0d90f)

### What you expected to happen

After the sse connection fails, the front-end automatically reconnects

### How to reproduce

restart backend then click the monitor page or the setting page

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ysq5202121** [comment]
要重新登录吧，老问题了!
建议登录颁发token 存储在localstore 就不会有类似问题
