### ISSUE TITLE
Yarn Application submitted CDCSOURCE task, connection refused: hadoop01:8083

### ISSUE THREAD

**Issue by jamyma** [DataLinkDC/dinky#2879]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

1、Flink配置文件中已经添加rest.bind-port，AM还是去连接rest.port的8083端口，导致应用启动失败。
![image](https://github.com/DataLinkDC/dinky/assets/7929890/7dce8679-c892-41ff-83f2-618bbfa84c85)

2、如果将rest.bind-port去掉，AM能连接8083端口成功，应用成功但是solt没有创建，Dinky日志提示No Flink task found, try again in 2 seconds.....

3、Dinky0.7.5+Flink1.16.2+Yarn Application 是成功， Dinky1.0.0.RC+Flink1.17.2或 Flink1.16.2+Yarn Appliction均失败

### What you expected to happen

1

### How to reproduce

1

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
please try 1.0.0.rc3
