### ISSUE TITLE
dolphinscheduler can not get the result of running job of tasks from dinky

### ISSUE THREAD

**Issue by fj199** [DataLinkDC/dinky#2882]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

I use dinky push a hivesql task to dolphinscheduler and the dolphinscheduler receive this job ,then ,i run this job in  dolphinscheduler,.
In fact ，this job has been executed successfully and i already has check the resulte in hive ,but，the dolphinschedler can not get the result correctlly, the task instance in dolphinscheduler displayed is failed 
![Snipaste_2024-01-03_09-01-51](https://github.com/DataLinkDC/dinky/assets/87365036/d0458a1d-816d-4879-8edf-cdb4d4904de6)
![Snipaste_2024-01-03_09-03-27](https://github.com/DataLinkDC/dinky/assets/87365036/7bb95f0b-42aa-4f4a-99e1-bf3457cb9249)
![Snipaste_2024-01-03_09-04-59](https://github.com/DataLinkDC/dinky/assets/87365036/4cd82435-442a-45b0-9478-0b7e45d1b9b0)

### What you expected to happen

The dolphinschedler need to  get the result correctlly, the task instance in dolphinscheduler displayed need to be success

### How to reproduce

l略

### Version

0.7.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
What's your dinky version?

**Comment by aiwenmo** [comment]
Fixed in #2999

**Comment by aiwenmo** [comment]
https://github.com/apache/dolphinscheduler/pull/15479
