### ISSUE TITLE
[Bug] [dinky-flink] Parameters 'set xxx = xxx' in flinksql task has no effect

### ISSUE THREAD

**Issue by xialei30** [DataLinkDC/dinky#2890]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

在 flinksql 作业中，使用 set 命令配置的参数在作业提交后没有生效，在其他配置选项中填写的参数可以生效
![参数配置](https://github.com/DataLinkDC/dinky/assets/140967927/3b89fe58-726e-48f4-91fb-673e3241aa96)
![savepoint路径](https://github.com/DataLinkDC/dinky/assets/140967927/d0925b95-f429-4619-8754-fb4f1cac7214)
![内存占比](https://github.com/DataLinkDC/dinky/assets/140967927/d9b25e90-c75d-488b-ae99-461bae9e62ed)

### What you expected to happen

开发作业中 set 命令生效，配置命令优先级 > 默认配置

### How to reproduce

如上

### Version

1.0.0

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Ak47biubiuaa** [comment]
是的，在刚刚发布的v1.0.0中我也遇到了这个问题。

**Comment by aiwenmo** [comment]
Please try Dinky v1.0.0-rc2.

**Comment by aiwenmo** [comment]
thx. I will fix it.
