### ISSUE TITLE
[Bug] [devops, webui] The running job displays 'End Time' with '1970-01-01 08:00:00'

### ISSUE THREAD

**Issue by leeoo** [DataLinkDC/dinky#2898]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![图片](https://github.com/DataLinkDC/dinky/assets/2136182/365c4c0f-2c4c-4b29-b937-5677d6e68623)

### What you expected to happen

The running job shoud display 'End Time' with '-' or blank.

### How to reproduce

![图片](https://github.com/DataLinkDC/dinky/assets/2136182/365c4c0f-2c4c-4b29-b937-5677d6e68623)

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
image is error

**Comment by Zzm0809** [comment]
you can fix this bug
