### ISSUE TITLE
[Bug] [Module Name] Bug title 

### ISSUE THREAD

**Issue by fengyangdi** [DataLinkDC/dinky#2915]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

add jar files in `Registration Center-Jar Management`, then refresh the jar file list, some times has result sometimes is empty
![image](https://github.com/DataLinkDC/dinky/assets/8668258/ddd7f733-645b-4f92-a644-b0246f06f7e1)
and in `Data Studio`, I have created a flink jar task and want to select the jar which uploaded in `Registration Center-Jar Management `, but the jar file list is empty.

### What you expected to happen

The jar list is correct, and in `Data Studio` can select if the jar file is enabled.

### How to reproduce

Create a new Tenant

login and select new Tenant

Add jar in `Registration Center-Jar Management`
![image](https://github.com/DataLinkDC/dinky/assets/8668258/8e208f2c-ec3c-4a44-adc6-e71b5ca97c59)

refresh the list of jar
![image](https://github.com/DataLinkDC/dinky/assets/8668258/8e208f2c-ec3c-4a44-adc6-e71b5ca97c59)
not 100 % occur and refresh list some times may occurs

### Anything else

Check the source code,
![image](https://github.com/DataLinkDC/dinky/assets/8668258/489e3535-ea31-471d-8082-29b295734299)
 the URI of `/api/jar` not interceptor by the TenantInterceptor and use Tenant last set in the thread. so the jar file may be belong to other tenants. And also others, like `/api/catalogue` etc. has the same problem.

### Version

0.7.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
use dinky 1.0.0

**Comment by fengyangdi** [comment]
> use dinky 1.0.0

ok
