### ISSUE TITLE
[Bug] [savepoint] restart with savepoint error

### ISSUE THREAD

**Issue by Pandas886** [DataLinkDC/dinky#2925]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

从savepoint重启无法使用
![image](https://github.com/DataLinkDC/dinky/assets/123344357/ac758073-ba6f-4e47-8966-cfa990a5027f)

开发页面无法看到保存点列表
![image](https://github.com/DataLinkDC/dinky/assets/123344357/a286cbb6-656a-4b38-9f3a-279bd84304b4)

history页面可以看到savepoint的记录。
![image](https://github.com/DataLinkDC/dinky/assets/123344357/39aa22f7-e881-40c7-ae40-d5bcc7a7d543)
但是切换savepoint页签就看不到了，savepoint列表空了。
![image](https://github.com/DataLinkDC/dinky/assets/123344357/f042f8b9-a4fb-4286-a7ba-5d0d88fc367e)

### What you expected to happen

正常使用savepoint处重启

### How to reproduce

如上

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
this bug fixed
