### ISSUE TITLE
[Bug] [yarn-session] cannot kill yarn session provided by dinky

### ISSUE THREAD

**Issue by Pandas886** [DataLinkDC/dinky#2926]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

无法删除dinky启动的yarn session
点击删除实例
![image](https://github.com/DataLinkDC/dinky/assets/123344357/ae76df51-4c71-4e5a-915b-dff01780bf3f)
确认删除后，yarn上依旧存在。
![image](https://github.com/DataLinkDC/dinky/assets/123344357/375ab933-1b7f-4f38-b2f2-f1b075ebbeb6)

### What you expected to happen

正常删除yarn-session

### How to reproduce

none

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
The latest code adds a button to stop the cluster. The cluster needs to be stopped before it can be deleted, waiting for subsequent releases.
