### ISSUE TITLE
[Bug] [dataStudio] Running status cannot change

### ISSUE THREAD

**Issue by Pandas886** [DataLinkDC/dinky#2935]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

在数据开发模块使用flinksql yarn application启动后。即使结束右上角还在运行中。
![image](https://github.com/DataLinkDC/dinky/assets/123344357/32820637-7ce0-4dc3-88ab-ed945b3a6e0d)

不只是yarn模式，local、standalone等都会有该问题

### What you expected to happen

能同步真实状态，即使有延迟。

### How to reproduce

none

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
Thank you for your feedback. This issue has been optimized. You can take a look at the PR below. If there are still problems, please continue to provide feedback.

#2933
