### ISSUE TITLE
[Bug] [devops] open job detail page error

### ISSUE THREAD

**Issue by Pandas886** [DataLinkDC/dinky#2939]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

当使用yarn-app模式，batch作业时，打开运维详情会报错
![image](https://github.com/DataLinkDC/dinky/assets/123344357/cc9a3799-7f03-42c3-a3df-6dfdfef5fcd0)
报错如下：
![image](https://github.com/DataLinkDC/dinky/assets/123344357/67cb6a26-c423-4522-967d-9cb1c192a874)

我的作业内容
![image](https://github.com/DataLinkDC/dinky/assets/123344357/a8e85810-159c-47e1-bddc-169febe1de2f)

### What you expected to happen

正常打开

### How to reproduce

none

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
Sorry for not able to reproduce the problem. Can you describe the process in more detail?

**Comment by gaoyan1998** [comment]
resolve #2978
