### ISSUE TITLE
There is an error in the dinky-pg.sql file of dinky-release-1.0.0-rc3 version

### ISSUE THREAD

**Issue by cncaizheng** [DataLinkDC/dinky#2960]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

dinky-pg.sql文件第537行，多了一个e字母，会在执行时出现报错

### What you expected to happen

请修复错误sql脚本

### How to reproduce

脚本拿到pg执行

### Version

1.0.0

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
Thanks feedback
