### ISSUE TITLE
[Bug] [dataStudio] FlinkJar Error

### ISSUE THREAD

**Issue by Pandas886** [DataLinkDC/dinky#2967]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

dinky version: 1.0.0-rc3

无法执行flinkjar任务，这个jar是flink的examples里的例子，已经上传到dinky的资源中心
![image](https://github.com/DataLinkDC/dinky/assets/123344357/b02e60b1-8d1b-4364-9b30-91da4cf96915)

### What you expected to happen

正常执行

### How to reproduce

none

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Pandas886** [comment]
检查了一下代码，是因为该jar是用dataset api实现的，没有生成streamGraph导致。如果用table api或者datastream开发的jar应该是可以的

**Comment by gaoyan1998** [comment]
try latest dev code? I couldn't reproduce it

**Comment by Pandas886** [comment]
> try latest dev code? I couldn't reproduce it
