### ISSUE TITLE
Are there any plans to support pyflink in the future?

### ISSUE THREAD

**Issue by aruizhong** [DataLinkDC/dinky#2968]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zackyoungh** [comment]
Can you create a list of PyFlink features so that we can align which features have been implemented
