### ISSUE TITLE
[Bug] [openAPI] submitTask request failed

### ISSUE THREAD

**Issue by yicong0513** [DataLinkDC/dinky#2969]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

接口调用失败

### What you expected to happen

![微信图片_20240109202807](https://github.com/DataLinkDC/dinky/assets/37571946/a97d1b83-fbd3-40b5-bf33-87798fbee591)

### How to reproduce

每次调用都可以复现

### Version

1.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Fixed in #2999
