### ISSUE TITLE
[Bug] [Module Name] When global variables are enabled in Application mode, Non-query expression encountered in illegal context is reported.

### ISSUE THREAD

**Issue by xjiahai** [DataLinkDC/dinky#2970]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Application模式下开启全局变量执行任务时报Non-query expression encountered in illegal context，禁止全局变量并修改sql不使用变量后执行正常，从flink日志中发现打印执行flinksql时会把变量也会打出来，应该是这个地方处理有问题，变量需要过滤

### What you expected to happen

启用全局变量执行application模式正常运行

### How to reproduce

设置数据源并开启全局变量，使用application模式执行

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
1. 目前不会过滤全局变量
2. 注意 1.0.0 下的全局变量使用方式和整库同步下的内置变量使用方式
3. 提供复现步骤,以及相关报错日志

**Comment by xjiahai** [comment]
以下两种方式注册全局变量在Yarn Application模式使用时执行都不行，报Non-query expression encountered in illegal context，见Flink执行日志，在Local、Yarn Per-Job没问题：
1、通过 注册中心->全局变量 定义
2、通过 注册中心->数据源 注册全局变量

![image](https://github.com/DataLinkDC/dinky/assets/21072848/cd7662f8-0d66-4634-b7b3-c19be09b97eb)

**Comment by gaoyan1998** [comment]
Duplicate of #2973
