### ISSUE TITLE
[Bug] [WEB] dinky-release-rc3 After creating a new user, configuring roles and resource permissions, an error message appears when the user successfully login

### ISSUE THREAD

**Issue by chuansenwang** [DataLinkDC/dinky#2971]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

After creating a new user, configuring roles and resource permissions, an error message appears when the user successfully logs in
![image](https://github.com/DataLinkDC/dinky/assets/125018730/afe8559e-0110-42ea-a432-f4c1b5833ee5)

### What you expected to happen

login success

### How to reproduce

![image](https://github.com/DataLinkDC/dinky/assets/125018730/24fddbd7-3967-4dcb-9711-1f49994b446c)
![image](https://github.com/DataLinkDC/dinky/assets/125018730/85f83704-32d7-41e8-9768-bbece1e5f5b2)
![image](https://github.com/DataLinkDC/dinky/assets/125018730/57181f0a-e343-4fdf-8e53-935d9b413214)

### Version

1.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
you can fix it

**Comment by Zzm0809** [comment]
无法复现
