### ISSUE TITLE
Integrating Alink

### ISSUE THREAD

**Issue by junyan-zg** [DataLinkDC/dinky#2976]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

As an excellent data warehouse software, whether to consider integrating Alink is also based on the Flink technology stack. If integrated, it will also become an application with data mining functions.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Pandas886** [comment]
good idea.

**Comment by junyan-zg** [comment]
![image](https://github.com/DataLinkDC/dinky/assets/15311002/575796e4-424e-4c63-a391-ae4c9b2f3dac)

Here is a prototype for reference, a demo by Smartbi (a commercial software). I hope you can make better designs, and I am very much looking forward to it. @Pandas886

**Comment by whmnoe4j** [comment]
考虑Flink ML吗，Alink 是 Flink 生态之外的一块项目，我们希望把 Alink 的所有能力都赋能给 Flink ML。

**Comment by junyan-zg** [comment]
> 考虑Flink ML吗，Alink 是 Flink 生态之外的一块项目，我们希望把 Alink 的所有能力都赋能给 Flink ML。

这样会面临很大工作量吧

**Comment by Pandas886** [comment]
> 考虑Flink ML吗，Alink 是 Flink 生态之外的一块项目，我们希望把 Alink 的所有能力都赋能给 Flink ML。

目前哪个更活跃一些？

**Comment by junyan-zg** [comment]
> > 考虑Flink ML吗，Alink 是 Flink 生态之外的一块项目，我们希望把 Alink 的所有能力都赋能给 Flink ML。
> 
> 目前哪个更活跃一些？

ML功能很少

**Comment by aiwenmo** [comment]
Alink only supports Flink version 1.9~1.13.

**Comment by junyan-zg** [comment]
> Alink only supports Flink version 1.9~1.13.

I think it is compatible with future versions

**Comment by aiwenmo** [comment]
> > Alink only supports Flink version 1.9~1.13.
> 
> I think it is compatible with future versions

At present, the dinky community team has no plans in this direction. Welcome to discuss and exchange ideas.
