### ISSUE TITLE
[Bug]  submit job to flink k8s-session fail

### ISSUE THREAD

**Issue by chuansenwang** [DataLinkDC/dinky#2977]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

我配置的flink实例，taskmanager 地址配置的是域名。心跳检测是正常的。但是提交任务的时候，配置的flink实例域名自动拼接的端口号导致连接失败
![image](https://github.com/DataLinkDC/dinky/assets/125018730/268d5494-b39e-4aa0-8317-0caac745d32f)

### What you expected to happen

正常提交

### How to reproduce

![image](https://github.com/DataLinkDC/dinky/assets/125018730/3b5fa95a-238f-4eff-b727-c0a04010d42a)
![image](https://github.com/DataLinkDC/dinky/assets/125018730/ee5cceb6-977c-4e1a-800f-753eba43cd8b)

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Thanks for your feedback. We will fix it.

**Comment by aiwenmo** [comment]
what's your dinky version?

**Comment by jiyong101** [comment]
try to change jobManager address to  internal ip  + port
