### ISSUE TITLE
[Bug] [datastudio] open saved flinksql ,form not correct

### ISSUE THREAD

**Issue by Pandas886** [DataLinkDC/dinky#2982]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.0.0-rc3

已保存的任务第一次打开页签时，内容不正确。我的任务是yarn-session模式，已经选择flink集群配置的。但是关闭所有任务页签后，重新打开，会丢失掉flink集群配置。

yarn-session,application都会有这个问题。
![image](https://github.com/DataLinkDC/dinky/assets/123344357/c7ea142a-af05-4aaa-a85c-1634e36eeca2)

### What you expected to happen

表单展现已保存的内容。

### How to reproduce

none

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
this is bug , please wait for me to fix it

**Comment by Pandas886** [comment]
> this is bug , please wait for me to fix it

Thanks.
