### ISSUE TITLE
[Bug] [datastudio] ctas flnksql check error

### ISSUE THREAD

**Issue by Pandas886** [DataLinkDC/dinky#2983]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.0.0-rc3

paimon create table xx as select xxx 语句实际运行是不会报错，但是点击检查时会报错。
这里的bigtable 是一张paimon表。

![image](https://github.com/DataLinkDC/dinky/assets/123344357/029a8a71-79d7-4fde-9d37-8f48f40cb7e2)

![image](https://github.com/DataLinkDC/dinky/assets/123344357/8d27bcba-76a4-44d8-b8b8-b7a3303db2d2)

### What you expected to happen

检查不报错

### How to reproduce

none

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leechor** [comment]
this is a flink bug, it's at code of scala part, I fed it to the community a few months ago, https://issues.apache.org/jira/projects/FLINK/issues/FLINK-32990

**Comment by Pandas886** [comment]
> this is a flink bug, it's at code of scala part, I fed it to the community a few months ago, https://issues.apache.org/jira/projects/FLINK/issues/FLINK-32990

thanks for reply.
