### ISSUE TITLE
An error occurred when starting the yarn application task. Asynchronous submission failed.

### ISSUE THREAD

**Issue by cncaizheng** [DataLinkDC/dinky#2985]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

控制台打印：
Dinky User Console:
[FlinkSubmit] 2024-01-11T11:17:44.206 INFO: Initializing Flink job config...
[FlinkSubmit] 2024-01-11T11:17:44.228 INFO: A total of 0 UDF have been Init.
[FlinkSubmit] 2024-01-11T11:17:44.228 INFO: Initializing Flink UDF...Finish
[FlinkSubmit] 2024-01-11T11:17:44.272 INFO: Submit Flink SQL finished.
<img width="1156" alt="image" src="https://github.com/DataLinkDC/dinky/assets/67569112/948f0ca4-e092-41e7-81e4-f4981e9c057e">

### What you expected to happen

希望能协助排查这个使用问题

### How to reproduce

1

### Version

0.7.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
需要提供下 完整地复现流程 包括:
sql 语句
操作步骤
后台日志
