### ISSUE TITLE
[Bug] [Module Name] cdc for mysql to starrocks,datetime is different

### ISSUE THREAD

**Issue by microxxx** [DataLinkDC/dinky#2988]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

EXECUTE CDCSOURCE test_ods_sync WITH (
  'connector' = 'mysql-cdc',
  'hostname' = '192.168.0.181',
  'port' = '3306',
  'username' = 'test',
  'password' = '***',
  'checkpoint' = '300000',
  'scan.startup.mode' = 'initial',
  'parallelism' = '1',
  'source.server-time-zone' = 'Asia/Shanghai',
  'table-name' = 'test\.company',
  'sink.connector' = 'starrocks',
  'sink.jdbc-url' = 'jdbc:mysql://192.168.0.182:19030',
  'sink.load-url' = '192.168.0.182:18030',
  'sink.username' = 'test',
  'sink.password' = '****',
  'sink.sink.db' = 'test',
  'sink.table.prefix' = 'ods_',
  'sink.table.lower' = 'true',
  'sink.database-name' = 'test',
  'sink.table-name' = '${tableName}',
  'sink.sink.properties.format' = 'json',
  'sink.sink.properties. timezone' = '+08:00',
  'sink.sink.properties.strip_outer_array' = 'true',
  'sink.sink.max-retries' = '10',
  'sink.sink.buffer-flush.interval-ms' = '60000',
  'sink.sink.parallelism' = '1'
) 

采用dinky0.7.5,flink 1.16 使用以上sql 去同步数据，相同时区下 源表mysql的数据 和结果表starrocks 的数据总差8个小时。

中间对时区参数做过很多调整，结果一直不对。

### What you expected to happen

希望源表和结果表数据一致。

### How to reproduce

mysql 默认是东八区时区
starrocks 也是东八区时区
版本: dinky 0.7.5,flink1.16
直接采用上述sql,两边时间查8个小时

### Version

0.7.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by microxxx** [comment]
flinkcdc 采用的是3.0版本，在不用全库同步的情况下，数据同步正常。

**Comment by aiwenmo** [comment]
`'sink.timezone' = 'UTC'`

**Comment by aiwenmo** [comment]
Specify the time zone required for time conversion through this parameter.
