### ISSUE TITLE
[Bug] [devops] job instance status not correct of flinksql yarn-app mode 

### ISSUE THREAD

**Issue by Pandas886** [DataLinkDC/dinky#2990]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.0.0-rc3

yarn-app模式下flinksql jar无法正常sendhook给dinky。以下是jm的一些日志。
![image](https://github.com/DataLinkDC/dinky/assets/123344357/4437d0a6-edca-4a89-a3ea-7bb474270747)
无法正确获取在yarn上启动的jm的rest.port
![image](https://github.com/DataLinkDC/dinky/assets/123344357/e6b1c31d-a7b0-4a6e-8c9e-29201b9a3dfa)

导致在运维中心查看的状态和时长都是不正确的。
![image](https://github.com/DataLinkDC/dinky/assets/123344357/eb291bae-d905-4bee-8c46-052190b8e125)
实际完成时间不是这么短的，但是dinky会自动处理成finish，即使没接收hook，而且完成时间也不正确
![image](https://github.com/DataLinkDC/dinky/assets/123344357/f0d73813-ba0e-4121-a093-d725ee2e3831)

### What you expected to happen

yarn-app模式下的flinksq可以正常在运维中心中看到准确的状态和时间

### How to reproduce

none

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
You can solve this problem by uncommenting 'res.port' in the flink configuration file。
I will fix later

**Comment by Pandas886** [comment]
After use latest branch , some error appear when many jobmanager start on same Yarn NodeManager. 
This error will cause dinky-app could not run.
![image](https://github.com/DataLinkDC/dinky/assets/123344357/3f9b7aa2-6274-4d02-88e4-a55690ef8a47)

**Comment by Pandas886** [comment]
是否直接查询dinky 数据库，查询出job对应的cluster host和端口更合适？

**Comment by Zzm0809** [comment]
> 是否直接查询dinky 数据库，查询出job对应的cluster host和端口更合适？

@gaoyan1998

**Comment by yangzehan** [comment]
> 使用 latest 分支后，当多个 jobmanager 在同一个 Yarn NodeManager 上启动时，会出现一些错误。此错误将导致 dinky-app 无法运行。 ![图像](https://private-user-images.githubusercontent.com/123344357/296785517-3f9b7aa2-6274-4d02-88e4-a55690ef8a47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODQxMTIsIm5iZiI6MTcwNTQ4MzgxMiwicGF0aCI6Ii8xMjMzNDQzNTcvMjk2Nzg1NTE3LTNmOWI3YWEyLTYyNzQtNGQwMi04OGU0LWE1NTY5MGVmOGE0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QwOTMwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjJiZTY3MDIwZDdhZGI1YjUzZjllY2M1YWI3MmZlMjhjMTgwMWE3NTU2MjBiNDA4MWU0ZTQzYTUwOWQwY2Q2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n3xVjU-fKLjjAicHTbcp8_bgX-ApS7u-vv0iI1zielc)

如果不在配置文件中指定端口的话用dev的代码还是会端口为0吗？

**Comment by zackyoungh** [comment]
已使用其他方式解决了此问题 ，请看 #3025
