### ISSUE TITLE
[FAQ] [devops] The status is abnormal after the task is manually stopped.

### ISSUE THREAD

**Issue by xjiahai** [DataLinkDC/dinky#2991]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

点击智能停止后，任务会处于一段时间reconnect状态，然后最后是unknown状态
![image](https://github.com/DataLinkDC/dinky/assets/21072848/e7641b00-ad7f-447e-8d13-f2aff2874b57)

### What you expected to happen

正常状态应该为已停止

### How to reproduce

点击智能停止后，任务会处于一段时间reconnect状态，然后最后是unknown状态
![image](https://github.com/DataLinkDC/dinky/assets/21072848/e7641b00-ad7f-447e-8d13-f2aff2874b57)

### Version

1.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
Please provide the  dinky version and cluster execution mode

**Comment by aiwenmo** [comment]
For the job status of perjob, the final result will be obtained through Yarn. The current `unknow` status is not as expected, which may be a bug.

**Comment by xjiahai** [comment]
dinky version:1.0.0-rc3
execution mode:yarn application

**Comment by Zzm0809** [comment]
this is normal in dinky
