### ISSUE TITLE
[Bug] [datastudio] After opening multiple task tags, when viewing the historical version of any task opened later, it will be the historical version of the first task tag.

### ISSUE THREAD

**Issue by xjiahai** [DataLinkDC/dinky#2992]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

打开多个任务标签后查看后面打开的任意一个任务的历史版本时均为第一个任务标签的历史版本
![image](https://github.com/DataLinkDC/dinky/assets/21072848/1eaef69b-b963-4df8-bfab-449887e19ff2)

### What you expected to happen

应该为对应任务标签的历史发布版本

### How to reproduce

打开多个任务标签后查看后面打开的任意一个任务的历史版本时均为第一个任务标签的历史版本
![image](https://github.com/DataLinkDC/dinky/assets/21072848/1eaef69b-b963-4df8-bfab-449887e19ff2)

### Version

1.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Thanks for your feedback. We will fix it.

**Comment by Zzm0809** [comment]
i will be fix it
