### ISSUE TITLE
[Bug] [WEB] Web pages of version 1.0.0 cannot be used in lower versions of Chrome, such as 76, 77, etc. Version 0.7.5 is normal.

### ISSUE THREAD

**Issue by xjiahai** [DataLinkDC/dinky#2993]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.0.0版本的Web页面在Chrome低版本无法使用，如76、77等，0.7.5版本是正常的
![image](https://github.com/DataLinkDC/dinky/assets/21072848/3e320b81-332e-4c21-a10d-605b3d1fb223)

### What you expected to happen

对于Chrome低版本也应该提供兼容支持

### How to reproduce

1.0.0版本的Web页面在Chrome低版本无法使用，如76、77等，0.7.5版本是正常的
![image](https://github.com/DataLinkDC/dinky/assets/21072848/3e320b81-332e-4c21-a10d-605b3d1fb223)

### Version

1.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Thanks for your feedback. This issue is very tricky to handle.

**Comment by Zzm0809** [comment]
Upgrading the browser version by yourself will not solve this compatibility issue
