### ISSUE TITLE
After submitting the task to Flink On Yarn in version 1.0.0, the Yarn cluster cannot display detailed Flink logs, but after submitting the task in version 0.7.0, it can

### ISSUE THREAD

**Issue by XiaoXingChiRou** [DataLinkDC/dinky#2996]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

同样的Yarn集群，同样配置的Flink 1.14.3安装包及使用Jar包
Yanr集群使用CDH6.3.2搭建集群
0.7.0版本Dinky，将Flink Jar任务到Yarn Application后，Yarn会显示详细日志，详细图片如下
![详细日志1](https://github.com/DataLinkDC/dinky/assets/77185888/eea8542c-79c4-4bc0-9314-615d3ed66e92)
![详细日志2](https://github.com/DataLinkDC/dinky/assets/77185888/3c0f3d1b-aa6f-407e-bbd1-27b8fc950dc6)
![详细日志3](https://github.com/DataLinkDC/dinky/assets/77185888/4e94d9b9-bb93-45be-b242-8c71d9084857)
![详细日志4](https://github.com/DataLinkDC/dinky/assets/77185888/b838743c-ce32-4364-92e3-dc380ebd43f1)
但是更换到1.0.0版本后，Yarn界面无法显示详细日志，详细图片如下
![非详细日志](https://github.com/DataLinkDC/dinky/assets/77185888/ee0ef0d8-3cd0-49c1-86c3-4fcfb367c42e)
只有结束日志，任务报错日志并无

### What you expected to happen

希望可以像0.7.0版本一样看到Yarn中的详细日志

### How to reproduce

任务提交后，访问Yarn控制平台

### Anything else

新版本经常发生

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Thanks for your feedback. We will fix it.
