### ISSUE TITLE
After submitting the Flink On Yarn task in version 1.0.0, after clicking the end task button, the operation and maintenance center displays the status of reconnecting to the cluster.

### ISSUE THREAD

**Issue by XiaoXingChiRou** [DataLinkDC/dinky#2997]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![运行状态1](https://github.com/DataLinkDC/dinky/assets/77185888/2b702ad1-f844-483d-a206-5bb27ed470b0)
![运行状态2](https://github.com/DataLinkDC/dinky/assets/77185888/b2d86a1e-c5d7-4f27-83ad-29ad2b398e12)
![运行状态3](https://github.com/DataLinkDC/dinky/assets/77185888/79027f82-4434-41e9-95a5-d28993dd520c)
使用Flink Application提交任务到Yarn后，运维中心显示任务在运行，但是停止任务后，运维中心一直在重新连接集群，0.7.0版本并不是这样

### What you expected to happen

希望可以将状态表明为关闭

### How to reproduce

数据开发界面后，提交任务到Yarn集群（Application），停止任务，观察运维中心状态显示

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
Repeat with #2990
