### ISSUE TITLE
 Cannot resolve path parameter (jobid) from value "undefined".

### ISSUE THREAD

**Issue by xiazhuyidechenqiliang** [DataLinkDC/dinky#2998]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

flink 版本1.15 dinky 版本1.0.0 运行mysql cdc to HUDI 时
用yarn-session模式任务无异常  但是checkpoint 为空
![image](https://github.com/DataLinkDC/dinky/assets/156416203/ca0f30a3-ab63-44ad-b277-72b3e72c8b01)
而且 JOBmanager 报错
![image](https://github.com/DataLinkDC/dinky/assets/156416203/a6ac0b64-c700-4c8a-9cb7-90d244c9ba51)

但是同样的sql在yarn-application模式是正常的

另外用sql-client跑在同一个session模式也是正常的

### What you expected to happen

是否是无法获取jobid的问题
这是同样的sql用sql-client跑在同一个flink-session的jobid
![Uploading image.png…]()

### How to reproduce

启动一个yarn-session测试一下

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Need to use `Set` syntax in FlinkSQL to specify the configuration of Checkpoint. 
`SET execution.checkpointing.interval = 80000;`
