### ISSUE TITLE
[Bug] [Data Development] Data source connection cache problem

### ISSUE THREAD

**Issue by liurulin1993** [DataLinkDC/dinky#3000]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

添加数据源后，在数据开发页面查看数据源时，当我修改数据库表名时，无论怎么刷新，数据源界面查看的表名并没有更新最新数据库状态

### What you expected to happen

当我改变数据库结构时，刷新数据源后应该加载最新的数据库信息

### How to reproduce

添加数据源后，点击数据开发，查看数据源，修改数据库表名或者结构，再查看数据源时，数据库信息并没有更新

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zackyoungh** [comment]
我尝试了，并没有复现此问题
