### ISSUE TITLE
[Bug] [assignMenuToRole] Creates a new role and assigns all menu permissions but loses permissions for the data source

### ISSUE THREAD

**Issue by wdssky** [DataLinkDC/dinky#3002]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.0.0-rc3
I created a new role and assigned datasource menu permissions,and parameters are also uploaded normally
![image](https://github.com/DataLinkDC/dinky/assets/28669978/4930f1b8-7a77-403f-88a0-13e5cc7cc1c2)
The dinky_sys_role_menu table of the dinky database can also be queried(menu_id is 10)
![image](https://github.com/DataLinkDC/dinky/assets/28669978/9874ccbb-0288-4645-8efd-5f671a56820c)
However, if you login with an account under the new role, you cannot see the datasource page
![image](https://github.com/DataLinkDC/dinky/assets/28669978/f52be0ef-7922-4319-9087-a3ff6b6e063a)
There is no datasource menu in the left sidebar of the registry menu (id: 10, parent id: 3), access to /registration/datasource in the browser address bar will be rejected, and it is found that there is an api "current" return result with some menu bars, and the search can only search for one datasource (this is the datasource in the left menu bar of the data development menu, id: 35, parent id: 5)

### What you expected to happen

Displays the datasource menu for the registry

### How to reproduce

Step 1:create a new role with admin.  Step 2:create a new user and assign the new user to the new role.  Step 3:assign menu to the role and submit it.  Step 4: use new user login in dinky and visit that page

### Version

1.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Thanks for your feedback. We will fix it.
