### ISSUE TITLE
Unable to initialize FlinkBatchRuleSets

### ISSUE THREAD

**Issue by DriftXjh** [DataLinkDC/dinky#3007]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/DataLinkDC/dinky/assets/36782165/7cf09416-8cd6-43df-a2b8-695ef5869bb1)
![image](https://github.com/DataLinkDC/dinky/assets/36782165/06ca4372-c0fa-402a-83c2-d28db7ae3819)
![image](https://github.com/DataLinkDC/dinky/assets/36782165/9a743d25-873d-4a85-86ef-fe38e5882c37)
![image](https://github.com/DataLinkDC/dinky/assets/36782165/1df6aee7-3ec0-4723-9bb8-9643c3f58271)
[c7d769ab-daee-4754-bedc-b4d2a3e2dd60.txt](https://github.com/DataLinkDC/dinky/files/13937047/c7d769ab-daee-4754-bedc-b4d2a3e2dd60.txt)
点了预览以上报错
版本jdk11，flink1.18，dinky1.0rc3。

### What you expected to happen

正常执行

### How to reproduce

.

### Version

1.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Pandas886** [comment]
有没有试过删除dinky/extends下的其他flink版本目录

**Comment by Zzm0809** [comment]
why flink-connector-jdbc version is 1.17????

**Comment by Zzm0809** [comment]
need more log

**Comment by aiwenmo** [comment]
This is normal.
Your source is stream not batch. 
The data gen is unbounded.

**Comment by DriftXjh** [comment]
> 有没有试过删除dinky/extends下的其他flink版本目录
有，已经试过了

**Comment by DriftXjh** [comment]
> why flink-connector-jdbc version is 1.17????
已经删了这个包了，也重启了，目前就是local模式。也没用到。但是错误还是有。

**Comment by DriftXjh** [comment]
> need more log

全日志文件已经上传了。
