### ISSUE TITLE
[Feature] I hope to add deduplication in the email alarm function and increase the interval alarm function.

### ISSUE THREAD

**Issue by XiaoXingChiRou** [DataLinkDC/dinky#3010]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![报警邮件](https://github.com/DataLinkDC/dinky/assets/77185888/aa8efbf4-7110-4031-b753-db305e55544b)
现阶段邮件报警功能，在测试过程中，报警太过于频繁，只测试了一个任务，任务提交后遇到重启，相同任务一分钟报警20+邮件。
任务停止后，若不下线任务，则会一直报警任务停止。
希望增加一个报警间隔，例如同一个任务，两次报警时间间隔五分钟，如果报警的状态一致，希望每隔五分钟报警一次，如果任务停止状态，希望只报警一次，或者半小时后再次报警。

### Use case

例：
第一次报警       时间：2024.01.16 15:00:00     报警状态：重启     任务ID：12345
第二次报警       时间：2024.01.16 15:05:00     报警状态：重启     任务ID：12345
第三次报警       时间：2024.01.16 15:10:00     报警状态：重启     任务ID：12345
第四次报警       时间：2024.01.16 15:11:00     报警状态：重新连接集群     任务ID：12345
第五次报警       时间：2024.01.16 15:11:12     报警状态：停止     任务ID：12345
第六次报警       时间：2024.01.16 15:41:12     报警状态：停止     任务ID：12345

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
- [X] #3011
