### ISSUE TITLE
[Optimization] [web] When creating a project-multi-level directory, the mouse cannot be clicked to collapse it.

### ISSUE THREAD

**Issue by 372242283** [DataLinkDC/dinky#3019]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

版本：1.0.0-rc3
描述如下图：鼠标点击aaa文件夹或者测试文件夹，无法折叠（有时候可以折叠，有时候不可以）
![image](https://github.com/DataLinkDC/dinky/assets/43502242/ae4fe0e5-c509-4e47-8212-b995bde65809)

### What you expected to happen

期待：当创建多级项目的时候，鼠标点击可以折叠项目，这样用户体验就会好很多，应该是前端的一个bug，因为有时候可以折叠，但是大部分时候不可以折叠

### How to reproduce

期待：当创建多级项目的时候，鼠标点击可以折叠项目，这样用户体验就会好很多，应该是前端的一个bug，因为有时候可以折叠，但是大部分时候不可以折叠

### Anything else

期待：当创建多级项目的时候，鼠标点击可以折叠项目，这样用户体验就会好很多，应该是前端的一个bug，因为有时候可以折叠，但是大部分时候不可以折叠

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 372242283** [comment]
另外还发现个问题，就是不同项目下，是不能创建相同名字的作业
页面会提示：操作未成功  作业已存在

**Comment by Zzm0809** [comment]
> 另外还发现个问题，就是不同项目下，是不能创建相同名字的作业 页面会提示：操作未成功 作业已存在

这不是问题,本来就这要求

**Comment by Zzm0809** [comment]
目前的逻辑当该节点下有目录且为展开状态下 ,该节点不能折叠 ,需要优化

**Comment by 372242283** [comment]
> > 另外还发现个问题，就是不同项目下，是不能创建相同名字的作业 页面会提示：操作未成功 作业已存在
> 
> 这不是问题,本来就这要求

但是不同项目下，有相同名字的作业应该是可以允许的吧，是否考虑这个问题呢，当然这不是特别重要的问题

**Comment by Zzm0809** [comment]
> > > 另外还发现个问题，就是不同项目下，是不能创建相同名字的作业 页面会提示：操作未成功 作业已存在
> > 
> > 
> > 这不是问题,本来就这要求
> 
> 但是不同项目下，有相同名字的作业应该是可以允许的吧，是否考虑这个问题呢，当然这不是特别重要的问题

不允许 , 不会考虑, 这里是全局的

**Comment by 372242283** [comment]
> > > > 另外还发现个问题，就是不同项目下，是不能创建相同名字的作业 页面会提示：操作未成功 作业已存在
> > > 
> > > 
> > > 这不是问题,本来就这要求
> > 
> > 
> > 但是不同项目下，有相同名字的作业应该是可以允许的吧，是否考虑这个问题呢，当然这不是特别重要的问题
> 
> 不允许 , 不会考虑

好的，多谢。应该是考虑到提交任务的时候，任务名称必须唯一吧

**Comment by Zzm0809** [comment]
已存在 issue : #2770

后续优化
