### ISSUE TITLE
[Bug] [Front-end] After creating the FlinkSqlEnv job in the project, the FlinkSQL environment on the right does not display the newly added FlinkSqlEnv job.

### ISSUE THREAD

**Issue by 372242283** [DataLinkDC/dinky#3023]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

版本：1.0.0-rc3
描述如下图：当新创建FlinkSqlEnv作业后，右侧的FlinkSQL 环境应该要显示新添加的FlinkSqlEnv作业。重新登录也不显示，相同的配置和操作rc_2版本可以显示。
![image](https://github.com/DataLinkDC/dinky/assets/43502242/6ad62d96-dfca-401e-a26f-ca8b1ba3af1e)

### What you expected to happen

当新创建FlinkSqlEnv作业后，右侧的FlinkSQL 环境应该要显示新添加的FlinkSqlEnv作业。重新登录也不显示，相同的配置和操作rc_2版本可以显示。

### How to reproduce

当新创建FlinkSqlEnv作业后，右侧的FlinkSQL 环境应该要显示新添加的FlinkSqlEnv作业。重新登录也不显示，相同的配置和操作rc_2版本可以显示。

### Anything else

当新创建FlinkSqlEnv作业后，右侧的FlinkSQL 环境应该要显示新添加的FlinkSqlEnv作业。重新登录也不显示，相同的配置和操作rc_2版本可以显示。

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
已修复

**Comment by Zzm0809** [comment]
pr is #2726

**Comment by 372242283** [comment]
说明一下：
有问题的是当我使用pgsql的时候，右边FlinkSqlEnv不能自动显示出来了。
然后我修改为MySQL的时候，FlinkSqlEnv是正常，右边可以显示；
所以我也很奇怪，就修改了数据库，其他都没有动，你们有使用pgsql的吗，应该可以复现这个问题？
