### ISSUE TITLE
[Bug] [WEB] After using Pgsql to create a FlinkSqlEnv job, the drop-down selection cannot be made

### ISSUE THREAD

**Issue by 372242283** [DataLinkDC/dinky#3029]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

版本：1.0.0-rc3
后端数据库：Pgsql
描述如下图：当新创建FlinkSqlEnv作业后，右侧FlinkSQL环境  无法显示新创建的FlinkSqlEnv。换成Mysql可以，Pgsql不行
![image](https://github.com/DataLinkDC/dinky/assets/43502242/ad0ad5bb-ea5d-43bc-9c0a-f571aa814856)

### What you expected to happen

当新创建FlinkSqlEnv作业后，右侧FlinkSQL环境  无法显示新创建的FlinkSqlEnv。换成Mysql可以，Pgsql不行，就比较奇怪

### How to reproduce

当新创建FlinkSqlEnv作业后，右侧FlinkSQL环境  无法显示新创建的FlinkSqlEnv。换成Mysql可以，Pgsql不行，就比较奇怪

### Anything else

当新创建FlinkSqlEnv作业后，右侧FlinkSQL环境  无法显示新创建的FlinkSqlEnv。换成Mysql可以，Pgsql不行，就比较奇怪

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
There is a default value problem in initializing sql. Let me fix it.
