### ISSUE TITLE
[Feature] Support Execute a set of SQL statements

### ISSUE THREAD

**Issue by chuansenwang** [DataLinkDC/dinky#3036]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

我希望增加支持语句集语法来执行一组SQL语句。语句集语法包含一个或多个INSERT INTO语句。我们使用的Flink1.17.2 在SQL Client 已经实现了该特性。
参考链接：https://nightlies.apache.org/flink/flink-docs-release-1.17/docs/dev/table/sqlclient/#execute-a-set-of-sql-statements
语法
EXECUTE STATEMENT SET 
BEGIN
  -- one or more INSERT INTO statements
  { INSERT INTO|OVERWRITE <select_statement>; }+
END;

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
这个功能在 dinky 诞生之初就已经存在.
你无需编写:
```sql
EXECUTE STATEMENT SET
BEGIN

...

end

```
这种语句, 直接写多个 insert into ...... ;
例如:
```sql

insert into sink_table_a select * from a;
insert into sink_table_b select * from a;
insert into sink_table_c select * from a;

```

如果使用的是 1.0.0 之前的版本 在作业配置中找到`开启语句集`
如果使用的是 1.0.0 及其之后的版本, 在程序中已经默认开启,按照上述例子编写完成之后,并保证作业配置配置完成,直接点击运行即可
