### ISSUE TITLE
[Bug] [Packaging exception] dinky-core prompts jdk version issue

### ISSUE THREAD

**Issue by suiquantong** [DataLinkDC/dinky#3037]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

has been compiled by a more recent version of the Java Runtime (class file version 56.0)
<img width="1234" alt="8856ec0e6ba095531869f2ea342c443f" 
src="https://github.com/DataLinkDC/dinky/assets/37520861/71927871-55a2-4f41-ac88-50cf7402a7b5">

### What you expected to happen

jdk 1.8 
dinky 1.0.0 -r3
flink 1.16 
打包时 进行mvn  spotless:apply    但是 到了core 包就会报错，升级jdk 11 才能解决这个问题

### How to reproduce

修复这个问题，缺包jdk8 可以正常打包，并且目前还存在很多 class 找不到的问题 flinksql 在flink客户端可以执行 但是在dinky 就会报错的问题 报错需要优化 不能直接跳到错误编译页面

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
目前打包插件强制要求 jdk11 这是正常的
