### ISSUE TITLE
Missing source code，Unable to compile

### ISSUE THREAD

**Issue by liukundong** [DataLinkDC/dinky#3042]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

怎么源代码缺失这么多呢？都无法编译：
import org.dinky.data.model.FlinkCDCConfig;
import org.dinky.data.model.Table;
import org.dinky.utils.SplitUtil;
在dinky-client-base都没有

### What you expected to happen

怎么源代码缺失这么多呢？都无法编译：
import org.dinky.data.model.FlinkCDCConfig;
import org.dinky.data.model.Table;
import org.dinky.utils.SplitUtil;
在dinky-client-base都没有

### How to reproduce

怎么源代码缺失这么多呢？都无法编译：
import org.dinky.data.model.FlinkCDCConfig;
import org.dinky.data.model.Table;
import org.dinky.utils.SplitUtil;
在dinky-client-base都没有

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
去看官网 注意 profile 的勾选
