### ISSUE TITLE
[Bug] [Module Name] I’m numb, and it’s a bug after just using it.

### ISSUE THREAD

**Issue by ysq5202121** [DataLinkDC/dinky#3048]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/DataLinkDC/dinky/assets/8586973/a065234f-7782-44f0-8831-7409296349e7)
用的是快速启动docker版本rc3，才添加了一个企业微信告警就系统挂掉了

### What you expected to happen

1

### How to reproduce

1

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ysq5202121** [comment]
有一个报错其他所有页面将无法打开

**Comment by ysq5202121** [comment]
必须先刷新缓存才能打开其他页面

**Comment by Zzm0809** [comment]
docker 1.x 镜像目前不可用

**Comment by ysq5202121** [comment]
OK
