### ISSUE TITLE
[Bug] [Registration Center] The 'Flink Instance' cannot be updated properly

### ISSUE THREAD

**Issue by leeoo** [DataLinkDC/dinky#3053]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Env: Dinky 1.0.0-rc3

There is an old flink-instance with jobManager address 192.168.200.179:8081 (**1.18.0** standalone HA) , I update it with new jobManager address 192.168.200.167:8081 (**1.18.1** standalone HA), then I see it still show me with the old jobManager address even if after clicking [Heartbeat] button.

![4493b5ef8f8d40830c3617cf163d0f9](https://github.com/DataLinkDC/dinky/assets/2136182/22191393-690c-46e0-b145-a10d739cdb87)

![fcb69ab361f1eaa9a940d74163249e4](https://github.com/DataLinkDC/dinky/assets/2136182/28771291-7d4e-484f-b7b2-76b0f4353de5)

![34b44475a37577347e18ba6fbba3933](https://github.com/DataLinkDC/dinky/assets/2136182/fdee2c6e-edae-4a3e-8222-bb1adb33fde3)

![a4f79f2a952eb32b420c3952eab89cc](https://github.com/DataLinkDC/dinky/assets/2136182/ae78d361-b705-4f51-b971-04ac6b279268)

![8e6d1b1a3a4d7dcb0fcb6a891f4cbed](https://github.com/DataLinkDC/dinky/assets/2136182/b8538537-c6d8-4ec4-b263-217dbe6d1667)

### What you expected to happen

The 'Flink Instance' can be updated properly.

### How to reproduce

1. Registration Center -> Cluster -> Flink,  create a flink cluster instance with Flink **1.18.0** jobManager HA address (e.g. 192.168.200.179:8081).
2. Edit above flink cluster instance, update it with Flink **1.18.1** jobManager HA address (e.g. 192.168.200.167:8081).
3. See the flink cluster instance info, even after clicking [Heartbeat] button.

Note that the two jobManagers above-mentioned are not belong to a flink cluster, they are just two flink clusters with different flink version.

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
#3070
