### ISSUE TITLE
[Bug] Data development submission task error

### ISSUE THREAD

**Issue by XiaoXingChiRou** [DataLinkDC/dinky#3082]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![微信图片_20240129140927](https://github.com/DataLinkDC/dinky/assets/77185888/f59ef5d1-5a05-4af6-b7ec-3a12d5aa4306)
![微信图片_20240129140943](https://github.com/DataLinkDC/dinky/assets/77185888/fe62c6e1-9a78-4f2c-89f6-5b91b0af647f)
资源中心上传Flink Jar包后，编辑任务，可顺利提交。
但是删除资源中心所用包，HDFS上资源包同样删除，上传更改后的Jar包，相同命名，使用原来保存的任务提交，但是报错空指针，新的Jar里面已经打包相应类。

### What you expected to happen

希望在不重启Dinky的情况下，更新任务包不会报错，可以使用最新包进行任务提交。

### How to reproduce

资源中心上传包 -> 数据开发界面编辑任务并保存提交 -> 关闭任务 -> 删除资源中心所用任务包，删除HDFS上面相应包 -> 资源中心添加新编译包，同样名字，同样启动类 -> 数据开发点击之前保存任务，提交集群运行

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
@XiaoXingChiRou 请规范修改 issue 的 title

**Comment by XiaoXingChiRou** [comment]
@Zzm0809 已修改

**Comment by Zzm0809** [comment]
删除并行度参数设置, 使用 set 语法 或者在作业配置 -> 其他配置增加并行度参数配置
