### ISSUE TITLE
[Bug] [CDCSOURCE] CDCSOURCE synchronizes the entire database from MySQL5.7 to doris and reports an error

### ISSUE THREAD

**Issue by sitong000** [DataLinkDC/dinky#3089]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

环境：Dinky0.7.5+Flink1.17.2
现象：配置整库同步任务提交flink无报错日志，dinky有报错如下：
[dlink] 2024-01-29 08:29:55 CST ERROR com.alibaba.druid.stat.DruidDataSourceStatManager 165 addDataSource - register mbean error javax.management.MalformedObjectNameException: Invalid character '=' in value part of property

### What you expected to happen

无

### How to reproduce

创建CDC任务

### Version

0.7.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Use Dinky 1.0
