### ISSUE TITLE
[Optimization][MySQLCDC] MySQLCDCBuild can't support `earliest-offset` or `timestamp` scanStartupMode now.Hope to upgrade it.

### ISSUE THREAD

**Issue by hpp523661618** [DataLinkDC/dinky#3090]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

situation：It seems like MySQLCDCBuild do not support `earliest-offset` and `timestamp` scanStartupMode. Perhaps you can upgrade the version of cdc version to be more useful in production.

`if (Asserts.isNotNullString(config.getStartupMode())) {
            switch (config.getStartupMode().toLowerCase()) {
                case "initial":
                    sourceBuilder.startupOptions(StartupOptions.initial());
                    break;
                case "latest-offset":
                    sourceBuilder.startupOptions(StartupOptions.latest());
                    break;
                default:
            }
        } else {
            sourceBuilder.startupOptions(StartupOptions.latest());
        }`
version:  dlink-0.7.0/ flink-1.14

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
@hpp523661618 请补全 issue title , 否则将置为无效 issue

**Comment by aiwenmo** [comment]
Thanks for your feedback.
0.7 has no planned upgrade, you can try modifying the source code yourself or upgrading to 1.0.
