### ISSUE TITLE
[Bug] [datastudio] execute error when flinksql has Space bar

### ISSUE THREAD

**Issue by Pandas886** [DataLinkDC/dinky#3095]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

如果flinksql中包含空格键，执行会报错
![image](https://github.com/DataLinkDC/dinky/assets/123344357/b6dfa34d-5dd2-46a8-a3dc-6bbd489abcb3)
![image](https://github.com/DataLinkDC/dinky/assets/123344357/53a53ecb-bd34-45fc-9bcb-b87948c16ab2)

### What you expected to happen

正常执行

### How to reproduce

对用户提交的sql脚本进行空格处理

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
This is correct, no spaces should appear here.

**Comment by aiwenmo** [comment]
I have tested the latest code and it is compatible with spaces.
