### ISSUE TITLE
[Bug] [client] While using 'Execute jar with(...) ', the parallelism of the Flink task is still 1, even though I set it to 8 in three ways

### ISSUE THREAD

**Issue by LDA1314** [DataLinkDC/dinky#3103]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Dinky version:dinky-release-1.17-1.0.0-rc4

When I was testing ‘Execution jar with(...)’, I specified the degree of parallelism 8 for the job in three ways,but there was still 1 of the parallelism in operator chain on the Flink Web UI.That is to say,it seems that this configuration parameter doesn't work!
1.set parallelism with dinky suggested

<img width="1508" alt="db67dde900154df6c3066977adae68f" src="https://github.com/DataLinkDC/dinky/assets/107840929/a2e58d0e-1cfe-48ce-a89d-bc0f159acfe1">
ng…]()

2.set parallelism with flink language 'Set'
<img width="479" alt="060c4783bade7d5a837c845a0b5fe16" src="https://github.com/DataLinkDC/dinky/assets/107840929/57d839fa-2159-433b-945d-dda12df4e333">

3.Flink Web UI
<img width="1499" alt="6704e5465097b49976e7c433c367281" src="https://github.com/DataLinkDC/dinky/assets/107840929/04b77a56-bb02-46fb-84c4-ec1d7518da65">

### What you expected to happen

this configuration parameter can work

### How to reproduce

just like what I describe

### Version

1.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
@LDA1314 请规范你的 issue title ,参考 [Issue 须知](http://www.dinky.org.cn/docs/next/developer_guide/contribution/issue), 否则将视为无效 issue

**Comment by zackyoungh** [comment]
Please check if there is a method to set parallelism in your Java code

**Comment by LDA1314** [comment]
> Please check if there is a method to set parallelism in your Java code

Thanks for your reply,in fact, I didn't set any parallelism in my code,usually,it is specified when submitting Flink job.

**Comment by zackyoungh** [comment]
Fixed, wait for the next version to set parallelism on the right side
