### ISSUE TITLE
[Optimization][CDCSOURCE] Issues with using global variables in CDCSOURCE scenarios

### ISSUE THREAD

**Issue by Zzm0809** [DataLinkDC/dinky#3104]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

CDCSOURCE 场景下, 使用全局变量功能,任务发布后,在查看版本历史中,没有将使用到的全局变量进行前置拼接, 与预期不符
但是不影响执行, 此处需要优化

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
After the task is published, all types of tasks will not concatenate global variables, which is correct.
