### ISSUE TITLE
[FAQ] [Alarm instance management] user must be m

### ISSUE THREAD

**Issue by niuhu3** [DataLinkDC/dinky#3125]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

我设置了一个邮箱报警实例，测试的时候报错User must not be null，经过排查发现是前端没有传user参数，后端有这个判断，所以报错

### What you expected to happen

<img width="444" alt="Snipaste_2024-02-01_14-01-06" src="https://github.com/DataLinkDC/dinky/assets/149749618/f8445418-5aea-4cc5-89b3-3ff7a9a0f5d8">

### How to reproduce

<img width="444" alt="Snipaste_2024-02-01_14-01-06" src="https://github.com/DataLinkDC/dinky/assets/149749618/f8445418-5aea-4cc5-89b3-3ff7a9a0f5d8">

前端参数:

{id: 1, name: "email", type: "Email",…}
enabled
: 
true
id
: 
1
name
: 
"email"
params
: 
"{\"receivers\":\"2697603612@qq.com\",\"receiverCcs\":\"2697603612@qq.com\",\"serverHost\":\"hadoop100\",\"serverPort\":\"2697603612@qq.com\",\"sender\":\"二狗子\",\"msgtype\":\"text\"}"
type
: 
"Email"

后端校验: MailSender.java
        mailUser = config.get(EmailConstants.NAME_MAIL_USER);
        requireNonNull(mailUser, EmailConstants.NAME_MAIL_USER + mustNotNull);

### Anything else

no

### Version

0.7.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
你不开认证怎么发送呢 , 开启邮箱验证 填账号和密码
