### ISSUE TITLE
[Feature][admin]When uploading resources to HDFS in the registry center, it can support kerberos authentication

### ISSUE THREAD

**Issue by tzx-xzt** [DataLinkDC/dinky#3127]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

When selecting HDFS for resource configuration, upload resources in the registration center. If HDFS has enabled KerberOS authentication, resource uploading is currently not possible

### Use case

uploading resources to HDFS in the registry center, it can support kerberos authentication

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
There is no environment. If you have this need, you are welcome to contribute, but you need to wait until #3115 is implemented.

**Comment by tzx-xzt** [comment]
I have a cluster environment with Kerberos authentication and I have already tried to implement it based on RC4. I don't know how to contribute it, If my code is workable!

**Comment by Zzm0809** [comment]
> I have a cluster environment with Kerberos authentication and I have already tried to implement it based on RC4. I don't know how to contribute it, If my code is workable!
> 
> 

you can use dev branch to implemented it

**Comment by Zzm0809** [comment]
> I have a cluster environment with Kerberos authentication and I have already tried to implement it based on RC4. I don't know how to contribute it, If my code is workable!

If you don’t know how to contribute, please refer to
http://www.dinky.org.cn/docs/next/developer_guide/contribution/commit_code

**Comment by Zzm0809** [comment]
@tzx-xzt Please contact community members or express your thoughts in the community group
