### ISSUE TITLE
[Bug] Dinky1.0 version DefaultCatalog cannot be used

### ISSUE THREAD

**Issue by ConradWen** [DataLinkDC/dinky#3133]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

问题描述
环境：RockyLinux9.3，Mysql8，Java8，Flink1.17，Dinky1.0 2024-01-01

问题复现步骤:
1. 按照官方部署步骤进行部署，Dinky正常启动并运行，在使用简单SQL进行测试，为了持久化SQL所创建的表，在尝试使用Dinky作业配置时，”FlinkSQL环境“ 选择 DefaultCatalog时无法正常运行
2. 在”FlinkSQL环境“ 选择“禁用”时则无此问题
![image](https://github.com/DataLinkDC/dinky/assets/69459423/67268da9-4489-4a62-8f12-d4b3f73dd1c5)

### What you expected to happen

跟0.7版本一样可以使用DefaultCatalog进行持久化SQL所创建的表

### How to reproduce

希望能使用DefaultCatalog正常持久化SQL所创建的表

### Anything else

官网未见内置DefaultCatalog的文档内容，希望有所补充

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
@ConradWen 请规范你的 issue title

**Comment by Zzm0809** [comment]
1. 问题原因: 分隔符问题 去配置中心-> 全局配置-> flink 配置 -> 分隔符 修改为 ;\n
2. 文档欢迎来贡献

**Comment by aiwenmo** [comment]
Replace ; into ';\n' on sql.
