### ISSUE TITLE
[Bug] [open api] api executeJar missing

### ISSUE THREAD

**Issue by ldwnt** [DataLinkDC/dinky#3149]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

api executeJar not included in v1.0.0.rc4

### What you expected to happen

api executeJar exists as documented in http://www.dinky.org.cn/docs/next/openapi/openapi_overview

### How to reproduce

curl localhost:8888/openapi/executeJar

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ldwnt** [comment]
git checkout branch origin/1.0.0-rc4, there is no endpoint /executeJar in class APIController

**Comment by aiwenmo** [comment]
http://www.dinky.org.cn/docs/next/extend/expand_statements/execute_jar
