### ISSUE TITLE
[Bug] [k8s operator] Application mode jar file path

### ISSUE THREAD

**Issue by RaymondFishWang** [DataLinkDC/dinky#3156]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

我使用k8s operator，需要维护jar文件路径，我编写flinksql, 程序帮我打成jar包发布，我原来写的local:///， 因为现在的项目已经不再使用hdfs ，所以也没有hdfs路径， 后来发现这个路径其实指的是容器内的路径，但是这个pod是系统帮我生成的，所以报错文件不存在，我不确定该如何写这个路径，或者宿主机，或者nfs路径可以找到这个文件

### What you expected to happen

系统可以不使用hdfs路径，并且用flink sql 执行程序

### How to reproduce

如上描述

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by borderf** [comment]
你好，请问这个问题是怎么解决的

**Comment by RaymondFishWang** [comment]
我是重新把要的文件打到了flink的dockerfile中，然后在部署k8s，这样就可以执行了
