### ISSUE TITLE
cat not create a paimon catalog and select a existed table

### ISSUE THREAD

**Issue by xindon** [DataLinkDC/dinky#3166]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

cat not create a paimon catalog and select a existed table

the same sql executed successfully in flink ' s sql client, but error in dinky , like pic

sql：
![Dingtalk_20240219194638](https://github.com/DataLinkDC/dinky/assets/33594102/911b879e-82dc-4e0f-b74e-e0496cd665f0)

error :
![Dingtalk_20240219194901](https://github.com/DataLinkDC/dinky/assets/33594102/8a54a3e8-05c3-4b72-9574-6b008121c0f4)

### What you expected to happen

execute successfully like flink sql-client

### How to reproduce

none

### Anything else

none

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
Please upgrade the rc4 version

**Comment by aiwenmo** [comment]
Upgrade to dinky-1.0.0-rc4
