### ISSUE TITLE
[Feature][dinky-flink] Will version 1.0 support flink 1.13 in the future?

### ISSUE THREAD

**Issue by nianhua99** [DataLinkDC/dinky#3171]
### Search before asking

- [x] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Now, version 1.0 supports Flink versions 1.14-1.18, and we previously used version 0.7 of Dinky and version 1.13 of Flink

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
In dinky version 1.0 and later versions, only up to 5 versions are retained, that is, every time Flink adds a new version, dinky will eliminate one version.

**Comment by nianhua99** [comment]
> 在 dinky 1.0 及之后的版本中，最多只保留 5 个版本，即每次 Flink 添加一个新版本，dinky 都会删除一个版本。

请问我可以自行在dinky-flink模块中把flink 1.13加回来吗

**Comment by nianhua99** [comment]
> In dinky version 1.0 and later versions, only up to 5 versions are retained, that is, every time Flink adds a new version, dinky will eliminate one version.

Can I add flink 1.13 back in the dinky-flink module by myself?

**Comment by Zzm0809** [comment]
> > In dinky version 1.0 and later versions, only up to 5 versions are retained, that is, every time Flink adds a new version, dinky will eliminate one version.
> 
> Can I add flink 1.13 back in the dinky-flink module by myself?

Of course , but you need to develop it yourself and solve a series of problems in the process. You can refer to other sub-modules under the `dinky-flink` module and `dinky-client` module for development.
