### ISSUE TITLE
[Bug] [k8s on application mode] The parameter "--output" option is missing when running in a kubernetes application.

### ISSUE THREAD

**Issue by zhaoxunyong** [DataLinkDC/dinky#3173]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

The parameter "--output" of the latest version  is missing when running in a kubernetes application mode. 

I found this option in the version 0.7.5 version, but cannot find this in the latest version:

The screenshot is 0.7.5 version, as follows:
![image](https://github.com/DataLinkDC/dinky/assets/8733266/424115de-b194-4fe9-8cd5-bcc27c3fb814)

### What you expected to happen

I hope I can pass --output to kubernetes application mode, but I have no idea how to pass this parameter. Like the following command:

bin/flink run-application \
 --target kubernetes-application \
 -Dkubernetes.namespace=flink \
 ...
 local:///opt/flink/usrlib/TopSpeedWindowing.jar \
**_--output /opt/flink/log/topSpeedWindowing-output_**

### How to reproduce

Running a job in Kubernetes Native Application Mode via Dinky Web UI.

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
This feature has been refactored in version 1.0
