### ISSUE TITLE
[Bug][cdcsource]cdc source creates containers that consume all the memory in the Yarn cluster

### ISSUE THREAD

**Issue by scottxing** [DataLinkDC/dinky#3176]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Simply put, when submitting from `cdcsource mysql` to `print` with `yarn session`, it continuously creates containers that consume all the memory in the Yarn cluster, and the two operators remain in the `created` state for a long time without progressing to the `running` state; however, when submitted as a `yarn application`, it operates normally.

### What you expected to happen

Simply put, when submitting from `cdcsource mysql` to `print` with `yarn session`, it continuously creates containers that consume all the memory in the Yarn cluster, and the two operators remain in the `created` state for a long time without progressing to the `running` state; however, when submitted as a `yarn application`, it operates normally.

### How to reproduce

submitting from `cdcsource mysql2print` with `yarn session`
```sql
EXECUTE CDCSOURCE mysql2print WITH (
  'connector' = 'mysql-cdc',
  'hostname' = '192.168.3.53',
  'port' = '3306',
  'username' = 'root',
  'password' = '123456',
  'checkpoint' = '10000',
  'scan.starup.mode' = 'initial',
  'parallelism' = '1',
  'table-name' = 'demo\.order',
  'sink.connector' = 'print'
);
```

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
@scottxing 请规范你的 issue title , 否则将视为无效 issue

**Comment by aiwenmo** [comment]
Check the JobManager logs to find the reason, it may be due to unreasonable resource allocation.
