### ISSUE TITLE
[Feature][admin,web] New homepage platform to data map and statistical information

### ISSUE THREAD

**Issue by aiwenmo** [DataLinkDC/dinky#319]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

New homepage platform to data map and statistical information

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leeoo** [comment]
这个页面会不会包含微信2群里讨论的”采集/同步数据量“？或者另外做一个 Dashboard 页面（类似下图），统计这类信息？
![图片](https://user-images.githubusercontent.com/2136182/191649440-45ef171d-d756-4b8f-b4f2-fbf99a86a44f.png)
![图片](https://user-images.githubusercontent.com/2136182/191649616-3655405d-54c0-436b-b363-e04e01f9bbcc.png)

**Comment by aiwenmo** [comment]
#2030
