### ISSUE TITLE
[Bug] There is no task when deploying yarn-application in jar package mode and running it.

### ISSUE THREAD

**Issue by lliuql** [DataLinkDC/dinky#3194]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

`EXECUTE JAR WITH (
'uri'='rs:///flink_hello-1.0-SNAPSHOT.jar',
'main-class'='org.liu.StreamWordCount',
'parallelism'='1');`
用applicaiton运行jar包后，提示部署成功
`
2024-02-28 13:35:32.614 INFO  org.apache.flink.yarn.YarnClusterDescriptor(1136): YARN application has been deployed successfully.
2024-02-28 13:35:32.614 INFO  org.apache.flink.yarn.YarnClusterDescriptor(1688): Found Web Interface hadoop167:38618 of application 'application_1709022070519_0014'.
2024-02-28 13:36:03.139 INFO  org.dinky.service.impl.TaskServiceImpl(190): execute job finished,status is SUCCESS
Process Step SUBMIT_EXECUTE exit with status:FINISHED
`
运维中心没有任务：
![image](https://github.com/DataLinkDC/dinky/assets/12395527/2aeaed98-f0b1-4f72-8291-0972f4ef218d)

yarn启动了容器：
![image](https://github.com/DataLinkDC/dinky/assets/12395527/1d8f1b0f-3db6-4d14-8ca0-762f9202980e)

但是flink没有任何任务：
![image](https://github.com/DataLinkDC/dinky/assets/12395527/2e5de3e5-5447-48b7-8ae3-5b7de42c0bb9)

### What you expected to happen

应该能够在运维中心找到任务。且flink应该有任务

### How to reproduce

jar包的内容
`
public class StreamWordCount {
    public static void main(String[] args) throws Exception {
        // 1. 创建流式执行环境
        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        // 2. 读取文本流：hadoop102表示发送端主机名、7777表示端口号
        DataStreamSource<String> lineStream = env.socketTextStream("hadoop165", 7777);

        // 3. 转换、分组、求和，得到统计结果
        SingleOutputStreamOperator<Tuple2<String, Long>> sumStream = lineStream.flatMap(new FlatMapFunction<String, Tuple2<String, Long>>() {
            @Override
            public void flatMap(String line, Collector<Tuple2<String, Long>> out) throws Exception {
                String[] words = line.split(" ");
                for (String word : words) {
                    out.collect(Tuple2.of(word, 1L));
                }
            }
        }).keyBy(new KeySelector<Tuple2<String, Long>, Object>() {
            @Override
            public Object getKey(Tuple2<String, Long> data) throws Exception {
                return data.f0;
            }
        }).sum(1);
        // 4. 打印
        sumStream.print();

        // 5. 执行
        env.execute();

    }

}
pom内容：
`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.liu</groupId>
    <artifactId>flink_hello</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <flink.version>1.17.0</flink.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-streaming-java</artifactId>
            <version>${flink.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-clients</artifactId>
            <version>${flink.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <artifactSet>
                                <excludes>
                                    <exclude>com.google.code.findbugs:jsr305</exclude>
                                    <exclude>org.slf4j:*</exclude>
                                    <exclude>log4j:*</exclude>
                                </excludes>
                            </artifactSet>
                            <filters>
                                <filter>
                                    
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <transformers combine.children="append">
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer">
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
`

`

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
无法复现
