### ISSUE TITLE
Unable to start dinky, java.lang.ClassNotFoundException: org.dinky.Dinky Exception occurred.

### ISSUE THREAD

**Issue by MarkZeng222** [DataLinkDC/dinky#3208]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

执行sh auto.sh start后，
powershell显示：
........................................Start Dinky Successfully........................................
(base) PS D:\dlink\dinky-release-1.18-1.0.0-rc4> nohup: appending output to 'nohup.out'

日志显示如下：
Java HotSpot(TM) 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
错误: 找不到或无法加载主类 org.dinky.Dinky
原因: java.lang.ClassNotFoundException: org.dinky.Dinky

结果dinky无法启动

### What you expected to happen

启动Dinky

### How to reproduce

在powershell 中 执行sh auto.sh start

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
jdk 13 is not supported. Currently, jdk11 and jdk 8 can be fully adapted.

**Comment by MarkZeng222** [comment]
@Zzm0809 
当前使用的是Java 1.8
(base) PS D:\dlink\dinky-release-1.18-1.0.0-rc4> java -version
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)
