### ISSUE TITLE
dinky1.0mysql file import problem

### ISSUE THREAD

**Issue by lyl1230** [DataLinkDC/dinky#3221]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I deployed the dinky1.0 version and imported the dinkymysql file, an error occurred: 
    ERROR 1170 (42000) at line 1689: BLOB/TEXT column 'full_name' used in key specification without a key length
   
![image](https://github.com/DataLinkDC/dinky/assets/151730895/9cd38ebb-5d74-4c73-a26e-44efa8926928)

### What you expected to happen

mysql file

### How to reproduce

imported the dinky1.0 mysql file

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
It has been hot-fixed. Please wait for a while and then download the realease package again.
