### ISSUE TITLE
[Bug] [function] NullPointerException occurs when creating udf function

### ISSUE THREAD

**Issue by lyl1230** [DataLinkDC/dinky#3236]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I use dinky1.0 version to create a udf task, a null pointer error occurs regardless of java/scala/python.
![image](https://github.com/DataLinkDC/dinky/assets/151730895/f3bc96b3-6edc-44b0-8faf-4c260b40f63e)

### What you expected to happen

Tasks can be created normally

### How to reproduce

dinky1.0 creates udf task

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
fixed, #3225

**Comment by lyl1230** [comment]
Do I need to pull the dev package or download the release version?

**Comment by Zzm0809** [comment]
> Do I need to pull the dev package or download the release version?

If you need to use the latest one now, you need to use the `dev` branch for packaging. Please refer to the `Compile and Deployment` chapter on the official website.
If you are not in a hurry, please wait for the 1.0.1 realease version

**Comment by lyl1230** [comment]
okky, thanks
