### ISSUE TITLE
[Bug] [k8a app] Global variable read failure on k8s app mode

### ISSUE THREAD

**Issue by zhengtingxue** [DataLinkDC/dinky#3241]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Global variable read failure on k8s app mode

### What you expected to happen

Global variable read failure on k8s app mode

### How to reproduce

Global variable read failure on k8s app mode

### Version

1.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Similar to #3206
