### ISSUE TITLE
[Optimization] [CDCSOURCE] The database name contains a string - the entire database cannot be synchronized

### ISSUE THREAD

**Issue by lliuql** [DataLinkDC/dinky#3242]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/DataLinkDC/dinky/assets/12395527/fc47f117-96e6-44f7-a50f-062f1cef07d9)

### What you expected to happen

带字符串-会导致同步不了。

### How to reproduce

EXECUTE CDCSOURCE cdc_mysql WITH (
 'connector' = 'mysql-cdc',
 'hostname' = 'rm-xxxxxxxx',
 'port' = '3306',
 'username' = 'root',
 'password' = 'xxx-xxxx',
 'checkpoint' = '3000',
 'scan.startup.mode' = 'initial',
 'parallelism' = '1',
 'database-name' = 'middle-platform',
  'table-name' = 'middle-platform\.blade_client,middle-platform\.blade_dept',
 'sink.connector' = 'jdbc',
 'sink.url' = 'jdbc:mysql://120.0.0.1:3306/middle-platform?characterEncoding=utf-8&useSSL=false',
 'sink.username' = 'root',
 'sink.password' = 'x-x',
 'sink.sink.db' = 'middle-platform',
 'sink.table.prefix' = '',
 'sink.table-name' = '#{tableName}',
 'sink.driver' = 'com.mysql.cj.jdbc.Driver',
 'sink.sink.buffer-flush.interval' = '2s',
 'sink.sink.buffer-flush.max-rows' = '100',
 'sink.sink.max-retries' = '5',
 'sink.auto.create' = 'true'
)

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
Normally, with - is not in compliance with the specification, and is not supported by flinkcdc.

**Comment by Zzm0809** [comment]
Perhaps you can do some compatibility processing at the code level when building the entire library to synchronize ddl, such as adding `` backticks.

**Comment by Zzm0809** [comment]
已修复
