### ISSUE TITLE
[Bug] [k8s app] submit job with k8s app ha mode,flink have the same jobid,submit and cancle job throw error

### ISSUE THREAD

**Issue by zhengtingxue** [DataLinkDC/dinky#3244]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

submit job with k8s app ha mode,flink have the same jobid,like 0000000006924de00000000000000000;submit job throw error  "Duplicate entry 'test20000000006924de00000000000000000-1' for key 'cluster_un_idx1'" when the old flink instance still exists,and cancle job throw error "Expected one result (or null) to be returned by selectOne(), but found: 5"  because of the same id;

### What you expected to happen

submit job and cancle job work well

### How to reproduce

submit job with k8s app ha mode,

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
mysql表内可以试着取消name唯一约束，这个不影响任务，后续会修复此问题
