### ISSUE TITLE
[Improvement] The method of getting the first value of an element uses get(0) and needs to be optimized.

### ISSUE THREAD

**Issue by Zzm0809** [DataLinkDC/dinky#3280]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

The method to obtain the first value of an element uses get(0). There may be situations where the array goes out of bounds when the data is empty. It needs to be optimized to increase its robustness.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
#3279
