### ISSUE TITLE
[Bug] [SsesessionContextHolder] Error sending sse data:java.io.I0Exception: Broken pipe

### ISSUE THREAD

**Issue by mc123h** [DataLinkDC/dinky#3286]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

After I finished modifying the SQL and clicked to run it, the UI displayed a crash page.
<img width="931" alt="image" src="https://github.com/DataLinkDC/dinky/assets/37317325/11a874cc-e4b9-4de1-95ad-123ba0c34895">

### What you expected to happen

log：
start Process:Flinksubmit/24
Start Process Step:SUBMIT_PRECHECK
2024-03-13 15:44:52.992 ERROR org.dinky.context.SsesessionContextHolder(166): Error sending sse data:java.io.I0Exception: Broken pipe
2024-03-13 15:44:52.999 INF0 org.dinky.Service.impl.TaskserviceImpl(175): start check and config task, task:inmaininfo2hudi
Process step sUBMIT_PRECHECK exit with status:FINISHED
Start Process Step:SUBMIT_EXEcUTE
Start Process Step:SUBMIT_BUILD_CONFIG
2024-03-1315:44:53.002INF0
org.dinky.service.impl.TaskserviceImpl(284): Start initialize FlinksqLEnv:
2024-03-1315:44:53.003INF0
org.dinky.service.impl.TaskserviceImpl(3e4): Initializing data permissions,
2024-03-13 15:44:53. 003 ERROR org. dinky.context.5sesessionContextHolder(132) : Type: Ssesession [4309ceb4-ac87-4081-80fd-b6b89e807973]
Error, Message: java.io.IoException: Broken pipe
2024-03-13 15:44:53.008 INF0
org.dinky.service.impl.TaskserviceImpl(3a6): Finish initialize FlinksqLEnv.
org.dinky.service.impl.TaskseryiceImpl(22l) : Init gateway config,

### How to reproduce

The probability of encountering this issue is higher when you click on "Run" after modifying the SQL without saving it, as it automatically saves the changes before execution.

### Version

1.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
What's your sql?

**Comment by mc123h** [comment]
I am using the SQL on the official page.I don't think this issue is related to SQL.
https://dinky.org.cn/docs/next/user_guide/studio/all_task_devlop

**Comment by Zzm0809** [comment]
无法复现 请在 demo 环境下使用 LOCAL 模式 试着能否复现

**Comment by mc123h** [comment]
After using version 1.0.1, the issue was fixed
