### ISSUE TITLE
[Optimization] parameter configuration does not take effect

### ISSUE THREAD

**Issue by zfz748** [DataLinkDC/dinky#3293]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

Hadoop3.3.6    flink1.17   作业执行模式为perjob

配置情况：
checkpoint Interval这个配置没有在 set、 右侧配置  、集群配置这三个地方配置，只在flink 配置文件中有，但是我在右侧配置加了其他配置项，flink-conf.yaml文件里配置了checkpoint Interval是3分钟，flink webui和dinky两边配置显示不一样，flink webui显示为3min，作业没有checkpoint产生，

尝试：
尝试在集群配置里配置没有生效，在数据开发的右侧配置上配置后生效了

感觉配置和任务执行模式没关系，能感受到从高到低的优先级配置，只是感觉配置没有从高到低进行覆盖和拼接，使用起来有点儿不大方便

<img width="1278" alt="4cfeec33a7bece07e01e44d8a92b45f" src="https://github.com/DataLinkDC/dinky/assets/73456708/b1063332-c4d8-41f6-89ac-ec9812196503">
<img width="1281" alt="5ecfe4e09ad854156ce71dacba2a481" src="https://github.com/DataLinkDC/dinky/assets/73456708/318dd297-f80f-49d9-bd09-4bcf1f60bb51">

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
hi @zfz748 Have you finished this pr?

**Comment by Zzm0809** [comment]
无法复现
