### ISSUE TITLE
[Bug] [Module Name] why the executeSql method in the Api controller was removed in version 1.0.0 ?

### ISSUE THREAD

**Issue by qunincey** [DataLinkDC/dinky#3300]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Can you tell me why the executeSql method in the Api controller was removed in version 1.0.0. I have always used dinky as the base setup for data synchronization, using executeSql to complete the interaction between the original big data service and dinky. I generate the corresponding sql in advance and submit it to dinky via api, if there is a better way to integrate with dinky, please let me know!

### What you expected to happen

none

### How to reproduce

none

### Anything else

none

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
现在只支持调用/执行 dinky 中定义的任务

**Comment by qunincey** [comment]
> 现在只支持调用/执行 dinky 中定义的任务

能说一下这样做的目的是什么吗？后续有增加接口的计划吗

**Comment by Zzm0809** [comment]
> > 现在只支持调用/执行 dinky 中定义的任务
> 
> 能说一下这样做的目的是什么吗？后续有增加接口的计划吗

增加接口的前提同样是针对在 dinky平台内定义的任务

**Comment by Pandas886** [comment]
> > 现在只支持调用/执行 dinky 中定义的任务
> 
> 能说一下这样做的目的是什么吗？后续有增加接口的计划吗

是否可以将sql通过接口创建dinky的任务，然后再调用执行

**Comment by qunincey** [comment]
> > > 现在只支持调用/执行 dinky 中定义的任务
> > 
> > 
> > 能说一下这样做的目的是什么吗？后续有增加接口的计划吗
> 
> 是否可以将sql通过接口创建dinky的任务，然后再调用执行

估计是不再支持了，之后只能基于dinky做二开了或者就是自己加一个接口了，而不能单纯当成一个中间件来用了。
