### ISSUE TITLE
[Bug] The tasks submitted by Yarn Per Job cannot be queried in version 1.0.1

### ISSUE THREAD

**Issue by miaoze8** [DataLinkDC/dinky#3304]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Yarn Per Job递交的任务无法在运维中心查看以及无法在数据开发页面正确获取运行状态

使用官网文档demo代码测试https://www.dlink.top/docs/next/practical_guide/Integration_practice/dinky_integration_flink#datagen-%E4%BB%BB%E5%8A%A1-demo

yarn session任务递交后 可以在运维中心查看    刷新数据开发页面后点击任务也能正确获取任务当前状态
<img width="1214" alt="yarnsession" src="https://github.com/DataLinkDC/dinky/assets/3348537/10897dea-19bf-4280-ac37-165827850753">
yarn perjob任务递交后  不可以在运维中心查看    刷新数据开发页面后点击任务不能正确获取任务当前状态  返回 null
<img width="1004" alt="perjob" src="https://github.com/DataLinkDC/dinky/assets/3348537/52a2a1d5-89ef-4914-838c-037f3da8c547">

![运维中心-yarnperjob](https://github.com/DataLinkDC/dinky/assets/3348537/0774c0c3-59c5-45f8-9482-71b934afcc3f)
![运维中心-yarnsession](https://github.com/DataLinkDC/dinky/assets/3348537/6fa1b390-7f84-4523-b8cb-f153d1f4e4ac)
注册中心  可看到2个任务都正常
![注册中心](https://github.com/DataLinkDC/dinky/assets/3348537/9316e298-1e04-4b10-9765-12c3000a5aa9)
点击yarn per job任务也能看到flink界面确定任务执行正常
![注册中心可看到yarnperjob](https://github.com/DataLinkDC/dinky/assets/3348537/a0adc767-4850-432b-819c-7b7fbf76f3a4)

### What you expected to happen

Yarn Per Job递交的任务在运维中心可查看以及在数据开发页面正确获取运行状态

### How to reproduce

1.0.1版本
使用官网文档demo代码测试https://www.dlink.top/docs/next/practical_guide/Integration_practice/dinky_integration_flink#datagen-%E4%BB%BB%E5%8A%A1-demo

创建一个 yarn session 任务   再创建另一个 yarn per job任务   然后运行

在运维中心就无法查看到  yarn per job任务

在数据开发页面刷新后，重新点击到yarn per job任务  发现任务还是未运行状态1.0.1版本

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
无法复现
