### ISSUE TITLE
[Bug] [udf on k8s app] error when add udf jar on k8s app mode

### ISSUE THREAD

**Issue by zhengtingxue** [DataLinkDC/dinky#3312]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![1c06dad6f6994042faaad35d9585071](https://github.com/DataLinkDC/dinky/assets/19706871/5007ae5a-419a-4bfa-97e0-8318dbabc796)
![d14b04f0c77e553771e68c062a6a558](https://github.com/DataLinkDC/dinky/assets/19706871/69aa880d-6b3f-4c86-82d1-4b7b288393e5)

### What you expected to happen

work fine

### How to reproduce

1. flink sql on k8s app mode,dinky1.0.1
2. set execution.checkpointing.interval=60sec;
set taskmanager.memory.process.size=1024m;
set jobmanager.memory.process.size=1024m;
ADD jar   'rs:/jobjars/original-flinksqludf-0.0.1-SNAPSHOT.jar';
create temporary system function hello_udf as 'com.gszq.flinksqludf.HelloUdf';

use set and add jar together,submit job then throw error

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
this is flink bug，remove checkpoint set
