### ISSUE TITLE
[Bug] [Catalog] Data development FlinkSQL environment selects catalog, which is inconsistent with the catalog name in the catalog drop-down.

### ISSUE THREAD

**Issue by hawk9821** [DataLinkDC/dinky#3317]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

数据开发FlinkSQL环境选择catalog，与catalog下拉中的catalog名称不一致。

### What you expected to happen

数据开发页面查询calalog接口返回名称的名称应从数据库中获取之前创建的FlinkSQLENV 的任务名称

### How to reproduce

![image](https://github.com/DataLinkDC/dinky/assets/39961809/92bd9b58-79b6-414d-ad19-bc7e435f0143)

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
此 catalog 非彼 catalog
