### ISSUE TITLE
[Bug] [savepoints] CDC SOURCE The operator graph generated by each submission task is inconsistent, resulting in the failure to restore the old and new serialization of the savepoints.

### ISSUE THREAD

**Issue by tttzzzwww** [DataLinkDC/dinky#3318]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

采用的是dlink本身的提交流程，提交SQL未发生变化，算子不应该出现问题才对
早期测试：
两张表同步任务这样操作是可以正常恢复
使用3张表提交记录保存点，再恢复不行，尝试等待10分钟后记录保存点并取消任务，依然恢复失败
**中间没有多加或者少表步骤，只是测试的表数量不一样，但恢复的保存点记录操作表是一样的**

**后续测试：
2张表不一定百分比成功，除非恢复任务生成的算子图跟上次提交的算子图一致才能成功，否则失败
结论：若多表的情况下， 执行任务和恢复任务生成的算子图顺序的排列组合越来越多，每次生成算子图表的顺序一致的概率会大大降低，导致按保存点恢复任务成功的概率很少**

confProperties["execution.savepoint.path"] = “file:/tmp/flink/savepoints/savepoint-7a7365-ef55ca3e1604” 恢复任务，提示：
`Caused by: org.apache.flink.runtime.state.BackendBuildingException: Caught unexpected exception.
	at org.apache.flink.contrib.streaming.state.RocksDBKeyedStateBackendBuilder.build(RocksDBKeyedStateBackendBuilder.java:409)
	at org.apache.flink.contrib.streaming.state.EmbeddedRocksDBStateBackend.createKeyedStateBackend(EmbeddedRocksDBStateBackend.java:505)
	at org.apache.flink.contrib.streaming.state.EmbeddedRocksDBStateBackend.createKeyedStateBackend(EmbeddedRocksDBStateBackend.java:98)
	at org.apache.flink.streaming.api.operators.StreamTaskStateInitializerImpl.lambda$keyedStatedBackend$1(StreamTaskStateInitializerImpl.java:336)
	at org.apache.flink.streaming.api.operators.BackendRestorerProcedure.attemptCreateAndRestore(BackendRestorerProcedure.java:168)
	at org.apache.flink.streaming.api.operators.BackendRestorerProcedure.createAndRestore(BackendRestorerProcedure.java:135)
	... 13 more
Caused by: org.apache.flink.util.StateMigrationException: The new key serializer (org.apache.flink.table.runtime.typeutils.RowDataSerializer@58a0d672) must be compatible with the previous key serializer (org.apache.flink.table.runtime.typeutils.RowDataSerializer@24d).
	at org.apache.flink.contrib.streaming.state.restore.RocksDBIncrementalRestoreOperation.readMetaData(RocksDBIncrementalRestoreOperation.java:549)
	at org.apache.flink.contrib.streaming.state.restore.RocksDBIncrementalRestoreOperation.readMetaData(RocksDBIncrementalRestoreOperation.java:516)
	at org.apache.flink.contrib.streaming.state.restore.RocksDBIncrementalRestoreOperation.restoreFromLocalState(RocksDBIncrementalRestoreOperation.java:232)
	at org.apache.flink.contrib.streaming.state.restore.RocksDBIncrementalRestoreOperation.restoreFromRemoteState(RocksDBIncrementalRestoreOperation.java:222)
	at org.apache.flink.contrib.streaming.state.restore.RocksDBIncrementalRestoreOperation.restoreWithoutRescaling(RocksDBIncrementalRestoreOperation.java:189)
	at org.apache.flink.contrib.streaming.state.restore.RocksDBIncrementalRestoreOperation.restore(RocksDBIncrementalRestoreOperation.java:169)
	at org.apache.flink.contrib.streaming.state.RocksDBKeyedStateBackendBuilder.build(RocksDBKeyedStateBackendBuilder.java:329)
	... 18 more
2024-03-22 11:11:17,318 INFO  org.apache.flink.runtime.dispatcher.StandaloneDispatcher     [] - Job c3664a9c7786cfc963452fec76db7928 has been registered for cleanup in the JobResultStore after reaching a terminal state.`

submit FlinkSQL：
EXECUTE CDCSOURCE jira.TY002-JIRA-SDI2_2TEST_ODS_JIRA.TY999-DW WITH (
   'connector' = 'mysql-cdc',
   'hostname' = '192.168.10.171',
   'port' = '3336',
   'username' = 'read_jira',
   'password' = 'xxxxxx',
   'database-name' = 'jira',
   'parallelism' = '1',
   'checkpoint' = '300000',
   'scan.startup.mode' = 'latest-offset',
   'table-name' = 'jira\.jiraaction,jira\.fileattachment,jira\.issuestatus,jira\.jiraissue,jira\.label,jira\.issuetype,jira\.project',
   'sink.table.prefix' = 'ODS_',
   'sink.table-name' ='SDI2_2TEST_ODS_JIRA.${tableName}',
   'sink.connector' = 'jdbc',
   'sink.url' = 'jdbc:oracle:thin:@//192.168.10.161:1521/dev',
   'sink.username' = 'zt_2_2_test',
   'sink.password' = 'xxxxxx')

### What you expected to happen

本地测试使用LocalStreamExecutor方式提交并记录保存点文件，再恢复没有问题，而远程RemoteStreamExecutor对象记录的保存点失败，按理说本地可以说明算子本身没有发生变化，不应该失败才对，辛苦作者帮忙看下或者有没有遇到相似的问题

### How to reproduce

以当前时间提交任务，然后调用flink restAPI记录保存点并取消任务，这时候存储数据状态的rocksb文件会被自动dispose掉，保存点仅.metadata文件，再配置：confProperties["execution.savepoint.path"] = executionSavepointPath 即可复现

### Version

0.7.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
加一个表 算子图就变了 肯定无法恢复, 需要指定参数

**Comment by tttzzzwww** [comment]
不好意思，我描述错了，不是加一张表，在测试的过程中，表的数量是没有发现变化，只是一套流程，同步两张表记录的保存点文件可以正常恢复取消后的任务，但如果测试改成：3张表先提交后记录保存点，再根据记录的保存点提交，则提示序列化失败，但整个过程不管是2张还是3张表，流程中表的数量从一开始就固定了，若表数量发生变化，我会重新生成保存点文件恢复

**Comment by tttzzzwww** [comment]
不过在您的提醒下，我刚刚查看了生成的算子图，例如：同步表jira\.jiraaction,jira\.fileattachment,jira\.issuestatus,jira\.jiraissue,jira\.label,jira\.issuetype,jira\.project,首次提交生成的算子图顺序是

![首次提交任务图](https://github.com/DataLinkDC/dinky/assets/142898753/038c5254-e761-490f-a3e0-0451d7db143d)

根据保存点恢复的算子图
![失败任务图](https://github.com/DataLinkDC/dinky/assets/142898753/ece15ea8-2de8-489c-87e5-3ffa744cfe6a)

虽然表是一样的，但算子图下方的表的顺序不一致

**Comment by tttzzzwww** [comment]
根据算子图顺序测试，两张表能够成功恢复的概率不是100%，因为两张表排列组合只有2种情况，每次提交的算子图顺序一致概率是50%，一旦超过2张表进行同步，其生成的算子图顺序情况将会递增，也就导致正常恢复的概率很小
结论：无法通过保存点恢复的原因是，内部生成的算子图不是按照SQL指定的表的顺序进行生成

**Comment by tttzzzwww** [comment]
大哥，这个参数可以控制算子图每次生成的顺序按指定同步表生成吗

**Comment by tttzzzwww** [comment]
根据源码分析，dlink内部在sink表时，是先获取指定schema下所有表，然后内部match同步的表，这里不用同步的表去匹配同步的表，是因为要支持正则匹配同步的表，导致每次生成的算子图顺序不一致
我看了下 ExecutorSetting对象可以支持savepointPath入参，但指定了路径，而不指定execution.savepoint.path，提交后保存点没有生效，我尝试入参和恢复保存点路径**都指定**，提交任务后保存点**成功恢复**且每次提交生成的**算子图一致**，例如：

HashMap<String, String> tableConf = new HashMap<>();
tableConf.put("execution.savepoint.path", "file:///tmp/flink/savepoints/savepoint-d031e7-a02abd60af81");
String savepointPath = "file:///tmp/flink/savepoints/savepoint-d031e7-a02abd60af81";
ExecutorSetting executorSetting = new ExecutorSetting(3000, 1, false, false, false, savepointPath, testJobName, tableConf);
Executor executor = new RemoteStreamExecutor(eEnvironmentSetting, executorSetting);

本地测试这块代码通过，具体问题还需要进一步研究下ExecutorSetting对象入参保存点内部到底做了什么操作以及为什么指定后算子图每次顺序一致

**Comment by tttzzzwww** [comment]
经过研究算子图生成源码，发现dlink内部是hashmap无序存储同步的表，每次生成的算子图必然无序，而且即使改成有序存储，dlink内部是支持正则匹配同步的表的，例如：${schema}.*，也就意味着无法保证每次生成的算子图顺序是一致的，尝试改了下源码，测试无正则的情况下是没有问题的，每次生成的算子图也是一致，但这解决不了根本原因，这里有点难啃......
![按照同步表顺序生成算子图](https://github.com/DataLinkDC/dinky/assets/142898753/38418a60-2314-4fe9-a493-15b74d8c3602)

**Comment by Zzm0809** [comment]
> 经过研究算子图生成源码，发现dlink内部是hashmap无序存储同步的表，每次生成的算子图必然无序，而且即使改成有序存储，dlink内部是支持正则匹配同步的表的，例如：${schema}.*，也就意味着无法保证每次生成的算子图顺序是一致的，尝试改了下源码，测试无正则的情况下是没有问题的，每次生成的算子图也是一致，但这解决不了根本原因，这里有点难啃...... ![按照同步表顺序生成算子图](https://private-user-images.githubusercontent.com/142898753/316080101-38418a60-2314-4fe9-a493-15b74d8c3602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMjI5MzgsIm5iZiI6MTcxMTEyMjYzOCwicGF0aCI6Ii8xNDI4OTg3NTMvMzE2MDgwMTAxLTM4NDE4YTYwLTIzMTQtNGZlOS1hNDkzLTE1Yjc0ZDhjMzYwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxNTUwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjNkZGMzMzI0OWZkNWI4MzRlNTBhYWNiOGYyYjA1YzgyZTA3NTU3OTYyODQwNjZlYmFiY2Q2NzYwNmM0ZjEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._SxeII7iKOBL088w6imjiZjhiqKMyJIOXin8zTapmJE)

正则匹配之后进行一次排序呢?

**Comment by tttzzzwww** [comment]
> > 经过研究算子图生成源码，发现dlink内部是hashmap无序存储同步的表，每次生成的算子图必然无序，而且即使改成有序存储，dlink内部是支持正则匹配同步的表的，例如：${schema}.*，也就意味着无法保证每次生成的算子图顺序是一致的，尝试改了下源码，测试无正则的情况下是没有问题的，每次生成的算子图也是一致，但这解决不了根本原因，这里有点难啃...... ![按照同步表顺序生成算子图](https://private-user-images.githubusercontent.com/142898753/316080101-38418a60-2314-4fe9-a493-15b74d8c3602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMjI5MzgsIm5iZiI6MTcxMTEyMjYzOCwicGF0aCI6Ii8xNDI4OTg3NTMvMzE2MDgwMTAxLTM4NDE4YTYwLTIzMTQtNGZlOS1hNDkzLTE1Yjc0ZDhjMzYwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxNTUwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjNkZGMzMzI0OWZkNWI4MzRlNTBhYWNiOGYyYjA1YzgyZTA3NTU3OTYyODQwNjZlYmFiY2Q2NzYwNmM0ZjEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._SxeII7iKOBL088w6imjiZjhiqKMyJIOXin8zTapmJE)
> 
> 正则匹配之后进行一次排序呢?

这个办法可以，直接对最终匹配的结果集合排序，这样就不用关心中间处理的流程，源码位置：
![结果集排序](https://github.com/DataLinkDC/dinky/assets/142898753/9555065b-4867-4ecd-9def-62f13f6cb32a)

**Comment by Zzm0809** [comment]
> > > 经过研究算子图生成源码，发现dlink内部是hashmap无序存储同步的表，每次生成的算子图必然无序，而且即使改成有序存储，dlink内部是支持正则匹配同步的表的，例如：${schema}.*，也就意味着无法保证每次生成的算子图顺序是一致的，尝试改了下源码，测试无正则的情况下是没有问题的，每次生成的算子图也是一致，但这解决不了根本原因，这里有点难啃...... ![按照同步表顺序生成算子图](https://private-user-images.githubusercontent.com/142898753/316080101-38418a60-2314-4fe9-a493-15b74d8c3602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMjI5MzgsIm5iZiI6MTcxMTEyMjYzOCwicGF0aCI6Ii8xNDI4OTg3NTMvMzE2MDgwMTAxLTM4NDE4YTYwLTIzMTQtNGZlOS1hNDkzLTE1Yjc0ZDhjMzYwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxNTUwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjNkZGMzMzI0OWZkNWI4MzRlNTBhYWNiOGYyYjA1YzgyZTA3NTU3OTYyODQwNjZlYmFiY2Q2NzYwNmM0ZjEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._SxeII7iKOBL088w6imjiZjhiqKMyJIOXin8zTapmJE)
> > 
> > 正则匹配之后进行一次排序呢?
> 
> 这个办法可以，直接对最终匹配的结果集合排序，这样就不用关心中间处理的流程，源码位置：
> ![结果集排序](https://github.com/DataLinkDC/dinky/assets/142898753/9555065b-4867-4ecd-9def-62f13f6cb32a)
> 

可以改下代码测试一下，看一下构建结果是否与预期一致，以及savepoint是否与预期一致。同时欢迎贡献该优化点

**Comment by tttzzzwww** [comment]
> > > > 经过研究算子图生成源码，发现dlink内部是hashmap无序存储同步的表，每次生成的算子图必然无序，而且即使改成有序存储，dlink内部是支持正则匹配同步的表的，例如：${schema}.*，也就意味着无法保证每次生成的算子图顺序是一致的，尝试改了下源码，测试无正则的情况下是没有问题的，每次生成的算子图也是一致，但这解决不了根本原因，这里有点难啃...... ![按照同步表顺序生成算子图](https://private-user-images.githubusercontent.com/142898753/316080101-38418a60-2314-4fe9-a493-15b74d8c3602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMjI5MzgsIm5iZiI6MTcxMTEyMjYzOCwicGF0aCI6Ii8xNDI4OTg3NTMvMzE2MDgwMTAxLTM4NDE4YTYwLTIzMTQtNGZlOS1hNDkzLTE1Yjc0ZDhjMzYwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxNTUwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjNkZGMzMzI0OWZkNWI4MzRlNTBhYWNiOGYyYjA1YzgyZTA3NTU3OTYyODQwNjZlYmFiY2Q2NzYwNmM0ZjEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._SxeII7iKOBL088w6imjiZjhiqKMyJIOXin8zTapmJE)
> > > 
> > > 
> > > 正则匹配之后进行一次排序呢?
> > 
> > 
> > 这个办法可以，直接对最终匹配的结果集合排序，这样就不用关心中间处理的流程，源码位置：
> > ![结果集排序](https://private-user-images.githubusercontent.com/142898753/316213816-9555065b-4867-4ecd-9def-62f13f6cb32a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDE1MjksIm5iZiI6MTcxMTcwMTIyOSwicGF0aCI6Ii8xNDI4OTg3NTMvMzE2MjEzODE2LTk1NTUwNjViLTQ4NjctNGVjZC05ZGVmLTYyZjEzZjZjYjMyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQwODMzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjI4YWIzYWEwZjY5ZGJjNDExMTEzMzZhZGFhNWJmYTkyZjFhZGVlNGVjMzlhZmNlMmJmODljNTA1M2YxODdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YbYw1ICh4xdPcozVLrLjZzT8aq1dr-1YOpbuytRqXbA)
> 
> 可以改下代码测试一下，看一下构建结果是否与预期一致，以及savepoint是否与预期一致。同时欢迎贡献该优化点

目前测试是没问题的，源码修改不多，就增加了排序，如下：
![修改差异](https://github.com/DataLinkDC/dinky/assets/142898753/b4da7a50-3b03-4bc3-a5a0-797586b770cc)
不过还是等博主回复吧，目前根据上下文没看出来为什么不加排序和使用hashmap存储

**Comment by aiwenmo** [comment]
Sorry, I 've been a little busy recently and haven't replied to you in time.
The reason for not sorting and not using LinkedHashMap storage is that previous tests neglected this situation. 
Thank you very much for your research and answers. I agree with your solution. Welcome to submit PR to dev branch. If you encounter any problems during this period, you can communicate continuously.

**Comment by aiwenmo** [comment]
Hi. Are you willing to contribute code? If you have no time, I will fix the problem.

**Comment by tttzzzwww** [comment]
> Hi. Are you willing to contribute code? If you have no time, I will fix the problem.

不好意思，这几天项目有点赶/(ㄒoㄒ)/~~，一直在加班，博主你提交下吧

**Comment by Zzm0809** [comment]
@aiwenmo @tttzzzwww , I will fix the problem

**Comment by Zzm0809** [comment]
> > Hi. Are you willing to contribute code? If you have no time, I will fix the problem.
>
> Sorry, the project is a bit rushed these days /(ㄒoㄒ)/~~, I have been working overtime, blogger, please submit it


You are on the 0.7 branch. Currently, 0.7 is not maintained, Can be modified in the dev branch
