### ISSUE TITLE
[Bug] [dinky-cdc] The entire MySQL database is synchronized to Kafka, and the sub-database and sub-table mode does not take effect.

### ISSUE THREAD

**Issue by lyheimat** [DataLinkDC/dinky#3320]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

同步MySQL整库数据到Kafka，配置了分库分表模式，测试单表可写入，正则匹配的表无法写入

CDCSOURCE 任务配置如下：
```
EXECUTE CDCSOURCE ranger_to_kafka WITH (
    'connector' = 'mysql-cdc',
    'hostname' = 'localhost',
    'port' = '3306',
    'username' = 'root',
    'password' = 'xxxxx',
    'checkpoint' = '10000',
    'scan.startup.mode' = 'initial',
    'parallelism' = '1',
    'database-name' = 'ranger',
    'table-name' = 'ranger\.stu,ranger\.person,ranger\.order_[0-9]+',
    'split.enable' = 'true',
    'split.match_number_regex' = '_[0-9]+',
    'sink.connector' = 'datastream-kafka',
    'sink.table.prefix' = 'ods_',
    'sink.brokers' = 'bigdata101:9092,bigdata102:9092,bigdata103:9092',
    'sink.properties.transaction.timeout.ms' = '900000',
    'sink.properties.transactional.id' = 'ranger'
);
```

### What you expected to happen

stu表写入ods_stu主题
person表写入ods_person主题
order_01、order02、order03表写入ods_order主题

### How to reproduce

创建一个CDCSOURCE任务

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lyheimat** [comment]
![image](https://github.com/DataLinkDC/dinky/assets/73530795/c7c73271-a46d-44cd-af3b-67f16c6f5c3b)
创建了对应kafkaSink，但是没有接收到数据

**Comment by Zzm0809** [comment]
分库分表整库同步目前只支持目标端是MySQL
