### ISSUE TITLE
[Improvement] CPU is too high

### ISSUE THREAD

**Issue by Gianzie** [DataLinkDC/dinky#3343]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

If I don't log in to Dinky over the weekend, my CPU will soar to 80% when I log in on Monday, and I can't log in anymore. The only solution is to restart. I'm not sure if it's caused by Dinky's built-in monitoring.

### What you expected to happen

If I don't log in to Dinky over the weekend, my CPU will soar to 80% when I log in on Monday, and I can't log in anymore. The only solution is to restart. I'm not sure if it's caused by Dinky's built-in monitoring.

### How to reproduce

If I don't log in to Dinky over the weekend, my CPU will soar to 80% when I log in on Monday, and I can't log in anymore. The only solution is to restart. I'm not sure if it's caused by Dinky's built-in monitoring.

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
可以 dump 下内存快照协助排查一下该问题 , 目前确实有人反馈该问题,初步排查是由于 paimon 作为了监控存储介质,运行一段时间内会有内存泄漏风险, 可以协助确认一下该问题

**Comment by sin70611** [comment]
找到问题了么 解决了嘛

**Comment by Zzm0809** [comment]
> 找到问题了么 解决了嘛

可以一起协助排查该问题

**Comment by Pandas886** [comment]
> ### Search before asking 先搜索后询问
> * [x]  I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.我在问题中搜索过，没有发现类似的问题。
> 
> ### What happened 发生了什么事
> If I don't log in to Dinky over the weekend, my CPU will soar to 80% when I log in on Monday, and I can't log in anymore. The only solution is to restart. I'm not sure if it's caused by Dinky's built-in monitoring.如果我周末不登录 Dinky，周一登录时我的 CPU 会飙升到 80%，我再也无法登录了。唯一的解决方案是重新启动。我不确定这是否是由 Dinky 的内置监控引起的。
> 
> ### What you expected to happen
> 您期望发生的情况
> If I don't log in to Dinky over the weekend, my CPU will soar to 80% when I log in on Monday, and I can't log in anymore. The only solution is to restart. I'm not sure if it's caused by Dinky's built-in monitoring.如果我周末不登录 Dinky，周一登录时我的 CPU 会飙升到 80%，我再也无法登录了。唯一的解决方案是重新启动。我不确定这是否是由 Dinky 的内置监控引起的。
> 
> ### How to reproduce 如何繁殖
> If I don't log in to Dinky over the weekend, my CPU will soar to 80% when I log in on Monday, and I can't log in anymore. The only solution is to restart. I'm not sure if it's caused by Dinky's built-in monitoring.如果我周末不登录 Dinky，周一登录时我的 CPU 会飙升到 80%，我再也无法登录了。唯一的解决方案是重新启动。我不确定这是否是由 Dinky 的内置监控引起的。
> 
> ### Anything else 别的东西
> _No response 没有回应_
> 
> ### Version 版本
> 1.0.0
> 
> ### Are you willing to submit PR?
> 你愿意提交公关吗？
> * [ ]  Yes I am willing to submit a PR!是的，我愿意提交PR！
> 
> ### Code of Conduct 行为准则
> * [x]  I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)我同意遵守本项目的行为准则

有试过关闭dinky上的jvm监控按钮吗

**Comment by Gianzie** [comment]
@Pandas886 sure，但貌似没什么用，不知道新版本是否修复好
