### ISSUE TITLE
[Bug] [dinky-admin] Got an exception - "Cause: java.sql.SQLException: Field 'name' doesn't have a default value"  when i run a jar task 

### ISSUE THREAD

**Issue by yingh0ng** [DataLinkDC/dinky#3344]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

运行jar任务报错
![image](https://github.com/DataLinkDC/dinky/assets/22335970/b89a957e-4a1f-4767-bc23-110767459f9f)

### What you expected to happen

运行成功

### How to reproduce

1、配置本地standalone集群
2、资源中心选择LOCAL模式
3、创建flink jar作业
4、使用以下语句运行作业：
EXECUTE JAR WITH (
'uri'='rs:/flink-quikstart-java-1.0-SNAPSHOT.jar',
'main-class'='org.apache.flink.DorisBatchTest',
'args'='1770003084665495553'
);

### Anything else

dinky版本：dinky-release-1.18-1.0.1（下面的version无法选择1.0.1分支）

task接口请求体
![image](https://github.com/DataLinkDC/dinky/assets/22335970/aa3a0571-c890-4cbf-9afe-9c0c94472165)

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
请规范化 issue title

**Comment by Zzm0809** [comment]
此问题无法复现 请尝试清除缓存后重试

**Comment by yingh0ng** [comment]
> 此问题无法复现 请尝试清除缓存后重试

刷新缓存或者更换浏览器都不行哦，而且我这是第一次部署dinky。
无论是点保存还是运行都报一样的异常，感觉是前端没有传任务名称参数。

**Comment by yingh0ng** [comment]
![image](https://github.com/DataLinkDC/dinky/assets/22335970/f95cf461-b37c-42c1-aa6b-623c5a687a56)

**Comment by yingh0ng** [comment]
重新部署在Ubuntu上就好了，原来是部署在Debian上

**Comment by aiwenmo** [comment]
What operation triggered the exception?

**Comment by Zane56Git** [comment]
> 什么操作触发了异常？

我也遇到过，Profile配置不对，代码编译没有选择dev、fast（并且flink选了all），直接创建一个任务输入模板的代码保存点击运行就会有这个报错了，前端根本没传参数到后端后面按官网重新配置了Profile，重新编译启动，清理页面缓存后就可以了，后端接口有限制必填参数好排查些

**Comment by Zane56Git** [comment]
> > 此问题无法复现 请尝试清除缓存后重试
> 
> 刷新缓存或者更换浏览器都不行哦，而且我这是第一次部署dinky。 无论是点保存还是运行都报一样的异常，感觉是前端没有传任务名称参数。

我也遇到过，Profile配置不对，代码编译没有选择dev、fast（并且flink选了all），发现前端根本没传参数到后端，后面按官网重新配置了Profile，重新编译启动，清理页面缓存后就可以了
