### ISSUE TITLE
[Feature][Flink] DataSource sql generated  supports cdc and jdbc task different type conversion rules

### ISSUE THREAD

**Issue by xiaofan2022** [DataLinkDC/dinky#3346]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

sql generated by data source supports cdc and jdbc task different type conversion rules。 [jdbc type mapping](https://nightlies.apache.org/flink/flink-docs-release-1.19/docs/connectors/table/jdbc/#data-type-mapping)， [cdc type mapping](https://nightlies.apache.org/flink/flink-cdc-docs-release-3.0/docs/connectors/legacy-flink-cdc-sources/oracle-cdc/#data-type-mapping)

### Use case

sql generated by data source supports cdc and jdbc task different type conversion rules

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xiaofan2022** [comment]
Support for major connectors such as flink-cdc,flink-jdbc,flink-hive,flink-hudi mainstream sql field type mapping

**Comment by Zzm0809** [comment]
Please explain the purpose and design plan

**Comment by Zzm0809** [comment]
参考  https://www.dinky.org.cn/docs/next/practical_guide/cdcsource_practice/cdcsource_mysqlcdc2kafka#%E5%90%8C%E6%AD%A5%E5%88%B0%E5%AF%B9%E5%BA%94-topic

**Comment by xiaofan2022** [comment]
Purpose: sql generation function automatically generates synchronous sql (type mapping) based on connector
Plan: First support jdbc type sql generated field type mapping

**Comment by Zzm0809** [comment]
> Purpose: sql generation function automatically generates synchronous sql (type mapping) based on connector Plan: First support jdbc type sql generated field type mapping

Can you implement this function?

**Comment by xiaofan2022** [comment]
I can do the backend. The frontend？

**Comment by aiwenmo** [comment]
> I can do the backend. The frontend？

Thank you very much for your participation. Please clarify the front-end requirements, and we will be responsible for their implementation.

**Comment by xiaofan2022** [comment]
The front end adds different connector types (such as CDC, JDBC, Hive, Hudi) when generating SQL statements, and the back end maps the corresponding fields according to the official documentation based on the connector type.

**Comment by Zzm0809** [comment]
> The front end adds different connector types (such as CDC, JDBC, Hive, Hudi) when generating SQL statements, and the back end maps the corresponding fields according to the official documentation based on the connector type.

you can provide a map data  struct example of backend  . i will be design the frontend

**Comment by Zzm0809** [comment]
> The front end adds different connector types (such as CDC, JDBC, Hive, Hudi) when generating SQL statements, and the back end maps the corresponding fields according to the official documentation based on the connector type.

I understand whether it can be designed as follows
1. The front end adds a drop-down box in Generate sql -> Flinksql Tag (values such as: CDC, JDBC, Hive, Hudi)
2. Then select and call the interface input parameters before adding the connector type input parameters. The interface generates results based on the connector type, and then returns



how?

**Comment by xiaofan2022** [comment]
yes

**Comment by xiaofan2022** [comment]
If you want to add flink-cdc type mapping, is to add a new flink-cdc-meta, and then put the corresponding logic into flink- CDC-meta?

**Comment by Zzm0809** [comment]
@aiwenmo What do you think?

**Comment by aiwenmo** [comment]
Put the corresponding logic into dinky-cdc.

**Comment by Zzm0809** [comment]
> Put the corresponding logic into dinky-cdc.

It would be inappropriate to put everything in dinky-cdc. In theory, the column type information on the data source module also needs to use the type conversion here to achieve a unified effect.

**Comment by xiaofan2022** [comment]
Is it possible to maintain different conversion logic for different sources (e.g. flink-cdc,jdbc,hive,hudi) in the conversion logic corresponding to the connector?
