### ISSUE TITLE
Error creating mapping relationship for table field ‘time’ type in cdcsource task creation，string to time(0)What is your Dinky version?

### ISSUE THREAD

**Issue by liukundong** [DataLinkDC/dinky#3347]
What is your Dinky version?
v1.0.0_flink_1.18
_Originally posted by @aiwenmo in https://github.com/DataLinkDC/dinky/issues/3065#issuecomment-1925722792_

**Comment by Zzm0809** [comment]
不要重复提交issue

**Comment by liukundong** [comment]
> 不要重复提交issue

这个问题解决了吗？
