### ISSUE TITLE
When using flinksql to create create view as select in Dinky, the order of the fields is confused (dinky is arranged according to the first letter of the fields)

### ISSUE THREAD

**Issue by liaoxiaodongabc** [DataLinkDC/dinky#3352]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

在dinky1.0.1的flinksql作业中create view as select 建立视图时，视图的字段顺序默认是按照字段首字母排序的，导致数据全部混乱，作业报错，
[error.csv](https://github.com/DataLinkDC/dinky/files/14846058/error.csv)

### What you expected to happen

希望dinky社区修复此bug

### How to reproduce

请在dinky1.0.1的flinksql作业中create view as select b, c, a from table，然后在flink的8081界面查看报错的task打印的日志，日志出现的应该是 select b as a, c as b, a as c from table.

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi. What's your sql?
