### ISSUE TITLE
[Bug] [Devops] The status of the completed Flink batch task is UNKNOWN

### ISSUE THREAD

**Issue by kaijli-bigdata** [DataLinkDC/dinky#3361]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

The status of the completed Flink batch task is UNKNOWN
![image](https://github.com/DataLinkDC/dinky/assets/21278751/5b7bf078-2712-41e3-8276-ecbbfaaecb72)

### What you expected to happen

The status of completing the Flink batch task should be completed

### How to reproduce

Execute Flink batch tasks on Dinky, and then check the task status in the operations center.

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
i will fix it

**Comment by gaoyan1998** [comment]
link #3373
