### ISSUE TITLE
[Bug] [dinky] Conflict problem between flink and hive classes

### ISSUE THREAD

**Issue by aiyingyi** [DataLinkDC/dinky#3379]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

dinky添加hive数据源时，需要在extends目录下添加hive-exec 依赖，与flin-table-planner中的org.apache.calcite.sql.parser.SqlParser发生冲突，导致flinksql无法执行

### What you expected to happen

这种该如何解决

### How to reproduce

在extends目录下添加hive-exec 依赖

### Version

1.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
无需添加hive-exec  添加 hive-jdbc 和 hive-service

**Comment by aiyingyi** [comment]
@Zzm0809  无hive-exec，会报错，hive版本 4.0.0
![image](https://github.com/DataLinkDC/dinky/assets/33448382/2aa4ce01-3782-4bd9-b913-3acb87833bdf)

**Comment by Zzm0809** [comment]
> @Zzm0809 无hive-exec，会报错，hive版本 4.0.0 ![image](https://private-user-images.githubusercontent.com/33448382/321531685-2aa4ce01-3782-4bd9-b913-3acb87833bdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjUwNTMsIm5iZiI6MTcxMjgyNDc1MywicGF0aCI6Ii8zMzQ0ODM4Mi8zMjE1MzE2ODUtMmFhNGNlMDEtMzc4Mi00YmQ5LWI5MTMtM2FjYjg3ODMzYmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA4MzkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTk2OWE3MDhlNDgzNWY2ZmJlNDkwZmNhNjU0YmMwZDBjNWJmMzViZjQ0MDRjZDY1OWRjZDdhZTgzODg0ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bSFKaWK9LBTLnWix5LcaWlsa9NJZilyqFut9gAjPoqc)

版本太新 需要自己解决依赖问题

**Comment by aiwenmo** [comment]
Method 1: Manually resolve dependency conflicts.
Method 2: Start two dinky, one specifically for querying hive.
