### ISSUE TITLE
[Bug] [dinky-admin]  Constructing any path will expose sensitive file information of the DINKY deployment server

### ISSUE THREAD

**Issue by sgsdehen** [DataLinkDC/dinky#3380]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

web漏洞系统检测SystemController  /readFile接口存在安全隐患 暴露服务器敏感文件信息

### What you expected to happen

拒绝未验证的请求

### How to reproduce

构造任意path比如/etc/passwd 访问 https://xx.dinky.com/api/system/readFile?path=/etc/password  ,返回服务器此文件内容

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
link #3383
