### ISSUE TITLE
[Feature][Studio] support execute jar by form

### ISSUE THREAD

**Issue by Pandas886** [DataLinkDC/dinky#3381]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

目前提交jar任务是需要sql的，但是如果jar的入参比较复杂，比如有单引号和双引号等，会导致execute jar sql解析失败。建议可以用前端表单来提交，更解决云厂商的jar任务管理方式，降低学习成本。
![image](https://github.com/DataLinkDC/dinky/assets/123344357/0ed7c115-f2ff-4dc2-9670-3950588ab6b4)

### Use case

目前1.0.0版本中的execute jar sql是没法正常跑下面用例的
Examples:
 Find all orders mentioned in the source table, then mark as important if the price is above 100 
 or delete if the price is under 10.
```


./flink run \
    /path/to/paimon-flink-action-0.8-SNAPSHOT.jar \
    merge_into \
    --warehouse <warehouse-path> \
    --database <database-name> \
    --table T \
    --source_table S \
    --on "T.id = S.order_id" \
    --merge_actions \
    matched-upsert,matched-delete \
    --matched_upsert_condition "T.price > 100" \
    --matched_upsert_set "mark = 'important'" \
    --matched_delete_condition "T.price < 10" 
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
你可以来实现此功能吗?

**Comment by 18216499322** [comment]
![image](https://github.com/DataLinkDC/dinky/assets/75019445/620d32c3-2f7c-4aba-980c-89cc5d83f1ae)
我可以实现，做成这种表单可以不

**Comment by gaoyan1998** [comment]
> ![image](https://private-user-images.githubusercontent.com/75019445/347326766-620d32c3-2f7c-4aba-980c-89cc5d83f1ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDEwMDgsIm5iZiI6MTcyMDYwMDcwOCwicGF0aCI6Ii83NTAxOTQ0NS8zNDczMjY3NjYtNjIwZDMyYzMtMmY3Yy00YWJhLTk4MGMtODljYzVkODNmMWFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA4MzgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMzIyNzkzYWQxMWQ0MTg0MDgyMTc5M2U2MjAzN2NmZTdjMmI1YTBkOTllODljNWQwYTljZjVmNDA1OGIyNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fRxunaiGdHU1jTucYKtivHLYDalDI2_WBaep_6fVa78) 我可以实现，做成这种表单可以不

我觉得阔以

**Comment by Zzm0809** [comment]
此需求弊大于利, 不建议实现

**Comment by aiwenmo** [comment]
- [X] #3949
