### ISSUE TITLE
[Bug] [dinky-metadata] datasource oracle generate sql all column type is string

### ISSUE THREAD

**Issue by xiaofan2022** [DataLinkDC/dinky#3409]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

generate sql：
DROP TABLE IF EXISTS EXAMPLE_TABLE;
CREATE TABLE IF NOT EXISTS EXAMPLE_TABLE (
    `ID` STRING,
    `VARCHAR_COL` STRING,
    `CHAR_COL` STRING,
    `NUMERIC_COL1` STRING,
    `NUMERIC_COL2` STRING,
    `DATE_COL` STRING,
    `TIMESTAMP_COL` STRING,
    `CLOB_COL` STRING,
    `BLOB_COL` STRING) WITH (
)
all cloumn type is string

### What you expected to happen

Generate sql based on type mapping[https://nightlies.apache.org/flink/flink-docs-release-1.19/docs/connectors/table/jdbc/#data-type-mapping](url)

### How to reproduce

oracle ddl:
CREATE TABLE example_table
(
    id            NUMBER(10, 0),
    varchar_col   VARCHAR2(100),
    char_col      CHAR(10),
    numeric_col1  NUMBER(10, 2),
    numeric_col2  NUMBER,
    date_col      DATE,
    timestamp_col TIMESTAMP,
    clob_col      CLOB,
    blob_col      BLOB
); 
use datasource->generate sql

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xiaofan2022** [comment]
I see that the OracleTypeConvert class in the code defines the relationship between db types and java types. Then we generate database field types from java types and documents, so why not directly use database types to generate table types according to document rules? ![image](https://github.com/DataLinkDC/dinky/assets/41982310/944beeaa-1974-4fa1-882b-ff5ff9d0bfba)

**Comment by aiwenmo** [comment]
The reason is to reduce workload.
This is a feasible solution that use database types to generate table types according to document rules.

**Comment by Zzm0809** [comment]
maybe like issue #3346
