### ISSUE TITLE
[Bug] [FLINK SQL] Could not load service provider for table factories.

### ISSUE THREAD

**Issue by wangsan1988** [DataLinkDC/dinky#3415]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

run  the demo job by  quick start of offical website .https://dinky.org.cn/docs/next/get_started/quick_experience
get a error : Could not load service provider for table factories. java.util.ServiceConfigurationError: org.apache.flink.table.factories.TableFactory: Provider org.apache.flink.table.planner.StreamPlannerFactory not a subtype.

![image](https://github.com/DataLinkDC/dinky/assets/30817233/e58505ad-59dc-4ea3-9b4e-eb762e6d2565)

job submit to yarn is successfully，then get a error : ava.lang.IndexOutOfBoundsException: Index: 0, Size: 0 , getYarnContainerLog
![image](https://github.com/DataLinkDC/dinky/assets/30817233/2189b207-c548-43e3-b1eb-f2dbe35f8e37)

i think "Could not load service provider for table factories." it the root cause ,seem like jars or dependence problem ,but don't know how to fix it.
[d6b42e62-5693-4d93-8656-61aff01022ad.txt](https://github.com/DataLinkDC/dinky/files/15032866/d6b42e62-5693-4d93-8656-61aff01022ad.txt)

### What you expected to happen

mate the demo job run

### How to reproduce

* dinky 1.0.0
* flink 1.18.1
* here is jars at /opt/software/dinky/extends/flink1.18
![image](https://github.com/DataLinkDC/dinky/assets/30817233/d6eeb97b-1662-4ab6-9550-6153049fa0ef)
* here is the cluster config
![image](https://github.com/DataLinkDC/dinky/assets/30817233/496d8f5c-3ecb-43dc-a566-4ee721ac8c7a)

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangsan1988** [comment]
d6b42e62-5693-4d93-8656-61aff01022ad.txt   above is the full log file.
can anyone help,thanks

**Comment by wangsan1988** [comment]
when change to local mode ,then  get  another error: 
Caused by: org.apache.flink.table.api.ValidationException: Multiple factories for identifier 'datagen' that implement 'org.apache.flink.table.factories.DynamicTableFactory' found in the classpath.

Ambiguous factory classes are:

org.apache.flink.connector.datagen.table.DataGenTableSourceFactory
org.apache.flink.table.factories.DataGenTableSourceFactory
![image](https://github.com/DataLinkDC/dinky/assets/30817233/d780f841-3b25-4d2f-8c3d-a5722dad38f2)

**Comment by Zzm0809** [comment]
排查环境

**Comment by wangsan1988** [comment]
算了，还是试试streampark了
