### ISSUE TITLE
[Bug] [Dinky-log] dinky flink local  can't see job log and task log

### ISSUE THREAD

**Issue by CoderXionghs** [DataLinkDC/dinky#3416]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

I used dinky run flink local,  but i can't see the job-manager and taskmanager log,also the stdout;
![image](https://github.com/DataLinkDC/dinky/assets/10545364/0dbcb50d-c4e5-4a28-98fa-7c7d78041643)
![image](https://github.com/DataLinkDC/dinky/assets/10545364/e56f5c64-7653-4743-8b22-27974c582603)

### What you expected to happen

show the local flink  job's log and stdout,  so that can help debug sometimes;

### How to reproduce

none

### Anything else

none

### Version

1.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
这不是bug
