### ISSUE TITLE
[Feature][scheduler] Support task group selection from DolphinScheduler

### ISSUE THREAD

**Issue by Yangxiaotian** [DataLinkDC/dinky#3418]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

1. The form of sending a task to DolphinScheduler will be added a new selection field -- task groups of DS, and after sending the taskGroupId value will write into DS's database. The task groups is showed relatived to current project code.

![image](https://github.com/DataLinkDC/dinky/assets/6516805/bdb83e28-5d79-4571-a03d-a490fe74bd00)
3. Fix a bug: when the form window is reopened after sending to DS, some field values are not correctly shown even though the request's callback contains the correct value.
![fcae52dda3ea8c6b5297a78553a9212](https://github.com/DataLinkDC/dinky/assets/6516805/b4b33653-ce50-4357-8274-84f31c19c2f4)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
I saw that there is also an intra-group priority configuration for task groups in ds. Would you consider adding it together?
If you add a new one, you need to pay attention to selecting the task group before entering the priority.

![image](https://github.com/DataLinkDC/dinky/assets/58576849/d57ba6fd-36ec-4931-bc5d-b587813be754)

**Comment by Yangxiaotian** [comment]
OK, we will add the priority field.
