### ISSUE TITLE
[BUG][CDCSOURCE]dinky0.73 flink1.14.6 failed to synchronize the entire CDC database

### ISSUE THREAD

**Issue by baron-fly** [DataLinkDC/dinky#3424]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

一直报缺少jar包的错误，在之前的issue中看到是connector包的问题，之前是2.2.1版本胖包，会报错，换成2.3.0还是会报错，这是我所有包的信息，求各位指点。
![1](https://github.com/DataLinkDC/dinky/assets/48245255/53cb9bf8-87b1-48f6-8648-1badd6a85f01)

### What you expected to happen

应该是jar包依赖有问题，以下是我所有jar包信息。
![flink1 14依赖](https://github.com/DataLinkDC/dinky/assets/48245255/5d3cb698-b897-4f26-a0a1-bf6a9336fda4)

### How to reproduce

运行官网0.7下CDC同步 mysql->kafka时报错

### Version

0.7.3(Archived, Not Maintained)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
@baron-fly 请规范化你的 issue title , 否则视为无效 issue

**Comment by baron-fly** [comment]
> @baron-fly 请规范化你的 issue title , 否则视为无效 issue

你好，已按照规范修改title。

**Comment by baron-fly** [comment]
在dinky0.7.3环境下，使用flink1.14运行官网“实时数据合并至一个 kafka topic”用例，报错信息如上，考虑是jar包冲突。

**Comment by Zzm0809** [comment]
整库同步需要把 dinky 的几个包丢给 flink , 请认真看文档

**Comment by baron-fly** [comment]
> 整库同步需要把 dinky 的几个包丢给 flink , 请认真看文档

flink的lib目录下按照官网要求已放置3个dlink依赖包

**Comment by Zzm0809** [comment]
> > 整库同步需要把 dinky 的几个包丢给 flink , 请认真看文档
> 
> flink的lib目录下按照官网要求已放置3个dlink依赖包

运行模式如果是 application 模式也需要
如果是 yarn-session 或者 standalone 需要重启 flink 集群

**Comment by baron-fly** [comment]
> > > 整库同步需要把 dinky 的几个包丢给 flink , 请认真看文档
> > 
> > 
> > flink的lib目录下按照官网要求已放置3个dlink依赖包
> 
> 运行模式如果是 application 模式也需要 如果是 yarn-session 或者 standalone 需要重启 flink 集群

我用的standalone模式，今天早上启动的时候发现工作状态变为正常，期间flink和dinky都未重启过，真是怪了。然后遇到下面这个问题，flink无法把数据传给kafka，已检查过有flink-sql-connector-kafka_2.12-1.14.6.jar的包，错误如下图。
![sink不到](https://github.com/DataLinkDC/dinky/assets/48245255/e4ee2732-832b-48b0-9e05-c8b1cbcd5000)

**Comment by Zzm0809** [comment]
> > > > 整库同步需要把 dinky 的几个包丢给 flink , 请认真看文档
> > > 
> > > 
> > > flink的lib目录下按照官网要求已放置3个dlink依赖包
> > 
> > 
> > 运行模式如果是 application 模式也需要 如果是 yarn-session 或者 standalone 需要重启 flink 集群
> 
> 我用的standalone模式，今天早上启动的时候发现工作状态变为正常，期间flink和dinky都未重启过，真是怪了。然后遇到下面这个问题，flink无法把数据传给kafka，已检查过有flink-sql-connector-kafka_2.12-1.14.6.jar的包，错误如下图。 ![sink不到](https://private-user-images.githubusercontent.com/48245255/325814832-e4ee2732-832b-48b0-9e05-c8b1cbcd5000.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTM4OTAsIm5iZiI6MTcxNDA5MzU5MCwicGF0aCI6Ii80ODI0NTI1NS8zMjU4MTQ4MzItZTRlZTI3MzItODMyYi00OGIwLTllMDUtYzhiMWNiY2Q1MDAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDAxMDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZjNlODBmMmE1ZWRiZTc1MWE4MTZkZTEwYjYxNWI1ZGFhNjhhMGVhZjE5MTBkYmI3OGUwMWQ2MzdmYzJhODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gcHAYohU5X5yaiOl-6d0JmAulYMk1woQl5O-qd3oXtk)

无法构建 sink 端,查看日志排查出错原因
