### ISSUE TITLE
[Bug] dinky(v1.0.1) not support dolphinscheduler(v3.1.8)

### ISSUE THREAD

**Issue by GuangliHan** [DataLinkDC/dinky#3425]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

用dolphinscheduler（v3.1.8）调用dinky（v1.0.1）任务发布运行失败。
根据dolphinscheduler后台日志，dolphinscheduler调用dinky API接口（/openapi/onLineTask?id=xxx）调用失败，提示确认dinky版本是否大于等于0.6.5版本。
log:
[ERROR] 2024-04-24 21:42:27.051 +0800 - dinky task terminated,response: HttpResponseProxy{HTTP/1.1 404  [Vary: Origin, Vary: Access-Control-Request-Method, Vary: Access-Control-Request-Headers, Content-Type: application/json, Transfer-Encoding: chunked, Date: Wed, 24 Apr 2024 13:42:27 GMT, Keep-Alive: timeout=60, Connection: keep-alive] ResponseEntityProxy{[Content-Type: application/json,Chunked: true]}}
[ERROR] 2024-04-24 21:42:27.051 +0800 - dinky task submit failed with error: Please check that the dinky version is greater than or equal to 0.6.5
[INFO] 2024-04-24 21:42:27.052 +0800 - Send task execute result to master, the current task status: TaskExecutionStatus{code=6, desc='failure'}

### What you expected to happen

新版本Dinky兼容旧版本的/openapi/onLineTask接口,确保dolphinscheduler调用dinky任务发布成功

### How to reproduce

用dolphinscheduler对dinky任务进行调度

### Anything else

every time

### Version

1.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GuangliHan** [comment]
dolphinscheduler log:

[INFO] 2024-04-24 21:42:27.047 +0800 - access url: http://10.2.18.66:8888/openapi/onLineTask?id=12
[ERROR] 2024-04-24 21:42:27.051 +0800 - dinky task terminated,response: HttpResponseProxy{HTTP/1.1 404  [Vary: Origin, Vary: Access-Control-Request-Method, Vary: Access-Control-Request-Headers, Content-Type: application/json, Transfer-Encoding: chunked, Date: Wed, 24 Apr 2024 13:42:27 GMT, Keep-Alive: timeout=60, Connection: keep-alive] ResponseEntityProxy{[Content-Type: application/json,Chunked: true]}}
[ERROR] 2024-04-24 21:42:27.051 +0800 - dinky task submit failed with error: Please check that the dinky version is greater than or equal to 0.6.5
[INFO] 2024-04-24 21:42:27.052 +0800 - Send task execute result to master, the current task status: TaskExecutionStatus{code=6, desc='failure'}

**Comment by Zzm0809** [comment]
方案 1: ds 必须 3.2.1+  低版本需要自己适配
方案 2: 或者拿到ds 中 3.2.1+ 的 dinky-task.jar 替换下你目前ds版本中的 dinky-task.jar

**Comment by GuangliHan** [comment]
> 方案 1: ds 必须 3.2.1+ 低版本需要自己适配 方案 2: 或者拿到ds 中 3.2.1+ 的 dinky-task.jar 替换下你目前ds版本中的 dinky-task.jar

我将ds 3.2.1版本的/api-server/libs/dolphinscheduler-task-dinky-3.2.1.jar 替换我安装的ds 3.1.8路径后，重启ds 仍然报错一样的。请问还需要替换什么？
ds log
[INFO] 2024-04-26 10:46:43.834 +0800 - Task plugin: DINKY create success
[INFO] 2024-04-26 10:46:43.834 +0800 - dinky task params:{"localParams":[],"resourceList":[],"address":"http://10.2.18.66:8888","taskId":"15","online":true}
[INFO] 2024-04-26 10:46:43.834 +0800 - Success initialized task plugin instance success
[INFO] 2024-04-26 10:46:43.834 +0800 - Success set taskVarPool: null
[INFO] 2024-04-26 10:46:43.835 +0800 - access url: http://10.2.18.66:8888/openapi/onLineTask?id=15
[ERROR] 2024-04-26 10:46:43.839 +0800 - dinky task terminated,response: HttpResponseProxy{HTTP/1.1 404  [Vary: Origin, Vary: Access-Control-Request-Method, Vary: Access-Control-Request-Headers, Content-Type: application/json, Transfer-Encoding: chunked, Date: Fri, 26 Apr 2024 02:46:43 GMT, Keep-Alive: timeout=60, Connection: keep-alive] ResponseEntityProxy{[Content-Type: application/json,Chunked: true]}}
[ERROR] 2024-04-26 10:46:43.839 +0800 - dinky task submit failed with error: Please check that the dinky version is greater than or equal to 0.6.5

**Comment by aiwenmo** [comment]
Close the online button in dolphinscheduler's dinky task.

**Comment by GuangliHan** [comment]
> Close the online button in dolphinscheduler's dinky task.

@aiwenmo 

ds log:
[INFO] 2024-04-26 14:04:03.459 +0800 - Task plugin: DINKY create success
[INFO] 2024-04-26 14:04:03.459 +0800 - dinky task params:{"localParams":[],"resourceList":[],"address":"http://10.2.18.66:8888","taskId":"15","online":false}
[INFO] 2024-04-26 14:04:03.459 +0800 - Success initialized task plugin instance success
[INFO] 2024-04-26 14:04:03.459 +0800 - Success set taskVarPool: null
[INFO] 2024-04-26 14:04:03.460 +0800 - **access url: http://10.2.18.66:8888/openapi/submitTask?id=15
[INFO] 2024-04-26 14:04:03.468 +0800 - dinky task succeed with results: {"data":"org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' not supported\n\tat** org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping.handleNoMatch(RequestMappingInfoHandlerMapping.java:260)\n\tat org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.lookupHandlerMethod(AbstractHandlerMethodMapping.java:442)\n\tat org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.getHandlerInternal(AbstractHandlerMethodMapping.java:383)\n\tat org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping.getHandlerInternal(RequestMappingInfoHandlerMapping.java:125)\n\tat org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping.getHandlerInternal(RequestMappingInfoHandlerMapping.java:67)\n\tat org.springframework.web.servlet.handler.AbstractHandlerMapping.getHandler(AbstractHandlerMapping.java:498)\n\tat org.springframework.web.servlet.DispatcherServlet.getHandler(DispatcherServlet.java:1266)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1048)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)\n\tat org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:529)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:623)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)\n\tat org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)\n\tat org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)\n\tat cn.dev33.satoken.filter.SaPathCheckFilterForServlet.doFilter(SaPathCheckFilterForServlet.java:55)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)\n\tat org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)\n\tat org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)\n\tat org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.lang.Thread.run(Thread.java:750)\n","code":5,"msg":"Request method 'GET' not supported","time":"2024-04-26 14:04:03","success":false}
[ERROR] 2024-04-26 14:04:03.469 +0800 - Task execute failed, due to meet an exception
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.plugin.task.dinky.DinkyTask.handle(DinkyTask.java:107)
	at org.apache.dolphinscheduler.server.worker.runner.DefaultWorkerDelayTaskExecuteRunnable.executeTask(DefaultWorkerDelayTaskExecuteRunnable.java:49)
	at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecuteRunnable.run(WorkerTaskExecuteRunnable.java:174)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
[INFO] 2024-04-26 14:04:03.470 +0800 - trying terminate dinky task, taskId: 81, address: http://10.2.18.66:8888, taskId: 15
[INFO] 2024-04-26 14:04:04.500 +0800 - dinky task succeed with results: {"data":null,"code":1,"msg":"org.apache.flink.runtime.rest.handler.RestHandlerException: Config key [state.savepoints.dir] is not set. Property [target-directory] must be provided.","time":"2024-04-26 14:04:04","success":false}
[WARN] 2024-04-26 14:04:04.500 +0800 - dinky task terminated, taskId: 81, address: http://10.2.18.66:8888, taskId: 15
[INFO] 2024-04-26 14:04:04.500 +0800 - Get a exception when execute the task, will send the task execute result to master, the current task execute result is TaskExecutionStatus{code=6, desc='failure'}

**Comment by aiwenmo** [comment]
Your dinky-task.jar has not been updated to version 3.2.1

**Comment by GuangliHan** [comment]
> Your dinky-task.jar has not been updated to version 3.2.1

this is my dinky-task.jar version 3.2.1 
[dolphinscheduler-task-dinky-3.2.1.jar.zip](https://github.com/DataLinkDC/dinky/files/15126423/dolphinscheduler-task-dinky-3.2.1.jar.zip)
and replace ds dinky task lib path:
./api-server/libs/dolphinscheduler-task-dinky-3.1.8.jar
./master-server/libs/dolphinscheduler-task-dinky-3.1.8.jar
./worker-server/libs/dolphinscheduler-task-dinky-3.1.8.jar

**Comment by GuangliHan** [comment]
The issue has been resolved.
1. replace the following ds paths with lib version 3.2.1 version [dolphinscheduler-task-dinky-3.2.1.jar.zip](https://github.com/DataLinkDC/dinky/files/15126423/dolphinscheduler-task-dinky-3.2.1.jar.zip):
./api-server/libs/dolphinscheduler-task-dinky-3.1.8.jar
./master-server/libs/dolphinscheduler-task-dinky-3.1.8.jar
./worker-server/libs/dolphinscheduler-task-dinky-3.1.8.jar

2.restart the ds service.
