### ISSUE TITLE
When dinky runs mysql full database synchronization, it only synchronizes the table structure, but the data is not synchronized!

### ISSUE THREAD

**Issue by Hello-Linux** [DataLinkDC/dinky#3430]

**Comment by Hello-Linux** [comment]
我的 flink sql如下
```
EXECUTE CDCSOURCE cdc_mysql WITH (
 'connector' = 'mysql-cdc',
 'hostname' = '192.168.98.199',
 'port' = '3307',
 'username' = 'root',
 'password' = 'buzhidao',
 'checkpoint' = '3000',
 'scan.startup.mode' = 'initial',
 'parallelism' = '1',
 'database-name' = 'sn_metrics',
 'table-name' = 'sn_metrics\..*',
 'sink.connector' = 'jdbc',
 'sink.url' = 'jdbc:mysql://192.168.98.167:3307/sn_metrics?characterEncoding=utf-8&useSSL=false',
 'sink.username' = 'root',
 'sink.password' = 'buzhidao',
 'sink.sink.db' = 'sn_metrics',
 'sink.table.prefix' = 'test_',
 'sink.table.lower' = 'true',
 'sink.table-name' = '#{tableName}',
 'sink.driver' = 'com.mysql.jdbc.Driver',
 'sink.sink.buffer-flush.interval' = '2s',
 'sink.sink.buffer-flush.max-rows' = '100',
 'sink.sink.max-retries' = '5',
 'sink.auto.create' = 'true'
)
```

**Comment by Hello-Linux** [comment]
flink lib dir picture
<img width="366" alt="jar1" src="https://github.com/DataLinkDC/dinky/assets/17851645/36b680e9-1323-4e30-ae88-e3bc90da1ed0">

dinky/extends picture:

<img width="404" alt="jar2" src="https://github.com/DataLinkDC/dinky/assets/17851645/703bc0fe-6c61-425e-bff1-aa97b15b7b1b">

**Comment by Hello-Linux** [comment]
flink lib dir picture
<img width="381" alt="jar1" src="https://github.com/DataLinkDC/dinky/assets/17851645/02771b81-f84b-4337-a440-7f1c5f27ad63">

dinky/extends picture:
<img width="396" alt="jar2" src="https://github.com/DataLinkDC/dinky/assets/17851645/b51b2b67-654d-4bbc-80ef-9b04af6b03f3">

**Comment by Hello-Linux** [comment]
Dinky 任务截图
<img width="950" alt="001" src="https://github.com/DataLinkDC/dinky/assets/17851645/df4911cc-3d0c-43ad-8b24-835a2c2ad08c">

**Comment by Zzm0809** [comment]
升级到最新版本，并在任务中开启checkpoint

**Comment by Hello-Linux** [comment]
@Zzm0809  你好，目前观察同步成功了，另外我想知道文章里面提高的“MySQL CDC 的 Flink connector jar” 指的是flink-cdc-pipeline-connector-mysql-3.0.0.jar，还是flink-connector-mysql-cdc-3.0.0.jar？

另外这个“请确保已经在 Flink/lib 和 dinky/extends 目录下放置了 Jdbc 的 Flink connector jar” 指的是flink-connector-jdbc-3.0.0-1.16.jar对吧？

**Comment by Zzm0809** [comment]
> @Zzm0809  你好，目前观察同步成功了，另外我想知道文章里面提高的“MySQL CDC 的 Flink connector jar” 指的是flink-cdc-pipeline-connector-mysql-3.0.0.jar，还是flink-connector-mysql-cdc-3.0.0.jar？
> 
> 另外这个“请确保已经在 Flink/lib 和 dinky/extends 目录下放置了 Jdbc 的 Flink connector jar” 指的是flink-connector-jdbc-3.0.0-1.16.jar对吧？
> 

连接器版本不同，需要的不一样，这块dinky不会限制，按照cdc的具体版本具体放哪个包就行

**Comment by Hello-Linux** [comment]
@Zzm0809 好的，谢谢

**Comment by Hello-Linux** [comment]
@Zzm0809  另外这个sink.table.prefix 表前缀可以不加么？我想保持数据库名字不一样，但是里面表是跟原表保持一致的

**Comment by Hello-Linux** [comment]
@Zzm0809  其次我使用docker部署的dinky，默认是h2数据库，请问怎么持久化呢？每次重启就没有数据了

**Comment by Zzm0809** [comment]
> @Zzm0809  另外这个sink.table.prefix 表前缀可以不加么？我想保持数据库名字不一样，但是里面表是跟原表保持一致的

可以  看dinky官网

**Comment by Zzm0809** [comment]
> @Zzm0809  其次我使用docker部署的dinky，默认是h2数据库，请问怎么持久化呢？每次重启就没有数据了

看官网

**Comment by Hello-Linux** [comment]
@Zzm0809  另外dinky使用mysql CDC进行mysql全库同步数据到mysql的时候，是基于mysql binlog日志的CDC模式么？

**Comment by Zzm0809** [comment]
> @Zzm0809  另外dinky使用mysql CDC进行mysql全库同步数据到mysql的时候，是基于mysql binlog日志的CDC模式么？

看官网
