### ISSUE TITLE
[Bug] [Configuration Center] OSS bucket name invalid

### ISSUE THREAD

**Issue by bbccaaac** [DataLinkDC/dinky#3432]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Input other bucket name(not default) In Resource configure of Configure center.Unable to upload file.After tracing by arthas,I found   the bucket name was dinky.
![image](https://github.com/DataLinkDC/dinky/assets/11207733/0f62a2b8-9fd4-49fa-a03c-5343b6f1a19b)
![image](https://github.com/DataLinkDC/dinky/assets/11207733/2ced0817-f9f2-4c41-bbfb-64022efc82c1)

### What you expected to happen

Hope to fix this bug.

### How to reproduce

As mentioned above.

### Version

1.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
如果修改了资源配置中的某一配置项需要先禁用 `是否启用Resource` 配置项,然后再开启 来进行重新加载

**Comment by bbccaaac** [comment]
> 如果修改了资源配置中的某一配置项需要先禁用 `是否启用Resource` 配置项,然后再开启 来进行重新加载

禁用后再启用可以正常上传了
