### ISSUE TITLE
Regarding MySQLCDC, will the entire database be synchronized to MySQL and will read locks be added?

### ISSUE THREAD

**Issue by Hello-Linux** [DataLinkDC/dinky#3434]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

你好，flink cdc 2.0版本官方说是可以不用加读锁表了，我搭建的dinky 使用的flink版本是1.16.3，flink cdc版本是3.0，默认情况下dinky 使用flink sql 从binlog同步数据到mysql的过程中是不会加读锁的吧？

### Version

1.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
dinky 不做侵入,只做扩展,你去了解下 dinky 的定位吧
