### ISSUE TITLE
[Feature][Registration Center] Suggested that the Kubernetes application mode supports s3 or http

### ISSUE THREAD

**Issue by bbccaaac** [DataLinkDC/dinky#3437]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Since flink 1.19,k8s application can be submitted by s3 or http.[https://nightlies.apache.org/flink/flink-docs-release-1.19/docs/deployment/resource-providers/native_kubernetes/](https://nightlies.apache.org/flink/flink-docs-release-1.19/docs/deployment/resource-providers/native_kubernetes/)
Suggested that the Kubernetes application mode supports s3 or http in Dinky.

### Use case

Dinky in Docker is unable to upload jar file.Jar file are usually uploaded to s3 or other file service.

### Related issues

![image](https://github.com/DataLinkDC/dinky/assets/11207733/d02cdd12-7b09-4f4b-9cd3-cdb0ce247d71)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
你要来实现吗

**Comment by bbccaaac** [comment]
好我试试

**Comment by Zzm0809** [comment]
可以使用 init container , 或者自己打一个包含 app.jar 的dinky 镜像.

如果你对这个有兴趣可以来试着贡献下,但是需要等到 dinky-release-1.0.2 发布之后,或者基于 dev 分支,因为在上述版本中才添加了 Flink1.19 的支持,同时你需要考虑不同的 Flink 版本如何兼容, 创建的集群配置不可能都是 Flink1.19

**Comment by bbccaaac** [comment]
我今天看了下源码并做了一些测试，发现使用s3或http提交jar包到kubernetes application和dinky没什么关系，flink支持就行，也许可以关闭这个issue了
