### ISSUE TITLE
[Optimization][Devops] Dinky Devops FlinkWebUI can access directly And it may cause security issues

### ISSUE THREAD

**Issue by HejiaHo** [DataLinkDC/dinky#3441]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

Dinky proxy Flink dashboard, and it can directly access by `http://[dinky_host]:[dinky_port]/api/flink/localhost:8082/#/`, don't need Dinky auth. Flink dashboard can submit jar，and it can cause security issues.
I wish access Devops FlinkWebUI need Diny auth OR disable FlinkWebUI by setting property file.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
目前在 Dinky 内运维中心访问跳转时需要有 dinky 登录后的 token, 否则无法访问

**Comment by Zzm0809** [comment]
禁用jar 提交自行通过flink 配置文件控制, dinky 不介入这个

**Comment by HejiaHo** [comment]
> 目前在 Dinky 内运维中心访问跳转时需要有 dinky 登录后的 token, 否则无法访问

`http://[dinky_host]:[dinky_port]/api/flink/localhost:8082/#/` 经测试，通过该方式是可以直接访问的，不需要任何认证。无痕模式或者换个浏览器都可以访问到。

**Comment by gaoyan1998** [comment]
> > 目前在 Dinky 内运维中心访问跳转时需要有 dinky 登录后的 token, 否则无法访问
> 
> `http://[dinky_host]:[dinky_port]/api/flink/localhost:8082/#/` 经测试，通过该方式是可以直接访问的，不需要任何认证。无痕模式或者换个浏览器都可以访问到。

1.0.2 has fixd
