### ISSUE TITLE
[Bug] When PG configures the library, it reports an error: the enabled type operations of the task table are not uniform, some use bool for true, and some use numeric 1

### ISSUE THREAD

**Issue by Wang112233www** [DataLinkDC/dinky#3448]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

PG做配置库时执行报错：经查代码用bool的true，如： defaultFlinkSQLEnvTask.setEnabled(true);
一些代码用数字1，如：
public List getReleaseUDF() {
return list(new LambdaQueryWrapper()
.in(Task::getDialect, Dialect.JAVA.getValue(), Dialect.SCALA.getValue(), Dialect.PYTHON.getValue())
.eq(Task::getEnabled, 1)
.eq(Task::getStep, JobLifeCycle.PUBLISH.getValue())
.isNotNull(Task::getSavePointPath));
}

### What you expected to happen

PG做配置库时执行报错，建议统一用true/flase

### How to reproduce

PG做配置库时执行报错，建议统一用true/flase

### Version

1.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
已有pr。等1.1.0 release

**Comment by Wang112233www** [comment]
未彻底解决
