### ISSUE TITLE
[Bug] [Trivial] When copying a task, the create time will also be copied

### ISSUE THREAD

**Issue by suxinshuo** [DataLinkDC/dinky#3450]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

当复制任务的时候，新复制出来的任务使用的创建时间、更新时间还是被复制任务的，包括创建人、更新人也是没有重置
![image](https://github.com/DataLinkDC/dinky/assets/34018346/2f78bd76-4655-41b3-8d94-9796a7c8d0c3)

### What you expected to happen

复制任务应该只是复制任务内部的逻辑、任务配置等，不应该把创建人、创建时间这些也复制过来

### How to reproduce

使用复制功能即可重现问题
![image](https://github.com/DataLinkDC/dinky/assets/34018346/fa1f6a72-3db3-4425-ab2b-c6bc08e92535)

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
来优化一下？？

**Comment by suxinshuo** [comment]
> 来优化一下？？

ok
