### ISSUE TITLE
[Bug] [Minor] Copy task failed

### ISSUE THREAD

**Issue by suxinshuo** [DataLinkDC/dinky#3451]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

当复制任务的时候，报错失败
![image](https://github.com/DataLinkDC/dinky/assets/34018346/c89a657a-1fe2-4fe0-8451-80ff23bca120)

### What you expected to happen

复制任务的时候，会查询数据库中是否已经有同名的任务，然后在后面加后缀 `-(size+1)`，但是查询同名任务的 sql，使用的后缀是 `_[0-9]`，导致没有查到数据，实际上是存在的。建议统一成 "-" 或者 "_"
![image](https://github.com/DataLinkDC/dinky/assets/34018346/d69b46b1-69a2-4971-aa36-91e5e128ef1b)
![image](https://github.com/DataLinkDC/dinky/assets/34018346/eb0af5e8-8503-4d2e-bc4f-d0d622f3d036)

### How to reproduce

多次复制同一个任务
![image](https://github.com/DataLinkDC/dinky/assets/34018346/7679e774-273c-4fac-bf1e-d24690e4aff0)

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
来修复一下？？

**Comment by suxinshuo** [comment]
> 来修复一下？？

ok
