### ISSUE TITLE
[Optimization][web] update @antdesign/charts then npm install don‘t need --force

### ISSUE THREAD

**Issue by qppq54s** [DataLinkDC/dinky#3454]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

after update to @antdesign/charts@latest version，npm install will success without ’--force‘

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
你要来优化吗??

**Comment by qppq54s** [comment]
> 你要来优化吗??

我想尝试下

**Comment by Zzm0809** [comment]
> > 你要来优化吗??
> 
> 我想尝试下

ok, assigned
