### ISSUE TITLE
hub.docker.com Please push the latest image into it.

### ISSUE THREAD

**Issue by xiechao240** [DataLinkDC/dinky#3465]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

hub.docker.com 麻烦推送最新的镜像进去啊

### Use case

hub.docker.com 麻烦推送最新的镜像进去啊

### Related issues

hub.docker.com 麻烦推送最新的镜像进去啊

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xiechao240** [comment]
最新的1.0.2 麻烦推送一下最新的镜像进去

**Comment by Zzm0809** [comment]
你来推动啊

**Comment by xiechao240** [comment]
@Zzm0809  我没这本事啊。。。。。。。。

**Comment by Zzm0809** [comment]
> @Zzm0809 我没这本事啊。。。。。。。。

那你先用本地部署呗

**Comment by Hello-Linux** [comment]
@xiechao240  哈哈哈，自己本地使用官方的dockerfile构建一下就行了，官方更新速度很慢的。
