### ISSUE TITLE
Dinky's submission of flink tasks does not support oceanbase

### ISSUE THREAD

**Issue by pangfeihu** [DataLinkDC/dinky#3476]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

原因是dinky提交包的时候使用了hutool的类型推断功能，发生在org.dinky.app.db.DBUtil第47行， hutool类型推断中不包含oceanbase。

### What you expected to happen

希望希望支持oceanbase数据库。 

### How to reproduce

目前我采用的为yarn的application模式进行提交的，数据库驱动使用的是ocenbase驱动

### Version

1.0.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
如果是将 dinky 的数据库存储指定为 oceanbase 的话, 此建议不会支持, 不在社区规划内
