### ISSUE TITLE
Upgrade from 1.0.1 to 1.0.2, no version update displayed on the page

### ISSUE THREAD

**Issue by ljs033** [DataLinkDC/dinky#3483]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![微信图片_20240514222245](https://github.com/DataLinkDC/dinky/assets/34953192/3d08360f-6953-4e8c-9070-5c54627a6f02)
![微信图片_20240514222251](https://github.com/DataLinkDC/dinky/assets/34953192/e1a5c914-bcbd-405d-a143-cc2436067059)

### What you expected to happen

The page can synchronously display updated versions

### How to reproduce

I don't know

### Version

1.0.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
不明白你在表达什么

**Comment by ljs033** [comment]
执行升级脚本1.0.2_schema后，重启版本号没有更新为1.0.2

**Comment by Zzm0809** [comment]
> 执行升级脚本1.0.2_schema后，重启版本号没有更新为1.0.2

版本号在代码里 不在库里, 你下载 1.0.2 的 release 包,安装部署
