### ISSUE TITLE
When upgrading from version 1.0.1 to version 1.0.2, there are indeed fields in the dinky_task table: first_level_owner, second_level_owner

### ISSUE THREAD

**Issue by ljs033** [DataLinkDC/dinky#3484]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![微信图片_20240514223906](https://github.com/DataLinkDC/dinky/assets/34953192/35a788f2-45e5-4dfa-a35b-e2652173bc75)
![微信图片_20240514223914](https://github.com/DataLinkDC/dinky/assets/34953192/2b75eefb-471b-4c51-ad59-ed68919c5cac)

### What you expected to happen

Can smoothly upgrade

### How to reproduce

I can pack it myself, but there are fields added at the end of the ddl file in 1.0.0_schema

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
不要用 dev 打包,dev 是开发分支 有新功能 , 下载 github 已经发布的 release 包安装部署即可
