### ISSUE TITLE
[Bug] [metadata] Failed to query clickhouse table description information

### ISSUE THREAD

**Issue by suxinshuo** [DataLinkDC/dinky#3494]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

## 问题1: 查询 ck 表描述信息报错
![image](https://github.com/DataLinkDC/dinky/assets/34018346/fbfe3616-b377-4ab6-ac81-5a119234edc5)

问题原因: 当查询 clickhouse 描述信息的时候，如果表字段有 Array(String) 类型，查询会报错，是因为下面这行代码，replace 以后变成空字符串，转数字报错。
![image](https://github.com/DataLinkDC/dinky/assets/34018346/c87762c0-80c5-4eb0-878b-fac2eda7db56)

## 问题2: ck 表描述信息中，字段类型展示有误
例如下面这个表
![image](https://github.com/DataLinkDC/dinky/assets/34018346/33c36897-8b31-44c6-a7c9-2450625fcfac)
实际的字段类型
![image](https://github.com/DataLinkDC/dinky/assets/34018346/b707d484-051d-4636-932d-8f821a18c232)

### What you expected to happen

字段信息可以正常展示，如下图所示
![image](https://github.com/DataLinkDC/dinky/assets/34018346/050b8b1e-f363-4c6b-9f27-71287f22bf5a)

### How to reproduce

新建 clickhouse 表，包含 Array(String) 类型的字段，进入数据源查询页面查询该表的描述信息

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
社区无此环境进行修复, 如你有意愿可进行修复

**Comment by suxinshuo** [comment]
> 社区无此环境进行修复, 如你有意愿可进行修复

可以的

**Comment by Zzm0809** [comment]
> > 社区无此环境进行修复, 如你有意愿可进行修复
> 
> 可以的

已分配
