### ISSUE TITLE
[Bug] The job ran successfully, but the operation and maintenance center did not display the job status

### ISSUE THREAD

**Issue by ljs033** [DataLinkDC/dinky#3502]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![微信截图_20240516162917](https://github.com/DataLinkDC/dinky/assets/34953192/14ea3444-ef4b-4edf-9e40-08b6778b15b9)
![1715848199957](https://github.com/DataLinkDC/dinky/assets/34953192/a6abaf2e-bdda-4ada-95c5-a6fd97f3cf9f)
![微信截图_20240516163105](https://github.com/DataLinkDC/dinky/assets/34953192/19533c5a-f948-4a63-93ba-b2de883797c9)
![微信截图_20240516163032](https://github.com/DataLinkDC/dinky/assets/34953192/f9355589-dd46-4aff-a374-1f6efb227b73)

### What you expected to happen

作业提交并成功执行，但是运维中心无法查看该作业的运行情况。

### How to reproduce

同一个作业启动停止多次，或者更改启动模式在启动

### Version

1.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ljs033** [comment]
![微信图片_20240516210511](https://github.com/DataLinkDC/dinky/assets/34953192/ae3485f7-39cf-475f-b356-eeecd491f69c)
![微信图片_20240516210517](https://github.com/DataLinkDC/dinky/assets/34953192/4a7e48da-5941-4f9e-8633-96a41fbc6f39)
日志没报错

**Comment by ljs033** [comment]
![微信图片_20240518215502](https://github.com/DataLinkDC/dinky/assets/34953192/87770e15-5380-4f60-b188-5840b2845367)
你好，@github-actions，知道原因了是执行作业时间过长超过了flink job提交等待的时间了，有没有什么办法可以优化下，提高作业提交的效率

**Comment by Zzm0809** [comment]
> ![微信图片_20240518215502](https://private-user-images.githubusercontent.com/34953192/331806184-87770e15-5380-4f60-b188-5840b2845367.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNjc1OTcsIm5iZiI6MTcxNjE2NzI5NywicGF0aCI6Ii8zNDk1MzE5Mi8zMzE4MDYxODQtODc3NzBlMTUtNTM4MC00ZjYwLWIxODgtNTg0MGIyODQ1MzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDAxMDgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMTE5ZTVlMzZmNmJjMTYzNWFlNGVkMzNjOWIzNDAxYTgzMmI0MDJkZjM3OGI1MzA3YjI1ZjBmYjRlNTIwMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E7BW864YFgWg2kqRZATsbZtlGmi1sNJP_zumeEYnIZI) 你好，@github-actions，知道原因了是执行作业时间过长超过了flink job提交等待的时间了，有没有什么办法可以优化下，提高作业提交的效率

设置如下配置

![image](https://github.com/DataLinkDC/dinky/assets/58576849/8e594d54-79ac-428e-bf01-ba8005d66213)
