### ISSUE TITLE
[BUG] Error sending sse data:java.io.IOException: Broken pipe

### ISSUE THREAD

**Issue by Wang112233www** [DataLinkDC/dinky#3522]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

最新的版本编译后，后台报错：CST ERROR org.dinky.context.SseSessionContextHolder 61 lambda$checkHeart$0 - Error sending sse data:java.io.IOException: 断开的管道
前端显示：cannot read properties of undefined (reading 'data')

### What you expected to happen

最新的版本编译后，后台报错：CST ERROR org.dinky.context.SseSessionContextHolder 61 lambda$checkHeart$0 - Error sending sse data:java.io.IOException: 断开的管道
前端显示：cannot read properties of undefined (reading 'data')

### How to reproduce

最新的版本编译后，后台报错：CST ERROR org.dinky.context.SseSessionContextHolder 61 lambda$checkHeart$0 - Error sending sse data:java.io.IOException: 断开的管道
前端显示：cannot read properties of undefined (reading 'data')

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
1. 登录后右侧头像悬浮 找到`清除页面缓存`
2. Error sending sse data:java.io.IOException: 断开的管道 此问题无需关心,仅为后端长连接意外断开,不影响主流程
