### ISSUE TITLE
[Optimization][Catalog] Supports viewing the schema of SQL tables containing complex data types in catalog

### ISSUE THREAD

**Issue by 6-archer-9** [DataLinkDC/dinky#3532]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

Ⅰ.In the catalog list, it's not possible to view the table schema if it includes complex types
_1.When clicking to view the table structure under the catalog:_
<img width="316" alt="Snipaste_2024-05-24_17-16-39" src="https://github.com/DataLinkDC/dinky/assets/140578059/b39f0eb8-03fd-4d91-b831-83752c26c664">
<img width="795" alt="Snipaste_2024-05-24_17-14-15" src="https://github.com/DataLinkDC/dinky/assets/140578059/9fbcd606-acd4-4ff8-884c-a0bf7b9c392a">

_2.The situation leads to incorrect display,resulting in the following error:_
<img width="947" alt="Snipaste_2024-05-24_17-19-32" src="https://github.com/DataLinkDC/dinky/assets/140578059/c068b731-a477-46fb-88e0-2f23ef501893">

_3.The original table structure is:_
<img width="946" alt="Snipaste_2024-05-24_17-20-55" src="https://github.com/DataLinkDC/dinky/assets/140578059/77f29c01-4781-4b1e-a035-12518e3407b4">

_4.The reason for encountering this issue is due to the inclusion of some complex Flink types, such as:_
<img width="388" alt="Snipaste_2024-05-24_17-18-42" src="https://github.com/DataLinkDC/dinky/assets/140578059/b874e087-fcd2-45da-b5d9-eb1822f1c5f7">

**Looking forward to being able to view the structure of tables containing these data types.**

Ⅱ.The list of views is unavailable
<img width="307" alt="Snipaste_2024-05-24_17-28-29" src="https://github.com/DataLinkDC/dinky/assets/140578059/f579fdf1-4f32-4140-9649-6bdf33b71241">
<img width="266" alt="Snipaste_2024-05-24_17-28-50" src="https://github.com/DataLinkDC/dinky/assets/140578059/5ed8da99-46d1-4193-8deb-46d93f356b16">
For the created views, they appear duplicated in the tables list and can be clicked to view. However, clicking on the views in the views section does not produce any response. I'm not sure if this is a bug.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
你有兴趣来优化此功能吗?

**Comment by suxinshuo** [comment]
> 你有兴趣来优化此功能吗?

我看这个报错是由于找不到对应的 java type 报的空指针错误，从官网上我没有找到这几种复杂类型对应的 java type，对于这种，我们是不是可以暂时在 java 类型这里放个空，最起码不会报错导致表结构看不到 @Zzm0809 
![image](https://github.com/DataLinkDC/dinky/assets/34018346/7714ccde-bd53-47af-9f57-1b2a089a4c14)
![image](https://github.com/DataLinkDC/dinky/assets/34018346/8b929551-acf4-4776-8cf4-72a1013e31bf)

**Comment by Zzm0809** [comment]
> > 你有兴趣来优化此功能吗?
> 
> 我看这个报错是由于找不到对应的 java type 报的空指针错误，从官网上我没有找到这几种复杂类型对应的 java type，对于这种，我们是不是可以暂时在 java 类型这里放个空，最起码不会报错导致表结构看不到 @Zzm0809 ![image](https://private-user-images.githubusercontent.com/34018346/338852820-7714ccde-bd53-47af-9f57-1b2a089a4c14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NTEzNzYsIm5iZiI6MTcyMDQ1MTA3NiwicGF0aCI6Ii8zNDAxODM0Ni8zMzg4NTI4MjAtNzcxNGNjZGUtYmQ1My00N2FmLTlmNTctMWIyYTA4OWE0YzE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDE1MDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZmNlNTZiNDQ1Mjc0ZjVjYWU4ZjYzNDQ4MTJlN2RmODgxYjg4MTc4M2M0MWE1ODY3YTVhZTU0OTRhNmFlZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p0kuOXSN0TXc5uIpD1S86zdGxQjRDJSFusi5b7tPLiU) ![image](https://private-user-images.githubusercontent.com/34018346/338853856-8b929551-acf4-4776-8cf4-72a1013e31bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NTEzNzYsIm5iZiI6MTcyMDQ1MTA3NiwicGF0aCI6Ii8zNDAxODM0Ni8zMzg4NTM4NTYtOGI5Mjk1NTEtYWNmNC00Nzc2LThjZjQtNzJhMTAxM2UzMWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDE1MDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZmRiOTE3ZWQ0NTlmYzI2ZDkwOTdhNmQxZTk3NTIyYjQzYmY2MDJlOGE5OWJiMmNmYjk2YmQ2MWE0NTNhMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VorhSwoRop8DqF188c3gIZ9Ng389nsDaKLfNXpJsbrY)

未给出映射关系的统一默认 `string` 类型即可!! @suxinshuo
