### ISSUE TITLE
[Bug] [Local] Caused by: java.lang.NumberFormatException: For input string: 'abc'. Invalid character found

### ISSUE THREAD

**Issue by json-wei** [DataLinkDC/dinky#3533]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

在local  模式下执行 select CAST('abc' as int)；语句，无报错提示，正常页面因该提示类型转换错误，系统日志里面是存在报错的

### What you expected to happen

正常页面因该提示类型转换错误，控制台打印报错日志，提示类似ava.lang.NumberFormatException: For input string: 'abc'. Invalid character foun报错 ，execute job finished,status is Fail

### How to reproduce

![image](https://github.com/DataLinkDC/dinky/assets/40455758/c068db6c-7c82-494d-86a2-cd74a73532b3)

### Anything else

no

### Version

1.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
这个错误本身就应该是 flink 运行时抛出来的, 因为任务已经提交到 flink 上了,local 模式相当于是 flink 的 minicluster 具体看 flink 官网
