### ISSUE TITLE
An error is reported in the log when running flink cdc, and an error is also reported when saving.

### ISSUE THREAD

**Issue by wolfewf** [DataLinkDC/dinky#3535]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar document requirement.

### Description

运行flink cdc 时日志报错，保存时也报错

### Cause: java.sql.SQLException: Field 'name' doesn't have a default value
; Field 'name' doesn't have a default value; nested exception is java.sql.SQLException: Field 'name' doesn't have a default value

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfewf** [comment]
@aiwenmo 这个问题有结果了吗

**Comment by Zzm0809** [comment]
> @aiwenmo 这个问题有结果了吗

依赖问题导致 先把基础环境搞好，按照官网的dinky集成flink相关文档操作
