### ISSUE TITLE
mysql catalog script unable to connect

### ISSUE THREAD

**Issue by ljs033** [DataLinkDC/dinky#3541]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![微信截图_20240528095833](https://github.com/DataLinkDC/dinky/assets/34953192/bdffd160-6832-466e-a81f-479275722f47)
![微信图片_20240528095845](https://github.com/DataLinkDC/dinky/assets/34953192/9675692c-6330-4c77-afcc-1f3f0cd9d42e)
mysql catalog 无法连接上，但是和dinky访问的是同一个库，dinky访问数据库没问题

### What you expected to happen

在flinksqlEnv创建了一个mysql catalog，执行检查出错

### How to reproduce

能够创建连接mysql catalog

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
无法复现 排查下网络原因
