### ISSUE TITLE
[Bug] [MySQLCDC 整库到 MySQL] The default value for datetime should be `CURRENT_TIMESTAMP` instead of `'CURRENT_TIMESTAMP'`.

### ISSUE THREAD

**Issue by hepeitong** [DataLinkDC/dinky#3542]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I perform a full database synchronization and add `'sink.auto.create' = 'true'`, the sink side creates tables with the datetime data type defaulting to the string format `'CURRENT_TIMESTAMP'` instead of the datetime format `CURRENT_TIMESTAMP`.
![PixPin_2024-05-28_11-03-34](https://github.com/DataLinkDC/dinky/assets/49541649/c5d4ae1c-922a-4e3c-9dc8-715d827250d0)
![微信图片_20240528110054](https://github.com/DataLinkDC/dinky/assets/49541649/6739593d-6e91-4f63-9d0f-232328aa84ca)

### What you expected to happen

When I perform a full database synchronization and add `'sink.auto.create' = 'true'`, the sink side creates tables with the datetime data type defaulting to the string format `'CURRENT_TIMESTAMP'` instead of the datetime format `CURRENT_TIMESTAMP`.

### How to reproduce

Just find any table with a datetime attribute and let Dinky create it automatically.

### Version

1.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
已修复 等1.0.3发版
