### ISSUE TITLE
DECIMAL(38,null) of flink sql shows null

### ISSUE THREAD

**Issue by wolfewf** [DataLinkDC/dinky#3583]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/DataLinkDC/dinky/assets/31426089/c82f8832-651d-4c48-82e1-086476906e2a)

flink sql 的DECIMAL(38,null) 显示了null

### What you expected to happen

flink sql 的DECIMAL(38,null) 显示了null

### How to reproduce

flink sql 的DECIMAL(38,null) 显示了null

### Anything else

flink sql 的DECIMAL(38,null) 显示了null

### Version

1.0.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
What is the structure of your source table?

**Comment by wolfewf** [comment]
> What is the structure of your source table?

mysql @aiwenmo
