### ISSUE TITLE
[Bug] The FlinkJar task encountered runtime errors due to an excessive number of parameters during submission

### ISSUE THREAD

**Issue by 18216499322** [DataLinkDC/dinky#3587]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

The FlinkJar task encountered runtime errors due to an excessive number of parameters during submission,not sure if the Per-Job mode of the FlinkJar task has this issue

### What you expected to happen

The submission ran successfully without any issues

### How to reproduce

![image](https://github.com/DataLinkDC/dinky/assets/75019445/f534357a-8e2f-4c98-80e7-3dd04fe74ff8)
![企业微信截图_17180694251099](https://github.com/DataLinkDC/dinky/assets/75019445/04d52ca3-96b3-49b2-a1ec-a8162359f8db)

### Version

1.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Close global variable.

**Comment by gaoyan1998** [comment]
this issue is fixed, will be closed
