### ISSUE TITLE
The changed password is not synchronized to the database. After Dinky is restarted, the password is still the initial password.

### ISSUE THREAD

**Issue by littlebeandou** [DataLinkDC/dinky#3595]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

修改密码没有同步到数据库中，dinky重启后，密码还是初始密码

### What you expected to happen

修改密码没有同步到数据库中，dinky重启后，密码还是初始密码

### How to reproduce

修改密码没有同步到数据库中，dinky重启后，密码还是初始密码

### Version

1.0.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
What password to change?
