### ISSUE TITLE
[Optimization][Dinky-cdc] The package com.verica.cdc.connectors.shade.org.apache.kafka.connect.data does not exist

### ISSUE THREAD

**Issue by yclxf** [DataLinkDC/dinky#3596]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

**Issue desc**
[Optimization][Dinky-cdc] 当我通过Maven编译时，提示“程序包com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.data不存在”
It have a error as "The package com.verica.cdc.connectors.shade.org.apache.kafka.connect.data does not exist" when i "package/install with Maven".

**Dinky version**: 
1.0.2, 1.0.3 with flink 1.19

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yclxf** [comment]
<img width="1397" alt="image" src="https://github.com/DataLinkDC/dinky/assets/16517743/ee87bcb5-89be-4181-b115-90473183298f">

**Comment by yclxf** [comment]
<img width="199" alt="image" src="https://github.com/DataLinkDC/dinky/assets/16517743/6dfba8ee-42f8-4849-b482-52392bf66bf7">

**Comment by Zzm0809** [comment]
profile 不对 , 请阅读官网文档关于本地调试章节

**Comment by yclxf** [comment]
最后发现IDEA支持Maven有一些问题，就是在选择Maven的profiles选项时，install/packages运行时不生效，需要手工编辑运行配置。mvn clean package -DskipTests=true -P prod,flink-single-version,scala-2.12,aliyun,flink-1.19,web,fast 参考类似这种，把-P后面的参数加入即可解决问题。

**Comment by yclxf** [comment]
<img width="430" alt="image" src="https://github.com/DataLinkDC/dinky/assets/16517743/5f0586f0-cb9a-44d4-8235-ac81405fd3e0">
<img width="659" alt="image" src="https://github.com/DataLinkDC/dinky/assets/16517743/82dc6332-fc4b-4943-8c33-1c38eb13f219">

**Comment by aiwenmo** [comment]
Reload All Maven Projects.
