### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.conf.Configuration

### ISSUE THREAD

**Issue by wuguaner** [DataLinkDC/dinky#3600]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

第一次点查询报错如下
![1718694690314](https://github.com/DataLinkDC/dinky/assets/34933361/c9c102da-73d4-429a-9ac1-0bdd8cfd8ed4)
再点一次查询，报错如下
![1718694705467](https://github.com/DataLinkDC/dinky/assets/34933361/e9ed4606-4e90-493e-a33c-6d442db939e5)
依赖包都已经放进去了
![image](https://github.com/DataLinkDC/dinky/assets/34933361/224cf030-ecc6-4444-b49c-c7d78b50e436)

### What you expected to happen

无

### How to reproduce

无

### Anything else

无

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Please check if the startup script includes the dependency path.

**Comment by wuguaner** [comment]
docker方式部署的，路径都是对的，hadoop-common-3.3.2.jar 就是这个依赖包，去掉后就提示找不到包，放进去又提示无法初始化。
![1718759216245](https://github.com/DataLinkDC/dinky/assets/34933361/35445c39-bd09-40bf-be13-5f88b8c93cec)

**Comment by wuguaner** [comment]
done
