### ISSUE TITLE
[Optimization][dinky-cdc] Suggest to fix the dinky cdc integration issue after flink cdc upgraded from 3.1

### ISSUE THREAD

**Issue by medivh511** [DataLinkDC/dinky#3604]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

After the flink cdc released the new version 3.1, the whole project was developed under apache scope and package names all changed；If u integrate the latest flink cdc into dinky, the version conflict will happen, because the jar depandency and class import could not be found

1. The pom xml still contain the flink cdc package from ververica

![25ed0cb8b7d35fa781c49946c5047a1](https://github.com/DataLinkDC/dinky/assets/136689882/d9ebbb83-16b7-4fba-93aa-5f2d8528b688)

2. The cdc class still be imported from ververica

![1028bd703223251d13b95758b8acfc4](https://github.com/DataLinkDC/dinky/assets/136689882/638c4122-fecc-4cba-9ff7-9f1d00125ead)

**We hope dinky from 1.1 could catch up with the latest flink cdc!**

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
在 1.1.0 版本中会只使用最新的依赖,且不会做兼容,至此在 dinky1.1.0 及以后,最低 cdc 要求版本在 3.1+
