### ISSUE TITLE
1.0.3 version idea run debug

### ISSUE THREAD

**Issue by yimingtech** [DataLinkDC/dinky#3644]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://github.com/user-attachments/assets/5e8d1e72-9afd-46cd-a305-ee82ea425d7b)
1.0.3 版本，在本地 idea 里面运行 debug，一直报这个错误，任务提交不了；是不是缺少哪个依赖啊，我在 idea 里面打的 dinky-release-1.18-1.0.3.tar.gz；把相关 flink 依赖放到 lib 目录是可以提交任务的；

### Use case

![image](https://github.com/user-attachments/assets/2e261422-194e-43a8-b94b-6c7b1cc015ac)
我看 dinky-flink1.18 和 1.19 相关依赖都有的

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
看官网文档关于本地调试文档
