### ISSUE TITLE
[Bug] When dinky submitted flinksql, the entry class could not be found in Kubernetes Application mode.

### ISSUE THREAD

**Issue by YTQ419** [DataLinkDC/dinky#3645]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

想询问一下这个应该如何正确编写配置 解决这个问题
![8bce82ed7eacfab0196556524b151ddd](https://github.com/user-attachments/assets/aa1c1805-910a-4a6a-8e5a-5848c5f932df)
![4277f5b62b924f19906a205f1430378](https://github.com/user-attachments/assets/df8e87f2-84fd-4df1-aa4a-9f4501979839)

这是我的dockerfile

FROM flink:1.16.2-scala_2.12
# 创建用户库目录
RUN mkdir -p $FLINK_HOME/usrlib
RUN echo $FLINK_HOME
# 修改时区为 Asia/Shanghai
RUN rm -f /etc/localtime && ln -sv /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone
# 删除旧的 flink-K8S-1.0-SNAPSHOT.jar 文件
RUN if [ -d "$FLINK_HOME/lib" ]; then rm -rf $FLINK_HOME/lib/*; fi
#将dinky的相关jar包房入lib目录中
ADD extends $FLINK_HOME/lib
#将dinky的包放进去
COPY dinky-app-1.16-1.0.1-jar-with-dependencies.jar $FLINK_HOME/dinky-app-1.16-1.0.1-jar-with-dependencies.jar 
![c69ca2141250c95051f012cec4284a8](https://github.com/user-attachments/assets/f88acf88-cddd-409b-af8e-e30f05b9d30e)

### What you expected to happen

我不确定是哪里出现了问题

### How to reproduce

我提交上去就是显示找不到入口类

### Version

1.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
This error is meaningless, please provide a more complete log, thank you

**Comment by YTQ419** [comment]
> This error is meaningless, please provide a more complete log, thank you

![73a63bf06d7945ce27e94baef1c57ba](https://github.com/user-attachments/assets/19185ff8-6f12-48c2-9d73-478e89edecc4)

这是在dinky中出现的错误

**Comment by gaoyan1998** [comment]
> > This error is meaningless, please provide a more complete log, thank you
> 
> ![73a63bf06d7945ce27e94baef1c57ba](https://private-user-images.githubusercontent.com/71495889/348653124-19185ff8-6f12-48c2-9d73-478e89edecc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzUxMjEsIm5iZiI6MTcyMTAzNDgyMSwicGF0aCI6Ii83MTQ5NTg4OS8zNDg2NTMxMjQtMTkxODVmZjgtNmYxMi00OGMyLTlkNzMtNDc4ZTg5ZWRlY2M0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA5MTM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwY2MyNjQ0NDM1OTUwOWY3ZjlmMTNhMzE1MTYwZDExMjdjYzQyYjllMmM4OWUxODBhOTg5NDgzOTI5MzhhMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YqbNPKmDKJikTe3EB_-CuaL2k_xe8TRptXvCu23qWjs)
> 
> 这是在dinky中出现的错误
Please provide k8s log

**Comment by gaoyan1998** [comment]
Please provide k8s log

**Comment by YTQ419** [comment]
> This error is meaningless, please provide a more complete log, thank you

确实可以提交到k8s集群上，在k8s上面查看日志显示找不到入口类
![8bce82ed7eacfab0196556524b151ddd](https://github.com/user-attachments/assets/87f397d7-a268-4ce7-bc57-e4282eb3b9f3)

**Comment by gaoyan1998** [comment]
This error is not a class not found, please observe the error carefully, this is just a generic error that the task has failed, it doesn't make any sense for you to provide this log!

**Comment by YTQ419** [comment]
> This error is not a class not found, please observe the error carefully, this is just a generic error that the task has failed, it doesn't make any sense for you to provide this log!
这个是什么原因呀,是需要把dinky-app-1.15-1.0.0-SNAPSHOT-jar-with-dependencies.jar 这个包也放到lib目录下吗
![3e4e622ea0cbaff4fe97ea0b38bf6c4](https://github.com/user-attachments/assets/281610eb-9d19-4233-86ff-9ca6c4c2a564)

我都已经放到容器中了 
![image](https://github.com/user-attachments/assets/84214b72-b09a-4559-81b2-3d0c6f1eb583)
并且在注册中心已经指定 
![image](https://github.com/user-attachments/assets/19cdd13b-a903-4384-a31f-5848dd3faa2f)
