### ISSUE TITLE
Unable to connect to the Flink cluster to obtain the latest job status information?

### ISSUE THREAD

**Issue by Sdreamery** [DataLinkDC/dinky#3646]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Dinky正常运行Flink任务3天，第4天的时候与Flink集群脱离，但Flink集群及任务都正常且无报错信息，这是为什么？
![ebfa7ee940cf97ede4e70ec4877c499](https://github.com/user-attachments/assets/0fcfb399-049c-4756-9782-db463e6b1295)
![bbb8e2ac71557b6a97e9a710b226e13](https://github.com/user-attachments/assets/f1003e78-61cb-466c-ad04-b634b58c12fe)
![70898997f2230e207e6a69a5faa2fc0](https://github.com/user-attachments/assets/17c990ce-adcf-4ffd-b662-dc06d9dd3ff1)
![7cf5c1dd084cc70b94d68ebe1a6cc0c](https://github.com/user-attachments/assets/af80f2d0-cec3-48e9-a75e-afd8f0c302c7)

### What you expected to happen

感觉是yarn与Dinky集成的问题，但又不确定

### How to reproduce

使用yarn session模式，大概三四太难就会出现这种问题，已经测试过两次了

### Version

1.0.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
你jobmanager地址是不是变了？
