### ISSUE TITLE
Use flinksql to submit to k8s in application mode. The task can be submitted normally but the log cannot be viewed. Flink version 1.16.2

### ISSUE THREAD

**Issue by YTQ419** [DataLinkDC/dinky#3647]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

在提交任务的是时候任务可以正常提交但是查看不到日志
![image](https://github.com/user-attachments/assets/fbfed2c3-752f-488f-8f73-66f997905b6e)
但是我通过客户端提交是可以正常看到了日志输出的，
把本地提交的和使用dinky提交的pod.yaml 下载出来进行对比  shaole少了日志的相关配置
![image](https://github.com/user-attachments/assets/87de96f9-4c8c-4f12-9156-d0d674ccac80)

### What you expected to happen

期望可以正常看到日志输出

### How to reproduce

最简单的示例
![image](https://github.com/user-attachments/assets/1e31f8f3-a4d5-4002-9ba3-526acf59599a)

### Version

1.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by YTQ419** [comment]
![image](https://github.com/user-attachments/assets/9d13e0b3-6612-4d0c-af24-0f997bd5bd82)
这是在k8s中的日志

**Comment by gaoyan1998** [comment]
1. 本地 新建 /opt/flink/con目录
2.把flink 1.16的conf目录复制进去
3. dinky上面配置写/opt/flink/conf
4.再试试

**Comment by YTQ419** [comment]
> 1. 本地 新建 /opt/flink/con目录
>    2.把flink 1.16的conf目录复制进去
> 2. dinky上面配置写/opt/flink/conf
>    4.再试试
解决了一个 log这个日志可以正常输出
![image](https://github.com/user-attachments/assets/762c3e84-09a8-4945-a349-886e37df5dd3)
但是std out 还是不行
![image](https://github.com/user-attachments/assets/692947ad-a3cf-4474-b4a6-5c5abd7c1597)
我这里面已经加上打印了
![image](https://github.com/user-attachments/assets/26c7e6e2-1a57-42f1-ba14-8069044ce1f5)

**Comment by Zzm0809** [comment]
运维中心的数据都是从 flink 的 rest api 获取的, flink 有就是有,flink 没有也就拿不到, 需要排查一下你的 flink 集群相关问题
