### ISSUE TITLE
When synchronizing data to doris, do I have to create tables in doris in advance?

### ISSUE THREAD

**Issue by QuintinLuke** [DataLinkDC/dinky#3657]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

同步数据到doris中时，必须要提前在doris中建表吗？

### What you expected to happen

能否自动同步，不用在doris中建表

### How to reproduce

能否自动同步，不用在doris中建表

### Anything else

能否自动同步，不用在doris中建表

### Version

1.0.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
目前支持 mysql, doris 自动建表

**Comment by QuintinLuke** [comment]
> 目前支持 mysql, doris 自动建表

我是从oracle同步到doris，采用cdcsource的模式，必须要先在doris先建表吗？
