### ISSUE TITLE
I am synchronizing from Oracle to Doris using cdcsource mode. Do I have to create the table in Doris first?

### ISSUE THREAD

**Issue by QuintinLuke** [DataLinkDC/dinky#3658]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

我是从oracle同步到doris，采用cdcsource的模式，必须要先在doris先建表吗？

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
需要
