### ISSUE TITLE
Using dinky1.0.3 version, synchronizing mysql to doris2.0.6 reports an error

### ISSUE THREAD

**Issue by QuintinLuke** [DataLinkDC/dinky#3668]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

org.apache.doris.flink.sink.DorisSink(594): Doris FE's response cannot map to schema. res: "errCode=7,detailMessage=unknowntable,tableName=test" org.apache.doris.shaded.com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type int from String "errCode=7,detailMessage=unknowntable,tableName=test": not a valid int value 

### What you expected to happen

org.apache.doris.flink.sink.DorisSink(594): Doris FE's response cannot map to schema. res: "errCode=7,detailMessage=unknowntable,tableName=test" org.apache.doris.shaded.com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type int from String "errCode=7,detailMessage=unknowntable,tableName=test": not a valid int value 

### How to reproduce

org.apache.doris.flink.sink.DorisSink(594): Doris FE's response cannot map to schema. res: "errCode=7,detailMessage=unknowntable,tableName=test" org.apache.doris.shaded.com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type int from String "errCode=7,detailMessage=unknowntable,tableName=test": not a valid int value 

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
根据提供的日志,属于 doris 端出现的问题,不在 dinky侧,需要自行解决该问题
