### ISSUE TITLE
Oracle  Date converter is not available

### ISSUE THREAD

**Issue by ljs033** [DataLinkDC/dinky#3673]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![微信图片_20240727094340](https://github.com/user-attachments/assets/241dfba8-9b46-40d5-bca0-b1c547c815f4)
使用oracle日期转换器存在许多问题：
1.timestamp类型无法转换成：'yyyy-MM-dd HH:mm:ss.SSS');
2.date类型在增量写入时候没转换并把转换格式带入：TO_DATE('2025-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')

### What you expected to happen

在整库同步中使用了日期转换器  
'debezium.converters'='dinkyDateConverter',
  'debezium.dinkyDateConverter.type'='org.dinky.cdc.debezium.converter.OracleDebeziumConverter',
  'debezium.dinkyDateConverter.database.type'='oracle',
  'debezium.dinkyDateConverter.format.date'='yyyy-MM-dd',
  'debezium.dinkyDateConverter.format.timestamp' = 'yyyy-MM-dd HH:mm:ss.SSS'

### How to reproduce

期望CDC获取oracle日期类型，能够将时间戳转换成正确的日期格式

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
建议看一下 flink 关于数据类型的映射关系
