### ISSUE TITLE
[Bug] [Data Development] The name of the copied job cannot be changed. After the copied job is renamed, and then copied based on this job, the name will be the name of the first copied job, and when it is submitted to k8s for running, the job name will not take effect.

### ISSUE THREAD

**Issue by 617450941** [DataLinkDC/dinky#3678]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

[Bug] [数据开发] 作业复制 名字改不过来 复制的作业再改名字后 再基于这个作业复制  出来的名字是第一个复制的作业的名字  并且投递到k8s运行 作业名字也是不生效的 还是之前复制对象的作业的名字

### What you expected to happen

[Bug] [数据开发] 作业复制 名字改不过来 复制的作业再改名字后 再基于这个作业复制  出来的名字是第一个复制的作业的名字  并且投递到k8s运行 作业名字也是不生效的 还是之前复制对象的作业的名字

### How to reproduce

[Bug] [数据开发] 作业复制 名字改不过来 复制的作业再改名字后 再基于这个作业复制  出来的名字是第一个复制的作业的名字  并且投递到k8s运行 作业名字也是不生效的 还是之前复制对象的作业的名字

### Anything else

[Bug] [数据开发] 作业复制 名字改不过来 复制的作业再改名字后 再基于这个作业复制  出来的名字是第一个复制的作业的名字  并且投递到k8s运行 作业名字也是不生效的 还是之前复制对象的作业的名字

### Version

1.0.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
提供复现步骤, 目前 dev 最新代码无法复现

**Comment by gaoyan1998** [comment]
I have reproduced it, I saw you checked `Yes I am willing to submit a PR!' ` Are you willing to fix this problem？, I can Assignees this issue to you

**Comment by Zzm0809** [comment]
升级最新版本看是否仍存在此问题
@617450941

**Comment by 617450941** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
