### ISSUE TITLE
[Bug] flink1.14 ,scala-2.11 java.lang.NoSuchMethodError: scala.Predef$.refArrayOps

### ISSUE THREAD

**Issue by chenhaipeng** [DataLinkDC/dinky#3680]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

version info
jdk1.8 ,flink1.14 ,scala-2.11 , dinky1.0.3
when i use command compiled package , 
`mvn clean package -U -DskipTests=true -P prod,flink-single-version,scala-2.11,aliyun,flink-1.14,web`
i got `dinky-release-1.14-1.0.3.tgz`, but  i doesn't work well and there is the following error

```
Caused by: java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
	at org.apache.flink.table.planner.delegation.PlannerBase.<init>(PlannerBase.scala:109) ~[flink-table-planner_2.11-1.14.6.jar:1.14.6]
	at org.apache.flink.table.planner.delegation.StreamPlanner.<init>(StreamPlanner.scala:52) ~[flink-table-planner_2.11-1.14.6.jar:1.14.6]
	at org.apache.flink.table.planner.delegation.DefaultPlannerFactory.create(DefaultPlannerFactory.java:61) ~[flink-table-planner_2.11-1.14.6.jar:1.14.6]
	at org.apache.flink.table.factories.PlannerFactoryUtil.createPlanner(PlannerFactoryUtil.java:50) ~[flink-table_2.11-1.14.6.jar:1.14.6]
	at org.dinky.executor.CustomTableEnvironmentImpl.create(CustomTableEnvironmentImpl.java:159) ~[dinky-client-1.14-1.0.3.jar:?]
	at org.dinky.executor.CustomTableEnvironmentImpl.create(CustomTableEnvironmentImpl.java:122) ~[dinky-client-1.14-1.0.3.jar:?]
	at org.dinky.executor.LocalStreamExecutor.createCustomTableEnvironment(LocalStreamExecutor.java:72) ~[dinky-core-1.0.3.jar:?]
	at org.dinky.executor.Executor.init(Executor.java:161) ~[dinky-core-1.0.3.jar:?]
	at org.dinky.executor.LocalStreamExecutor.<init>(LocalStreamExecutor.java:67) ~[dinky-core-1.0.3.jar:?]
	at org.dinky.executor.ExecutorFactory.buildLocalExecutor(ExecutorFactory.java:52) ~[dinky-core-1.0.3.jar:?]
	at org.dinky.executor.ExecutorFactory.buildExecutor(ExecutorFactory.java:44) ~[dinky-core-1.0.3.jar:?]
	at org.dinky.job.JobManager.init(JobManager.java:225) ~[dinky-core-1.0.3.jar:?]
	at org.dinky.job.JobManager.build(JobManager.java:203) ~[dinky-core-1.0.3.jar:?]
	at org.dinky.service.task.FlinkSqlTask.getJobManager(FlinkSqlTask.java:73) ~[dinky-admin-1.0.3.jar:?]
	at org.dinky.service.task.FlinkSqlTask.<init>(FlinkSqlTask.java:52) ~[dinky-admin-1.0.3.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_392]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_392]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_392]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_392]
	at cn.hutool.core.util.ReflectUtil.newInstance(ReflectUtil.java:873) ~[hutool-all-5.8.27.jar:5.8.27]
	at org.dinky.service.task.BaseTask.getTask(BaseTask.java:67) ~[dinky-admin-1.0.3.jar:?]
	at org.dinky.service.impl.TaskServiceImpl.explainTask(TaskServiceImpl.java:481) ~[dinky-admin-1.0.3.jar:?]
	at org.dinky.service.impl.TaskServiceImpl$$FastClassBySpringCGLIB$$22087f7c.invoke(<generated>) ~[dinky-admin-1.0.3.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.dinky.aop.UdfClassLoaderAspect.round(UdfClassLoaderAspect.java:55) ~[dinky-admin-1.0.3.jar:?]
	... 89 more
```
<img width="1716" alt="image" src="https://github.com/user-attachments/assets/3e37ea12-6354-4e10-8111-c47de81c11be">

### What you expected to happen

At first, I suspected it was an issue with my Scala compilation. I have already changed all the Scala versions in the pom file to 2.11, but the problem still persists.
<img width="1618" alt="image" src="https://github.com/user-attachments/assets/e54e6b3f-d4da-4ede-b190-29f87ff88986">

### How to reproduce

1. compile with scala2.11 and flink1.14 `mvn clean package -U -DskipTests=true -P prod,flink-single-version,scala-2.11,aliyun,flink-1.14,web`
2. add into extends
flink-table_2.11-1.4.2.jar
flink-scala_2.11-1.14.6.jar
flink-table-runtime_2.11-1.14.6.jar
flink-table-planner_2.11-1.14.6.jar

### Version

1.0.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chenhaipeng** [comment]
> Hello @chenhaipeng, this issue is about web, so I assign it to @Zzm0809. If you have any questions, you can comment and reply.
> 
> 你好 @chenhaipeng, 这个 issue 是关于 web 的，所以我把它分配给了 @Zzm0809。如有任何问题，可以评论回复。

不是一个web的bug， scala的兼容问题，我不知道如何解决，我已经在所有地方指定scala的版本

**Comment by chenhaipeng** [comment]
`mvn dependency:tree` there is dependency for scala

<img width="1660" alt="image" src="https://github.com/user-attachments/assets/f2e031d2-19c4-4de5-bd9b-9ce2d6fe8faf">

**Comment by Zzm0809** [comment]
非 dinky 问题, scala 兼容性问题 , 可添加 [scala-library](https://mvnrepository.com/artifact/org.scala-lang/scala-library)

另: scala-1.11 将在 dinky-v1.1.0 中移除

**Comment by chenhaipeng** [comment]
> 非 dinky 问题, scala 兼容性问题 , 可添加 [scala-library](https://mvnrepository.com/artifact/org.scala-lang/scala-library)
> 
> 另: scala-1.11 将在 dinky-v1.1.0 中移除

意思是要添加scal scala-library-2.11.12.jar吗，还是把jar 添加到pom里面，我测试的版本是v1.0.3 基于源码自己编译的

**Comment by chenhaipeng** [comment]
在lib 目录增加scala-library-2.11.12.jar 解决，话说pom 里面是不是需要添加     才对
```
 <dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala-library</artifactId>
      <version>${scala.version}</version>
</dependency>
```

**Comment by Zzm0809** [comment]
> > 非 dinky 问题, scala 兼容性问题 , 可添加 [scala-library](https://mvnrepository.com/artifact/org.scala-lang/scala-library)
> > 另: scala-1.11 将在 dinky-v1.1.0 中移除
> 
> 意思是要添加scal scala-library-2.11.12.jar吗，还是把jar 添加到pom里面，我测试的版本是v1.0.3 基于源码自己编译的

放在部署 lib 下 或者 extends 下即可

**Comment by Zzm0809** [comment]
> 在lib 目录增加scala-library-2.11.12.jar 解决，话说pom 里面是不是需要添加 才对
> 
> ```
>  <dependency>
>       <groupId>org.scala-lang</groupId>
>       <artifactId>scala-library</artifactId>
>       <version>${scala.version}</version>
> </dependency>
> ```

只有 scala-1.11 才有可能出现此问题, 在 dinky-v1.1.0 发布后不再支持切换 scala 版本, 默认只有 scala-2.12

**Comment by chenhaipeng** [comment]
> > 在lib 目录增加scala-library-2.11.12.jar 解决，话说pom 里面是不是需要添加 才对
> > ```
> >  <dependency>
> >       <groupId>org.scala-lang</groupId>
> >       <artifactId>scala-library</artifactId>
> >       <version>${scala.version}</version>
> > </dependency>
> > ```
> 
> 只有 scala-1.11 才有可能出现此问题, 在 dinky-v1.1.0 发布后不再支持切换 scala 版本, 默认只有 scala-2.12

scala-2.11 也有

**Comment by Zzm0809** [comment]
> > > 在lib 目录增加scala-library-2.11.12.jar 解决，话说pom 里面是不是需要添加 才对
> > > ```
> > >  <dependency>
> > >       <groupId>org.scala-lang</groupId>
> > >       <artifactId>scala-library</artifactId>
> > >       <version>${scala.version}</version>
> > > </dependency>
> > > ```
> > 
> > 只有 scala-1.11 才有可能出现此问题, 在 dinky-v1.1.0 发布后不再支持切换 scala 版本, 默认只有 scala-2.12
> 
> scala-2.11 也有

不太明白你意思，官方发布包基于scala-2.12,目前不会有此问题。无法复现。

**Comment by chenhaipeng** [comment]
> > > > 在lib 目录增加scala-library-2.11.12.jar 解决，话说pom 里面是不是需要添加 才对
> > > > ```
> > > >  <dependency>
> > > >       <groupId>org.scala-lang</groupId>
> > > >       <artifactId>scala-library</artifactId>
> > > >       <version>${scala.version}</version>
> > > > </dependency>
> > > > ```
> > > 
> > > 
> > > 只有 scala-1.11 才有可能出现此问题, 在 dinky-v1.1.0 发布后不再支持切换 scala 版本, 默认只有 scala-2.12
> > 
> > 
> > scala-2.11 也有
> 
> 不太明白你意思，官方发布包基于scala-2.12,目前不会有此问题。无法复现。
mvn clean package -U -DskipTests=true -P prod,flink-single-version,scala-2.11,aliyun,flink-1.14,web, 指定为scala-2.11 会出现这个问题

**Comment by chenhaipeng** [comment]
另外测试更新：
指定scala-2.11 没有效果，因为dinky-shaded-paimon 依赖 paimon-common， paimon-common 的包是基于scala-2.12 编译
<img width="977" alt="image" src="https://github.com/user-attachments/assets/6eeadc42-3fa1-4507-8be9-7c971d66a194">
![image](https://github.com/user-attachments/assets/3a96b4fb-245f-4055-8f29-8db1f2b59f49)
这个问题无法闭环

**Comment by Zzm0809** [comment]
> 另外测试更新：
> 指定scala-2.11 没有效果，因为dinky-shaded-paimon 依赖 paimon-common， paimon-common 的包是基于scala-2.12 编译
> <img width="977" alt="image" src="https://github.com/user-attachments/assets/6eeadc42-3fa1-4507-8be9-7c971d66a194">
> ![image](https://github.com/user-attachments/assets/3a96b4fb-245f-4055-8f29-8db1f2b59f49)
> 这个问题无法闭环

dev分支不需要指定scala版本

**Comment by chenhaipeng** [comment]
> > 另外测试更新：
> > 指定scala-2.11 没有效果，因为dinky-shaded-paimon 依赖 paimon-common， paimon-common 的包是基于scala-2.12 编译
> > <img alt="image" width="977" src="https://private-user-images.githubusercontent.com/6678954/354249797-6eeadc42-3fa1-4507-8be9-7c971d66a194.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NzQ4NDcsIm5iZiI6MTcyMjU3NDU0NywicGF0aCI6Ii82Njc4OTU0LzM1NDI0OTc5Ny02ZWVhZGM0Mi0zZmExLTQ1MDctOGJlOS03Yzk3MWQ2NmExOTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMDQ1NTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTJkNWY3ZmQ3YjZmMWVjNDIxZTIzYmIwNDJmMWE3ZjVhYTJkODZkMzlkMmE3Y2UyMWY0OGQxMzU4NzRlMzQzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-pDUx4X8YjDQb1xXANSsMiXLOICPvzle3iuaIWan_xI">
> > ![image](https://private-user-images.githubusercontent.com/6678954/354250710-3a96b4fb-245f-4055-8f29-8db1f2b59f49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NzQ4NDcsIm5iZiI6MTcyMjU3NDU0NywicGF0aCI6Ii82Njc4OTU0LzM1NDI1MDcxMC0zYTk2YjRmYi0yNDVmLTQwNTUtOGYyOS04ZGIxZjJiNTlmNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMDQ1NTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzYzNWVkY2U2YzgzYTNhZmM4Y2Q0MGU3ZmJiMmQ2MGYxNDlkNzBmNjM1YWRkMGY1OGZhOTkzN2FmMzAwMWFiZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PECLydZKmDg-ZNTVAWdSiT8MqSQUxoNikyphYDsyzjs)
> > 这个问题无法闭环
> 
> dev分支不需要指定scala版本

不是这个意思，拉一个后端的进来，我的意思是，v1.0.3 版本无论是否指定scala-2.11 版本都没有意义，因为引用的paimon 是基于scala-2.12 编译的，导致功能有问题

**Comment by gaoyan1998** [comment]
> > > 另外测试更新：
> > > 指定scala-2.11 没有效果，因为dinky-shaded-paimon 依赖 paimon-common， paimon-common 的包是基于scala-2.12 编译
> > > <img alt="image" width="977" src="https://private-user-images.githubusercontent.com/6678954/354249797-6eeadc42-3fa1-4507-8be9-7c971d66a194.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NzQ4NDcsIm5iZiI6MTcyMjU3NDU0NywicGF0aCI6Ii82Njc4OTU0LzM1NDI0OTc5Ny02ZWVhZGM0Mi0zZmExLTQ1MDctOGJlOS03Yzk3MWQ2NmExOTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMDQ1NTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTJkNWY3ZmQ3YjZmMWVjNDIxZTIzYmIwNDJmMWE3ZjVhYTJkODZkMzlkMmE3Y2UyMWY0OGQxMzU4NzRlMzQzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-pDUx4X8YjDQb1xXANSsMiXLOICPvzle3iuaIWan_xI">
> > > ![image](https://private-user-images.githubusercontent.com/6678954/354250710-3a96b4fb-245f-4055-8f29-8db1f2b59f49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NzQ4NDcsIm5iZiI6MTcyMjU3NDU0NywicGF0aCI6Ii82Njc4OTU0LzM1NDI1MDcxMC0zYTk2YjRmYi0yNDVmLTQwNTUtOGYyOS04ZGIxZjJiNTlmNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMDQ1NTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzYzNWVkY2U2YzgzYTNhZmM4Y2Q0MGU3ZmJiMmQ2MGYxNDlkNzBmNjM1YWRkMGY1OGZhOTkzN2FmMzAwMWFiZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PECLydZKmDg-ZNTVAWdSiT8MqSQUxoNikyphYDsyzjs)
> > > 这个问题无法闭环
> > 
> > 
> > dev分支不需要指定scala版本
> 
> 不是这个意思，拉一个后端的进来，我的意思是，v1.0.3 版本无论是否指定scala-2.11 版本都没有意义，因为引用的paimon 是基于scala-2.12 编译的，导致功能有问题

1.1.0已经取消paimon强依赖，后续计划作为可选

**Comment by chenhaipeng** [comment]
> > > > 另外测试更新：
> > > > 指定scala-2.11 没有效果，因为dinky-shaded-paimon 依赖 paimon-common， paimon-common 的包是基于scala-2.12 编译
> > > > <img alt="image" width="977" src="https://private-user-images.githubusercontent.com/6678954/354249797-6eeadc42-3fa1-4507-8be9-7c971d66a194.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NzQ4NDcsIm5iZiI6MTcyMjU3NDU0NywicGF0aCI6Ii82Njc4OTU0LzM1NDI0OTc5Ny02ZWVhZGM0Mi0zZmExLTQ1MDctOGJlOS03Yzk3MWQ2NmExOTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMDQ1NTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTJkNWY3ZmQ3YjZmMWVjNDIxZTIzYmIwNDJmMWE3ZjVhYTJkODZkMzlkMmE3Y2UyMWY0OGQxMzU4NzRlMzQzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-pDUx4X8YjDQb1xXANSsMiXLOICPvzle3iuaIWan_xI">
> > > > ![image](https://private-user-images.githubusercontent.com/6678954/354250710-3a96b4fb-245f-4055-8f29-8db1f2b59f49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NzQ4NDcsIm5iZiI6MTcyMjU3NDU0NywicGF0aCI6Ii82Njc4OTU0LzM1NDI1MDcxMC0zYTk2YjRmYi0yNDVmLTQwNTUtOGYyOS04ZGIxZjJiNTlmNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMDQ1NTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzYzNWVkY2U2YzgzYTNhZmM4Y2Q0MGU3ZmJiMmQ2MGYxNDlkNzBmNjM1YWRkMGY1OGZhOTkzN2FmMzAwMWFiZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PECLydZKmDg-ZNTVAWdSiT8MqSQUxoNikyphYDsyzjs)
> > > > 这个问题无法闭环
> > > 
> > > 
> > > dev分支不需要指定scala版本
> > 
> > 
> > 不是这个意思，拉一个后端的进来，我的意思是，v1.0.3 版本无论是否指定scala-2.11 版本都没有意义，因为引用的paimon 是基于scala-2.12 编译的，导致功能有问题
> 
> 1.1.0已经取消paimon强依赖，后续计划作为可选

v1.1.0 官方没有提供了scala-2.11的版本，如果我修改pom.xml 的scala 依赖为scala-2.11 功能有影响吗，我这边项目比较旧，依赖的组件还是hadoop 是2.7.5 ，flink 是1.14.6-scala-2.11

**Comment by aiwenmo** [comment]
scala-2.12 的 dinky 往 scala-2.11 的flink 提交应该可以兼容，试试看

**Comment by chenhaipeng** [comment]
> scala-2.12 的 dinky 往 scala-2.11 的flink 提交应该可以兼容，试试看

我重新用dinky 1.1.0, 修改里面pom scala 版本，已经测试可以了
