### ISSUE TITLE
Each time you restart the dinky1.1 version, tasks are cleared

### ISSUE THREAD

**Issue by laixueyong** [DataLinkDC/dinky#3682]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "select id, tenant_id, name, task_id, step, cluster_id, jid, status, history_id, error, create_time, update_time, finish_time, duration, failed_restart_count, creator, updater, operator from dinky_job_instance where (id in ()[*]) and tenant_id = 1"; expected "NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
SELECT id, tenant_id, name, task_id, step, cluster_id, jid, status, history_id, error, create_time, update_time, finish_time, duration, failed_restart_count, creator, updater, operator FROM dinky_job_instance WHERE (id IN ()) AND tenant_id = 1 [42001-200]

### What you expected to happen

底层源码查询有误sqlCaused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "select id, tenant_id, name, task_id, step, cluster_id, jid, status, history_id, error, create_time, update_time, finish_time, duration, failed_restart_count, creator, updater, operator from dinky_job_instance where (id in ()[*]) and tenant_id = 1"; expected "NOT, EXISTS, INTERSECTS, UNIQUE"; SQL statement:
SELECT id, tenant_id, name, task_id, step, cluster_id, jid, status, history_id, error, create_time, update_time, finish_time, duration, failed_restart_count, creator, updater, operator FROM dinky_job_instance WHERE (id IN ()) AND tenant_id = 1 [42001-200]

### How to reproduce

下载1.1版本然后在web上制造几个文件夹 然后在次重启dinky 任务消失

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
H2仅用于快速体验，正式使用请不要使用h2，换mysql
