### ISSUE TITLE
 The rights of the common tenant cannot be used to view any web function. Common users can use the rights of the super tenant only

### ISSUE THREAD

**Issue by laixueyong** [DataLinkDC/dinky#3683]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

创建一个普通用户绑定普通的租户 选择角色权限后  选择普通用户登录后没有权限去看任意功能 做不到权限控制

### What you expected to happen

创建一个普通用户绑定普通的租户 选择角色权限后 选择普通用户登录后没有权限去看任意功能 做不到权限控制

### How to reproduce

这个功能1.1版本不知道有没有实现 旧版本是可以的

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
![5e293de436f70e39717724bd9e32d08c](https://github.com/user-attachments/assets/7d8d4ff0-a8f0-4286-8f02-50f782f7884b)

**Comment by laixueyong** [comment]
哪如果生产上想分配一个用户给其他人但是又不想给他看其他的一些任务 不就做不到权限控制

**Comment by Zzm0809** [comment]
> 哪如果生产上想分配一个用户给其他人但是又不想给他看其他的一些任务 不就做不到权限控制 
> 

你想要的是更细粒度的资源类型的权限控制  目前dinky暂时无精力去实现。如你对此需求较为强烈，可进行二开实现，如你实现后有意愿贡献，欢迎提pr
