### ISSUE TITLE
[Improvement][web] Optimize the worker's place page display

### ISSUE THREAD

**Issue by suxinshuo** [DataLinkDC/dinky#3689]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

dinky 1.1.0 版本新增的工作台页面，在 chrome 浏览器上展示格式有点乱，可以稍微改一下样式
![image](https://github.com/user-attachments/assets/37ca4048-f52b-4264-a113-ba85051317b2)
改动后: 
![image](https://github.com/user-attachments/assets/4364ed70-ddf6-41c0-97b4-c48f9a3b27e5)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
thanks，Very good job, it has been assigned to you
