### ISSUE TITLE
[Bug] [Docker] v1.1.0 Docker image not uploaded to Dockerhub

### ISSUE THREAD

**Issue by wowq** [DataLinkDC/dinky#3691]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

v1.1.0 Docker镜像未上传到Dockerhub

### What you expected to happen

v1.1.0 Docker镜像上传到Dockerhub

### How to reproduce

v1.1.0 Docker镜像上传到Dockerhub

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
finished
