### ISSUE TITLE
[Bug] [Cluster Configuration] There is a problem with the display of custom drop-down options in the cluster

### ISSUE THREAD

**Issue by 617450941** [DataLinkDC/dinky#3692]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

粘贴一个选项名字进去 然后下拉拖动 会出现多个重复选项
https://s17.aconvert.com/convert/p3r68-cdx67/zraem-khlr4.gif

### What you expected to happen

key重复之类的

### How to reproduce

粘贴一个选项名字进去 然后下拉拖动 会出现多个重复选项

### Version

1.0.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
看不到粘贴的图
