### ISSUE TITLE
[Bug] [migrate] failed to start service via postgres 

### ISSUE THREAD

**Issue by xiaoxiaodek** [DataLinkDC/dinky#3695]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. failed start dinky service by docker-compose var dinkydocker/dinky:1.1.0-flink1.17

```shell
[dinky] 2024-08-07 16:27:28.565  ERROR    62 --- [           main] org.springframework.boot.SpringApplication: Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gitController' defined in URL [jar:file:/opt/dinky/lib/dinky-admin-1.1.0.jar!/org/dinky/controller/GitController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gitProjectServiceImpl': Unsatisfied dependency expressed through field 'baseMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gitProjectMapper' defined in URL [jar:file:/opt/dinky/lib/dinky-admin-1.1.0.jar!/org/dinky/mapper/GitProjectMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionTemplate'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/dinky/configure/DatabaseFlywayMigration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V20240729.1.1.0__release.sql failed
---------------------------------------------
SQL State  : 23505
Error Code : 0
Message    : ERROR: duplicate key value violates unique constraint "dinky_sys_menu_pkey"
  Detail: Key (id)=(2) already exists.
Location   : db/migration/pgsql/V20240729.1.1.0__release.sql (/opt/dinky/file:/opt/dinky/lib/dinky-admin-1.1.0.jar!/db/migration/pgsql/V20240729.1.1.0__release.sql)
Line       : 6
Statement  : INSERT INTO public.dinky_sys_menu (parent_id, name, path, component, perms, icon, type, display, order_num,
                                   create_time, update_time, note)
VALUES (164, '仪表盘列表', '/dashboard/list', './Dashboard', 'dashboard:list', 'UnorderedListOutlined', 'F', 0, 167,
        '2024-07-29 15:37:46', '2024-07-29 15:37:46', NULL)
```

### What you expected to happen

The service was successfully started

### How to reproduce

```shell
# .env
DINKY_VERSION=1.1.0
FLINK_VERSION=1.17

# Customize other dependent paths,
# which will be mounted to dinky and flink containers
# 自定义其他依赖路径，会挂载到dinky和flink容器中
CUSTOM_JAR_PATH=/home/dinky-volume/extends/
FLINK_PROPERTIES="jobmanager.rpc.address: jobmanager"
TZ=Asia/Shanghai

# mysql,h2,pgsql
# DB_ACTIVE=h2
DB_ACTIVE=pgsql
```

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhm684957** [comment]
I also encountered this problem when using regular deployment.

**Comment by zhm684957** [comment]
The issue is caused by the file V20240729.1.1.0_release.sql located in the \db\migration\pgsql directory within the dinky-admin-1.1.0.jar package. To resolve this, open the jar package with a compression software, remove the mentioned file, re-compress the package, and then replace the original jar file in the lib directory.

**Comment by zhm684957** [comment]
> ### 先搜索后询问
> * [x] 我在[这些问题](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue)中进行了搜索，没有发现类似的问题。
> 
> ### 发生了什么事
> 1. 通过 docker-compose var dinkydocker/dinky：1.1.0-flink1.17 启动 dinky 服务失败
> 
> ```shell
> [dinky] 2024-08-07 16:27:28.565  ERROR    62 --- [           main] org.springframework.boot.SpringApplication: Application run failed
> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gitController' defined in URL [jar:file:/opt/dinky/lib/dinky-admin-1.1.0.jar!/org/dinky/controller/GitController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gitProjectServiceImpl': Unsatisfied dependency expressed through field 'baseMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gitProjectMapper' defined in URL [jar:file:/opt/dinky/lib/dinky-admin-1.1.0.jar!/org/dinky/mapper/GitProjectMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionTemplate'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/dinky/configure/DatabaseFlywayMigration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V20240729.1.1.0__release.sql failed
> ---------------------------------------------
> SQL State  : 23505
> Error Code : 0
> Message    : ERROR: duplicate key value violates unique constraint "dinky_sys_menu_pkey"
>   Detail: Key (id)=(2) already exists.
> Location   : db/migration/pgsql/V20240729.1.1.0__release.sql (/opt/dinky/file:/opt/dinky/lib/dinky-admin-1.1.0.jar!/db/migration/pgsql/V20240729.1.1.0__release.sql)
> Line       : 6
> Statement  : INSERT INTO public.dinky_sys_menu (parent_id, name, path, component, perms, icon, type, display, order_num,
>                                    create_time, update_time, note)
> VALUES (164, '仪表盘列表', '/dashboard/list', './Dashboard', 'dashboard:list', 'UnorderedListOutlined', 'F', 0, 167,
>         '2024-07-29 15:37:46', '2024-07-29 15:37:46', NULL)
> ```
> 
> ### 你预期会发生什么
> 服务已成功启动
> 
> ### 如何繁殖
> ```shell
> # .env
> DINKY_VERSION=1.1.0
> FLINK_VERSION=1.17
> 
> # Customize other dependent paths,
> # which will be mounted to dinky and flink containers
> # 自定义其他依赖路径，会挂载到dinky和flink容器中
> CUSTOM_JAR_PATH=/home/dinky-volume/extends/
> FLINK_PROPERTIES="jobmanager.rpc.address: jobmanager"
> TZ=Asia/Shanghai
> 
> # mysql,h2,pgsql
> # DB_ACTIVE=h2
> DB_ACTIVE=pgsql
> ```
> 
> ### 别的东西
> _没有回应_
> 
> ### 版本
> 开发
> 
> ### 你愿意提交PR吗？
> * [ ] 是的，我愿意提交PR！
> 
> ### 行为准则
> * [x] 我同意遵守这个项目[的行为准则](https://www.apache.org/foundation/policies/conduct)

The issue is caused by the file V20240729.1.1.0_release.sql located in the \db\migration\pgsql directory within the dinky-admin-1.1.0.jar package. To resolve this, open the jar package with a compression software, remove the mentioned file, re-compress the package, and then replace the original jar file in the lib directory.

**Comment by Zzm0809** [comment]
主键冲突 你是否有二开的菜单数据录入? 如果有自行排查, 上述文件在执行时未指定自增 id , 按照正常逻辑会自动递增不会报错主键冲突

**Comment by xiaoxiaodek** [comment]
> 主键冲突 你是否有二开的菜单数据录入? 如果有自行排查, 上述文件在执行时未指定自增 id , 按照正常逻辑会自动递增不会报错主键冲突

没有录入其他数据，是执行默认的 migrate sql
