### ISSUE TITLE
[Optimization][web] move sql cli to left bar

### ISSUE THREAD

**Issue by gaoyan1998** [DataLinkDC/dinky#3702]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

![1723452307108](https://github.com/user-attachments/assets/09e99d8b-0c2a-4296-926c-11f979f45af7)

这个sql cli按钮放在这里不合适，最好移动到左侧边栏上面

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Liammcl** [comment]
may i submit a PR？

**Comment by gaoyan1998** [comment]
> may i submit a PR？
Thank you for your interest in contributing! Yes, please submit a PR and we'll review it as soon as possible.

**Comment by gaoyan1998** [comment]
> may i submit a PR？

Thank you for your interest in contributing! Yes, please submit a PR and we'll review it as soon as possible.

**Comment by Zzm0809** [comment]
数据开发页面已经重构, 已经移动至左下角工具栏中
#3854
