### ISSUE TITLE
[Bug] [Data Development] An exception is thrown when using show tables queries in version 1.1.0

### ISSUE THREAD

**Issue by dsanww** [DataLinkDC/dinky#3704]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

An exception is thrown when using show tables queries in version 1.1.0
![image](https://github.com/user-attachments/assets/4e5709d0-c627-46c8-9950-cf5f74221102)

### What you expected to happen

There is nothing wrong with querying table statements, only sql querying metadata

### How to reproduce

dinky version：1.1.0
mode：yarn session
query sql: show tables

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by suxinshuo** [comment]
I checked and found that when executing the show statement, the TableResult returned by flink env does not contain JobClient. We modified the judgment condition in the new version, which caused the error.
![image](https://github.com/user-attachments/assets/653d09b3-9156-4b32-b6f4-b0227851dd88)
Assign jids only if JobClient is not empty.
org.dinky.job.builder.JobTransBuilder#updateJobWithTableResult
![image](https://github.com/user-attachments/assets/ca92152d-e753-4fdb-a28c-26cdec8073bd)
org.dinky.job.handler.Job2MysqlHandler#success
![image](https://github.com/user-attachments/assets/73660f5f-8c02-43f4-884d-6a7630d4e7c6)
I think for this situation, we can manually set a JobId.
Can I try it? @gaoyan1998

**Comment by gaoyan1998** [comment]
> I checked and found that when executing the show statement, the TableResult returned by flink env does not contain JobClient. We modified the judgment condition in the new version, which caused the error. ![图像](https://private-user-images.githubusercontent.com/34018346/357365683-653d09b3-9156-4b32-b6f4-b0227851dd88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MDI5ODIsIm5iZiI6MTcyMzYwMjY4MiwicGF0aCI6Ii8zNDAxODM0Ni8zNTczNjU2ODMtNjUzZDA5YjMtOTE1Ni00YjMyLWI2ZjQtYjAyMjc4NTFkZDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDAyMzEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYjQwMjM0Y2IxNzM5OGU4MzliYmU2MTJlYjZmN2U2N2NjMTYyNTZiYTc1OWIzOWY0MzliYTE4NzBiZTE0MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aYM6wa-j8i4K7MgcrQU9RCsAGeVM33gq4O1hthcu9U4) Assign jids only if JobClient is not empty. org.dinky.job.builder.JobTransBuilder#updateJobWithTableResult ![图像](https://private-user-images.githubusercontent.com/34018346/357365833-ca92152d-e753-4fdb-a28c-26cdec8073bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MDI5ODIsIm5iZiI6MTcyMzYwMjY4MiwicGF0aCI6Ii8zNDAxODM0Ni8zNTczNjU4MzMtY2E5MjE1MmQtZTc1My00ZmRiLWEyOGMtMjZjZGVjODA3M2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDAyMzEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYWI2ZmMwMDQzZmM2YmMyNGIzYTVhYTI3YzhkYjdiODQ0MTc2YmQ0NGFkMmNjNjU4MGI5NjBiMTRmNmQyZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QSrOAOiNnktSdMDPtboqHL-mSTpYkXGfaa_EPQMoPEw) org.dinky.job.handler.Job2MysqlHandler#success ![图像](https://private-user-images.githubusercontent.com/34018346/357389578-73660f5f-8c02-43f4-884d-6a7630d4e7c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MDI5ODIsIm5iZiI6MTcyMzYwMjY4MiwicGF0aCI6Ii8zNDAxODM0Ni8zNTczODk1NzgtNzM2NjBmNWYtOGMwMi00M2Y0LTg4NGQtNmE3NjMwZDRlN2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDAyMzEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMzRjMTQ1YTg1MWU5NDMwNjNiMDgyYzgwYmQ5ODYyM2ZiNzJiZGIzZGIyNWQ5MWRjZTA4N2I2MTUzYTk5YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.97f7sJmjh4jIZKkb1D0UeQj--6CaPDQK5IgyXJoKpHI) I think for this situation, we can manually set a JobId. Can I try it? @gaoyan1998

Thank you for your interest in contributing! Yes, please submit a PR and we'll review it as soon as possible. @suxinshuo
