### ISSUE TITLE
[Feature][Catalog] Support the OSS filesystem for Paimon.

### ISSUE THREAD

**Issue by hdygxsj** [DataLinkDC/dinky#3710]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
Currently supports s3 and is compatible with oss

**Comment by hdygxsj** [comment]
> Currently supports s3 and is compatible with oss

Is it more user friendly to access oss using the oss protocol
