### ISSUE TITLE
[Bug] [Data Development] When I query the field type: array<row<c_id STRING,c_name STRING>> of the data, click the query button, the page error

### ISSUE THREAD

**Issue by dsanww** [DataLinkDC/dinky#3711]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened
flink：1.18
dinky：1.0.3

When I query the field type: Array<Struct<name string,id string>>  of the data, click the query button, the page error。

paimon ddl：

create TABLE if not exists
  `default`.`t2` (
    `theme_id` STRING NOT NULL COMMENT '主键，全局唯一id',
    `category_ids` array<row<c_id STRING,c_name STRING>> COMMENT '品类id',
    `update_time` TIMESTAMP(0) COMMENT '更新时间',
    PRIMARY KEY (`theme_id`) NOT ENFORCED
  )
WITH
  (
    'bucket' = '1',
    'changelog-producer' = 'lookup',
    'merge-engine'='partial-update',
    'fields.update_time.sequence-group'='category_ids',
    'fields.category_ids.aggregate-function' = 'nested_update',
  'fields.category_ids.nested-key' = 'c_id'
  );

when i try:
select * from `default`.`t2` ;

then:
found error page:
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bkind%2C%20arity%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

![image](https://github.com/user-attachments/assets/a6a5067e-a466-4916-b05f-d2a92e83fdc6)

### What you expected to happen

no error

### How to reproduce

paimon ddl：

create TABLE if not exists
  `default`.`t2` (
    `theme_id` STRING NOT NULL COMMENT '主键，全局唯一id',
    `category_ids` array<row<c_id STRING,c_name STRING>> COMMENT '品类id',
    `update_time` TIMESTAMP(0) COMMENT '更新时间',
    PRIMARY KEY (`theme_id`) NOT ENFORCED
  )
WITH
  (
    'bucket' = '1',
    'changelog-producer' = 'lookup',
    'merge-engine'='partial-update',
    'fields.update_time.sequence-group'='category_ids',
    'fields.category_ids.aggregate-function' = 'nested_update',
  'fields.category_ids.nested-key' = 'c_id'
  );

insert some data....

select * from `default`.`t2` ;

then click query result button

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
@gaoyan1998 paimon 作业下 是否能复现?

**Comment by Zzm0809** [comment]
数据开发页面重构.如有问题请再次提 bug
