### ISSUE TITLE
[Bug] [Module Name] Bug title helm install dinky-release-1.19-1.1.0 error

### ISSUE THREAD

**Issue by jiangxiaobai** [DataLinkDC/dinky#3712]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

root@JiangZhifuPC:~/bigdata/dinky/dinky-release-1.19-1.1.0/deploy/kubernetes/helm/dinky# kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.4
Kustomize Version: v5.0.1
Server Version: v1.27.12+rke2r1
root@JiangZhifuPC:~/bigdata/dinky/dinky-release-1.19-1.1.0/deploy/kubernetes/helm/dinky# helm --kubeconfig=/root/.kube/rke2-test -n flink install dinky .
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: apiVersion not set

### What you expected to happen

install success

### How to reproduce

helm install

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
未能复现
