### ISSUE TITLE
[Bug] [Task Submit] Submit two same name task，only display one

### ISSUE THREAD

**Issue by zhuxt2015** [DataLinkDC/dinky#3714]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

If you submit two tasks with the same name, they can run normally in Flink, but only one task can be seen in the devops module of Dinky In addition, it is recommended to be able to stop the task on the development page after submission, similar to the button to stop after submitting the task
<img width="1388" alt="image" src="https://github.com/user-attachments/assets/88004dae-b8f6-4e7e-b851-95d345a54f6c">
<img width="1176" alt="image" src="https://github.com/user-attachments/assets/1906a42f-ae98-49ce-bdf5-67b7401f1247">
@

### What you expected to happen

The user can be prompted to stop the previous task first, or the DevOps module shows 2 tasks

### How to reproduce

Click to 2 or more times query button in same task

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
你点击多次肯定触发多次提交, 这是正常的, 但是提交时按钮会呈现 loading 中状态,处于 loading 中状态的按钮是不可点击的,除非你刻意快速点击, 正常情况下不会出现此问题

**Comment by zhuxt2015** [comment]
> 你点击多次肯定触发多次提交, 这是正常的, 但是提交时按钮会呈现 loading 中状态,处于 loading 中状态的按钮是不可点击的,除非你刻意快速点击, 正常情况下不会出现此问题

我点一次查询按钮以后，等任务提交到flink，这时候查询按钮又可以点了

**Comment by Zzm0809** [comment]
> > 你点击多次肯定触发多次提交, 这是正常的, 但是提交时按钮会呈现 loading 中状态,处于 loading 中状态的按钮是不可点击的,除非你刻意快速点击, 正常情况下不会出现此问题
> 
> 我点一次查询按钮以后，等任务提交到flink，这时候查询按钮又可以点了

建议去了解下 flink 提交任务机制相关, 你在 sql-client 提交完成一个 自然还可以再次提交相同的, 道理是一样的, 这个是用户操作行为控制的, 而非 bug

**Comment by zhuxt2015** [comment]
> > > 你点击多次肯定触发多次提交, 这是正常的, 但是提交时按钮会呈现 loading 中状态,处于 loading 中状态的按钮是不可点击的,除非你刻意快速点击, 正常情况下不会出现此问题
> 
> > 
> 
> > 我点一次查询按钮以后，等任务提交到flink，这时候查询按钮又可以点了
> 
> 
> 
> 建议去了解下 flink 提交任务机制相关, 你在 sql-client 提交完成一个 自然还可以再次提交相同的, 道理是一样的, 这个是用户操作行为控制的, 而非 bug

我知道可以提交多个，是希望dinky能在前端功能上做一下优化，已经提交就别重复提交，同时提交一样的没有意义

**Comment by Zzm0809** [comment]
> > > > 你点击多次肯定触发多次提交, 这是正常的, 但是提交时按钮会呈现 loading 中状态,处于 loading 中状态的按钮是不可点击的,除非你刻意快速点击, 正常情况下不会出现此问题
> > 
> > 
> > > 
> > 
> > 
> > > 我点一次查询按钮以后，等任务提交到flink，这时候查询按钮又可以点了
> > 
> > 
> > 建议去了解下 flink 提交任务机制相关, 你在 sql-client 提交完成一个 自然还可以再次提交相同的, 道理是一样的, 这个是用户操作行为控制的, 而非 bug
> 
> 我知道可以提交多个，是希望dinky能在前端功能上做一下优化，已经提交就别重复提交，同时提交一样的没有意义

这个无法做, 任务本身就是可以重复提交的
