### ISSUE TITLE
[Bug] [Module Name] Bug title After deploying dinky-release-1.19-1.1.0.tar.gz for the first time, there is no data. When I click on the workbench, an exception is reported.

### ISSUE THREAD

**Issue by Freed2** [DataLinkDC/dinky#3725]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Caused by: org.springframework.jdbc.BadSqlGrammarException:
### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) AND tenant_id = 1' at line 1
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) AND tenant_id = 1' at line 1

### What you expected to happen

不出现报错，兼容无数据的情况，下面版本选不了1.1.0，下载的地址为：https://github.com/DataLinkDC/dinky/releases/download/v1.1.0/dinky-release-1.19-1.1.0.tar.gz

### How to reproduce

下载包https://github.com/DataLinkDC/dinky/releases/download/v1.1.0/dinky-release-1.19-1.1.0.tar.gz，部署后，登录，点击工作台查看日志

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
目前无法复现, 请提供详细复现流程步骤

**Comment by Zzm0809** [comment]
已复现, 已修复
