### ISSUE TITLE
dinky-app-1.19-1.1.0-jar-with-dependencies.jar path error

### ISSUE THREAD

**Issue by azaleaFang** [DataLinkDC/dinky#3731]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

用application方式的话，好像必须用这个路径，其它路径不行，不然会有如下错误
![微信图片_20240821163251](https://github.com/user-attachments/assets/01d55602-d31a-4dc3-bd48-f5f0f0bd3280)

如果是seesion模式的话，必须和flink的lib包放在一起
![微信图片_20240821163257](https://github.com/user-attachments/assets/25280014-f578-4b84-905a-af63006b721e)

### What you expected to happen

希望可以自由指定 dinky-app-1.19-1.1.0-jar-with-dependencies.jar 这个jar的位置，
同时希望session 和application 两种运行模式，dinky-app-1.19-1.1.0-jar-with-dependencies.jar 都是放在一个统一指定的地方

### How to reproduce

dinky 1.1.0 flink 1.19.1 hadoop-3.3.6
![微信图片_20240821163622](https://github.com/user-attachments/assets/62de0b19-f700-41b7-bc0f-0772cab2b017)

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
1. application 模式下 dinky-app jar 只要在 hdfs 上传 然后指定上传到的目的地路径即可, 不存在你说的不生效,唯一可能是你在提交时设定了 yarn.provided.lib.dirs 参数的配置覆盖掉了 所以可能导致不生效, 此问题需要自行排查.
2. 去了解下 yarn-session 模式的提交机制, lib 到底是用本地的还是用 hdfs 的.
