### ISSUE TITLE
[Optimization][Data Studio]  Recommend display the oracle schema in pagination

### ISSUE THREAD

**Issue by zhuxt2015** [DataLinkDC/dinky#3733]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

当oracle拥有大量schema时，切换到oracle数据源时页面卡死或者占用大量cpu
<img width="931" alt="image" src="https://github.com/user-attachments/assets/87865db0-f022-4765-912e-1f0c942e8429">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
You can try to optimize this problem
