### ISSUE TITLE
[Bug] [Data Development] When submitting a task, I found that there is no application cluster to choose from.

### ISSUE THREAD

**Issue by sprybee** [DataLinkDC/dinky#3734]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

提交任务的时候发现没有application集群可以选择 
![image](https://github.com/user-attachments/assets/5b5cf8d5-6b10-490d-8c4c-5dd3f13752bc)
![image](https://github.com/user-attachments/assets/13507c50-963f-4a25-b31d-0b12a349fc6c)

### What you expected to happen

可以把任务提交到flink集群以application模式

### How to reproduce

asd

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
集群处于启用状态+健康状态,才可以选择
