### ISSUE TITLE
[Optimization] [Module Name] Failed to submit task using yarn-application

### ISSUE THREAD

**Issue by diaozhonghao** [DataLinkDC/dinky#3736]
### Search before asking

- [x] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

在使用yarn-application提交任务失败,最开始还是好用的,不知道啥时候就突然不好使了, 不使用dinky时,flink on yarn是正常的能提交任务的
flink 1.17
dinky 1.0.0
hadoop 3.2
环境变量已加
![微信截图_20240825165742](https://github.com/user-attachments/assets/28ef7af8-de60-4f24-8791-a65aeff026f0)
![微信截图_20240825165805](https://github.com/user-attachments/assets/88dd188d-1d3a-41ad-bd08-0df56eb7667b)
![微信截图_20240825170141](https://github.com/user-attachments/assets/0f76c492-67d9-4708-aa26-9dbda895362b)

并且开启了配置中心的resource配置
![微信截图_20240825170112](https://github.com/user-attachments/assets/9a9dc392-3678-46b2-9892-0c4fb71b2127)

### What you expected to happen

希望大家帮忙看看原因

### How to reproduce

目前不清楚问题

### Version

1.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
未给出 yarn 任务的详细日志, 无法给出任何建议, 目前未有反馈出现你描述的情况

**Comment by diaozhonghao** [comment]
我这边标签选错了,不是个bug应该,就是我哪里配置错了
下面是我提供的yarn logs -applicationId application_xxxx
[application_1722045692740_80844.log](https://github.com/user-attachments/files/16740283/application_1722045692740_80844.log)
日志中没有有效信息
下面是dinky的日志
![微信截图_20240825203550](https://github.com/user-attachments/assets/2397eb18-d388-44ef-9aae-38d83e958441)

**Comment by diaozhonghao** [comment]
问题已经解决,后面发现是hdfs上缺少对应依赖,添加即可
![image](https://github.com/user-attachments/assets/98619c0d-fdcd-4f8c-ab3d-12ae808cad3e)
