### ISSUE TITLE
[Bug] Caused by: java.lang.IllegalArgumentException: EndPoint is not set

### ISSUE THREAD

**Issue by fengDianDemaNong** [DataLinkDC/dinky#3742]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

当我用dinky执行：
set 'fs.obs.impl'= 'org.apache.hadoop.fs.obs.OBSFileSystem';
set     'fs.obs.access.key'= 'xxxxxxx';
set    'fs.obs.secret.key'= 'xxxxxxx';
set    'fs.obs.endpoint'='xxxxxxx';
CREATE CATALOG paimon_obs2 WITH (
    'type'='paimon',
    'warehouse'='obs://xxxxxxx/flink/warehose'
);
![image](https://github.com/user-attachments/assets/b1383d08-7441-4763-9134-3e82541dc501)

但用 flink的sql-client执行正常的
![image](https://github.com/user-attachments/assets/b8264c7b-ff71-4345-8362-051c5440ace3)

### What you expected to happen

正常我理解应该用dinky执行和sql-client.sh是一样的效果

### How to reproduce

执行这个语句就可以复现：
set 'fs.obs.impl'= 'org.apache.hadoop.fs.obs.OBSFileSystem';
set     'fs.obs.access.key'= 'xxxxxxx';
set    'fs.obs.secret.key'= 'xxxxxxx';
set    'fs.obs.endpoint'='xxxxxxx';
CREATE CATALOG paimon_obs2 WITH (
    'type'='paimon',
    'warehouse'='obs://xxxxxxx/flink/warehose'
);

### Version

1.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fengDianDemaNong** [comment]
或者，我已经在flink-conf设置了对应文件系统的配置了，希望只指定对应warehouse路径就行。比如这样
CREATE CATALOG paimon_obs2 WITH (
'type'='paimon',
'warehouse'='obs://xxxxxxx/flink/warehose'
);

现在这种用flink自带的sql-client.sh 是正常的，但用dinky就会报错，java.lang.IllegalArgumentException: EndPoint is not set
![image](https://github.com/user-attachments/assets/0db05773-c140-400e-86a2-9ec783bccf43)

**Comment by Zzm0809** [comment]
目前社区无 obs 环境, 你可以根据官网本地调试文档进行修复/优化,同时欢迎回馈社区😄

**Comment by fengDianDemaNong** [comment]
> 目前社区无 obs 环境, 你可以根据官网本地调试文档进行修复/优化,同时欢迎回馈社区😄

我用oss也是一样的问题哈

**Comment by Zzm0809** [comment]
那你设置下 endpoint 配置呢, 或者说你设置的配置项不对
如无上述问题 建议 debug 进行排查

**Comment by gaoyan1998** [comment]
https://paimon.apache.org/docs/master/filesystems/s3/

paimon官网并无obs支持，使用s3即可

**Comment by fengDianDemaNong** [comment]
> https://paimon.apache.org/docs/master/filesystems/s3/
> 
> paimon官网并无obs支持，使用s3即可

1、是的官网没有直接支持，有其他人写了这个功能了。
https://github.com/littlefisher666/incubator-paimon/tree/master/paimon-filesystems
我用flink的 sql-client测试也是没问题的。

2、我用dinky1.0.3 测试 obs和oss报的一样的错。
代码：oss测试
CREATE CATALOG paimon_oss WITH (
'type'='paimon',
'warehouse'='oss://xxxxxxx/flink/warehose'
);

这个代码在 sql-client 没问题的，因为授权信息都写在flink集群配置里了。但用dinky就会报Caused by: java.lang.IllegalArgumentException: EndPoint is not set

**Comment by fengDianDemaNong** [comment]
> > https://paimon.apache.org/docs/master/filesystems/s3/
> > paimon官网并无obs支持，使用s3即可
> 
> 1、是的官网没有直接支持，有其他人写了这个功能了。 https://github.com/littlefisher666/incubator-paimon/tree/master/paimon-filesystems 我用flink的 sql-client测试也是没问题的。
> 
> 2、我用dinky1.0.3 测试 obs和oss报的一样的错。 代码：oss测试 CREATE CATALOG paimon_oss WITH ( 'type'='paimon', 'warehouse'='oss://xxxxxxx/flink/warehose' );
> 
> 这个代码在 sql-client 没问题的，因为授权信息都写在flink集群配置里了。但用dinky就会报Caused by: java.lang.IllegalArgumentException: EndPoint is not set

所以和obs没关系，应该是dinky这边有问题的。

**Comment by gaoyan1998** [comment]
> > > https://paimon.apache.org/docs/master/filesystems/s3/
> > > paimon官网并无obs支持，使用s3即可
> > 
> > 
> > 1、是的官网没有直接支持，有其他人写了这个功能了。 https://github.com/littlefisher666/incubator-paimon/tree/master/paimon-filesystems 我用flink的 sql-client测试也是没问题的。
> > 2、我用dinky1.0.3 测试 obs和oss报的一样的错。 代码：oss测试 CREATE CATALOG paimon_oss WITH ( 'type'='paimon', 'warehouse'='oss://xxxxxxx/flink/warehose' );
> > 这个代码在 sql-client 没问题的，因为授权信息都写在flink集群配置里了。但用dinky就会报Caused by: java.lang.IllegalArgumentException: EndPoint is not set
> 
> 所以和obs没关系，应该是dinky这边有问题的。

obs应该是支持s3协议的，你直接用s3试试呢

**Comment by fengDianDemaNong** [comment]
> > > > https://paimon.apache.org/docs/master/filesystems/s3/
> > > > paimon官网并无obs支持，使用s3即可
> > > 
> > > 
> > > 1、是的官网没有直接支持，有其他人写了这个功能了。 https://github.com/littlefisher666/incubator-paimon/tree/master/paimon-filesystems 我用flink的 sql-client测试也是没问题的。
> > > 2、我用dinky1.0.3 测试 obs和oss报的一样的错。 代码：oss测试 CREATE CATALOG paimon_oss WITH ( 'type'='paimon', 'warehouse'='oss://xxxxxxx/flink/warehose' );
> > > 这个代码在 sql-client 没问题的，因为授权信息都写在flink集群配置里了。但用dinky就会报Caused by: java.lang.IllegalArgumentException: EndPoint is not set
> > 
> > 
> > 所以和obs没关系，应该是dinky这边有问题的。
> 
> obs应该是支持s3协议的，你直接用s3试试呢
s3也试了，不加其他参数也是报错。如果所有参数加上是正常的。
我的意思是和协议无关，这是oss测试的。
![image](https://github.com/user-attachments/assets/546e7c3e-9259-4ff6-b6ec-73f3f8ad6ec7)

这个代码在 sql-client 没问题的，因为授权信息都写在flink集群配置里了。但用dinky就会报错，个人理解dinky提交的和sql-client 效果一样的

**Comment by Zzm0809** [comment]
> > > > > https://paimon.apache.org/docs/master/filesystems/s3/
> > > > > paimon官网并无obs支持，使用s3即可
> > > > 
> > > > 
> > > > 1、是的官网没有直接支持，有其他人写了这个功能了。 https://github.com/littlefisher666/incubator-paimon/tree/master/paimon-filesystems 我用flink的 sql-client测试也是没问题的。
> > > > 2、我用dinky1.0.3 测试 obs和oss报的一样的错。 代码：oss测试 CREATE CATALOG paimon_oss WITH ( 'type'='paimon', 'warehouse'='oss://xxxxxxx/flink/warehose' );
> > > > 这个代码在 sql-client 没问题的，因为授权信息都写在flink集群配置里了。但用dinky就会报Caused by: java.lang.IllegalArgumentException: EndPoint is not set
> > > 
> > > 
> > > 所以和obs没关系，应该是dinky这边有问题的。
> > 
> > 
> > obs应该是支持s3协议的，你直接用s3试试呢
> > s3也试了，不加其他参数也是报错。如果所有参数加上是正常的。
> > 我的意思是和协议无关，这是oss测试的。
> > ![image](https://private-user-images.githubusercontent.com/39053720/362057995-546e7c3e-9259-4ff6-b6ec-73f3f8ad6ec7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzM2NzcsIm5iZiI6MTcyNDgzMzM3NywicGF0aCI6Ii8zOTA1MzcyMC8zNjIwNTc5OTUtNTQ2ZTdjM2UtOTI1OS00ZmY2LWI2ZWMtNzNmM2Y4YWQ2ZWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA4MjI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjNWMxZjYxMDNlODlkYjIzYWRjMWVkMmM3ZDZjNDAyZWM2ZjU2YThiZDQ0MjUyMWNkNmM4ZjI4Mjc4YzMwYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bbkN_TLLScqfmbC3c0E3ZNkgDdFNd2JphB6RPMdHQjE)
> 
> 这个代码在 sql-client 没问题的，因为授权信息都写在flink集群配置里了。但用dinky就会报错，个人理解dinky提交的和sql-client 效果一样的

个人理解的不对, 按照上边说的增加对于配置项即可
