### ISSUE TITLE
[Feature][*] Release 1.2.0 (LTS)

### ISSUE THREAD

**Issue by Zzm0809** [DataLinkDC/dinky#3751]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
## English

### New features
- Added domestic npm mirror sources (supported by profile mode)
- Support Flink-1.20
- Support FlinkCDC 3.2.0
- Added built-in flink history server, which greatly reduces the problem of incorrect task status acquisition
- Added some page prompts for roles and permissions
- Added loading effects when displaying blood relationship acquisition
- Implemented job import and export
- Support mock test flinksql and CDCSOURCE task
- FlinkSQL Studio supports real-time update task status
- Add a boot initialization page for the first deployment

### Fixes
- Fix the problem that `show databases` cannot be executed normally
- Fix some json serialization problems
- Fix the problem of `SQL Cli` under Flink1.19
- Fix the problem that the task port is unavailable in `k8s` mode
- Fix some problems in the git project function (default value, drag and drop sorting)
- Fix the SavePoint path logic in `kubernetes-operator` mode and adjust the configuration method of Flink configuration acquisition
- Fix the problem that the page is unresponsive for a long time when too many tasks are opened on the data development page
- Fix git Problems in the project build process
- Fix the thumbnail display problem in the code editor
- Fix the sql automatic initialization problem of pg
- Fix the problem of submitting tasks in `local` mode
- Fix the data type conversion problem when synchronizing the entire database of `Oracle`
- Fix the exception caused by no instance when clicking on the workbench
- Fix the syntax error problem when querying data in `postgres`
- Fix the problem that `flyway` cannot support mysql5.7
- Fix the problem of incorrect primary key column acquisition in Oracle data source type
- Fix the problem that the task list sorting does not take effect
- Fix the problem of repeated refresh of Git project page
- Fix the null pointer exception that may exist in DingTalk alarm
- Fix the problem of proxy Flink address
- Fix the problem that the table structure in the catalog cannot be displayed normally

### Optimization
- Optimize the support of `https` protocol when obtaining task details
- Optimize the workbench page layout
- Delete the unique index of the `dinky_cluster` table to solve the problem in yarn/k8s Unique index conflict problem when high availability is enabled
- Optimize some Mapper queries
- Optimize the type of declared attributes of the git project backend class
- Delete the prompt text in `UDF registration management`
- Optimize some page layouts to make them more user-friendly on small screens
- Optimize the version update logic to solve the cache problem caused by the upgrade (automatic version comparison implementation)
- Optimize the virtual scrolling failure to take effect when there are too many nodes in the data source details list tree, resulting in slow page rendering
- Optimize the login page to solve the problem of excessive resource jams
- Optimize the application startup speed
- Optimize the cluster started from the cluster configuration to manual registration
- Optimize the display layout of the system configuration description that is too long
- Optimize the overall layout and rendering efficiency of the flink task operator graph in the operation and maintenance center

### Refactoring
- Refactor the `user.dir` acquisition method to avoid the problem of incorrectly obtaining the project root path in different deployment environments
- Refactor `SSE` to `websocket`
- Refactor the request method for obtaining task monitoring data
- Remove hutool-json to improve data conversion efficiency

### Documentation
- Added documentation for integrating Dinky into Datasophon
- Added documentation for using `SQL Cli`
- Optimized the document footer
- Added documentation for role binding tenants

### CI/CD
- Added optional version items for the github bug template
- Removed the domestic warehouse proxy configuration when deploying documents

---

## Chinese
### 新功能
- 添加了 国内 npm 的镜像源(使用 profile 方式支持)
- 支持 Flink-1.20
- 支持 FlinkCDC 3.2.0
- 新增内置的 flink history server，从而极大降低了任务状态获取不正确的问题
- 增加角色和权限的一些页面提示
- 增加血缘展示获取时的 loading 效果
- 实现作业导入导出
- 支持对 FlinkSQL 及 CDCSOURCE 作业进行 Mock 预览测试
- 数据开发支持实时更新作业状态
- 增加首次部署时的引导初始化页面

### 修复
- 修复`show databases` 无法正常执行的问题
- 修复部分 json 序列化问题
- 修复 Flink1.19 下的 `SQL Cli` 存在的问题
- 修复`k8s`模式下 任务端口不可用的问题
- 修复 git 项目功能中存在的一些问题(默认值,拖拽排序)
- 修复`kubernetes-operator`模式下的 SavePoint 路径逻辑并调整 Flink 配置获取的配置方法
- 修复当数据开发页面打开过多任务时导致页面长时间无响应问题
- 修复 git 项目在构建过程中存在的问题
- 修复代码编辑器中的缩略图显示问题
- 修复 pg 的 sql 自动初始化问题
- 修复`local` 模式提交任务的问题
- 修复 `Oracle` 整库同步时的数据类型转换问题
- 修复工作台点击作业时,无实例产生的异常
- 修复 `postgres` 查询数据时语法报错问题
- 修复 `flyway` 无法支持 mysql5.7 的问题
- 修复 Oracle 数据源类型中获取主键列不正确的问题
- 修复任务列表排序不生效问题
- 修复 Git 项目页面重复刷新问题
- 修复钉钉告警可能存在的空指针异常
- 修复代理 Flink 地址存在的问题
- 修复查看catalog中的表结构无法正常显示问题

### 优化
- 优化获取任务详情时,支持`https`协议
- 优化工作台页面布局
- 删除`dinky_cluster`表的唯一索引,解决在 yarn/k8s 开启高可用时造成唯一索引冲突问题
- 优化部分 Mapper 的查询
- 优化 git 项目后端类声明属性的类型
- 删除`UDF 注册管理`中的提示文案
- 优化部分页面布局，使其在小屏幕上显示更加友好
- 优化版本更新逻辑，解决升级带来的缓存问题(自动对比版本实现)
- 优化数据源详情列表树节点过多时虚拟滚动不生效导致页面渲染过慢问题
- 优化登录页,解决资源过大卡顿问题
- 优化应用启动速度
- 优化将从集群配置启动的集群变更为手动注册
- 优化系统配置描述过长的展示布局
- 优化运维中心 flink 任务算子图的整体布局及渲染效率

### 重构
- 重构 `user.dir` 获取方式,避免不同部署环境下获取项目根路径错误的问题
- 将 `SSE` 重构替换为 `websocket`
- 重构获取任务监控数据的请求方式
- 移除 hutool-json 提升数据转换效率


### 文档
- 添加 Dinky 集成到 Datasophon 的文档
- 添加 `SQL Cli` 使用文档
- 优化文档页脚
- 增加角色绑定租户相关提示文档

### CI/CD
- 添加 github bug 模版的可选择版本项
- 移除部署文档时的国内仓库代理配置

**Comment by medivh511** [comment]
none support for flink 1.20?

**Comment by Zzm0809** [comment]
> none support for flink 1.20?

1.1.1 发版无此计划,仅 bugfix 版本,如你有需求可以参与贡献 pr ,将在 1.2.0 发布

**Comment by Zzm0809** [comment]
经过讨论，此次发版变更为1.2.0

**Comment by chenhaipeng** [comment]
When will it be officially released， I found some issue in v1.1.0 hasn't fixed

**Comment by chenhaipeng** [comment]
我这边需要新的修复版本，如果可以的话，我可以帮忙协助解决一些issue ，加速这个版本的发布

**Comment by Zzm0809** [comment]
> 我这边需要新的修复版本，如果可以的话，我可以帮忙协助解决一些issue ，加速这个版本的发布

非常欢迎，你可以在issue列表中寻找你感兴趣的进行修复与优化，或者使用过程中遇到的问题进行修复

目前该版本已经基本ready，需要等待 #3889 #3898 #3897 合并

**Comment by czy006** [comment]
+1

**Comment by aiwenmo** [comment]
We will release Dinky1.2.0-rc1 over the weekend.

**Comment by 924035468** [comment]
yyds
