### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.cli.Option.builder(Ljava/lang/String;)Lorg/apache/commons/cli is reported when starting yarn-application in the hadoop cluster /Option$Builder;flink version is 1.18, hadoop cluster is version 3.3.6

### ISSUE THREAD

**Issue by QuintinLuke** [DataLinkDC/dinky#3752]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

在hadoop集群集群中采用yarn-application启动时报错Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.cli.Option.builder(Ljava/lang/String;)Lorg/apache/commons/cli/Option$Builder;flink版本是1.18,hadoop集群是3.3.6版本

### What you expected to happen

在hadoop集群集群中采用yarn-application启动时报错Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.cli.Option.builder(Ljava/lang/String;)Lorg/apache/commons/cli/Option$Builder;flink版本是1.18,hadoop集群是3.3.6版本

### How to reproduce

在hadoop集群集群中采用yarn-application启动时报错Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.cli.Option.builder(Ljava/lang/String;)Lorg/apache/commons/cli/Option$Builder;flink版本是1.18,hadoop集群是3.3.6版本

### Anything else

在hadoop集群集群中采用yarn-application启动时报错Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.cli.Option.builder(Ljava/lang/String;)Lorg/apache/commons/cli/Option$Builder;flink版本是1.18,hadoop集群是3.3.6版本

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
添加 common-cli 依赖

**Comment by QuintinLuke** [comment]
> 添加 common-cli 依赖
我在hdfs:///dingky/lib和dinky安装根目录的extends文件夹下、hadoop安装目录上、flink的lib的=上已经尝试添加了  common-cli -1.2、common-cli -1.5、common-cli-1.6、 common-cli -1.9版本，均是报这个错误。hdfs:///dingky/lib 是指定的flink lib 依赖路径。

**Comment by Zzm0809** [comment]
> > 添加 common-cli 依赖
> > 我在hdfs:///dingky/lib和dinky安装根目录的extends文件夹下、hadoop安装目录上、flink的lib的=上已经尝试添加了  common-cli -1.2、common-cli -1.5、common-cli-1.6、 common-cli -1.9版本，均是报这个错误。hdfs:///dingky/lib 是指定的flink lib 依赖路径。

添加完重启

**Comment by QuintinLuke** [comment]
> > > 添加 common-cli 依赖
> > > 我在hdfs:///dingky/lib和dinky安装根目录的extends文件夹下、hadoop安装目录上、flink的lib的=上已经尝试添加了  common-cli -1.2、common-cli -1.5、common-cli-1.6、 common-cli -1.9版本，均是报这个错误。hdfs:///dingky/lib 是指定的flink lib 依赖路径。
> 
> 添加完重启

有重启过的，还是这个错误

**Comment by Zzm0809** [comment]
以上报错原因就是 common-cli 依赖冲突导致的, 如还有问题,需要自行排查环境,是否包含了多个版本的此依赖 但是这个包是 yarn-application 模式必须加的

**Comment by QuintinLuke** [comment]
> 以上报错原因就是 common-cli 依赖冲突导致的, 如还有问题,需要自行排查环境,是否包含了多个版本的此依赖 但是这个包是 yarn-application 模式必须加的
现在报错事：classnotfoundexception:com.fastxml.jackson.datatype.jar310.deser.localdatetimedeserializer

**Comment by Zzm0809** [comment]
> > 以上报错原因就是 common-cli 依赖冲突导致的, 如还有问题,需要自行排查环境,是否包含了多个版本的此依赖 但是这个包是 yarn-application 模式必须加的
> > 现在报错事：classnotfoundexception:com.fastxml.jackson.datatype.jar310.deser.localdatetimedeserializer

这不是很明确吗? 这种问题建议自行排查/解决

**Comment by lianchaoqi** [comment]
哥们 咋样了，这个问题解决了嘛？我的问题跟你的一模一样，我整了几天了各种方式都试过了
