### ISSUE TITLE
AggTable is faulty in this document

### ISSUE THREAD

**Issue by luckyLJY** [DataLinkDC/dinky#3758]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar document requirement.

### Description

<img width="1087" alt="Snipaste_2024-08-29_10-16-53" src="https://github.com/user-attachments/assets/7b8c87bb-3278-4d22-9bc6-0f2556d71b55">

As shown in the figure above, the comma should be removed from the mark。

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
仅是 demo 作为参考而已

**Comment by luckyLJY** [comment]
OK
