### ISSUE TITLE
[Bug] [Module Name] The automatically registered K8S Session cannot be used

### ISSUE THREAD

**Issue by DesireWithin** [DataLinkDC/dinky#3763]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

如图所示，红框里面的自动注册的Session集群无法使用
![af234e25672b6adf29deb59aefa0aa0](https://github.com/user-attachments/assets/a20a610c-641d-46b8-b8e3-0a6eedb16859)
![56ab1dbba5cd635bf82447ae0d11cdc](https://github.com/user-attachments/assets/56550909-bf89-4336-9ee6-eeb7befccba0)

### What you expected to happen

可以正常使用

### How to reproduce

通过集群配置中的集群创建Session实例，无法使用

### Anything else

我是通过1.0.3升级到的1.1.0
1.0.3是可以使用k8s session集群的.
此外， 每次我自动创建session的时候， session实例都会显示异常， 当我打开并关闭启用按钮的时候，session实例才会显示正常
<img width="708" alt="企业微信截图_c3e46ffb-22eb-472f-9979-d9df6b57e864" src="https://github.com/user-attachments/assets/daad8d62-9bff-46f0-afc8-1d062284f9dc">
![企业微信截图_17250005409622](https://github.com/user-attachments/assets/67153f9f-b1a7-4f82-a591-60a8c9e26742)

### Version

1.1.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
根据上边的描述:
1. 猜测是你启动后的集群为不健康状态,然后你在数据开发页面去选择了集群,但是并没有刚启动的集群,原因是心跳状态不正常, 所以导致刚开始下拉框没有这个数据.
2. Flink 实例的状态截图为正常,猜测是你点击了启用/禁用后才更新的,因为修改这个状态同样会进行心跳检测

综上:
 心跳健康且启用状态就可以用了, 1.2.0 发版时此处会将由集群配置启动的集群变更为手动注册,同时部署完成后进行心跳检测
