### ISSUE TITLE
The entire database is synchronized with CDC, and the table is created after execution. Tip: Execute statement types are not included: INSERT, SELECT, WITH, SHOW, DESCRIBE, DESC, CTAS

### ISSUE THREAD

**Issue by zong-xin** [DataLinkDC/dinky#3764]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

提示 不包含可执行的语句类型: INSERT,SELECT,WITH,SHOW,DESCRIBE,DESC,CTAS

### What you expected to happen

异常提示：
org.dinky.data.exception.BusException: 不包含可执行的语句类型: INSERT,SELECT,WITH,SHOW,DESCRIBE,DESC,CTAS
	at org.dinky.job.builder.JobTransBuilder.run(JobTransBuilder.java:73) ~[classes/:?]
	at org.dinky.job.JobManager.executeSql(JobManager.java:299) ~[classes/:?]
	at org.dinky.service.task.FlinkSqlTask.execute(FlinkSqlTask.java:68) ~[classes/:?]
	at org.dinky.service.impl.TaskServiceImpl.executeJob(TaskServiceImpl.java:202) ~[classes/:?]
	at org.dinky.service.impl.TaskServiceImpl$$FastClassBySpringCGLIB$$22087f7c.invoke(<generated>) ~[classes/:?]

### How to reproduce

配置如下：
EXECUTE CDCSOURCE cdc_mysql WITH (
 'connector' = 'mysql-cdc',
 'hostname' = '127.0.0.1',
 'port' = '3306',
 'username' = 'dinky',
 'password' = 'dinky',
 'checkpoint' = '3000',
 'scan.startup.mode' = 'initial',
 'parallelism' = '1',
 'table-name' = 'dinky\.dinky_sys_operate_log,dinky\.dinky_sys_config',
 'sink.connector' = 'jdbc',
 'sink.url' = 'jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&useSSL=false',
 'sink.username' = 'test',
 'sink.password' = 'test123',
 'sink.sink.db' = 'test',
 'sink.table.prefix' = 'test_',
 'sink.table.lower' = 'true',
 'sink.table-name' = '#{tableName}',
 'sink.driver' = 'com.mysql.jdbc.Driver',
 'sink.sink.buffer-flush.interval' = '2s',
 'sink.sink.buffer-flush.max-rows' = '100',
 'sink.sink.max-retries' = '5',
 'sink.auto.create' = 'true'
)

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
@suxinshuo hi, 请协助验证是否存在该问题!!!

**Comment by suxinshuo** [comment]
> @suxinshuo hi, 请协助验证是否存在该问题!!!

确实存在这个问题，之前在 #3704 中把 return 改成了抛出异常，导致第四步没办法执行了。之前是认为 jobParam 的 trans 是空，就是没有可执行的语句，现在看来好像不对，我恢复成直接 return 吧，辛苦大佬帮忙确认一下 @Zzm0809 
![image](https://github.com/user-attachments/assets/6ac1d887-8a0a-4d6e-9cc9-aa14d41b4f14)
![image](https://github.com/user-attachments/assets/c87ef5c1-cd5d-4a5a-a155-386773f174cd)

**Comment by Zzm0809** [comment]
可以在增加这个参数值场景下本地调试一下进行验证，然后修复即可

**Comment by Zzm0809** [comment]
> > @suxinshuo hi, 请协助验证是否存在该问题!!!
> 
> 确实存在这个问题，之前在 #3704 中把 return 改成了抛出异常，导致第四步没办法执行了。之前是认为 jobParam 的 trans 是空，就是没有可执行的语句，现在看来好像不对，我恢复成直接 return 吧，辛苦大佬帮忙确认一下 @Zzm0809 
> ![image](https://github.com/user-attachments/assets/6ac1d887-8a0a-4d6e-9cc9-aa14d41b4f14)
> ![image](https://github.com/user-attachments/assets/c87ef5c1-cd5d-4a5a-a155-386773f174cd)
> 
> 

可以在增加这个参数值场景下本地调试一下进行验证，然后修复即可
