### ISSUE TITLE
[Bug] [Module Name] K8S Contairned deploy，auto.sh is missing？

### ISSUE THREAD

**Issue by zmyer** [DataLinkDC/dinky#3775]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

When deploying dinky in K8S，auto.sh is missing，I have no idea to deal with it....
![image](https://github.com/user-attachments/assets/f89aa432-a65a-49bf-841a-2663f44db60c)

### What you expected to happen

I need to deploy dinky in k8s，So，Can I have some help?

### How to reproduce

I follow your document to deploy，but such problem is happened，there is no suggestions to deal with it.

### Anything else

....
 containers:
    - name: dinky
      image: 'dinkydocker/dinky-standalone-server:1.1.0-flink1.17'
      command:
        - /bin/bash
        - '-c'
        - **/dinky/auto.sh startOnPending 1.17**
      ports:
        - name: rest
          containerPort: 8888
          protocol: TCP
      envFrom:
        - secretRef:
            name: dinky-mysql
      env:
.....

### Version

1.1.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wuganzhi** [comment]
我有同样的问题，请问你解决了吗？
