### ISSUE TITLE
[Bug] [Module Name] K8S Deploy BUG?

### ISSUE THREAD

**Issue by zmyer** [DataLinkDC/dinky#3781]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

with deploy in k8s，what is wrong with it?  it losts  jdbc driver jar? But, it is  an image, How to insert it with jdbc
![image](https://github.com/user-attachments/assets/d07c6c87-2a4c-4e36-9b58-72350ace4290)

### What you expected to happen

HOW TO DEAL WITH IT?

### How to reproduce

with deploy in k8s, it will happend....

### Version

1.1.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
请详细阅读官网, 添加 mysql 链接驱动包是基本操作 ,原因是协议问题,无法直接内置 mysql 的 jdbc 驱动,采用外挂方式(customJar 路径), 其他详细请自行百度

**Comment by zmyer** [comment]
问题是用的是k8s部署，你这个外挂要怎么挂呢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年09月04日 23:52 |
| 收件人 | ***@***.***> |
| 抄送至 | Zhou ***@***.***>***@***.***> |
| 主题 | Re: [DataLinkDC/dinky] [Bug] [Module Name] K8S Deploy BUG? (Issue #3781) |

请详细阅读官网, 添加 mysql 链接驱动包是基本操作 ,原因是协议问题,无法直接内置 mysql 的 jdbc 驱动,采用外挂方式(customJar 路径), 其他详细请自行百度
