### ISSUE TITLE
[Bug] [Data Studio] Qeury result data button don't display

### ISSUE THREAD

**Issue by zhuxt2015** [DataLinkDC/dinky#3783]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

After click search button, there is no  query result button sometimes.
<img width="1424" alt="image" src="https://github.com/user-attachments/assets/f6fb84a8-57f0-469b-97e5-6813d950c726">

### What you expected to happen

display query result button all the time

### How to reproduce

create flinkSQL task, write a select query SQL, then click search button

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
状态未重新更新, 运行完成之后刷新一下页面即可

**Comment by Zzm0809** [comment]
重构了新页面 不存在该问题了
