### ISSUE TITLE
[Bug] [web] Task sorting buttons not working

### ISSUE THREAD

**Issue by suxinshuo** [DataLinkDC/dinky#3785]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I click the task sorting button, the tasks are not sorted.
I looked at the request parameters and found that the request body format was incorrect. From the code git commit history, I saw that the request body format was modified when solving the NPE problem. I want to know in what scenario this NPE exception occurred. 
I want to fix the NPE exception without affecting the request body format.

Correct request body:
![image](https://github.com/user-attachments/assets/a412f816-15fb-4054-9393-d8dca2746efa)

Wrong request body:
![image](https://github.com/user-attachments/assets/5be43f39-330e-49b6-9e00-5ebe9cb13645)

Git commit history:
![image](https://github.com/user-attachments/assets/eabc8691-02e8-41c7-a1f6-d91798a5655d)

### What you expected to happen

Tasks can be sorted normally.

### How to reproduce

Click the task sorting button.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by suxinshuo** [comment]
Could you help me look into this issue? @gaoyan1998

**Comment by Zzm0809** [comment]
> Could you help me look into this issue? @gaoyan1998

this is a bug, i will be fix it, please view pr #3787
