### ISSUE TITLE
[Optimization][Frontend] The CPU of the browser tab spikes, causing the front-end page to freeze

### ISSUE THREAD

**Issue by zhuxt2015** [DataLinkDC/dinky#3800]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

When operating tasks, such as opening tasks and modifying tasks, I feel that the front-end page is stuck, and the CPU usage of the tab page soars
![image](https://github.com/user-attachments/assets/c8b3ce18-56e4-4ff8-aeac-415aeb693e7e)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
待 1.2.0 发版后,可再次观察! 在这之前,前端状态存储系统在打开过多内容是可能导致 CPU/内存 占用过高
1.2.0 更换了前端状态存储 详见 #3738
