### ISSUE TITLE
[Bug] [Data Studio]The query result is not displayed. The console reports an error

### ISSUE THREAD

**Issue by dsanww** [DataLinkDC/dinky#3825]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I query a simple sql, I click the query button and keep circling around without returning results.
Viewing the log appears to be: json parsing error
![image](https://github.com/user-attachments/assets/79cea6be-35b9-4d70-a08e-5806e438169d)
![image](https://github.com/user-attachments/assets/ac6d1dff-5068-49e6-a39a-f59c17a13231)

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.dinky.data.result.SelectResult` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"success":true,"time":0,"rowData":[{"a":2,"b":4}],"total":0,"columns":["a","b"],"truncationFlag":false,"destroyed":true}"; line: 1, column: 2]

### What you expected to happen

no error

### How to reproduce

select 1+1 as a,2+2 as b;
query sql  on yarn-session mode 

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
dinky 版本?

**Comment by dsanww** [comment]
> dinky 版本?

dev Latest commit

**Comment by Zzm0809** [comment]
> > dinky 版本?
> 
> dev Latest commit

使用 local 模式,可以复现吗?

**Comment by dsanww** [comment]
> > > dinky 版本?
> > 
> > 
> > dev Latest commit
> 
> 使用 local 模式,可以复现吗?

也可以的

**Comment by suxinshuo** [comment]
应该是所有的查询 sql 执行都有这个问题，这个可以分配给我吗？我之前写过执行历史这一块的代码 @Zzm0809

**Comment by Zzm0809** [comment]
> 应该是所有的查询 sql 执行都有这个问题，这个可以分配给我吗？我之前写过执行历史这一块的代码 @Zzm0809

Of course, assigned

**Comment by suxinshuo** [comment]
I see this issue has been fixed in #3831. Please try again. @dsanww
