### ISSUE TITLE
[Bug] [Module Name] Bug title dinky-standalone-server:1.1.0-flink1.19 The flink version path in the image is wrong

### ISSUE THREAD

**Issue by hdx1986** [DataLinkDC/dinky#3826]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

dinky-standalone-server:1.1.0-flink1.19 镜像里flink版本路径错误为flink1.17  /opt/dinky//extends/flink1.17/*

### What you expected to happen

dinky-standalone-server:1.1.0-flink1.19 镜像里flink版本路径错误为flink1.17  /opt/dinky//extends/flink1.17/*,导到jar加载错误

### How to reproduce

dinky-standalone-server:1.1.0-flink1.19 镜像里flink版本路径错误为flink1.17  /opt/dinky//extends/flink1.17/*

### Version

1.1.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
![image](https://github.com/user-attachments/assets/006fdb67-561c-4429-b841-0d406fa490ee)
![image](https://github.com/user-attachments/assets/96f60bc7-8b70-4051-b6ca-aecaf9fb4ef6)
![image](https://github.com/user-attachments/assets/4d020ec9-baf3-4061-8279-87d75b6a072d)
docker内的内容是正确的，检查一下你是不是做了什么特殊配置呢

**Comment by hdx1986** [comment]
镜像：dinky-standalone-server:1.1.0-flink1.19       镜像ID：ad3d3d076f2b
我只是重新构建，把mysql驱动放到 customJar 下，其它的不变
容器内的路径和包是1.19的没错，只是jar加载的地址不对
![1](https://github.com/user-attachments/assets/79aea964-af40-4648-8db2-3ccb204a94af)
![2](https://github.com/user-attachments/assets/4350b468-75f8-48a4-bbbe-067b80b0e677)
![3](https://github.com/user-attachments/assets/768f2d01-e6b0-4ac8-b7e1-83f482ed735e)

**Comment by gaoyan1998** [comment]
> 镜像：dinky-standalone-server:1.1.0-flink1.19 镜像ID：ad3d3d076f2b 我只是重新构建，把mysql驱动放到 customJar 下，其它的不变 容器内的路径和包是1.19的没错，只是jar加载的地址不对 ![1](https://private-user-images.githubusercontent.com/128459936/370104030-79aea964-af40-4648-8db2-3ccb204a94af.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNTA2MDcsIm5iZiI6MTcyNzE1MDMwNywicGF0aCI6Ii8xMjg0NTk5MzYvMzcwMTA0MDMwLTc5YWVhOTY0LWFmNDAtNDY0OC04ZGIyLTNjY2IyMDRhOTRhZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwMzU4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDBiODAwN2FkNDg2NmI1NjcyOWFlMGU4NzBiOWM1ZTdiMjBlOTRlNjIyM2IxNjUxODM4OTk1MmVlYTc5M2QzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.K2YYE6RIlgu1OYOfBYQfyo9bEHcH6ijvs5uMwXrEEUI) ![2](https://private-user-images.githubusercontent.com/128459936/370104056-4350b468-75f8-48a4-bbbe-067b80b0e677.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNTA2MDcsIm5iZiI6MTcyNzE1MDMwNywicGF0aCI6Ii8xMjg0NTk5MzYvMzcwMTA0MDU2LTQzNTBiNDY4LTc1ZjgtNDhhNC1iYmJlLTA2N2I4MGIwZTY3Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwMzU4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmUzODYxMWQzN2U2ZjllYzVlNTQyOTZlYWI0MzY4ODI1NmI1OTU1Y2FiMWI1ZmIxNzI3Yjk3YzE3YzczZGJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ia8QFEzPUhUMBLLO7oT95i7nqSrQNNDb8hLbZGC97VE) ![3](https://private-user-images.githubusercontent.com/128459936/370104067-768f2d01-e6b0-4ac8-b7e1-83f482ed735e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNTA2MDcsIm5iZiI6MTcyNzE1MDMwNywicGF0aCI6Ii8xMjg0NTk5MzYvMzcwMTA0MDY3LTc2OGYyZDAxLWU2YjAtNGFjOC1iN2UxLTgzZjQ4MmVkNzM1ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwMzU4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWZlYWMzMmJiZTVmMmQ2MDFlMzQxMDllYTdhMWVlNDNiNTc1NGVkNWE3MTVlYWMyYzA3ZmYxODU2YTAxMWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8uhnkgVJVIi3Tf3e6tpJxNtPm20gteqnN2EBhe03z9Y)

镜像里都没有这个路径，他是怎么加载到的呢，你重新构建是指的自己重新打包镜像吗，还是dockerhub上面的镜像

**Comment by hdx1986** [comment]
![4](https://github.com/user-attachments/assets/cd9be525-435a-490f-845c-85c2f2c09bf6)
是用dockerhub上的镜像 dinkydocker/dinky-standalone-server:1.1.0-flink1.19   image ID:ad3d3d076f2b
所以不清楚这个路怎么加进来的

**Comment by hdx1986** [comment]
我重新下个镜像试试

**Comment by hdx1986** [comment]
helm 安装时 有个版本配置
extraEnv:
    flinkVersion: "1.19"
