### ISSUE TITLE
[Bug] [python UDF] An error occurs when registering PythonFlinkUDF in a FlinkSQL task.

### ISSUE THREAD

**Issue by YANGZE98920** [DataLinkDC/dinky#3839]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

我在使用python flink udf 时报错 无法找到根因，需要帮助

### What you expected to happen

我在使用python flink udf 时报错 无法找到根因，需要帮助

### How to reproduce

帮帮忙排查一下问题在哪

### Anything else

![image](https://github.com/user-attachments/assets/96605f62-95fd-4257-a2bf-7ee87a935c7f)
![image](https://github.com/user-attachments/assets/8966db3a-91a3-4017-9d60-5523743aae70)
![image](https://github.com/user-attachments/assets/3d4e00e4-ebbe-4f21-8f55-f395321c182b)
![image](https://github.com/user-attachments/assets/e3a20030-42fe-4afd-b737-770b58b9e11d)

### Version

1.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by YANGZE98920** [comment]
帮忙排查下 ！！！感激不尽

**Comment by Zzm0809** [comment]
提供复现步骤

**Comment by YANGZE98920** [comment]
上述截图即是复现我按照步骤重新截图
第一步：写了一个udf的简单例子
 ![image](https://github.com/user-attachments/assets/75557775-1e4c-423e-aec3-58c3c2d6bef3)
第二步：注册udf函数 select 使用函数
![image](https://github.com/user-attachments/assets/22a07e8c-b6eb-4d45-9ef2-4279c8f0825d)
第三步：配置参数设置
![image](https://github.com/user-attachments/assets/8eae03b5-0f87-478f-a82d-57d77307cad1)
第四步：dinky 运行环境检查
![image](https://github.com/user-attachments/assets/176c3e7d-81c3-4d55-a322-6041038ab79d)
![image](https://github.com/user-attachments/assets/61da087b-03b6-4d97-a033-75da49358ed2)
第五步：flink on K8s seesion环境集群检查：
![image](https://github.com/user-attachments/assets/0a584df3-2f00-4852-bf16-fc6293c20f7e)
第六步：查询该任务报错
![image](https://github.com/user-attachments/assets/97ad3f78-c962-413a-b863-a718a8b8c8c0)

**Comment by Zzm0809** [comment]
请按照模版 python udf 修改

**Comment by YANGZE98920** [comment]
![image](https://github.com/user-attachments/assets/f4f5f916-eadf-439c-9a85-3f95d0ceacd9)
mo'ba模板上也是这样的呀

**Comment by YANGZE98920** [comment]
![image](https://github.com/user-attachments/assets/9adfe6ec-c862-4606-b79c-9080968e5b82)
yi'j已按照python udf 模板修改 修改后还是报同样错误 
![image](https://github.com/user-attachments/assets/99104501-7eac-4842-a420-14eeaea7f489)

**Comment by YANGZE98920** [comment]
![image](https://github.com/user-attachments/assets/1031ad05-e721-4ce7-9fb0-4cc09fbacc9f)
 跟这个地方相关嘛

**Comment by YANGZE98920** [comment]
大佬帮忙看看  搞定之后写成最佳实践文档 为社区做出贡献
