### ISSUE TITLE
[Bug] [dinky-admin] jdbc job click caused error page

### ISSUE THREAD

**Issue by gitfortian** [DataLinkDC/dinky#3846]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

create jdbc type job,when click the job,error page occurs
![image](https://github.com/user-attachments/assets/97606a5c-22bc-42f7-a89d-432428cd5f3a)

### What you expected to happen

show job detail

### How to reproduce

create a jdbc job then click the job

### Version

1.1.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gitfortian** [comment]
![image](https://github.com/user-attachments/assets/a9ddce79-314b-4663-8745-9643b744c5a6)

**Comment by gitfortian** [comment]
I found the cause. It was because the Dinky application was launched without placing the relevant Flink JAR files, which resulted in errors in the backend. Additionally, there was no null value check in the frontend, which caused the page to directly display an error.

**Comment by Zzm0809** [comment]
fixed
