### ISSUE TITLE
[Bug] [Registration Center] Duplicate configuration items are found in the search timeout

### ISSUE THREAD

**Issue by zhuxt2015** [DataLinkDC/dinky#3847]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="760" alt="image" src="https://github.com/user-attachments/assets/03879b1e-0ded-4215-84ca-780dca4e10f1">

### What you expected to happen

There are no duplicates in the configuration items

### How to reproduce

Go to the registry, create a new Kubernetes operator or application cluster, add configuration items, enter `timeout` word, and scroll through the pop-up search results

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
前端组件问题, 虚拟滚动无法准确计算导致

**Comment by zhuxt2015** [comment]
> 前端组件问题, 虚拟滚动无法准确计算导致

同时还存在无法删除配置项的bug，点击删除按钮没反应
<img width="634" alt="image" src="https://github.com/user-attachments/assets/12fc058b-4210-47cc-b867-35d1fbf3e73e">

**Comment by Zzm0809** [comment]
> 前端组件问题, 虚拟滚动无法准确计算导致

已修复

**Comment by Zzm0809** [comment]
> > 前端组件问题, 虚拟滚动无法准确计算导致
> 
> 同时还存在无法删除配置项的bug，点击删除按钮没反应 <img alt="image" width="634" src="https://private-user-images.githubusercontent.com/13765310/371763097-12fc058b-4210-47cc-b867-35d1fbf3e73e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NzYzMTksIm5iZiI6MTcyNzU3NjAxOSwicGF0aCI6Ii8xMzc2NTMxMC8zNzE3NjMwOTctMTJmYzA1OGItNDIxMC00N2NjLWI4NjctMzVkMWZiZjNlNzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDAyMTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNDY4MGEyOGI2M2Q4ZTQ5Zjc2YzAyZTQyOWM1NWNkZGMwZjUzMjUxOWI4ZDUyZWIwYzQ2ODAwOWU0MGZkNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Yq3DcLkHRSVcJBKiNM9vsM8FyrA75I2YwvyaFtt2HVk">

无法复现

**Comment by zhuxt2015** [comment]
> > > 前端组件问题, 虚拟滚动无法准确计算导致
> > 
> > 
> > 同时还存在无法删除配置项的bug，点击删除按钮没反应 <img alt="image" width="634" src="https://private-user-images.githubusercontent.com/13765310/371763097-12fc058b-4210-47cc-b867-35d1fbf3e73e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NzYzMTksIm5iZiI6MTcyNzU3NjAxOSwicGF0aCI6Ii8xMzc2NTMxMC8zNzE3NjMwOTctMTJmYzA1OGItNDIxMC00N2NjLWI4NjctMzVkMWZiZjNlNzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDAyMTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNDY4MGEyOGI2M2Q4ZTQ5Zjc2YzAyZTQyOWM1NWNkZGMwZjUzMjUxOWI4ZDUyZWIwYzQ2ODAwOWU0MGZkNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Yq3DcLkHRSVcJBKiNM9vsM8FyrA75I2YwvyaFtt2HVk">
> 
> 无法复现

Chrome 版本 128.0.6613.85（正式版本） (x86_64)

**Comment by Zzm0809** [comment]
> > > > 前端组件问题, 虚拟滚动无法准确计算导致
> > > 
> > > 
> > > 同时还存在无法删除配置项的bug，点击删除按钮没反应 <img alt="image" width="634" src="https://private-user-images.githubusercontent.com/13765310/371763097-12fc058b-4210-47cc-b867-35d1fbf3e73e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NzYzMTksIm5iZiI6MTcyNzU3NjAxOSwicGF0aCI6Ii8xMzc2NTMxMC8zNzE3NjMwOTctMTJmYzA1OGItNDIxMC00N2NjLWI4NjctMzVkMWZiZjNlNzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDAyMTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNDY4MGEyOGI2M2Q4ZTQ5Zjc2YzAyZTQyOWM1NWNkZGMwZjUzMjUxOWI4ZDUyZWIwYzQ2ODAwOWU0MGZkNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Yq3DcLkHRSVcJBKiNM9vsM8FyrA75I2YwvyaFtt2HVk">
> > 
> > 
> > 无法复现
> 
> Chrome 版本 128.0.6613.85（正式版本） (x86_64)

版本 129.0.6668.70（正式版本） (arm64)

**Comment by Zzm0809** [comment]
> > > > 前端组件问题, 虚拟滚动无法准确计算导致
> > > 
> > > 
> > > 同时还存在无法删除配置项的bug，点击删除按钮没反应 <img alt="image" width="634" src="https://private-user-images.githubusercontent.com/13765310/371763097-12fc058b-4210-47cc-b867-35d1fbf3e73e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NzYzMTksIm5iZiI6MTcyNzU3NjAxOSwicGF0aCI6Ii8xMzc2NTMxMC8zNzE3NjMwOTctMTJmYzA1OGItNDIxMC00N2NjLWI4NjctMzVkMWZiZjNlNzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDAyMTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNDY4MGEyOGI2M2Q4ZTQ5Zjc2YzAyZTQyOWM1NWNkZGMwZjUzMjUxOWI4ZDUyZWIwYzQ2ODAwOWU0MGZkNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Yq3DcLkHRSVcJBKiNM9vsM8FyrA75I2YwvyaFtt2HVk">
> > 
> > 
> > 无法复现
> 
> Chrome 版本 128.0.6613.85（正式版本） (x86_64)

试着调整你的 分辨率 或者浏览器缩放 , 这里没有做自适应布局, 可能导致右侧溢出 导致无法点击,如不是此原因,需自行排查
