### ISSUE TITLE
[Optimization][Registration Centor] Load from a local file not work

### ISSUE THREAD

**Issue by zhuxt2015** [DataLinkDC/dinky#3849]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

<img width="1047" alt="image" src="https://github.com/user-attachments/assets/36f53e9f-0e56-40ac-866d-5dddb9b58bbb">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
无法复现
