### ISSUE TITLE
[Bug] [dinky-admin] When create a directory, resources fullname is error

### ISSUE THREAD

**Issue by maikouliujian** [DataLinkDC/dinky#3859]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

When create a directory, if the pid of the resource is negative, the resources fullname is error.
Examples are as follows：
create a directory:config
<img width="532" alt="图片" src="https://github.com/user-attachments/assets/ed2810cd-e1fe-4c05-93cc-f9226a3b3c85">
the fullname is /config:
<img width="1636" alt="图片" src="https://github.com/user-attachments/assets/a111842e-42b0-4275-8335-cb2e0df15df8">
the code is:
<img width="905" alt="图片" src="https://github.com/user-attachments/assets/d4f86fe1-7cb5-40ff-a25b-fb0880b0d2f8">

### What you expected to happen

the fullname is /dw/dirtest/config

### How to reproduce

When create a directory, if the pid of the resource is negative, the resources fullname is error.

### Version

1.1.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Fixed.
