### ISSUE TITLE
[Bug] [Flink] java.lang.ClassNotFoundException: com.mysql.jdbc.Driver

### ISSUE THREAD

**Issue by faketrader** [DataLinkDC/dinky#3863]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

YARN Application 模式运行失败（YARN Session 模式可以运行）。

已在 dinky/extends/ 放置 `mysql-connector-j-8.0.33.jar`，未找到的类是 com.mysql.jdbc.Driver，同时放置了 `mysql-connector-java-5.1.49.jar`。

日志：
[mgigEGg6.txt](https://github.com/user-attachments/files/17306801/mgigEGg6.txt)

![image](https://github.com/user-attachments/assets/3b63c1a7-abf4-4b84-9514-6e82d6e1ef07)

### What you expected to happen

正常运行

### How to reproduce

使用 YARN Application 模式运行

```
--创建源表datagen_source
CREATE TABLE datagen_source(
  id  BIGINT,
  name STRING
) WITH (
  'connector' = 'datagen'
);
--创建结果表blackhole_sink
CREATE TABLE blackhole_sink(
   id  BIGINT,
   name STRING
) WITH (
  'connector' = 'blackhole'
);
--将源表数据插入到结果表
INSERT INTO blackhole_sink
SELECT
   id  ,
   name 
from datagen_source;
```

### Version

1.1.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
hdfs 的 flink/lib 下放一份, 这是基操
