### ISSUE TITLE
[Feature][Module Name] Can it be supported to synchronize the jobs submitted by the flink instance into the dinky platform?

### ISSUE THREAD

**Issue by kawsyd** [DataLinkDC/dinky#3892]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

公司已使用flink，有几个集群提交了很多作业。没办法把作业都下掉，再通过dinky提交。是否有办法，将已提交的作业，入dinky平台。

### Use case

无法同步现有集群任务入dinky监管

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
1. This capability is not currently provided
2. It is recommended that you savepoint existing jobs and then create them in dinky. When starting, execute the savepoint policy and start running the job from the specified time. The remaining risks need to be assessed by yourself.
