### ISSUE TITLE
[Bug] [Module Name] Bug title cant create catalog

### ISSUE THREAD

**Issue by cuanxiaopo** [DataLinkDC/dinky#3900]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

dinky版本1.0.0,使用default_catalog创建表时，提示无法创建catalog
![微信图片_20241105160556](https://github.com/user-attachments/assets/be488011-e35e-4d6f-ab83-4940a70335c6)

### What you expected to happen

能够使用dinky的catalog正常创建表

### How to reproduce

使用default_catalog建表

### Version

1.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
请添加flink MySQL cdc连接器

**Comment by cuanxiaopo** [comment]
添加的有cdc连接器，报错的是创建catalog报错，不是建表报错。如果不使用default_catalog，是可以创建成功的

**Comment by aiwenmo** [comment]
May I ask which dependencies have been added?
