### ISSUE TITLE
[Document][doc] Update data preview document Feature#3893

### ISSUE THREAD

**Issue by MactavishCui** [DataLinkDC/dinky#3916]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar document requirement.

### Description

Update the document to describe the feature 3893 [https://github.com/DataLinkDC/dinky/issues/3893](url)

I have submitted a draft PR [https://github.com/DataLinkDC/dinky/pull/3915](url) But I encountered a bottleneck during the submission process
Some pictures need to be updated, but I don't know how to upload pic to [http://pic.dinky.org.cn/dinky/docs/zh-CN](url)

Looking forward to your reply.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MactavishCui** [comment]
@Zzm0809 Hi, I found that the draft PR [https://github.com/DataLinkDC/dinky/pull/3915](url) has been approved. But the pictures are still need to be updated and I cannot find the way to upload new pictures to [http://pic.dinky.org.cn/dinky/docs/zh-CN](https://github.com/DataLinkDC/dinky/issues/url). Could you please tell me how to upload new pictures?
Looking forward to your reply

**Comment by gaoyan1998** [comment]
> @Zzm0809 Hi, I found that the draft PR [https://github.com/DataLinkDC/dinky/pull/3915](url) has been approved. But the pictures are still need to be updated and I cannot find the way to upload new pictures to [http://pic.dinky.org.cn/dinky/docs/zh-CN](https://github.com/DataLinkDC/dinky/issues/url). Could you please tell me how to upload new pictures? Looking forward to your reply

@MactavishCui 
You don't need to worry about this, you just need to give the image address, we will follow up and move it to [http://pic.dinky.org.cn/dinky/docs/zh-CN](https://github.com/DataLinkDC/dinky/issues/url) for you.   We are also looking for a better way about the image problem, if you have a better suggestion you can open another issue to put forward!

**Comment by MactavishCui** [comment]
> > @Zzm0809 Hi, I found that the draft PR [https://github.com/DataLinkDC/dinky/pull/3915](url) has been approved. But the pictures are still need to be updated and I cannot find the way to upload new pictures to [http://pic.dinky.org.cn/dinky/docs/zh-CN](https://github.com/DataLinkDC/dinky/issues/url). Could you please tell me how to upload new pictures? Looking forward to your reply
> 
> @MactavishCui You don't need to worry about this, you just need to give the image address, we will follow up and move it to [http://pic.dinky.org.cn/dinky/docs/zh-CN](https://github.com/DataLinkDC/dinky/issues/url) for you. We are also looking for a better way about the image problem, if you have a better suggestion you can open another issue to put forward!

Thx for your reply! I'll paste my prepared picture on the comment of this issue tonight after I back home, linked doc PR is `ready for view` now! [https://github.com/DataLinkDC/dinky/pull/3915](url)

**Comment by MactavishCui** [comment]
@gaoyan1998 Hi, here lists my picture for this feature doc
![f08ace91104f2ca877b8308daaf1293](https://github.com/user-attachments/assets/734420f2-9adf-4e30-be34-0003fa78eadf)
