### ISSUE TITLE
[Optimization][Data Development] Code auto completion on fragment

### ISSUE THREAD

**Issue by xialei30** [DataLinkDC/dinky#3977]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

已经注册后的全局变量，在开发页面使用代码自动补全，希望补全为变量名称，而非变量值。
应用场景为将数据库密码通过全局变量从代码中隐藏，但是自动补全时直接将密码显示在了代码中。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MactavishCui** [comment]
Please assign this issue to me, I will fix this issue today.

**Comment by MactavishCui** [comment]
> Please assign this issue to me, I will fix this issue today.

https://github.com/DataLinkDC/dinky/pull/3982

**Comment by aiwenmo** [comment]
So fast! The optimization has been merged into dinky-1.2.0-rc4. thx
