### ISSUE TITLE
[Bug] [dinky-web] Task naming rule restrictions.

### ISSUE THREAD

**Issue by Jam804** [DataLinkDC/dinky#3990]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Due to the conversion of underscores (_) to hyphens (-) when submitting Kubernetes tasks, there is a potential conflict if there are two tasks named test-1 and test_1 running in Kubernetes mode. Consider implementing strict restrictions on task names:

1. The name must consist of lowercase letters, numbers, '-', or '.'.
2. The name must start and end with a letter or a number.

![image](https://github.com/user-attachments/assets/0196804e-be75-4882-886b-c0f8b8f3aa74)

### What you expected to happen

Consider implementing strict restrictions on task names.

### How to reproduce

Creating a task named test-1 and a task named test_1 will cause the two tasks to affect each other.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
This naming restriction existed before, but this operation is not suitable. Dinky is not only for the k8s platform, also has a large number of session and yarn users. It is very common to use '_' naming, which is consistent with most user naming. habit, and we received a lot of user feedback before deciding to remove this naming restriction.   
I think there needs to be a better way than outright blocking this naming scheme

**Comment by Jam804** [comment]
> 此命名限制以前存在，但此操作不适用。Dinky 不仅针对 k8s 平台，还拥有大量的 session 和 yarn 用户。使用 '_' 命名是很常见的，这与大多数用户命名一致。习惯，在决定取消此命名限制之前，我们收到了大量用户反馈。我认为需要有更好的方法，而不是直接阻止这个命名方案

Thank you for your review. I will come up with a better solution to resolve this issue.
