### ISSUE TITLE
[Bug] [dinky-web] Issue with creating a new task with a subdirectory of the same name

### ISSUE THREAD

**Issue by Jam804** [DataLinkDC/dinky#3992]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/user-attachments/assets/8d83a39c-67fa-4ad9-8808-96a8948442cf)

Due to the unique index catalogue_un_idx1, an error is thrown on the backend when I try to add a subdirectory with the same name as an existing task, but the frontend page does not respond.

![image](https://github.com/user-attachments/assets/1ec73924-9dae-4d28-afba-223675454e30)

![image](https://github.com/user-attachments/assets/20a2549f-9c24-4e7f-9cd6-19b483cca805)

### What you expected to happen

I hope to either delete or modify the unique index catalogue_un_idx1, or have the frontend display a clear error message when adding a subdirectory fails.

### How to reproduce

Attempt to add a subdirectory with the same name as any task under the parent directory.

### Anything else

I want to fix this issue. Should I modify or delete this unique key constraint, or should I check for duplicates before inserting?

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
#3993
