### ISSUE TITLE
Failed to recyle database: database in auto-commit mode

### ISSUE THREAD

**Issue by AndyAiAlisa** [DataLinkDC/dinky#4012]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Steps to reproduce:

Prepare the following environment: HDP 3.1.4, Flink 1.17.2, HDFS 3.1.1, MySQL 5.7.
Download the Dinky installation package and follow the official documentation for installation.
After completing the configuration, start Dinky and check the log files or console output.
Key log when the issue occurs:
org.dinky.utils.SqliteUtil: Failed to recycle database: database in auto-commit mode

### What you expected to happen

Solve this problem.

### How to reproduce

Follow the steps, and you will find that the issue is consistently reproducible.

### Version

1.2.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
无法复现

**Comment by wang3680** [comment]
我也遇到了这个问题

**Comment by wang3680** [comment]
> ### Search before asking
> 
>     * [x]  I had searched in the [议题](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.
> 
> 
> ### What happened
> 
> Steps to reproduce:
> 
> Prepare the following environment: HDP 3.1.4, Flink 1.17.2, HDFS 3.1.1, MySQL 5.7. Download the Dinky installation package and follow the official documentation for installation. After completing the configuration, start Dinky and check the log files or console output. Key log when the issue occurs: org.dinky.utils.SqliteUtil: Failed to recycle database: database in auto-commit mode
> ### What you expected to happen
> 
> Solve this problem.
> ### How to reproduce
> 
> Follow the steps, 和 you will find that the issue is consistently reproducible.
> ### Anything else
> 
> _No response_
> ### Version
> 
> 1.2.0
> ### Are you willing to submit PR?
> 
>     * [x]  Yes I am willing to submit a PR!
> 
> 
> ### Code of Conduct
> 
>     * [x]  I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

这个问题，你解决了吗？？？
