### ISSUE TITLE
develop flink-jar task ing left windows and right windows data no sync 

### ISSUE THREAD

**Issue by pangfeihu** [DataLinkDC/dinky#4013]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

When developing the Flink jar task, the left and right window codes are not synchronized after the task is saved.
![微信截图_20241205153901](https://github.com/user-attachments/assets/3b62602e-0130-4b2b-b18d-ca7fd49de03a)

### What you expected to happen

Failed to retrieve server data after saving

### How to reproduce

Follow the problem description to reproduce

### Version

1.2.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Upgrade into Dinky-1.2.0-rc5.
