### ISSUE TITLE
 Git code builds error

### ISSUE THREAD

**Issue by pangfeihu** [DataLinkDC/dinky#4014]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

In the Git Project (Beta) module, Git code builds pass empty build parameters to the build command, causing Maven to find the corresponding command and unable to package it
![微信截图_20241205155014](https://github.com/user-attachments/assets/68924731-f0cd-4f4e-9c4b-228d4a2c9a2b)

### What you expected to happen

When executing the Maven command, parameter validation was not performed on the execution command. If it is an empty string, it should not be added to the Maven packaged command

### How to reproduce

According to the description, it can be reproduced

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
This problem is very simple, welcome to fix it

**Comment by suger-bl** [comment]
I can fix it, please give it to me
