### ISSUE TITLE
After being set to English, some pages will have Simplified Chinese

### ISSUE THREAD

**Issue by pangfeihu** [DataLinkDC/dinky#4015]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

After being set to English, some pages will have Simplified Chinese
![微信图片_20241205155841](https://github.com/user-attachments/assets/a1f22de5-60c8-4d9a-ab99-3b3be8417192)

### What you expected to happen

I don't know

### How to reproduce

According to the description, it can be reproduced

### Version

1.2.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zackyoungh** [comment]
dev已完善
