### ISSUE TITLE
[Optimization][UDF] New UDF execution diagram

### ISSUE THREAD

**Issue by zackyoungh** [DataLinkDC/dinky#4018]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

![udf执行图](https://github.com/user-attachments/assets/40a9c401-cb34-45a0-8925-7ac2c5087e64)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by luckyLJY** [comment]
Hello, once the UDF function is constructed in this way, how should it be used?
