### ISSUE TITLE
[Bug] [Module Name] LDAP The login button is not displayed

### ISSUE THREAD

**Issue by xiaoniankang** [DataLinkDC/dinky#4019]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.2.0版本开启LDAP登录，首次登录显示LDAP按钮，重新登录未显示LDAP按钮

### What you expected to happen

![image](https://github.com/user-attachments/assets/c860c824-1f72-4dc4-a267-43d1ca07695d)
![image](https://github.com/user-attachments/assets/2f73fb9d-e4d0-4a88-b851-aee9c485e9c0)
![image](https://github.com/user-attachments/assets/4b9d203e-cb41-48f6-b6a9-f9207b6edc2e)

### How to reproduce

开启LDAP登录选项，刷新页面第一次登录会出现LDAP选项按钮，退出登录，LDAP按钮消失，重新刷新页面无效
在chrome浏览器必须得清除缓存

### Version

1.2.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
close #4026
