### ISSUE TITLE
[Feature][FLINK SQL] Flink sql version history

### ISSUE THREAD

**Issue by chenhaipeng** [DataLinkDC/dinky#4033]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Situation: Every developer can push code online, but this may cause some issues. I can't find the correct historical version of the code. Therefore, I would like a feature to record the Flink SQL version upon publishing, creating a new version record each time.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
该功能早已实现，在发布时触发历史版本

**Comment by chenhaipeng** [comment]
> 该功能早已实现，在发布时触发历史版本

找到了，感谢！
