### ISSUE TITLE
[Bug] git Project : mvn Build failed Because build parameter parsing failed

### ISSUE THREAD

**Issue by bestboy** [DataLinkDC/dinky#4034]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

构建mvn项目，构建参数解析失败，导致项目构建失败。
当构建参数为空或者指定参数，拼接到mvn构建命令里是两个双引号引起来的，导致最后解析命令失败
<img width="1445" alt="image" src="https://github.com/user-attachments/assets/bce64d56-f172-45c9-bfd7-7913059a78d4">
<img width="1458" alt="image" src="https://github.com/user-attachments/assets/1eefe12c-a4cd-40bd-a7ba-a8a5c10d673f">

指定参数后：
<img width="1426" alt="image" src="https://github.com/user-attachments/assets/3c61a542-052f-4564-9117-86856b4c0214">
<img width="1445" alt="image" src="https://github.com/user-attachments/assets/f121d429-b3c2-4fbd-a78b-fd7433272c98">

### What you expected to happen

自定义参数构建成功

### How to reproduce

如图所示

### Version

1.2.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
重复 like #4014
