### ISSUE TITLE
[Bug] flink jar task cannot save set variables

### ISSUE THREAD

**Issue by bestboy** [DataLinkDC/dinky#4039]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

任务设置 SET 'execution.checkpointing.interval'='30'; 等变量，并且点击保存，提示保存成功。刷新页面或重新进入项目后，提示版本不一致，后端并没有保存上，右侧的勾选手动输入的选项也会重置为未选中。还有一个问题就是用EXECUTE JAR WITH语法一直提示格式有误，语法有误，最后只能使用右边的form提交

EXECUTE JAR WITH (
  -- 这里对应的就是我们刚刚在资源上传的Jar包
'uri'='rs:///flink-doris-connector-1.19-24.0.0.jar',
'main-class'='org.apache.doris.flink.tools.cdc.CdcTools',
'args'='    mysql-sync-database
    --database app_db
    --mysql-conf hostname=192.168.1.68
    --mysql-conf port=3306
    --mysql-conf username=root
    --mysql-conf password=123456
    --mysql-conf database-name=app_db
    --mysql-conf server-time-zone=UTC
    --including-tables "orders"
    --sink-conf fenodes=192.168.1.68:8030
    --sink-conf username=root
    --sink-conf jdbc-url=jdbc:mysql://192.168.1.68:9030
    --sink-conf sink.label-prefix=label-2
    --table-conf replication_num=1 '
);

<img width="1529" alt="image" src="https://github.com/user-attachments/assets/9f858ee5-6872-4f9a-8857-a8f4365790a0" />

<img width="1553" alt="image" src="https://github.com/user-attachments/assets/b8d598fb-74d2-4f61-82e6-be12cf21a4fb" />

### What you expected to happen

可以保存自定义信息

### How to reproduce

如图

### Version

1.2.0-RC5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
CC @zackyoungh
