### ISSUE TITLE
[Document][doc] Modify error link in README.md

### ISSUE THREAD

**Issue by binggana** [DataLinkDC/dinky#4043]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar document requirement.

### Description

在README.md文件中

> How to Deploy

标题下source code compilation链接地址错误，导致点击跳转404，已修改正确引用地址。

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Fixed
