### ISSUE TITLE
push task to dolphinschedule not work

### ISSUE THREAD

**Issue by Ak47biubiuaaa** [DataLinkDC/dinky#4050]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

I used dinky-1.2.0-rc5, configured dolphinschedule, and the Flink sql task was released with a push button, but nothing happened when I clicked on the button, and no task was received at dolphinschedule
![dinky](https://github.com/user-attachments/assets/854c3305-47bf-4e4c-b8b4-c62957b5ad00)

### What you expected to happen

push flink sql task to dolphinschedule

### How to reproduce

push flink sql task to dolphinschedule

### Anything else

none

### Version

1.2.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Fixed by #4048
