### ISSUE TITLE
[Bug] 1.2.0-RC5: flink jar task cdc to doris :create-table-only parameter ignore

### ISSUE THREAD

**Issue by bestboy** [DataLinkDC/dinky#4051]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

创建flink cdc 任务，当指定:create-table-only  参数时，无效，创建完表后，数据依然会同步
 mysql-sync-database
    --database datacenter
    --mysql-conf hostname=192.168.40.84
    --mysql-conf port=3306
    --mysql-conf username=develop
    --mysql-conf password=xxxxx
    --mysql-conf database-name=datacenter
    --mysql-conf server-time-zone=Asia/Shanghai
    --mysql-conf scan.startup.mode=latest-offset
    --use-new-schema-change true 
    --ignore-default-value true
    --including-tables "sbh_plat_order"
    --sink-conf fenodes=192.168.40.92:8030
    --sink-conf username=admin
    --sink-conf password=xxxx 
    --sink-conf jdbc-url=jdbc:mysql://192.168.40.92:9030
    --sink-conf sink.label-prefix=label-dev-datacenter-sbh_plat_order
    --table-conf replication_num=1
    --create-table-only=true

需要修改scan.startup.mode参数吗？改为哪个模式才不会同步数据，只同步表结构？

### What you expected to happen

正常执行

### How to reproduce

如图

### Version

1.2.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bestboy** [comment]
使用     --create-table-only=true 可以了

**Comment by aiwenmo** [comment]
Please check the official website documentation of the corresponding component.
