### ISSUE TITLE
[Bug] [FlinkJar Job] The newly created flink-jar job in v1.20-1.2.0 cannot edit the job content!

### ISSUE THREAD

**Issue by adu-shzz** [DataLinkDC/dinky#4084]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

在 dinky-v1.20-1.2.0 @2024-12-24 的正式版中，创建一个 flink-jar 作业，建完之后，创建者和维护者都无法编辑作业内容。

### What you expected to happen

期望自行创建的作业，作业的创建者和维护人，在 OWNER_AND_MAINTAINER 配置下，对作业的读写权限能持久化生效。

### How to reproduce

使用非 admin 账号，创建 flink-jar 作业，创建成功之后，此问题必现。
此问题的临时解决办法：需要手工点击作业的右键菜单，选编辑菜单项，出现编辑界面之后，什么也不用做，直接保存，这样就可以编辑作业内容了。但是，这种操作只有一次性效果，当刷新浏览器或者重新登录 dinky 时，问题依旧没解决，只能再来一次手工操作。

注：Flink-SQL 作业无此问题。admin 账号下无此问题。

### Version

1.2.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MactavishCui** [comment]
This bug is caused by front end code, `[dinky-web]pages/DataStudio/CenterTabContent/SqlTask/index.tsx`, insert a new line
> updateCenterTab({ ...props.tabData, params: newParams });

between line 239 and line 240 can solve this problem.

**Comment by MactavishCui** [comment]
> This bug is caused by front end code, `[dinky-web]pages/DataStudio/CenterTabContent/SqlTask/index.tsx`, insert a new line
> 
> > updateCenterTab({ ...props.tabData, params: newParams });
> 
> between line 239 and line 240 can solve this problem.

PR: https://github.com/DataLinkDC/dinky/pull/4100
