### ISSUE TITLE
 [Bug] [core] SessionPool中的push操作 executorList.size() >= FlinkConstant.DEFAULT_SESSION_COUNT 此处未生效

### ISSUE THREAD

**Issue by liulian6** [DataLinkDC/dinky#415]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

add session executor push operation,  this code judge is not execute forever
[executorList.size() >= FlinkConstant.DEFAULT_SESSION_COUNT]

### What you expected to happen

detele

### How to reproduce

doesn't work

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Yes, welcome to optimize.

**Comment by gaoyan1998** [comment]
session already removed in 1.0
