### ISSUE TITLE
数据源能否增加ES

### ISSUE THREAD

**Issue by wangxiaoming-wxm** [DataLinkDC/dinky#476]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar optimization requirement.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
欢迎贡献
