### ISSUE TITLE
[Feature][dlink-alert-wechat] configure whchat url on webui or application.yml

### ISSUE THREAD

**Issue by zhengtingxue** [DataLinkDC/dinky#492]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

now,the wechat push url is  "https://qyapi.weixin.qq.com" and can not changed, but my sending service is really an intranet and can't directly access this address. Instead, it needs to be accessed through nginx agent.，so i hope the urls can be configured on the webui or application.yml by users.

### Use case

1. configured the wechar sending urls on webui

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wmtbnbo** [comment]
是否可以考虑做成通用功能，直接通过配置api地址模板进行通知

**Comment by zhu-mingye** [comment]
> 是否可以考虑做成通用功能，直接通过配置api地址模板进行通知

欢迎贡献
