### ISSUE TITLE
[Optimization][admin, core] local 模式开发时是否考虑实时推送结果

### ISSUE THREAD

**Issue by gaopan-05** [DataLinkDC/dinky#590]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

是否考虑实时推送结果,而不是从 结果 -> 获取最新数据 中查询

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
请问您是要计划贡献该优化吗

**Comment by gaopan-05** [comment]
@aiwenmo 如果需要这个功能的话，我可以实现后端逻辑

**Comment by aiwenmo** [comment]
我目前的优化想法是前端自动轮询请求数据

**Comment by gaopan-05** [comment]
@aiwenmo 可以通过 websocket 将实时的 TableResult 推送给前端

**Comment by gaoyan1998** [comment]
1.0 has already support
