### ISSUE TITLE
[Optimization][jobmanager memory] dlink task, seems cost more jobmanager memory and cause jm down

### ISSUE THREAD

**Issue by txl2017** [DataLinkDC/dinky#598]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

![c7dadc53e89b05d2a57561a94db6837](https://user-images.githubusercontent.com/26540066/173309783-337eb567-b152-4c29-acf0-f4bf8679f366.png)
is dlink commit task
![9146ac34cc05d28f6227438d48e59ce](https://user-images.githubusercontent.com/26540066/173309873-b1e53599-b5b6-4633-bb9b-5136cdb4db2c.png)
is sql client commit

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi.Thanks for your question.What is your SQL?

**Comment by txl2017** [comment]
> Hi.Thanks for your question.What is your SQL?

insert into table1 (field1,.....,fieldN) select * from table2/*+OPTIONS('read.streaming.enabled'='true','read.streaming.skip_compaction'='true')*/);

a simple sql like this , stream read hudi table insert doris

**Comment by txl2017** [comment]
![image](https://user-images.githubusercontent.com/26540066/173525265-d34e2446-3de6-4c4e-b356-1338c1cb69a2.png)

and this is today monitor info

**Comment by txl2017** [comment]
![image](https://user-images.githubusercontent.com/26540066/173532170-f8c96903-45e1-4e9f-82b3-da5552ca0172.png)

when stop dlink，it seems OK

**Comment by aiwenmo** [comment]
Maybe dinky gets the metrics of jobmanager too fast.
