### ISSUE TITLE
[Bug] [dlink-connector-phoenix-1.13] 出现jar包冲突

### ISSUE THREAD

**Issue by hanpi14** [DataLinkDC/dinky#599]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

When the JAR package of dlink-Connenctor-Phoenix is used, it conflicts with the Flink-SQL-connector-hbase JAR
在使用  dlink-connenctor-phoenix的jar包的时候,出现与flink-sql-connector-hbase jar冲突的问题
![微信图片_20220614111832](https://user-images.githubusercontent.com/90750932/173486351-45e6a24d-8f5f-45cc-a5e1-44c5f8738b59.png)

### What you expected to happen

When the JAR package of dlink-Connenctor-Phoenix is used, it conflicts with the Flink-SQL-connector-hbase JAR
在使用  dlink-connenctor-phoenix的jar包的时候,出现与flink-sql-connector-hbase jar冲突的问题
![微信图片_20220614111832](https://user-images.githubusercontent.com/90750932/173486328-8730849b-f6eb-4c4f-95fa-e6e9a4ecbc6a.png)

### How to reproduce

I used FlinkSQL to read Kakfa data to synchronize to hbase, and used Phoenix view to query hbase's ishhou, and found a conflict between the two jars

 我在使用flinksql读取kakfa数据同步到hbase中,并且使用phoenix 的视图来查询hbase的的ishhou发现两者的jar存在冲突

### Anything else

May I ask how to modify this

### Version

0.6.5-SNAPSHOT

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaogao110** [comment]
There is no good way  .... 
I think:
It is recommended not to use them at the same time, or you can submit your tasks in two Separate Flink environments 

or

you can rebuild flink-connector-hbase jar and Exclude phoenix dependencies 

Or use only one of the two connectors instead of both connectors

**Comment by hanpi14** [comment]
> 没有什么好办法.... 我认为： 建议不要同时使用，或者你可以在两个单独的Flink环境中提交你的任务
> 
> 或者
> 
> 您可以重建 flink-connector-hbase jar 并排除 phoenix 依赖项
> 
> 或者只使用两个连接器中的一个而不是两个连接器

We plan to use Flink-connector-hbase for data synchronization, and Phoenix maps hbase tables for query

 我们准备主要是使用 flink-connector-hbase来进行数据的同步,Phoenix 主要是映射hbase的表用于查询使用

**Comment by gaogao110** [comment]
This is not recommended      example : hbase  write  & hbase read    or  phoenix write & phoenix read
