### ISSUE TITLE
[Bug] [dlink-connector-phoenix-1.13] 无法获取phoenix 映射的hbase的表

### ISSUE THREAD

**Issue by hanpi14** [DataLinkDC/dinky#601]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

Flinksql and Phoenix jar are used to obtain the hbase view or table mapped by Phoenix, but an error occurs, and the table data cannot be parsed

 本地使用flinksql与 phoenix的jar去获取phoenix 映射hbase的view或者table,但是出现报错,无法解析的到表数据

[ERROR] Could not execute SQL statement. Reason:
org.apache.phoenix.schema.ColumnNotFoundException: ERROR 504 (42703): Undefined column. columnName=KAFKA_HBASE.NAME

### What you expected to happen

Flinksql and Phoenix jar are used to obtain the hbase view or table mapped by Phoenix, but an error occurs, and the table data cannot be parsed

 本地使用flinksql与 phoenix的jar去获取phoenix 映射hbase的view或者table,但是出现报错,无法解析的到表数据

[ERROR] Could not execute SQL statement. Reason:
org.apache.phoenix.schema.ColumnNotFoundException: ERROR 504 (42703): Undefined column. columnName=KAFKA_HBASE.NAME

### How to reproduce

Please advise how to modify

### Version

0.6.5-SNAPSHOT

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaogao110** [comment]
Can you provide  flink ddl  ?
or check you  column

**Comment by hanpi14** [comment]
> 你能提供 flink ddl 吗？ 或检查你的专栏

DROP TABLE IF EXISTS phoenix_source;
CREATE TABLE phoenix_source (
id VARCHAR,
name VARCHAR,
addr VARCHAR,
PRIMARY KEY (id) NOT ENFORCED
) WITH (
  'connector.type' = 'phoenix', 
  'connector.url' = 'jdbc:phoenix:hadoop2:2181', 
  'connector.table' = 'kafka_hbase',  
  'connector.driver' = 'org.apache.phoenix.jdbc.PhoenixDriver', 
  'connector.username' = '', 
  'connector.password' = '',
  'phoenix.schema.isnamespacemappingenabled' = 'true',
  'phoenix.schema.mapsystemtablestonamespace' = 'true',
  'connector.write.flush.max-rows' = '1'
 );

Kafka_hbase is a view mapping table of Phoenix mapping hbase
这个kafka_hbase是phoenix映射hbase的视图映射表

**Comment by gaogao110** [comment]
If your Phoenix table does not exist, Flink will not recognize it.
  
If you use hbase Connector, you will need to query with hbase Connector .

**Comment by hanpi14** [comment]
> 如果你的 Phoenix 表不存在，Flink 将无法识别它。
> 
> 如果使用 hbase 连接器，则需要使用 hbase 连接器进行查询。

The Phoenix table exists, but it is only an hbase mapping table. Is the mapping table unavailabl
![微信图片_20220615101545](https://user-images.githubusercontent.com/90750932/173722203-cf57fabe-2c98-40f6-97ef-ef0a486fe8a0.png)
e

**Comment by gaogao110** [comment]
You can try to recreate a table with a schema. Your table has no schema

**Comment by hanpi14** [comment]
> 您可以尝试使用架构重新创建表。您的表没有架构



> Phoenix

Do you mean that I go to hbase to build the schema and create the corresponding table, and Phoenix also builds the corresponding schema and table to verify the mapping table

 你的意思是我去hbase中构建schema,创建对应表,而Phoenix中也构建对应schema和表来进行映射表的验证吗

**Comment by hanpi14** [comment]
> You can try to recreate a table with a schema. Your table has no schema

I've built the corresponding schema here and it still doesn't wor
![微信图片_20220615110652](https://user-images.githubusercontent.com/90750932/173728378-3984efa9-0162-4c4a-a111-2f522ef5dcc0.png)
![微信图片_20220615110656](https://user-images.githubusercontent.com/90750932/173728388-c3f55bf6-69bd-44ae-9594-7df7a6ac546e.png)
k

**Comment by gaogao110** [comment]
Phoenix is case sensitive    ，The columns of your phoneix table should be capitalized
