### ISSUE TITLE
[Bug] [data develop] when task submit fail, the state is running

### ISSUE THREAD

**Issue by txl2017** [DataLinkDC/dinky#620]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

when task submit fail, the state is runing, and always running, can not stop and resubmit
and return error the cluster is not exists

### What you expected to happen

1、submit fail, state should be stop
2、cluster not exists, set state to stop

### How to reproduce

when task submit fail, the state is runing, and always running, can not stop and resubmit
and return error the cluster is not exists

### Version

0.6.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
1.0 has solved
