### ISSUE TITLE
[Optimization][作业开发-执行历史] 部分作业提交失败时无法返回日志信息

### ISSUE THREAD

**Issue by zhanghairui521** [DataLinkDC/dinky#661]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

当业务开发人员在作业开发时，配置文件中可能多了个“,”，或者路径中多了一个空格导致任务提交失败，执行历史中返回的信息为“cancel，没有获取到任何JID，请自行排查原因”，虽然后台记录了日志，但是对于业务开发人员，没有日志很难发现问题出现在哪里，所以后续能够为用户提供更多的日志信息呢？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
try 1.0, more logs info
