### ISSUE TITLE
[Feature][作业开发]是否能够支持FlinkJar任务提交到k8s上运行模式

### ISSUE THREAD

**Issue by zhanghairui521** [DataLinkDC/dinky#664]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

因为jar不是dinky的主流提交方式，但我们还是希望能够支持jar任务提交到K8s上运行

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
未来会支持

**Comment by gaoyan1998** [comment]
1.0 has supported
