### ISSUE TITLE
[Feature][ui] 注释代码时候光标自动移动下一行

### ISSUE THREAD

**Issue by syyangs799** [DataLinkDC/dinky#680]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

类似于idea一样，当我在编写任务使用快捷键 crtl + / 时候 注释某一行的代码时候，光标可以自动移动到下一行，增强体验，目前是仍然停留在当前位置

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
这是一个好优化，请问您有解决方案吗

**Comment by syyangs799** [comment]
> 这是一个好优化，请问您有解决方案吗

不好意思，这一块的技术不在能力范围内，帮不上忙，可能需要其他的大佬支持
