### ISSUE TITLE
[Bug] [openapi/executeSql] 直接使用/openapi/executeSql提交的任务运维中心无法管理

### ISSUE THREAD

**Issue by qzgt** [DataLinkDC/dinky#695]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

直接使用 ： /openapi/executeSql提交的任务运维中心无法管理，状态一直显示初始化状态（INITIALIZING），同时在任务刷新的时候，报空指针异常。

### What you expected to happen

任务能正常提交，监控中心能像使用Dinky ui登录后提交的一样可以监控。

### How to reproduce

直接使用：http://192.168.119.1:8888/openapi/executeSql 
方式：post 
数据：json格式：
{
	"type": "standalone",
	"address": "192.168.119.101:8081",
	"statement": "EXECUTE CDCSOURCE test1 WITH ( \n \n'connector' = 'mysql-cdc',\n \n'hostname' = '192.168.119.101',\n \n'port' = '3307','username' = 'root',\n \n'password' = 'root',\n \n'server-id' = '16815',\n \n'scan.incremental.snapshot.enabled' = 'false',\n \n'checkpoint' = '3000',\n \n'scan.startup.mode' = 'latest-offset',\n \n'parallelism' = '1',\n \n'database-name' = 'demo_db',\n \n'sink.connector' = 'upsert-kafka-plus',\n \n'sink.topic' = 'dlinkcdc',\n \n'sink.key.format' = 'json',\n \n'sink.value.format' = 'json',\n \n'sink.key.json.ignore-parse-errors' = 'true',\n \n'sink.value.json.fail-on-missing-field' = 'false',\n \n'sink.properties.bootstrap.servers' = '192.168.119.101:9092',\n \n'sink.properties.zookeeper.connect' = '192.168.119.101:2181'\n \n)",
	"useResult": false,
	"useStatementSet": false,
	"useChangeLog": false,
	"useAutoCancel": false,
	"fragment": false,
	"maxRowNum": 100,
	"checkPoint": 0,
	"parallelism": 1,
	"jobName": "openapitest"
}
即可复现。
dinky：version 0.6.5

### Version

0.6.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qzgt** [comment]
> 请检查 standalone 集群上的任务是否提交成功或正常运行
可以正常提交，你们可以直接使用upsert-kafka模式，upsert-kafka-plus模式我们自己扩展的。所以你们要用upsert-kafka模式。

**Comment by aiwenmo** [comment]
是指通过dinky提交后，远程集群上任务是否存在

**Comment by deepthinkin** [comment]
我也遇到了这个问题，已经成功提交到远程集群上，但是，dlink后台报空指针异常，调取获取作业任务的接口返回
`{
    "datas": {
        "success": false,
        "startTime": null,
        "endTime": "2022-08-11T12:34:40.286",
        "time": 0,
        "error": null,
        "rowData": null,
        "total": null,
        "currentCount": null,
        "columns": null,
        "destroyed": true,
        "jobId": "df25127acbf22017cf540c5f1cc04e66"
    },
    "code": 0,
    "msg": "获取成功"
}`

运维中心，看到此作业显示INITIALIZING

**Comment by ekinguofeng** [comment]
同样的BUG我在 0.6.6 上面也重现出来，POST 提交后返回成功信息，但在运维中心查看状态是 INITIALIZING ，跟踪了一下数据库dlink_job_instance.task_id 这些都空值，希望在 0.6.7 版本中可以修复这个BUG

{'datas': {'jobManagerAddress': '192.168.0.100:8081', 'status': 'SUCCESS', 'success': True, 'jobId': 'd7eeeda7c88667d10c10552a5c7cf98e', 'error': None, 'startTime': '2022-08-21T12:06:55.163', 'endTime': '2022-08-21T12:06:58.48'}, 'code': 0, 'msg':  #'执行成功'}

**Comment by feature09** [comment]
是0.6.7版本。

使用yarn-session模式，dinky显示initializing，但是跳转到flink ui界面可以发现，其实任务是启动了的。
![image](https://user-images.githubusercontent.com/31058601/205591133-1f308e91-d9bb-41f3-b0fd-7f676f8ce3a2.png)

这是flink ui界面。
![image](https://user-images.githubusercontent.com/31058601/205591201-e0f4a475-c437-4ea7-a008-54c09d3565a7.png)

并且无法取消任务。右上角的普通取消（不保存savepoint）。

**Comment by aiwenmo** [comment]
> 是0.6.7版本。
> 
> 使用yarn-session模式，dinky显示initializing，但是跳转到flink ui界面可以发现，其实任务是启动了的。 ![image](https://user-images.githubusercontent.com/31058601/205591133-1f308e91-d9bb-41f3-b0fd-7f676f8ce3a2.png)
> 
> 这是flink ui界面。 ![image](https://user-images.githubusercontent.com/31058601/205591201-e0f4a475-c437-4ea7-a008-54c09d3565a7.png)
> 
> 并且无法取消任务。右上角的普通取消（不保存savepoint）。

看看日志有无报错，你的问题应该是和本issue没有关系
