### ISSUE TITLE
[Bug] when data type is Collection Data Types, the result tab can not display the result

### ISSUE THREAD

**Issue by nikshe** [DataLinkDC/dinky#707]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

when data type is Collection Data Types, such as ARRAY, MULTISET, MAP and ROW types , the result tab can not display the result,

### What you expected to happen

the results should be displayed corrently.

### How to reproduce

with flink 1.14.4 and dlink0.6.5, using the yarn session mode submit flowing job,
CREATE TEMPORARY TABLE hp (
  `character-with-age` MAP<STRING,INT>,
  `spells` MULTISET<STRING>,
  `locations` ARRAY<STRING>,
  `house-points` ROW<`house` STRING, `points` INT>
) WITH (
  'connector' = 'faker',
  'fields.character-with-age.key.expression' = '#{harry_potter.character}',
  'fields.character-with-age.value.expression' = '#{number.numberBetween ''10'',''100''}',
  'fields.character-with-age.length' = '2',
  'fields.spells.expression' = '#{harry_potter.spell}',
  'fields.spells.length' = '5',
  'fields.locations.expression' = '#{harry_potter.location}',
  'fields.locations.length' = '3',
  'fields.house-points.house.expression' = '#{harry_potter.house}',
  'fields.house-points.points.expression' = '#{number.numberBetween ''10'',''100''}'
);

SELECT * FROM hp;
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/2069663/178177846-a22a94eb-1c5b-4489-87ea-3ae60024f714.png">

### Version

0.6.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi. These data types require extension code to obtain values.
