### ISSUE TITLE
[Bug] When a task submits a jar package, the jar package submission parameters cannot be modified at the task level

### ISSUE THREAD

**Issue by waywtdcc** [DataLinkDC/dinky#712]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

When a task submits a jar package, the jar package submission parameters cannot be modified at the task level

![image](https://user-images.githubusercontent.com/59957056/178884585-7c2cea59-d5c6-45e8-a27c-2784ef4372a9.png)

### What you expected to happen

When a task submits a jar package, the jar package submission parameters cannot be modified at the task level

### How to reproduce

When a task submits a jar package, the jar package submission parameters cannot be modified at the task level

### Version

0.6.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
![image](https://user-images.githubusercontent.com/32723967/178910515-3142e5d7-8487-439b-8ae5-a2dba1f62606.png)

**Comment by waywtdcc** [comment]
Can this be modified at the task level? Because there may be only one package, the submission parameters will be different @aiwenmo

**Comment by aiwenmo** [comment]
It is not supported at present, and this feature can be easily extended.

**Comment by waywtdcc** [comment]
> It is not supported at present, and this feature can be easily extended.

Ok, thank you, I hope the next version can be used

**Comment by aiwenmo** [comment]
> 

Welcome to PR.

**Comment by nzh9900** [comment]
@aiwenmo    
    I am willing to help fix this issue.
    In my approach, I will add a field called "paras" to the  org.dinky.model.Task class to obtain startup parameters at the task level (this "paras" will be stored when the user saves the task).  When this parameter is not empty, the JAR task will start using the task-level parameters instead of the parameters provided during JAR registration. And I think that main class can also be modified at the task level when user have different main classes in one JAR.
    There is some frontend work needed, but I haven't done any frontend work before. Is there anyone who can help with this?
    What do you think of this idea?

**Comment by gaoyan1998** [comment]
try 1.0
