### ISSUE TITLE
[bug][app] dinky提交applictaion任务报错NPE

### ISSUE THREAD

**Issue by DeepMakerAi** [DataLinkDC/dinky#831]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

sql 中包含空指针，sql解析异常
![image](https://user-images.githubusercontent.com/45482447/183228756-9fca9d0f-0158-4bd8-89e5-bbfeb1f0fa97.png)

![image](https://user-images.githubusercontent.com/45482447/183228732-15de1afa-dc99-401b-8c8b-c33459012ed9.png)

### What you expected to happen

![image](https://user-images.githubusercontent.com/45482447/183228790-b7df50b4-dfcd-4a76-aeda-3f519985d3a4.png)
![image](https://user-images.githubusercontent.com/45482447/183228847-e07b50be-8e27-49f4-b0c2-0b3f233d6ddc.png)

复现步骤：flinkSQL环境先选择defaultcatalog，再选择无，就会导致表dlink_task中envId=0，dlink_task_statement中没有那条数据，将null拼接到sql，提交代码解析错误

### How to reproduce

![image](https://user-images.githubusercontent.com/45482447/183228790-b7df50b4-dfcd-4a76-aeda-3f519985d3a4.png)
![image](https://user-images.githubusercontent.com/45482447/183228847-e07b50be-8e27-49f4-b0c2-0b3f233d6ddc.png)

复现步骤：flinkSQL环境先选择defaultcatalog，再选择无，就会导致表dlink_task中envId=0，dlink_task_statement中没有那条数据，将null拼接到sql，提交代码解析错误

### Version

0.6.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
请问是什么提交模式

**Comment by Zzm0809** [comment]
如果提交模式是 application mode , 请升级到0.6.6 此版本修复了这个bug

**Comment by a279780399** [comment]
application mode

**Comment by DeepMakerAi** [comment]
> 如果提交模式是 application mode , 请升级到0.6.6 此版本修复了这个bug

好的

**Comment by DeepMakerAi** [comment]
> 请问是什么提交模式

application
