### ISSUE TITLE
[Bug] k8s application模式提交的任务无法在运维中心管理

### ISSUE THREAD

**Issue by JanCong** [DataLinkDC/dinky#837]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

k8s application模式提交上线的任务无法在运维中心管理，任务提交成功的，web ui里能看到任务正常运行，注册中心的集群实例管理也能看到新的集群，dlink_job_instance表里也没有新增
但个别application任务可以又正常看到，不知是不是提交的方式不对。

### What you expected to happen

k8s application模式提交上线的任务在运维中心管理

### How to reproduce

1. 新建k8s application集群配置，kubernetes.rest-service.exposed.type: clusterIP
2. 新建flink sql任务，选择k8s application模式
3. 发布上线任务，任务成功运行，注册中心能看到新的集群
4. 运维中心无法看到新的k8s application任务

### Version

0.6.6

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!
#972 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JanCong** [comment]
看了下，小的简单任务可以正常进入运维中心，但有时提交后状态是 UNKNOWEN 。
可能是任务启动较慢超过了10秒获取不到 JobId 了，导致最后因为没有 jid 无法保存 jobInstance。

com.dlink.gateway.kubernetes.KubernetesApplicationGateway#submitJar
是否可以等待任务完全启动后再获取 JobId，或者增加超时时间？

**Comment by aiwenmo** [comment]
您的提议很好，可以通过扩展 dinky 的系统配置参数添加一个获取jobid的最大等待时间
