### ISSUE TITLE
[Feature][CDCSOURCE] support option : table.exec.sink.not-null-enforcer

### ISSUE THREAD

**Issue by jeeinn** [DataLinkDC/dinky#839]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

使用 CDCSOURCE 整库同步时，某些表有不规范字段 null 值问题。
异常报错：
```
java.io.IOException: java.sql.BatchUpdateException: Column 'xxx' cannot be null
```

希望可以支持 null 字段跳过选项设置，如：
```
EXECUTE CDCSOURCE sync_all_database WITH (
  ...
  'table.exec.sink.not-null-enforcer' = 'drop',
  ...
)
```
或者
```
EXECUTE CDCSOURCE sync_all_database WITH (
  ...
  'sink.table.exec.sink.not-null-enforcer' = 'drop',
  ...
)
```

### Use case

整库同步，可以正常同步

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
用set语句或者右侧的其他配置，来试试这个参数是否生效
