### ISSUE TITLE
[Bug] [注册中心] 文档管理查询条件bug

### ISSUE THREAD

**Issue by lwzhangMr** [DataLinkDC/dinky#840]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

注册中心，文档中心，过滤查询，下拉框选项名字重复
![image](https://user-images.githubusercontent.com/31753959/183375977-93170b64-7e15-40a0-af85-5b6f843e8bcd.png)

### What you expected to happen

正确显示查询下拉框选项

### How to reproduce

注册中心，文档中心，过滤查询

### Version

0.6.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jkhhuse** [comment]
I will submit a PR to solve this problem.
