### ISSUE TITLE
[Bug] flink-sql从检查点启动任务，代码里写没有生效，在页面配置生效了

### ISSUE THREAD

**Issue by Leijingwen** [DataLinkDC/dinky#846]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.flink-sql 代码里写了检查点路径,重启任务没有生效

![flink-sql设置检查点](https://user-images.githubusercontent.com/88963951/183619202-4c8e8cf3-7396-4893-bbfa-c37a695e2614.jpg)

2.从web页面设置检查点生效了

![web-页面设置检查点](https://user-images.githubusercontent.com/88963951/183619993-d0ca94ef-10ec-414a-956a-87d00cb41ad3.jpg)

### What you expected to happen

希望从检查点由代码设置可以生效，flink sql client 就可以通过
SET execution.savepoint.path = 'hdfs:xxxxx' 生效

### How to reproduce

无

### Version

0.6.6

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
savepoint 被 dinky 托管了，不建议使用 set 来配置

**Comment by peter-cd** [comment]
这个问题和 dinky在 flink on yarn模式下 在flink-conf.yaml里配置了checkpoint相关的配置没生效类似，这个能修复成都生效吗？是有实现上的难点吗？感觉生效会合理一些，不然感觉和原生的出入有点大啊

**Comment by aiwenmo** [comment]
> 这个问题和 dinky在 flink on yarn模式下 在flink-conf.yaml里配置了checkpoint相关的配置没生效类似，这个能修复成都生效吗？是有实现上的难点吗？感觉生效会合理一些，不然感觉和原生的出入有点大啊

不一样，session 集群的flink-conf.yaml的checkpoint是不生效的。而讨论的这个问题是 Dinky 的savepoint托管机制优先级比你的set高。

**Comment by koqiui** [comment]
我也有类似问题，参看：https://github.com/DataLinkDC/dlink/discussions/1182
