### ISSUE TITLE
[Bug] [jackjson] jackjson低版本不支持flink1.14.4以上版本

### ISSUE THREAD

**Issue by sunyanqing01** [DataLinkDC/dinky#856]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

jackjson版本过低

### What you expected to happen

jackjson建议升级一下版本，原来的是2.11.4，flink1.14.4用2.11.4会报错，改成2.12.1就不会出错

### How to reproduce

使用dlink链接Flink1.14.4，SavePoint停止任务时会出现，这个问题我jackjson进行了升级就解决了，Flink1.14.4版本引用的是2.12.1
![image](https://user-images.githubusercontent.com/43230630/183826857-079db4b6-5dbf-4b05-a3ac-caa329e1791c.png)

### Version

0.6.6

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
您好，您可以 jackjson 的升级进行 PR。

**Comment by sunyanqing01** [comment]
已提交

**Comment by aiwenmo** [comment]
需要提交到该仓库的dev分支，您好像没提交成功

**Comment by sunyanqing01** [comment]
![image](https://user-images.githubusercontent.com/43230630/184047349-de704f7c-ea7f-4670-b6b1-9eaa8be3f758.png)
我无法push

**Comment by aiwenmo** [comment]
先fork，然后往自己的仓库提交，再pr
