### ISSUE TITLE
dlink sink  oracle  sqlserver 支持嘛？

### ISSUE THREAD

**Issue by roy-long** [DataLinkDC/dinky#859]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

请问一下，dlink  中的flinksql想实现sink到oracle或者SqlServer该怎么写，我看flink官网13.6没有支持。

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
CREATE TABLE BOOK (
    `ID` DECIMAL,
    `BOOK` STRING,
    `AUTHOR` STRING,
    PRIMARY KEY (ID) NOT ENFORCED
) WITH(
    'connector' = 'jdbc',
    'url' = 'jdbc:oracle:thin:@127.0.0.1:1521:orcl',
    'username' = 'root',
    'table-name' = 'TEST.BOOK',
    'password' = '123456'
);

**Comment by aiwenmo** [comment]
CREATE TABLE source (
    tid INT,
    tname STRING,
    PRIMARY KEY (tid) NOT ENFORCED
) WITH (
    'connector' = 'jdbc',
    'url' = 'jdbc:sqlserver://127.0.0.1:1433;DatabaseName=test',
    'username'='test',
    'password'='test',
    'table-name' = 'source'
);
