### ISSUE TITLE
[Bug] [admin] 使用OpenAPI并发调用MySQL作业时,会出现连接关闭

### ISSUE THREAD

**Issue by XiaoF-Liu** [DataLinkDC/dinky#861]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

当同时执行多个mysql作业时，其中一个作业完成时，剩余作业会失败，报错sql连接被关闭。

### What you expected to happen

创建连接源码(此处根据配置名称创建作为键只会创建一个连接)：
```
static Driver build(DriverConfig config) {
        String key = config.getName();
        if (DriverPool.exist(key)) {
            Driver driver = DriverPool.get(key);
            if (driver.isHealth()) {
                return driver;
            }
        }
        Optional<Driver> optionalDriver = Driver.get(config);
        if (!optionalDriver.isPresent()) {
            throw new MetaDataException("缺少数据源类型【" + config.getType() + "】的依赖，请在 lib 下添加对应的扩展依赖");
        }
        Driver driver = optionalDriver.get().connect();
        DriverPool.push(key, driver);
        return driver;
    }
```
关闭连接源码：TaskServiceImpl.executeCommonSql
```
 Driver driver = Driver.build(dataBase.getDriverConfig());
            JdbcSelectResult selectResult = driver.executeSql(sqlDTO.getStatement(), sqlDTO.getMaxRowNum());
            driver.close();
``` 

### How to reproduce

1、创建多个Mysql长时间的作业
2、使用OpenAPI同时调用

### Version

0.6.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by XiaoF-Liu** [comment]
**背景：**

- 项目已经引入了alibaba druid框架

- jdbc操作已经封装好

**解决方案：**

 - 在AbstractJdbcDriver 引入alibaba druid 创建连接
 - 不影响其他sql封装代码，只改变了连接创建方式，使用alibaba druid统一管理连接池
 
@aiwenmo

**Comment by aiwenmo** [comment]
> **背景：**
> 
> * 项目已经引入了alibaba druid框架
> * jdbc操作已经封装好
> 
> **解决方案：**
> 
> * 在AbstractJdbcDriver 引入alibaba druid 创建连接
> * 不影响其他sql封装代码，只改变了连接创建方式，使用alibaba druid统一管理连接池
> 
> @aiwenmo

这个思路可以

**Comment by XiaoF-Liu** [comment]
谢谢大佬采纳
