### ISSUE TITLE
[Feature][Common] Added github workflow to check the checkstyle, test and build of each PR

### ISSUE THREAD

**Issue by zhuangchong** [DataLinkDC/dinky#868]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Added github workflow to check the checkstyle, test and build of each PR

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi. The current old code cannot pass checkstyle. How to solve it ?

**Comment by zhuangchong** [comment]
> Hi. The current old code cannot pass checkstyle. How to solve it ?

In the transitional stage, checkstyle is not mandatory, and it will be fully covered in the later stage and will be mandatory.

**Comment by aiwenmo** [comment]
I agree with you


> > Hi. The current old code cannot pass checkstyle. How to solve it ?
> 
> In the transitional stage, checkstyle is not mandatory, and it will be fully covered in the later stage and will be mandatory.

I agree with you.

**Comment by aiwenmo** [comment]
Hi. Please contact me to enter the contributor group for more convenient communication.
