### ISSUE TITLE
[Optimization][datastudio] Please add the button on "FlinkSql syntax&logic check" dialog for copying exception message

### ISSUE THREAD

**Issue by leeoo** [DataLinkDC/dinky#881]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

If the job code check cannot be passed when clicking the check button on datastudio, then "FlinkSql syntax&logic check" dialog will show exception message(s), but these message(s) ofen is/are very long and dispaly with scroll bar, it's hard to read.

So please add the button on message box top-right corner for copying the exception message(s), then I can paste it into external text editor for further reading and investgating.

![图片](https://user-images.githubusercontent.com/2136182/184280363-3aea5166-a06a-4124-ab18-00c185bade1c.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi. We want to redesign the result display information of SQL verification. Do you have any suggestions?

**Comment by Zzm0809** [comment]
> Hi. We want to redesign the result display information of SQL verification. Do you have any suggestions?

https://ant.design/components/steps-cn
可以用步骤条组件 分段展示 每段下方描述信息使用CodeShow组件展示其结果 步骤可切换查看每一步的校验结果
eg:
![图片](https://user-images.githubusercontent.com/58576849/185062538-0c6d5734-a15b-4892-abc7-76e0e7a40296.png)

![图片](https://user-images.githubusercontent.com/58576849/185063537-f8b6c82a-b17a-45c4-b63c-96c99fa1942f.png)
