### ISSUE TITLE
[Feature][数据开发] 新增cdh6.3.2版本hive连接器：dlink-connector-hive-2.1.1-cdh6.3.2-1.13

### ISSUE THREAD

**Issue by DeepMakerAi** [DataLinkDC/dinky#896]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

使用官网提供的hive连接器 连接cdh6.3.2版本的hive，启动依赖冲突

### Use case

新增cdh6.3.2版本的hive连接器

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
新增这个连接器的目的是什么
