### ISSUE TITLE
Failed to submit the yarn application task

### ISSUE THREAD

**Issue by ghost** [DataLinkDC/dinky#901]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have registered the cluster successfully
![图片](https://user-images.githubusercontent.com/40230796/185014283-baec9fc7-4eec-447f-ac7f-53f09f30de4a.png)
but，When I submit a task asynchronously, an error is reported
![图片](https://user-images.githubusercontent.com/40230796/185014951-3185349a-6b58-44ad-9e46-8bfbad38b6dd.png)
[dlink] 2022-08-16 17:59:52 CST WARN  org.springframework.core.log.CompositeLog 127 warn - Failed to evaluate Jackson deserialization for type [[simple type, class com.dlink.model.Task]]: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.fasterxml.jackson.datatype.jsr310.deser.JSR310DateTimeDeserializerBase] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@2b71fc7e]

### What you expected to happen

Have no clue

### How to reproduce

http://www.dlink.top/docs/extend/practice_guide/yarnsubmit
yarn-application

flink-1.14.4
hadoop-3.3.1
Compile and generate dlink-client-hadoop-0.6.6.jar

### Version

0.6.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
The error may be caused by dependency conflict.
Please show me your plugins directory.

**Comment by ynzzxc** [comment]
> 

![图片](https://user-images.githubusercontent.com/40230796/185022947-31da3f64-7e34-4440-8ad4-d6fba820ac33.png)

**Comment by ghost** [comment]
> The error may be caused by dependency conflict. Please show me your plugins directory.

![图片](https://user-images.githubusercontent.com/40230796/185023104-03b5e9c2-0116-488f-8f5b-404347bfee1e.png)

**Comment by aiwenmo** [comment]
Warning is not affected, look at other errors.

**Comment by ghost** [comment]
> Warning is not affected, look at other errors.

No more logs

**Comment by aiwenmo** [comment]
Look at your sql.

**Comment by ghost** [comment]
> Look at your sql.

create table carflow (
    id bigint,
    plate_license varchar(20),
    site_id int 
) WITH (
    'connector' = 'sqlserver-cdc',
    'hostname' = 'xxx,
    'port' = '15168',
    'username' = 'xxx',
    'password' = 'xxx',
    'database-name' = 'AiScreen',
    'schema-name' = 'dbo',
    'debezium.snapshot.mode' = 'schema_only',
    'debezium.snapshot.isolation.mode' = 'read_committed',
    'table-name' = 'xxx_base_record'
) ;

create table carflow_site (
    id bigint,
    plate_license varchar(20),
    site_id int,
    primary key (id) NOT ENFORCED
)
PARTITIONED BY (site_id)
WITH (
    'connector'='hudi',
    'path'= 'hdfs:///hudi/test/carflow_site',
    'table.type'= 'MERGE_ON_READ',
    'write.tasks' = '1',
    'read.tasks' = '1',
    'compaction.tasks' = '1'
) ;

insert into carflow_site 
select * from carflow ;

**Comment by aiwenmo** [comment]
Does your yarn have any failed applications?

**Comment by ynzzxc** [comment]
> Does your yarn have any failed applications?

not hive

**Comment by ghost** [comment]
> Does your yarn have any failed applications?

not have

**Comment by aiwenmo** [comment]
I'm sorry. You can only find the problem by debugging the application remotely.

**Comment by ghost** [comment]
> I'm sorry. You can only find the problem by debugging the application remotely.

I have solved the above problems.but,I have a new problem.After I submitted the task, it reported an error：

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/dataxc/opt/hadoop-3.3.1/tmp/nm-local-dir/filecache/26/dlink-client-hadoop-0.6.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dataxc/opt/hadoop-3.3.1/share/hadoop/common/lib/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.cli.Option.builder(Ljava/lang/String;)Lorg/apache/commons/cli/Option$Builder;
	at org.apache.flink.runtime.entrypoint.parser.CommandLineOptions.<clinit>(CommandLineOptions.java:27)
	at org.apache.flink.runtime.entrypoint.DynamicParametersConfigurationParserFactory.options(DynamicParametersConfigurationParserFactory.java:43)
	at org.apache.flink.runtime.entrypoint.DynamicParametersConfigurationParserFactory.getOptions(DynamicParametersConfigurationParserFactory.java:50)
	at org.apache.flink.runtime.entrypoint.parser.CommandLineParser.parse(CommandLineParser.java:42)
	at org.apache.flink.runtime.entrypoint.ClusterEntrypointUtils.parseParametersOrExit(ClusterEntrypointUtils.java:64)
	at org.apache.flink.yarn.entrypoint.YarnApplicationClusterEntryPoint.main(YarnApplicationClusterEntryPoint.java:86)

I put commons-cli-1.2.jar into the hdfs:///flink/lib,flink/lib,plugins
but，The problem has not been solved

**Comment by ghost** [comment]
> I'm sorry. You can only find the problem by debugging the application remotely.

之前那个问题的解决过程。我将flink/lib路径由hdfs:///flink/lib更改为plugins，重启后dlink根目录下新增了一个dlink.log文件，可以看到报错信息为：No FileSystem for scheme “hdfs“ ，我将hadoop-hdfs-client-3.3.1.jar添加到plugins得以解决。

**Comment by aiwenmo** [comment]
刚发现你没有在 plugins 下添加 flink-shaded-hadoop-3-uber-3.1.1.7.2.1.0-327-9.0.jar 或使用环境变量。

**Comment by ghost** [comment]
> 刚发现你没有在 plugins 下添加 flink-shaded-hadoop-3-uber-3.1.1.7.2.1.0-327-9.0.jar 或使用环境变量。

是的。官网说“如果你的 Hadoop 为 3+ 也可以自行编译对应版本的 dlink-client-hadoop.jar 以替代 uber 包”，所以我使用的是dlink-client-hadoop.jar，没使用uber包，
我采用这种方式部署时，还需要添加对应版本hadoop-hdfs-client.jar，以及更新commons-cli.jar和commons-math.jar，job才能成功提交到yarn，
我的：hadoop-hdfs-client-3.3.1.jar，commons-cli-1.4.jar，commons-math3-3.6.1.jar

我现在能正确提交任务到yarn了，但好像遇到了日志冲突问题
并且在使用yarn-application模式提交时，返回的job id总是0000000000000000000000000000000000

**Comment by ghost** [comment]
> > 刚发现你没有在 plugins 下添加 flink-shaded-hadoop-3-uber-3.1.1.7.2.1.0-327-9.0.jar 或使用环境变量。
> 
> 是的。官网说“如果你的 Hadoop 为 3+ 也可以自行编译对应版本的 dlink-client-hadoop.jar 以替代 uber 包”，所以我使用的是dlink-client-hadoop.jar，没使用uber包， 我采用这种方式部署时，还需要添加对应版本hadoop-hdfs-client.jar，以及更新commons-cli.jar和commons-math.jar，job才能成功提交到yarn， 我的：hadoop-hdfs-client-3.3.1.jar，commons-cli-1.4.jar，commons-math3-3.6.1.jar
> 
> 我现在能正确提交任务到yarn了，但好像遇到了日志冲突问题 并且在使用yarn-application模式提交时，返回的job id总是0000000000000000000000000000000000

52797 [flink-rest-server-netty-worker-thread-10] ERROR org.apache.flink.runtime.rest.handler.taskmanager.TaskManagerLogFileHandler  - Unhandled exception.
org.apache.flink.util.FlinkException: The file LOG is not available on the TaskExecutor.

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/dataxc/opt/hadoop-3.3.1/tmp/nm-local-dir/filecache/27/dlink-client-hadoop-0.6.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dataxc/opt/hadoop-3.3.1/tmp/nm-local-dir/filecache/15/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dataxc/opt/hadoop-3.3.1/share/hadoop/common/lib/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]

**Comment by aiwenmo** [comment]
> > 刚发现你没有在 plugins 下添加 flink-shaded-hadoop-3-uber-3.1.1.7.2.1.0-327-9.0.jar 或使用环境变量。
> 
> 是的。官网说“如果你的 Hadoop 为 3+ 也可以自行编译对应版本的 dlink-client-hadoop.jar 以替代 uber 包”，所以我使用的是dlink-client-hadoop.jar，没使用uber包， 我采用这种方式部署时，还需要添加对应版本hadoop-hdfs-client.jar，以及更新commons-cli.jar和commons-math.jar，job才能成功提交到yarn， 我的：hadoop-hdfs-client-3.3.1.jar，commons-cli-1.4.jar，commons-math3-3.6.1.jar
> 
> 我现在能正确提交任务到yarn了，但好像遇到了日志冲突问题 并且在使用yarn-application模式提交时，返回的job id总是0000000000000000000000000000000000

目前达到这个现状是正确了，日志冲突和jobid是后续优化的问题了。

**Comment by ghost** [comment]
> > > 刚发现你没有在 plugins 下添加 flink-shaded-hadoop-3-uber-3.1.1.7.2.1.0-327-9.0.jar 或使用环境变量。
> > 
> > 
> > 是的。官网说“如果你的 Hadoop 为 3+ 也可以自行编译对应版本的 dlink-client-hadoop.jar 以替代 uber 包”，所以我使用的是dlink-client-hadoop.jar，没使用uber包， 我采用这种方式部署时，还需要添加对应版本hadoop-hdfs-client.jar，以及更新commons-cli.jar和commons-math.jar，job才能成功提交到yarn， 我的：hadoop-hdfs-client-3.3.1.jar，commons-cli-1.4.jar，commons-math3-3.6.1.jar
> > 我现在能正确提交任务到yarn了，但好像遇到了日志冲突问题 并且在使用yarn-application模式提交时，返回的job id总是0000000000000000000000000000000000
> 
> 目前达到这个现状是正确了，日志冲突和jobid是后续优化的问题了。

非常感谢！
