### ISSUE TITLE
[Bug] [Module Name] Bug k8s模式异步提交实际上还是本地运行

### ISSUE THREAD

**Issue by gaoyan1998** [DataLinkDC/dinky#903]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

作业开发完成后点击异步提交到k8s，页面一闪而过个报错，但太快了，看不清截不到，然后提示异步提交成功，后台日志查看还是本地运行了一个minicluster，根本没有提交k8s，刷新页面后历史记录显示的也是本地运行

### What you expected to happen

、

### How to reproduce

、

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
请问你提交的是 k8s application 吗

**Comment by gaoyan1998** [comment]
> 请问你提交的是 k8s application 吗

我清理了一下浏览器缓存好了，不太理解这些东西为啥要缓存呀

**Comment by gaoyan1998** [comment]
目测是缓存了东西，浏览器清理缓存就正常了
