### ISSUE TITLE
[Bug] [Module Name] Bug k8s任务发布上线后，运维中心看不到

### ISSUE THREAD

**Issue by gaoyan1998** [DataLinkDC/dinky#904]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

新建了好几个任务都一样，运维中心始终为0

### What you expected to happen

、

### How to reproduce

、

### Version

0.6.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
你上个issue里提到任务没有提交成功，运维中心只能看到提交成功的

**Comment by gaoyan1998** [comment]
> 你上个issue里提到任务没有提交成功，运维中心只能看到提交成功的

昂昂，好的

**Comment by gaoyan1998** [comment]
好的
