### ISSUE TITLE
[Feature][Module Name] flink jar 支持cicd

### ISSUE THREAD

**Issue by MonsterChenzhuo** [DataLinkDC/dinky#911]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

当我们要运行一个基于代码开发的flink任务时，每次代码的更新都需要jar的重新上传。更好的方式是通过集成gitlab/github来进行一键打包，一件同步更新

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
您好，您的提议非常有意义。对于代码开发的 Flink Jar 任务确实更适合通过 CI/DI 的方式进行。目前我们也想实现这个方向，但是目前有限的精力主要放在了 sql 层的应用探索，心有余而力不足。不知您是否有兴趣来与我们交流和讨论该方向，从而推动其的设计与落地，非常感谢。

**Comment by gaoyan1998** [comment]
1.0 has supported
