### ISSUE TITLE
[Bug] [openApi] 作业重启失败

### ISSUE THREAD

**Issue by lwzhangMr** [DataLinkDC/dinky#912]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

执行http://xxx:8888/openapi/restartTask?id=36重启作业，返回结果如下
{
    "datas": null,
    "code": 1,
    "msg": null
}
重启作业执行后无响应，其他api可以正常执行

### What you expected to happen

作业重启成功

### How to reproduce

{
    "datas": null,
    "code": 1,
    "msg": null
}

### Anything else

{
    "datas": null,
    "code": 1,
    "msg": null
}

### Version

0.6.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
这个需要通过远程调试的方式跟踪该接口来寻找问题
