### ISSUE TITLE
[Bug] [flinksql on yarn] 提交一个flinksql 的作业到yarn集群提示少包

### ISSUE THREAD

**Issue by zhong16602192407** [DataLinkDC/dinky#914]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

集群环境： hadoop 3.0.0 cdh6.2.0,flink 1.13.6,doris 1.1.1，dlink 0.6.6
1.按照官网的yarn部署任务篇，已按照描述进行。yarn集群已配置。
并且在hdfs上传并指定了6.3mb的dlink-app.jar （targer 包的dlink-app-1.13-0.6.6-jar-with-dependencies.jar）,
yarn 的日志：
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/48815337/185587343-e4f5438d-464d-4cfe-8574-c643833dc21d.png">

hdfs的flink lib：
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/48815337/185587417-41004522-9351-4094-a874-91f4bc2cb0fb.png">

### What you expected to happen

按照yarn application部署成功flink sql作业

### How to reproduce

一个正常的cdc任务

### Version

0.6.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
去掉 flink-connector-mysql-cdc-2.2.1.jar 试试

**Comment by zhong16602192407** [comment]
好滴，解决了，谢谢

**Comment by aiwenmo** [comment]
> 好滴，解决了，谢谢

请问是通过什么方式解决的

**Comment by zhong16602192407** [comment]
这边按照您的反馈，在hdfs上删除了flink-connector-mysql-cdc-2.2.1.jar ，随后就执行成功了
