### ISSUE TITLE
[Bug] [元数据] 数据开发-元数据-字段信息显示异常

### ISSUE THREAD

**Issue by ldbinac** [DataLinkDC/dinky#927]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/5122501/185888197-d12f5ef2-7867-48cc-8bf0-5192e46cc815.png)

如果字段列名比较长的时候，数据开发-元数据-字段信息显示异常，具体如图

### What you expected to happen

建议字段信息表格增加横向滚动条

### How to reproduce

配置MySQL数据源，选择 dlink自己的数据库，查看dlink.dlink_alert_group即可重现

### Version

0.6.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
1.0 already optimized
