### ISSUE TITLE
[Bug] [dlink-core] 创建hive 表的sql 语法检查会创建表，如果对sql做了语法检查，再执行会报错

### ISSUE THREAD

**Issue by xicm** [DataLinkDC/dinky#928]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

对创建hive 表sql 做语法检查，然后再提交，就会报TableAlreadyExistException的异常。

用CREATE TABLE  IF NOT EXISTS 可以避免这个问题，但是直接create 应该也要正常工作。

### What you expected to happen

语法检查的时候不创建表，而且语法检查应该是可以重复执行

### How to reproduce

sql 
```
CREATE CATALOG hive WITH ( 
    'type' = 'hive',
    'default-database' = 'default',
    'hive-conf-dir' = '/etc/hive/conf/', 
    'hadoop-conf-dir'='/etc/hadoop/conf/' 
);

USE CATALOG hive;
SET table.sql-dialect=hive;

CREATE TABLE hive_table_008 (
    id STRING,
    score STRING
) PARTITIONED BY (dt STRING, hr STRING) STORED AS parquet TBLPROPERTIES (
  'partition.time-extractor.timestamp-pattern'='$dt',
  'sink.partition-commit.trigger'='partition-time',
  'sink.partition-commit.delay'='1min',
  'sink.semantic' = 'exactly-once',
  'sink.rolling-policy.rollover-interval' ='1min',
  'sink.rolling-policy.check-interval'='1min',
  'sink.partition-commit.policy.kind'='metastore,success-file'
);
```

执行语法检查，然后提交或者再次进行语法检查

### Version

0.6.6

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xicm** [comment]
https://github.com/DataLinkDC/dlink/blob/c1b4b556e007ca14f23c00ea5d40c3f681d5537d/dlink-executor/src/main/java/com/dlink/executor/Executor.java#L247-L258

pretreatExecute 之后如果没有执行，再执行，设计的初衷就是这个逻辑吗

**Comment by aiwenmo** [comment]
> https://github.com/DataLinkDC/dlink/blob/c1b4b556e007ca14f23c00ea5d40c3f681d5537d/dlink-executor/src/main/java/com/dlink/executor/Executor.java#L247-L258
> 
> pretreatExecute 之后如果没有执行，再执行，设计的初衷就是这个逻辑吗

不是这里的问题，问题的原因是语法校验的原理是：
先执行 DDL 语句，在 explain INSERT 或 SELECT 语句。
如果采用了非内存的catalog，就会出现这些问题，建议前面加 IF NOT EXISTS

**Comment by xicm** [comment]
OK, 多谢，建表的时候加 IF NOT EXISTS
