### ISSUE TITLE
[Bug] [运维中心] 运维中心展示有问题

### ISSUE THREAD

**Issue by ChenpiDog** [DataLinkDC/dinky#929]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

经使用发现，之前发布了一个任务，在flink web ui 取消掉了，运维中心看到这个任务状态为cancelled，在数据开发界面，把同一个任务再提交一次，在运维中心看不到最新提交的，看到的还是之前那个cancelled的状态。提交时是显示提交成功了的。

运维中心初次提交作业是没问题的。
另外，希望运维中心的作业能够提供删除功能。

### What you expected to happen

期望能得到正确结果，我应该在运维中心看到一个最新提交的在运行的作业。

### How to reproduce

如上所述。

### Version

0.6.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ChenpiDog** [comment]
应该是注释导致的，发布了一个无任何注释的flink sql，在运维中心能看到正常结果。

**Comment by aiwenmo** [comment]
> 应该是注释导致的，发布了一个无任何注释的flink sql，在运维中心能看到正常结果。

insert 前请不要加注释，这个bug将在0.6.7版本修复

**Comment by Zzm0809** [comment]
你们的注释是什么格式  
是 /**/ 这样的块注释 
还是   **-- 注释信息** 这样的 注释  
我目前写第二种注释 没有发现这个问题

**Comment by aiwenmo** [comment]
> 你们的注释是什么格式 是 /**/ 这样的块注释 还是 **-- 注释信息** 这样的 注释 我目前写第二种注释 没有发现这个问题

写到;与insert关键字之间会有这个问题

**Comment by ChenpiDog** [comment]
@zhu-mingye 是 /**/ 这样的块注释

**Comment by Zzm0809** [comment]
> @zhu-mingye 是 /**/ 这样的块注释

目前写成  -- 注释  这种没有出现上述问题  如下截图
![图片](https://user-images.githubusercontent.com/58576849/186799026-f12b3c0f-db10-4aa5-bd9c-64d1d8a22071.png)

**Comment by gaoyan1998** [comment]
1.0 has fixed
