### ISSUE TITLE
[File][数据开发] 文件功能

### ISSUE THREAD

**Issue by hqgordon** [DataLinkDC/dinky#930]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

数据开发下的文件功能后续有考虑是怎么样的效果吗？
比如：通过文件导入数据或者导出？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
目前有贡献者在设计实现中，如集群配置的配置文件和依赖上传等

**Comment by aiwenmo** [comment]
#938
