### ISSUE TITLE
[Feature][数据服务] 提供数据服务API接口供外部访问

### ISSUE THREAD

**Issue by ChenpiDog** [DataLinkDC/dinky#940]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

用户只需要写SQL，Dinky一站式数据平台生成相关的数据服务API，以供外部访问数据，安全方面，数据服务API需要有对应的API Key。

### Use case

对Dinky未来功能的一点建议，提供数据服务API。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wellCh4n** [comment]
+1
