### ISSUE TITLE
[Feature][数据同步、整库同步] 关于整库同步的一些建议

### ISSUE THREAD

**Issue by ChenpiDog** [DataLinkDC/dinky#941]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

1）目标端如mysql、postgre、doris的自动建表，提升平台易用性，这一点已经在别的issue中提到。
2）整库同步是实时还是批量，可以细分为整库迁移与整库同步，整库迁移为批量一次性任务，整库同步为实时长期任务。
3）整库同步可配置，即用户可以批量选择源端是哪些库哪些表，同步到目标端的哪些库（可在一个界面一次性实现）。
4）数据同步可考虑对消息队列的支持，从消息队列获取数据，向消息队列推送数据。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ChenpiDog** [comment]
针对3），可在配置界面设置库名，若源库没有该库，则自动创建。

**Comment by aiwenmo** [comment]
1.在推动中，#796。
2.目前通过flinkcdc原生配置来决定是整库迁移还是整库同步。
3.可视化构建任务是后续的内容。
4.目前支持向消息队列推送数据。
