### ISSUE TITLE
[Feature][定时调度] 关于定时调度的一些建议

### ISSUE THREAD

**Issue by ChenpiDog** [DataLinkDC/dinky#942]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

之前已了解到Dinky有打算支持任务定时调度，对任务定时调度有如下建议：
1）调度支持按天调度，能设置调度起始及截止时间。按天调度：在具体的某个时间调度一次，针对具体的某个任务，任务失败能告警，具体到某个责任人，可设置该任务是否启动告警。
2）任务是以任务组进行调度，一个任务组里有多个任务，多个任务之间可以设置依赖。任务组与任务组之间也有依赖，前置任务组成功才能进行后续的任务组，如果后续任务组到了执行时间，但前置任务组还在执行，后置任务组就处于等待。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ChenpiDog** [comment]
任务是告警的最小单元，任务组是调度的最小单元。任务和任务组皆可设置告警，这并不冲突。
任务调度建议能设置任务优先级，以应对某时刻大量任务跑批的情况，达到最大并发任务数后，优先级低的处于等待状态。

**Comment by ChenpiDog** [comment]
@aiwenmo Dinky后续会上任务调度这个功能吗，统一数据库SQL和Flink SQL（批、流）的调度或管理，便于做全局数据血缘。

**Comment by aiwenmo** [comment]
正在建设中，可以进入社区群交流，也欢迎可以为该方向的探索研究分享经验与贡献代码

**Comment by cooltnt** [comment]
顶一个!  dag 可拖拽方式吗?

**Comment by aiwenmo** [comment]
> 顶一个! dag 可拖拽方式吗?

Dinky 不提供 DAG 工作流拖拽，使用 DolphinScheduler 的 DinkyTask。
