### ISSUE TITLE
[FAQ][CDCSOURCE]整库同步多表的参数配置及重启作业要注意的事项

### ISSUE THREAD

**Issue by leeoo** [DataLinkDC/dinky#947]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

Environment: Dinky 0.6.6, Flink 1.14.5 (Standalone), Doris 1.1.1, MySQL 8.0.29

参考官方文档 http://www.dlink.top/docs/data_integration_guide/cdcsource_statements 中的“实时数据 FlinkSQL 入仓 Doris”示例，发现配置多表时运行 mysql2doris CDCSOURCE 作业总报“DorisRuntimeException: stream load error: errCode = 2, detailMessage = User Abort, see more in null” 异常，如下图）
![图片](https://user-images.githubusercontent.com/2136182/186324652-56850668-da30-4e54-8b39-b198ba6f0242.png)
原因：没有配置动态 label 参数所致；
解决办法：在 WITH options 中配置参数项 `'sink.sink.label-prefix' = '${schemaName}_${tableName}'` 即可；
![图片](https://user-images.githubusercontent.com/2136182/186329160-0b9a7577-9934-4bd6-a854-7160fddbd55f.png)

注意：配置了动态 label 参数可解决上述异常，但如果手动关掉这个作业，然后再重启作业就会报 label 已存在，再改成 
`'sink.sink.label-prefix' = '${schemaName}_${tableName}_1'`
这样才可以，目前只能每次这样改。希望后续官方能有自动化的解决办法。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kaiwangleo** [comment]
大佬，现在还在用dinky吗，这个依赖问题是怎么解决的，整库同步一直报找不到类
