### ISSUE TITLE
[Feature][dlink-admin] sql 开发页面增加 checkpoint 相关配置

### ISSUE THREAD

**Issue by ziqiang-wang** [DataLinkDC/dinky#950]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![image](https://user-images.githubusercontent.com/107013241/186364333-3056c42a-3f16-418a-bcac-26433d4043ec.png)
![image](https://user-images.githubusercontent.com/107013241/186364921-094ec601-184b-419f-b9ad-9890ad272871.png)

如上图所示，在 flink sql 和 flink jar 任务的开发界面增加有关 checkpoint 的一些常用配置，并给出默认值，以增加平台的易用性。
以下是我建议的一些常用配置：

- execution.checkpointing.interval：checkpoint 时间间隔，单位：Duration，默认值 -1。建议直接让用户输入，比如：10s、1m，0 表示禁用，默认值建议为 0.
- execution.checkpointing.timeout：checkpoint 超时时间，单位：Duration，默认值 10m。
- execution.checkpointing.unaligned.forced：是否开启非对齐 checkpoint，在大作业下非常有用，单位：Boolean，默认值 false。可做成开关。
- state.backend.incremental：是否开启增量 checkpoint，单位：Boolean，默认值 false。默认值建议为 true。可做成开关。
- state.backend：状态后端，单位：String，默认值：hashmap，可用值：hashmap、rocksdb。可做成开关，开关值为 rocksdb 。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
try 1.0
