### ISSUE TITLE
[Feature][devops] Add "Jump to edit page" convenient function for job list on devops page

### ISSUE THREAD

**Issue by leeoo** [DataLinkDC/dinky#952]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Just want to quickly jump to the edit page of the selected job on devops page, maybe we can add a (HTTP) link to job name column for each job.

![图片](https://user-images.githubusercontent.com/2136182/186557054-93b033da-fb6c-4c7e-bdce-437b9a7b4f9e.png)

### Use case

Quickly jump to the edit page of the selected job after clicking the job name on devops page.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liusiyi77m** [comment]
Hello, I'm interested in solving this issue. Can I try?

**Comment by leeoo** [comment]
> Hello, I'm interested in solving this issue. Can I try?

Yes, you can do it.

**Comment by leeoo** [comment]
Update for Dinky 1.0.0-rc1: 

建议在运维中心添加跳转到所选作业的数据开发页面的便捷性小功能
（PS：作业比较多时这个功能会很方便）
![图片](https://github.com/DataLinkDC/dinky/assets/2136182/07cfb0f4-10c1-4656-8950-a667ff1f501b)
