### ISSUE TITLE
数据开发目录栏老是自动展开

### ISSUE THREAD

**Issue by freedata2022** [DataLinkDC/dinky#955]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

数据开发目录栏老是自动展开： 点其他导航栏后，在回点到数据开发导航栏

### What you expected to happen

数据开发目录栏收缩状态，或者保持操作者点击目录状态

### How to reproduce

 点其他导航栏后，在回点到数据开发导航栏

### Anything else

无

### Version

0.6.6

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
like issue #882

**Comment by aiwenmo** [comment]
- [x] #991
