### ISSUE TITLE
[Bug] [数据开发] 作业标题修改bug

### ISSUE THREAD

**Issue by lwzhangMr** [DataLinkDC/dinky#961]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

1、作业新建时，有名称和别名两字段，这个“名称”字段是什么用途呢？用作哪里显示？还是有特殊用途呢？
2、重命名作业时，显示的标题不对，“重命名目录” 应该显示 “重命名作业”，还有个问题目前页面显示的是 新建时 别名字段的值。

### What you expected to happen

1、新建作业，表单只有 名称输入框 是否就可以了呢！
2、重命名时，表单标题正确显示。

### How to reproduce

![image](https://user-images.githubusercontent.com/31753959/186834454-308c14a5-7c39-467b-9324-d391ebb4ec32.png)

### Anything else

![image](https://user-images.githubusercontent.com/31753959/186834211-4e2b6e22-d91e-41b3-b985-1482407de726.png)
![image](https://user-images.githubusercontent.com/31753959/186834310-091c82eb-63d8-4127-8e30-db42c536ad7d.png)

### Version

0.6.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
1.0 has fixed
