### ISSUE TITLE
[Feature][运维中心] 希望增加回收功能

### ISSUE THREAD

**Issue by lwzhangMr** [DataLinkDC/dinky#962]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

运维中新的任务实例，目前无法删除，在数据开发中将作业删除，但是运维中心里的实例还在，应该一并删除。

### Use case

1、数据开发中-新建作业，on yarn application模式运行，异步提交作业
2、运维中心显示正常
3、数据开发中-删除作业
4、运维中心查看，任务实例还在，应该级联删除。

### Related issues

无

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
1.0 has added, 
Currently supports regular cleaning of historical data
