### ISSUE TITLE
[Bug] [注册中心] 页面列表bug

### ISSUE THREAD

**Issue by lwzhangMr** [DataLinkDC/dinky#963]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

页面列表不能自动伸缩或超长隐藏，影响美观
![Uploading image.png…]()

### What you expected to happen

页面自动伸缩

### How to reproduce

列表页面自动伸缩

### Version

0.6.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
![image](https://user-images.githubusercontent.com/58576849/188044033-c1f6ef89-21b2-44f4-9c99-29c2203378b4.png)
截图看不到  你说的是注册中心的哪一块呢

**Comment by lwzhangMr** [comment]
![image](https://user-images.githubusercontent.com/31753959/188044493-cc2a5d86-218a-4d56-bb1b-eb8c139dcfb8.png)

**Comment by lwzhangMr** [comment]
![image](https://user-images.githubusercontent.com/31753959/188044605-7fad4219-5979-4fca-be57-0cf5189edc17.png)

**Comment by lwzhangMr** [comment]
> ![image](https://user-images.githubusercontent.com/58576849/188044033-c1f6ef89-21b2-44f4-9c99-29c2203378b4.png) 截图看不到 你说的是注册中心的哪一块呢

我又截取了一个图，是分辨率的问题吗

**Comment by Zzm0809** [comment]
未复现
