### ISSUE TITLE
[Bug] [dlink-connectors] Lack of flink-1.15 support

### ISSUE THREAD

**Issue by SnJForever** [DataLinkDC/dinky#964]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### #想使用flink1.15版本，发现没有dlink-connector-jdbc-1.15
1. 更改父工程pom 中的
`<dlink.flink.version>1.15</dlink.flink.version>`
2. 编译整个项目，出现
`Could not find artifact com.dlink:dlink-connector-jdbc-1.15:pom:unknown`

### What you expected to happen

1. 更改父工程pom 中的
`<dlink.flink.version>1.15</dlink.flink.version>`
2. 编译整个项目，出现
`Could not find artifact com.dlink:dlink-connector-jdbc-1.15:pom:unknown`

### How to reproduce

1. 更改父工程pom 中的
`<dlink.flink.version>1.15</dlink.flink.version>`
2. 编译整个项目，出现
`Could not find artifact com.dlink:dlink-connector-jdbc-1.15:pom:unknown`

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ziqiang-wang** [comment]
项目全局搜索“dlink-connector-jdbc”，然后注释掉这个依赖即可。
flink-1.15 已经实现了 mysql 类型的 jdbc  catalog，所以平台已经不需要自己单独实现了。
