### ISSUE TITLE
[Feature][web,metadata] 独立元数据管理功能

### ISSUE THREAD

**Issue by gaoyan1998** [DataLinkDC/dinky#965]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

目前dinky已经实现元数据功能，但是仅在工作台页面，而且操作也较为不方便，查看数据不直观，建议可以独立出一个数据中心管理元数据功能，并且日常开发中经常需要查看表信息与表内数据内容，所以我也添加了一个样例数据页面，将表信息与字段信息合并到一个页面，同时sql生成也可以增加更多语句如insert等，在开发中同样有帮助，在后台中我发现了也有insert的sql生成功能，不知道出于什么原因没有使用。

At present, dinky has implemented the metadata function, but it is only on the workbench page, and the operation is relatively inconvenient, and viewing the data is not intuitive. May be a data center to manage the metadata function？ and it is often necessary to view table information and table information in daily development. internal data content, so I also added a sample data page to combine table information and field information into one page, and sql generation can also add more statements such as insert, etc., which is also helpful in development. In the dinky-admin, I I found the sql generation function that also has insert, and I don't know why it is not used.

### Use case

实现的页面
![示例](https://github.com/ikiler/ikiler/blob/master/pic/dinky/metadata1.png?raw=true)
![示例](https://github.com/ikiler/ikiler/blob/master/pic/dinky/metadata2.png?raw=true)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi. Have you finished this function?

**Comment by gaoyan1998** [comment]
> Hi. Have you finished this function?

Sure， and i have submitted pr，I forgot the code style check yesterday, it has been changed

**Comment by Zzm0809** [comment]
Hello, the menu layout of this data center is recommended to be placed on the right side of the registration center

**Comment by gaoyan1998** [comment]
> Hello, the menu layout of this data center is recommended to be placed on the right side of the registration center

yes, this is better, i have modified

**Comment by aiwenmo** [comment]
Hi. Please contact my wechat. We will have a meeting tomorrow evening to discuss the details.

**Comment by gaoyan1998** [comment]
Modify the sample data for data query, provide where and order by query, Additional simple prompts based on column names
![](https://img1.imgtp.com/2022/09/03/ONUUWzeD.png)
![](https://img1.imgtp.com/2022/09/03/j6mmc8O5.png)
