### ISSUE TITLE
[Feature][CDCSOURCE ]  Write to Doris auto create table

### ISSUE THREAD

**Issue by xiaofan2022** [DataLinkDC/dinky#968]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Use FLINKSQL to synchronize the whole library, support to set the exclusion table. And the table creation template, which automatically creates tables when Doris does not exist

### Use case

No manual table building

### Related issues

no 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi. Are you willing to submit this PR?

**Comment by xiaofan2022** [comment]
Yes, I'm looking at the code

**Comment by xiaofan2022** [comment]
Yes, I'm looking at the code

**Comment by aiwenmo** [comment]
#796
