### ISSUE TITLE
[Bug] [banner] The banner seems has problem

### ISSUE THREAD

**Issue by xleoken** [DataLinkDC/dinky#975]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/95013770/187822002-d174edfd-fcaa-4d27-a0e2-49b03c13fa23.png)

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi. You are right. How to fix it?
