### ISSUE TITLE
[Feature][数据治理] 增加数据治理相关功能

### ISSUE THREAD

**Issue by ChenpiDog** [DataLinkDC/dinky#976]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

如数据目录、数据地图、数据字典、数据质量等。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi. These functions are not in the current project roadmap.

**Comment by ChenpiDog** [comment]
OK, dinky can consider these functions in the future. We hope that dinky will become better and attract more users.

**Comment by xleoken** [comment]
Good idea 👍

**Comment by aiwenmo** [comment]
> OK, dinky can consider these functions in the future. We hope that dinky will become better and attract more users.

Thanks for your support. ~

**Comment by lizhongshuai** [comment]
Very good idea. I hope to realize this function.

**Comment by fuboyu712** [comment]
+1

**Comment by 2645651783** [comment]
非常实用

**Comment by whmnoe4j** [comment]
这个功能挺好，可以一起建设起来
