### ISSUE TITLE
[Question] [spring] Why we need both application.yml and application.properties here?

### ISSUE THREAD

**Issue by xleoken** [DataLinkDC/dinky#978]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

Why we need both application.yml and application.properties here? It seems we can keep one.

![image](https://user-images.githubusercontent.com/95013770/187852274-666d4601-4f8b-431d-bd65-877ffd75df51.png)

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi.It can be optimized.

**Comment by xleoken** [comment]
Got, will do.
